package com.esc20.model;
// Generated Jan 4, 2019 3:30:30 PM by Hibernate Tools 4.3.5.Final

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BeaBusPhone generated by hbm2java
 */
@Entity
@Table(name = "BEA_BUS_PHONE", schema = "rsccc", catalog = "rsccc")
public class BeaBusPhone implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BeaBusPhoneId id;
	private String phoneAreaBus;
	private String phoneNbrBus;
	private String busPhoneExt;
	private String phoneAreaBusNew;
	private String phoneNbrBusNew;
	private String busPhoneExtNew;
	private String apprvdDts;
	private Integer apprvrUsrId;
	private Character statCd;

	public BeaBusPhone() {
	}

	public BeaBusPhone(BeaBusPhoneId id, String phoneAreaBus, String phoneNbrBus, String busPhoneExt,
			String phoneAreaBusNew, String phoneNbrBusNew, String busPhoneExtNew, String apprvdDts, Integer apprvrUsrId,
			Character statCd) {
		this.id = id;
		this.phoneAreaBus = phoneAreaBus;
		this.phoneNbrBus = phoneNbrBus;
		this.busPhoneExt = busPhoneExt;
		this.phoneAreaBusNew = phoneAreaBusNew;
		this.phoneNbrBusNew = phoneNbrBusNew;
		this.busPhoneExtNew = busPhoneExtNew;
		this.apprvdDts = apprvdDts;
		this.apprvrUsrId = apprvrUsrId;
		this.statCd = statCd;
	}

	public BeaBusPhone(BhrEmpDemo demo) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
		BeaBusPhoneId id = new BeaBusPhoneId();
		id.setEmpNbr(demo.getEmpNbr());
		id.setReqDts(sdf.format(new Date()).substring(0, 16));
		this.id = id;
		this.phoneAreaBus = demo.getPhoneAreaBus();
		this.phoneNbrBus = demo.getPhoneNbrBus();
		this.busPhoneExt = demo.getBusPhoneExt();
		this.phoneAreaBusNew = demo.getPhoneAreaBus();
		this.phoneNbrBusNew = demo.getPhoneNbrBus();
		this.busPhoneExtNew = demo.getBusPhoneExt();
		this.apprvdDts = "";
		this.apprvrUsrId = -1;
		this.statCd = 'P';
	}
	public BeaBusPhone(BhrEmpDemo demo, String empNbr, String reqDts, String phoneAreaBusNew, String phoneNbrBusNew,String busPhoneExtNew, Character statCd) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
		BeaBusPhoneId id = new BeaBusPhoneId();
		id.setEmpNbr(empNbr);
		id.setReqDts(reqDts);
		this.id = id;
		this.phoneAreaBus = demo.getPhoneAreaBus()==null?"":demo.getPhoneAreaBus();
		this.phoneAreaBusNew = phoneAreaBusNew;
		this.phoneNbrBus = demo.getPhoneNbrBus()==null?"":demo.getPhoneNbrBus();
		this.phoneNbrBusNew = phoneNbrBusNew;
		this.busPhoneExt = demo.getBusPhoneExt()==null?"":demo.getBusPhoneExt();
		this.busPhoneExtNew = busPhoneExtNew;
		
		if("A".equals(statCd.toString())) {
			this.apprvdDts = sdf.format(new Date()).substring(0, 16);
			this.apprvrUsrId = 0;
		}else {
			this.apprvdDts = "";
			this.apprvrUsrId = -1;
		}
		this.statCd = statCd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "reqDts", column = @Column(name = "REQ_DTS", nullable = false, length = 16)) })
	public BeaBusPhoneId getId() {
		return this.id;
	}

	public void setId(BeaBusPhoneId id) {
		this.id = id;
	}

	@Column(name = "PHONE_AREA_BUS", nullable = false, length = 3)
	public String getPhoneAreaBus() {
		return this.phoneAreaBus;
	}

	public void setPhoneAreaBus(String phoneAreaBus) {
		this.phoneAreaBus = phoneAreaBus;
	}

	@Column(name = "PHONE_NBR_BUS", nullable = false, length = 7)
	public String getPhoneNbrBus() {
		return this.phoneNbrBus;
	}

	public void setPhoneNbrBus(String phoneNbrBus) {
		this.phoneNbrBus = phoneNbrBus;
	}

	@Column(name = "BUS_PHONE_EXT", nullable = false, length = 4)
	public String getBusPhoneExt() {
		return this.busPhoneExt;
	}

	public void setBusPhoneExt(String busPhoneExt) {
		this.busPhoneExt = busPhoneExt;
	}

	@Column(name = "PHONE_AREA_BUS_NEW", nullable = false, length = 3)
	public String getPhoneAreaBusNew() {
		return this.phoneAreaBusNew;
	}

	public void setPhoneAreaBusNew(String phoneAreaBusNew) {
		this.phoneAreaBusNew = phoneAreaBusNew;
	}

	@Column(name = "PHONE_NBR_BUS_NEW", nullable = false, length = 7)
	public String getPhoneNbrBusNew() {
		return this.phoneNbrBusNew;
	}

	public void setPhoneNbrBusNew(String phoneNbrBusNew) {
		this.phoneNbrBusNew = phoneNbrBusNew;
	}

	@Column(name = "BUS_PHONE_EXT_NEW", nullable = false, length = 4)
	public String getBusPhoneExtNew() {
		return this.busPhoneExtNew;
	}

	public void setBusPhoneExtNew(String busPhoneExtNew) {
		this.busPhoneExtNew = busPhoneExtNew;
	}

	@Column(name = "APPRVD_DTS", nullable = false, length = 16)
	public String getApprvdDts() {
		return this.apprvdDts;
	}

	public void setApprvdDts(String apprvdDts) {
		this.apprvdDts = apprvdDts;
	}

	@Column(name = "APPRVR_USR_ID", nullable = false)
	public Integer getApprvrUsrId() {
		return this.apprvrUsrId;
	}

	public void setApprvrUsrId(Integer apprvrUsrId) {
		this.apprvrUsrId = apprvrUsrId;
	}

	@Column(name = "STAT_CD", nullable = false, length = 1)
	public Character getStatCd() {
		return this.statCd;
	}

	public void setStatCd(Character statCd) {
		this.statCd = statCd;
	}

}
