package com.esc20.model;
// Generated Jan 4, 2019 3:30:30 PM by Hibernate Tools 4.3.5.Final

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BeaDrvsLic generated by hbm2java
 */
@Entity
@Table(name = "BEA_DRVS_LIC", schema = "rsccc", catalog = "rsccc")
public class BeaDrvsLic implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BeaDrvsLicId id;
	private String driversLicNbr;
	private String driversLicSt;
	private String driversLicNbrNew;
	private String driversLicStNew;
	private String apprvdDts;
	private Integer apprvrUsrId;
	private Character statCd;

	public BeaDrvsLic() {
	}

	public BeaDrvsLic(BeaDrvsLicId id, String driversLicNbr, String driversLicSt, String driversLicNbrNew,
			String driversLicStNew, String apprvdDts, Integer apprvrUsrId, Character statCd) {
		this.id = id;
		this.driversLicNbr = driversLicNbr;
		this.driversLicSt = driversLicSt;
		this.driversLicNbrNew = driversLicNbrNew;
		this.driversLicStNew = driversLicStNew;
		this.apprvdDts = apprvdDts;
		this.apprvrUsrId = apprvrUsrId;
		this.statCd = statCd;
	}

	public BeaDrvsLic(BhrEmpDemo demo) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
		BeaDrvsLicId id = new BeaDrvsLicId();
		id.setEmpNbr(demo.getEmpNbr());
		id.setReqDts(sdf.format(new Date()).substring(0, 16));
		this.id = id;
		this.driversLicNbr = demo.getDriversLicNbr();
		this.driversLicSt = demo.getDriversLicSt();
		this.driversLicNbrNew = demo.getDriversLicNbr();
		this.driversLicStNew = demo.getDriversLicSt();
		this.apprvdDts = "";
		this.apprvrUsrId = -1;
		this.statCd = 'P';
	}
	
	public BeaDrvsLic(BhrEmpDemo demo, String empNbr, String reqDts, String driversLicNbrNew, String driversLicStNew, Character statCd) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
		BeaDrvsLicId id = new BeaDrvsLicId();
		id.setEmpNbr(empNbr);
		id.setReqDts(reqDts);
		this.id = id;
		this.driversLicNbr = demo.getDriversLicNbr()==null?"":demo.getDriversLicNbr();
		this.driversLicNbrNew = driversLicNbrNew;
		this.driversLicSt = demo.getDriversLicSt()==null?"":demo.getDriversLicSt();
		this.driversLicStNew = driversLicStNew;
	
		if("A".equals(statCd.toString())) {
			this.apprvdDts = sdf.format(new Date()).substring(0, 16);
			this.apprvrUsrId = 0;
		}else {
			this.apprvdDts = "";
			this.apprvrUsrId = -1;
		}
		this.statCd = statCd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "reqDts", column = @Column(name = "REQ_DTS", nullable = false, length = 16)) })
	public BeaDrvsLicId getId() {
		return this.id;
	}

	public void setId(BeaDrvsLicId id) {
		this.id = id;
	}

	@Column(name = "DRIVERS_LIC_NBR", nullable = false, length = 19)
	public String getDriversLicNbr() {
		return this.driversLicNbr;
	}

	public void setDriversLicNbr(String driversLicNbr) {
		this.driversLicNbr = driversLicNbr;
	}

	@Column(name = "DRIVERS_LIC_ST", nullable = false, length = 2)
	public String getDriversLicSt() {
		return this.driversLicSt;
	}

	public void setDriversLicSt(String driversLicSt) {
		this.driversLicSt = driversLicSt;
	}

	@Column(name = "DRIVERS_LIC_NBR_NEW", nullable = false, length = 19)
	public String getDriversLicNbrNew() {
		return this.driversLicNbrNew;
	}

	public void setDriversLicNbrNew(String driversLicNbrNew) {
		this.driversLicNbrNew = driversLicNbrNew;
	}

	@Column(name = "DRIVERS_LIC_ST_NEW", nullable = false, length = 2)
	public String getDriversLicStNew() {
		return this.driversLicStNew;
	}

	public void setDriversLicStNew(String driversLicStNew) {
		this.driversLicStNew = driversLicStNew;
	}

	@Column(name = "APPRVD_DTS", nullable = false, length = 16)
	public String getApprvdDts() {
		return this.apprvdDts;
	}

	public void setApprvdDts(String apprvdDts) {
		this.apprvdDts = apprvdDts;
	}

	@Column(name = "APPRVR_USR_ID", nullable = false)
	public Integer getApprvrUsrId() {
		return this.apprvrUsrId;
	}

	public void setApprvrUsrId(Integer apprvrUsrId) {
		this.apprvrUsrId = apprvrUsrId;
	}

	@Column(name = "STAT_CD", nullable = false, length = 1)
	public Character getStatCd() {
		return this.statCd;
	}

	public void setStatCd(Character statCd) {
		this.statCd = statCd;
	}

}
