package com.esc20.model;
// Generated Jan 4, 2019 3:30:30 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BeaDrctDpstBnkAcctId generated by hbm2java
 */
@Embeddable
public class BeaDrctDpstBnkAcctId implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private char payFreq;
	private String empNbr;
	private String reqDts;
	private String bnkCd;
	private String bnkAcctNbr;
	private String bnkCdNew;
	private String bnkAcctNbrNew;

	public BeaDrctDpstBnkAcctId() {
	}

	public BeaDrctDpstBnkAcctId(char payFreq, String empNbr, String reqDts, String bnkCd, String bnkAcctNbr,
			String bnkCdNew, String bnkAcctNbrNew) {
		this.payFreq = payFreq;
		this.empNbr = empNbr;
		this.reqDts = reqDts;
		this.bnkCd = bnkCd;
		this.bnkAcctNbr = bnkAcctNbr;
		this.bnkCdNew = bnkCdNew;
		this.bnkAcctNbrNew = bnkAcctNbrNew;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "REQ_DTS", nullable = false, length = 16)
	public String getReqDts() {
		return this.reqDts;
	}

	public void setReqDts(String reqDts) {
		this.reqDts = reqDts;
	}

	@Column(name = "BNK_CD", nullable = false, length = 3)
	public String getBnkCd() {
		return this.bnkCd;
	}

	public void setBnkCd(String bnkCd) {
		this.bnkCd = bnkCd;
	}

	@Column(name = "BNK_ACCT_NBR", nullable = false, length = 17)
	public String getBnkAcctNbr() {
		return this.bnkAcctNbr;
	}

	public void setBnkAcctNbr(String bnkAcctNbr) {
		this.bnkAcctNbr = bnkAcctNbr;
	}

	@Column(name = "BNK_CD_NEW", nullable = false, length = 3)
	public String getBnkCdNew() {
		return this.bnkCdNew;
	}

	public void setBnkCdNew(String bnkCdNew) {
		this.bnkCdNew = bnkCdNew;
	}

	@Column(name = "BNK_ACCT_NBR_NEW", nullable = false, length = 17)
	public String getBnkAcctNbrNew() {
		return this.bnkAcctNbrNew;
	}

	public void setBnkAcctNbrNew(String bnkAcctNbrNew) {
		this.bnkAcctNbrNew = bnkAcctNbrNew;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BeaDrctDpstBnkAcctId))
			return false;
		BeaDrctDpstBnkAcctId castOther = (BeaDrctDpstBnkAcctId) other;

		return (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
						&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& ((this.getReqDts() == castOther.getReqDts()) || (this.getReqDts() != null
						&& castOther.getReqDts() != null && this.getReqDts().equals(castOther.getReqDts())))
				&& ((this.getBnkCd() == castOther.getBnkCd()) || (this.getBnkCd() != null
						&& castOther.getBnkCd() != null && this.getBnkCd().equals(castOther.getBnkCd())))
				&& ((this.getBnkAcctNbr() == castOther.getBnkAcctNbr()) || (this.getBnkAcctNbr() != null
						&& castOther.getBnkAcctNbr() != null && this.getBnkAcctNbr().equals(castOther.getBnkAcctNbr())))
				&& ((this.getBnkCdNew() == castOther.getBnkCdNew()) || (this.getBnkCdNew() != null
						&& castOther.getBnkCdNew() != null && this.getBnkCdNew().equals(castOther.getBnkCdNew())))
				&& ((this.getBnkAcctNbrNew() == castOther.getBnkAcctNbrNew())
						|| (this.getBnkAcctNbrNew() != null && castOther.getBnkAcctNbrNew() != null
								&& this.getBnkAcctNbrNew().equals(castOther.getBnkAcctNbrNew())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + (getReqDts() == null ? 0 : this.getReqDts().hashCode());
		result = 37 * result + (getBnkCd() == null ? 0 : this.getBnkCd().hashCode());
		result = 37 * result + (getBnkAcctNbr() == null ? 0 : this.getBnkAcctNbr().hashCode());
		result = 37 * result + (getBnkCdNew() == null ? 0 : this.getBnkCdNew().hashCode());
		result = 37 * result + (getBnkAcctNbrNew() == null ? 0 : this.getBnkAcctNbrNew().hashCode());
		return result;
	}

}
