package com.esc20.model;
// Generated Jan 4, 2019 3:36:22 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrAca1095cEmpId generated by hbm2java
 */
@Embeddable
public class BhrAca1095cEmpId implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private String empNbr;
	private String calYr;
	private String calMon;

	public BhrAca1095cEmpId() {
	}

	public BhrAca1095cEmpId(String empNbr, String calYr, String calMon) {
		this.empNbr = empNbr;
		this.calYr = calYr;
		this.calMon = calMon;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "CAL_YR", nullable = false, length = 4)
	public String getCalYr() {
		return this.calYr;
	}

	public void setCalYr(String calYr) {
		this.calYr = calYr;
	}

	@Column(name = "CAL_MON", nullable = false, length = 3)
	public String getCalMon() {
		return this.calMon;
	}

	public void setCalMon(String calMon) {
		this.calMon = calMon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrAca1095cEmpId))
			return false;
		BhrAca1095cEmpId castOther = (BhrAca1095cEmpId) other;

		return ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
				&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& ((this.getCalYr() == castOther.getCalYr()) || (this.getCalYr() != null
						&& castOther.getCalYr() != null && this.getCalYr().equals(castOther.getCalYr())))
				&& ((this.getCalMon() == castOther.getCalMon()) || (this.getCalMon() != null
						&& castOther.getCalMon() != null && this.getCalMon().equals(castOther.getCalMon())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + (getCalYr() == null ? 0 : this.getCalYr().hashCode());
		result = 37 * result + (getCalMon() == null ? 0 : this.getCalMon().hashCode());
		return result;
	}

}
