package com.esc20.model;
// Generated Jan 4, 2019 3:36:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BhrAcaAirEmpRecord generated by hbm2java
 */
@Entity
@Table(name = "BHR_ACA_AIR_EMP_RECORD", schema = "rsccc", catalog = "rsccc")
public class BhrAcaAirEmpRecord implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrAcaAirEmpRecordId id;
	private BhrAcaAirFileRun bhrAcaAirFileRun;
	private long recordNbr;

	public BhrAcaAirEmpRecord() {
	}

	public BhrAcaAirEmpRecord(BhrAcaAirEmpRecordId id, BhrAcaAirFileRun bhrAcaAirFileRun, long recordNbr) {
		this.id = id;
		this.bhrAcaAirFileRun = bhrAcaAirFileRun;
		this.recordNbr = recordNbr;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "runId", column = @Column(name = "RUN_ID", nullable = false)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)) })
	public BhrAcaAirEmpRecordId getId() {
		return this.id;
	}

	public void setId(BhrAcaAirEmpRecordId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RUN_ID", nullable = false, insertable = false, updatable = false)
	public BhrAcaAirFileRun getBhrAcaAirFileRun() {
		return this.bhrAcaAirFileRun;
	}

	public void setBhrAcaAirFileRun(BhrAcaAirFileRun bhrAcaAirFileRun) {
		this.bhrAcaAirFileRun = bhrAcaAirFileRun;
	}

	@Column(name = "RECORD_NBR", nullable = false, precision = 11, scale = 0)
	public long getRecordNbr() {
		return this.recordNbr;
	}

	public void setRecordNbr(long recordNbr) {
		this.recordNbr = recordNbr;
	}

}
