package com.esc20.model;
// Generated Jan 4, 2019 3:36:55 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrActHrsWrked generated by hbm2java
 */
@Entity
@Table(name = "BHR_ACT_HRS_WRKED", schema = "rsccc", catalog = "rsccc")
public class BhrActHrsWrked implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrActHrsWrkedId id;
	private BigDecimal actHrs;
	private String trsMon;
	private String module;

	public BhrActHrsWrked() {
	}

	public BhrActHrsWrked(BhrActHrsWrkedId id, BigDecimal actHrs, String trsMon, String module) {
		this.id = id;
		this.actHrs = actHrs;
		this.trsMon = trsMon;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "actDt", column = @Column(name = "ACT_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)) })
	public BhrActHrsWrkedId getId() {
		return this.id;
	}

	public void setId(BhrActHrsWrkedId id) {
		this.id = id;
	}

	@Column(name = "ACT_HRS", nullable = false, precision = 5)
	public BigDecimal getActHrs() {
		return this.actHrs;
	}

	public void setActHrs(BigDecimal actHrs) {
		this.actHrs = actHrs;
	}

	@Column(name = "TRS_MON", nullable = false, length = 2)
	public String getTrsMon() {
		return this.trsMon;
	}

	public void setTrsMon(String trsMon) {
		this.trsMon = trsMon;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
