package com.esc20.model;
// Generated Jan 4, 2019 3:32:17 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BhrAca1095bEmp generated by hbm2java
 */
@Entity
@Table(name = "BHR_ACA_1095B_EMP", schema = "rsccc", catalog = "rsccc")
public class BhrAca1095bEmp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6343783440902197038L;
	private BhrAca1095bEmpId id;
	private char covrgTyp;
	private String module;
	private Set<BhrAca1095bCovrd> bhrAca1095bCovrds = new HashSet<BhrAca1095bCovrd>(0);

	public BhrAca1095bEmp() {
	}

	public BhrAca1095bEmp(BhrAca1095bEmpId id, char covrgTyp, String module) {
		this.id = id;
		this.covrgTyp = covrgTyp;
		this.module = module;
	}

	public BhrAca1095bEmp(BhrAca1095bEmpId id, char covrgTyp, String module, Set<BhrAca1095bCovrd> bhrAca1095bCovrds) {
		this.id = id;
		this.covrgTyp = covrgTyp;
		this.module = module;
		this.bhrAca1095bCovrds = bhrAca1095bCovrds;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "calYr", column = @Column(name = "CAL_YR", nullable = false, length = 4)) })
	public BhrAca1095bEmpId getId() {
		return this.id;
	}

	public void setId(BhrAca1095bEmpId id) {
		this.id = id;
	}

	@Column(name = "COVRG_TYP", nullable = false, length = 1)
	public char getCovrgTyp() {
		return this.covrgTyp;
	}

	public void setCovrgTyp(char covrgTyp) {
		this.covrgTyp = covrgTyp;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bhrAca1095bEmp")
	public Set<BhrAca1095bCovrd> getBhrAca1095bCovrds() {
		return this.bhrAca1095bCovrds;
	}

	public void setBhrAca1095bCovrds(Set<BhrAca1095bCovrd> bhrAca1095bCovrds) {
		this.bhrAca1095bCovrds = bhrAca1095bCovrds;
	}

}
