package com.esc20.model;
// Generated Jan 4, 2019 3:38:21 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrBankRecordsBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_BANK_RECORDS_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrBankRecordsBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrBankRecordsBkupPaycalcs5Id id;

	public BhrBankRecordsBkupPaycalcs5() {
	}

	public BhrBankRecordsBkupPaycalcs5(BhrBankRecordsBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "bankCd", column = @Column(name = "BANK_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "bankDepositAmt", column = @Column(name = "BANK_DEPOSIT_AMT", nullable = false, precision = 11)),
			@AttributeOverride(name = "payrollRunTyp", column = @Column(name = "PAYROLL_RUN_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "chkCleared", column = @Column(name = "CHK_CLEARED", nullable = false, length = 1)),
			@AttributeOverride(name = "micrChkNbr", column = @Column(name = "MICR_CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "reconDts", column = @Column(name = "RECON_DTS", nullable = false, length = 16)) })
	public BhrBankRecordsBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrBankRecordsBkupPaycalcs5Id id) {
		this.id = id;
	}

}
