package com.esc20.model;
// Generated Jan 4, 2019 3:38:21 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrBankRecords generated by hbm2java
 */
@Entity
@Table(name = "BHR_BANK_RECORDS", schema = "rsccc", catalog = "rsccc")
public class BhrBankRecords implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrBankRecordsId id;
	private BigDecimal bankDepositAmt;
	private char payrollRunTyp;
	private char chkCleared;
	private String micrChkNbr;
	private String reconDts;

	public BhrBankRecords() {
	}

	public BhrBankRecords(BhrBankRecordsId id, BigDecimal bankDepositAmt, char payrollRunTyp, char chkCleared,
			String micrChkNbr, String reconDts) {
		this.id = id;
		this.bankDepositAmt = bankDepositAmt;
		this.payrollRunTyp = payrollRunTyp;
		this.chkCleared = chkCleared;
		this.micrChkNbr = micrChkNbr;
		this.reconDts = reconDts;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "bankCd", column = @Column(name = "BANK_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)) })
	public BhrBankRecordsId getId() {
		return this.id;
	}

	public void setId(BhrBankRecordsId id) {
		this.id = id;
	}

	@Column(name = "BANK_DEPOSIT_AMT", nullable = false, precision = 11)
	public BigDecimal getBankDepositAmt() {
		return this.bankDepositAmt;
	}

	public void setBankDepositAmt(BigDecimal bankDepositAmt) {
		this.bankDepositAmt = bankDepositAmt;
	}

	@Column(name = "PAYROLL_RUN_TYP", nullable = false, length = 1)
	public char getPayrollRunTyp() {
		return this.payrollRunTyp;
	}

	public void setPayrollRunTyp(char payrollRunTyp) {
		this.payrollRunTyp = payrollRunTyp;
	}

	@Column(name = "CHK_CLEARED", nullable = false, length = 1)
	public char getChkCleared() {
		return this.chkCleared;
	}

	public void setChkCleared(char chkCleared) {
		this.chkCleared = chkCleared;
	}

	@Column(name = "MICR_CHK_NBR", nullable = false, length = 6)
	public String getMicrChkNbr() {
		return this.micrChkNbr;
	}

	public void setMicrChkNbr(String micrChkNbr) {
		this.micrChkNbr = micrChkNbr;
	}

	@Column(name = "RECON_DTS", nullable = false, length = 16)
	public String getReconDts() {
		return this.reconDts;
	}

	public void setReconDts(String reconDts) {
		this.reconDts = reconDts;
	}

}
