package com.esc20.model;
// Generated Jan 4, 2019 3:38:21 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrBankDepositBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_BANK_DEPOSIT_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrBankDepositBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrBankDepositBkupPaycalcs5Id id;

	public BhrBankDepositBkupPaycalcs5() {
	}

	public BhrBankDepositBkupPaycalcs5(BhrBankDepositBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "bankCd", column = @Column(name = "BANK_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "bankAcctNbr", column = @Column(name = "BANK_ACCT_NBR", nullable = false, length = 17)),
			@AttributeOverride(name = "bankAcctTyp", column = @Column(name = "BANK_ACCT_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "bankStat", column = @Column(name = "BANK_STAT", nullable = false, length = 1)),
			@AttributeOverride(name = "bankAcctAmt", column = @Column(name = "BANK_ACCT_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BhrBankDepositBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrBankDepositBkupPaycalcs5Id id) {
		this.id = id;
	}

}
