package com.esc20.model;
// Generated Jan 4, 2019 3:38:21 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrBankDepositBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BhrBankDepositBkupPaycalcs5Id implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private char cyrNyrFlg;
	private char payFreq;
	private String empNbr;
	private String bankCd;
	private String bankAcctNbr;
	private char bankAcctTyp;
	private char bankStat;
	private BigDecimal bankAcctAmt;
	private String module;

	public BhrBankDepositBkupPaycalcs5Id() {
	}

	public BhrBankDepositBkupPaycalcs5Id(char cyrNyrFlg, char payFreq, String empNbr, String bankCd, String bankAcctNbr,
			char bankAcctTyp, char bankStat, BigDecimal bankAcctAmt, String module) {
		this.cyrNyrFlg = cyrNyrFlg;
		this.payFreq = payFreq;
		this.empNbr = empNbr;
		this.bankCd = bankCd;
		this.bankAcctNbr = bankAcctNbr;
		this.bankAcctTyp = bankAcctTyp;
		this.bankStat = bankStat;
		this.bankAcctAmt = bankAcctAmt;
		this.module = module;
	}

	@Column(name = "CYR_NYR_FLG", nullable = false, length = 1)
	public char getCyrNyrFlg() {
		return this.cyrNyrFlg;
	}

	public void setCyrNyrFlg(char cyrNyrFlg) {
		this.cyrNyrFlg = cyrNyrFlg;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "BANK_CD", nullable = false, length = 3)
	public String getBankCd() {
		return this.bankCd;
	}

	public void setBankCd(String bankCd) {
		this.bankCd = bankCd;
	}

	@Column(name = "BANK_ACCT_NBR", nullable = false, length = 17)
	public String getBankAcctNbr() {
		return this.bankAcctNbr;
	}

	public void setBankAcctNbr(String bankAcctNbr) {
		this.bankAcctNbr = bankAcctNbr;
	}

	@Column(name = "BANK_ACCT_TYP", nullable = false, length = 1)
	public char getBankAcctTyp() {
		return this.bankAcctTyp;
	}

	public void setBankAcctTyp(char bankAcctTyp) {
		this.bankAcctTyp = bankAcctTyp;
	}

	@Column(name = "BANK_STAT", nullable = false, length = 1)
	public char getBankStat() {
		return this.bankStat;
	}

	public void setBankStat(char bankStat) {
		this.bankStat = bankStat;
	}

	@Column(name = "BANK_ACCT_AMT", nullable = false, precision = 9)
	public BigDecimal getBankAcctAmt() {
		return this.bankAcctAmt;
	}

	public void setBankAcctAmt(BigDecimal bankAcctAmt) {
		this.bankAcctAmt = bankAcctAmt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrBankDepositBkupPaycalcs5Id))
			return false;
		BhrBankDepositBkupPaycalcs5Id castOther = (BhrBankDepositBkupPaycalcs5Id) other;

		return (this.getCyrNyrFlg() == castOther.getCyrNyrFlg()) && (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
						&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& ((this.getBankCd() == castOther.getBankCd()) || (this.getBankCd() != null
						&& castOther.getBankCd() != null && this.getBankCd().equals(castOther.getBankCd())))
				&& ((this.getBankAcctNbr() == castOther.getBankAcctNbr())
						|| (this.getBankAcctNbr() != null && castOther.getBankAcctNbr() != null
								&& this.getBankAcctNbr().equals(castOther.getBankAcctNbr())))
				&& (this.getBankAcctTyp() == castOther.getBankAcctTyp())
				&& (this.getBankStat() == castOther.getBankStat())
				&& ((this.getBankAcctAmt() == castOther.getBankAcctAmt())
						|| (this.getBankAcctAmt() != null && castOther.getBankAcctAmt() != null
								&& this.getBankAcctAmt().equals(castOther.getBankAcctAmt())))
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCyrNyrFlg();
		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + (getBankCd() == null ? 0 : this.getBankCd().hashCode());
		result = 37 * result + (getBankAcctNbr() == null ? 0 : this.getBankAcctNbr().hashCode());
		result = 37 * result + this.getBankAcctTyp();
		result = 37 * result + this.getBankStat();
		result = 37 * result + (getBankAcctAmt() == null ? 0 : this.getBankAcctAmt().hashCode());
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		return result;
	}

}
