package com.esc20.model;
// Generated Jan 4, 2019 3:39:11 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrCollege generated by hbm2java
 */
@Entity
@Table(name = "BHR_COLLEGE", schema = "rsccc", catalog = "rsccc")
public class BhrCollege implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrCollegeId id;
	private String collegeCd;
	private String collegeMajor;
	private String collegeMinor;
	private char degreeTyp;
	private String degreeYr;
	private String module;

	public BhrCollege() {
	}

	public BhrCollege(BhrCollegeId id, String collegeCd, String collegeMajor, String collegeMinor, char degreeTyp,
			String degreeYr, String module) {
		this.id = id;
		this.collegeCd = collegeCd;
		this.collegeMajor = collegeMajor;
		this.collegeMinor = collegeMinor;
		this.degreeTyp = degreeTyp;
		this.degreeYr = degreeYr;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dts", column = @Column(name = "DTS", nullable = false, length = 16)) })
	public BhrCollegeId getId() {
		return this.id;
	}

	public void setId(BhrCollegeId id) {
		this.id = id;
	}

	@Column(name = "COLLEGE_CD", nullable = false, length = 6)
	public String getCollegeCd() {
		return this.collegeCd;
	}

	public void setCollegeCd(String collegeCd) {
		this.collegeCd = collegeCd;
	}

	@Column(name = "COLLEGE_MAJOR", nullable = false, length = 2)
	public String getCollegeMajor() {
		return this.collegeMajor;
	}

	public void setCollegeMajor(String collegeMajor) {
		this.collegeMajor = collegeMajor;
	}

	@Column(name = "COLLEGE_MINOR", nullable = false, length = 2)
	public String getCollegeMinor() {
		return this.collegeMinor;
	}

	public void setCollegeMinor(String collegeMinor) {
		this.collegeMinor = collegeMinor;
	}

	@Column(name = "DEGREE_TYP", nullable = false, length = 1)
	public char getDegreeTyp() {
		return this.degreeTyp;
	}

	public void setDegreeTyp(char degreeTyp) {
		this.degreeTyp = degreeTyp;
	}

	@Column(name = "DEGREE_YR", nullable = false, length = 4)
	public String getDegreeYr() {
		return this.degreeYr;
	}

	public void setDegreeYr(String degreeYr) {
		this.degreeYr = degreeYr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
