package com.esc20.model;
// Generated Jan 4, 2019 3:38:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BhrCalSchDays generated by hbm2java
 */
@Entity
@Table(name = "BHR_CAL_SCH_DAYS", schema = "rsccc", catalog = "rsccc")
public class BhrCalSchDays implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrCalSchDaysId id;
	private BhrCalSch bhrCalSch;
	private String julDay;
	private String julYr;
	private String module;

	public BhrCalSchDays() {
	}

	public BhrCalSchDays(BhrCalSchDaysId id, BhrCalSch bhrCalSch, String julDay, String julYr, String module) {
		this.id = id;
		this.bhrCalSch = bhrCalSch;
		this.julDay = julDay;
		this.julYr = julYr;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "calCd", column = @Column(name = "CAL_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dayDate", column = @Column(name = "DAY_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "dayTyp", column = @Column(name = "DAY_TYP", nullable = false, length = 1)) })
	public BhrCalSchDaysId getId() {
		return this.id;
	}

	public void setId(BhrCalSchDaysId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PAY_FREQ", referencedColumnName = "CAL_CD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CAL_CD", referencedColumnName = "PAY_FREQ", nullable = false, insertable = false, updatable = false) })
	public BhrCalSch getBhrCalSch() {
		return this.bhrCalSch;
	}

	public void setBhrCalSch(BhrCalSch bhrCalSch) {
		this.bhrCalSch = bhrCalSch;
	}

	@Column(name = "JUL_DAY", nullable = false, length = 3)
	public String getJulDay() {
		return this.julDay;
	}

	public void setJulDay(String julDay) {
		this.julDay = julDay;
	}

	@Column(name = "JUL_YR", nullable = false, length = 4)
	public String getJulYr() {
		return this.julYr;
	}

	public void setJulYr(String julYr) {
		this.julYr = julYr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
