package com.esc20.model;
// Generated Jan 4, 2019 3:38:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrCalYtdBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_CAL_YTD_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrCalYtdBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrCalYtdBkupPaycalcs5Id id;

	public BhrCalYtdBkupPaycalcs5() {
	}

	public BhrCalYtdBkupPaycalcs5(BhrCalYtdBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "calYr", column = @Column(name = "CAL_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "ficaTyp", column = @Column(name = "FICA_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "contrAmt", column = @Column(name = "CONTR_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "noncontrAmt", column = @Column(name = "NONCONTR_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "supplPayAmt", column = @Column(name = "SUPPL_PAY_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "annuityDed", column = @Column(name = "ANNUITY_DED", nullable = false, precision = 9)),
			@AttributeOverride(name = "ficaTax", column = @Column(name = "FICA_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "ficaGross", column = @Column(name = "FICA_GROSS", nullable = false, precision = 9)),
			@AttributeOverride(name = "unempIns", column = @Column(name = "UNEMP_INS", nullable = false, precision = 9)),
			@AttributeOverride(name = "unempGross", column = @Column(name = "UNEMP_GROSS", nullable = false, precision = 9)),
			@AttributeOverride(name = "eicAmt", column = @Column(name = "EIC_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "whGross", column = @Column(name = "WH_GROSS", nullable = false, precision = 9)),
			@AttributeOverride(name = "whTax", column = @Column(name = "WH_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "hlthInsDed", column = @Column(name = "HLTH_INS_DED", nullable = false, precision = 7)),
			@AttributeOverride(name = "dependCare", column = @Column(name = "DEPEND_CARE", nullable = false, precision = 9)),
			@AttributeOverride(name = "taxedBenefits", column = @Column(name = "TAXED_BENEFITS", nullable = false, precision = 9)),
			@AttributeOverride(name = "trsDeposit", column = @Column(name = "TRS_DEPOSIT", nullable = false, precision = 9)),
			@AttributeOverride(name = "trsSalaryRed", column = @Column(name = "TRS_SALARY_RED", nullable = false, precision = 9)),
			@AttributeOverride(name = "movingExpReimbr", column = @Column(name = "MOVING_EXP_REIMBR", nullable = false, precision = 9)),
			@AttributeOverride(name = "emplr457Contrib", column = @Column(name = "EMPLR_457_CONTRIB", nullable = false, precision = 7)),
			@AttributeOverride(name = "emp457Contrib", column = @Column(name = "EMP_457_CONTRIB", nullable = false, precision = 7)),
			@AttributeOverride(name = "withdraw457", column = @Column(name = "WITHDRAW_457", nullable = false, precision = 7)),
			@AttributeOverride(name = "empBusinessExpense", column = @Column(name = "EMP_BUSINESS_EXPENSE", nullable = false, precision = 7)),
			@AttributeOverride(name = "taxEmplrLife", column = @Column(name = "TAX_EMPLR_LIFE", nullable = false, precision = 9)),
			@AttributeOverride(name = "taxEmplrLifeGrp", column = @Column(name = "TAX_EMPLR_LIFE_GRP", nullable = false, precision = 9)),
			@AttributeOverride(name = "cafeAmt", column = @Column(name = "CAFE_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "qtrUnemplGross", column = @Column(name = "QTR_UNEMPL_GROSS", nullable = false, precision = 9)),
			@AttributeOverride(name = "medTax", column = @Column(name = "MED_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "medGross", column = @Column(name = "MED_GROSS", nullable = false, precision = 9)),
			@AttributeOverride(name = "nontrsReimbrExcess", column = @Column(name = "NONTRS_REIMBR_EXCESS", nullable = false, precision = 9)),
			@AttributeOverride(name = "nontrsReimbrBase", column = @Column(name = "NONTRS_REIMBR_BASE", nullable = false, precision = 9)),
			@AttributeOverride(name = "nontrsBusAllow", column = @Column(name = "NONTRS_BUS_ALLOW", nullable = false, precision = 9)),
			@AttributeOverride(name = "nontrsNontaxBusAllow", column = @Column(name = "NONTRS_NONTAX_BUS_ALLOW", nullable = false, precision = 9)),
			@AttributeOverride(name = "trsSupplComp", column = @Column(name = "TRS_SUPPL_COMP", nullable = false, precision = 7)),
			@AttributeOverride(name = "teaHealthInsContrib", column = @Column(name = "TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)),
			@AttributeOverride(name = "nontrsNonpayBusAllow", column = @Column(name = "NONTRS_NONPAY_BUS_ALLOW", nullable = false, precision = 9)),
			@AttributeOverride(name = "nontrsNontaxNonpayAllow", column = @Column(name = "NONTRS_NONTAX_NONPAY_ALLOW", nullable = false, precision = 9)),
			@AttributeOverride(name = "emplrDependCare", column = @Column(name = "EMPLR_DEPEND_CARE", nullable = false, precision = 9)),
			@AttributeOverride(name = "annuityRoth", column = @Column(name = "ANNUITY_ROTH", nullable = false, precision = 9)),
			@AttributeOverride(name = "emplrDependCareTax", column = @Column(name = "EMPLR_DEPEND_CARE_TAX", nullable = false, precision = 7)),
			@AttributeOverride(name = "hsaEmpSalRedctnContrib", column = @Column(name = "HSA_EMP_SAL_REDCTN_CONTRIB", nullable = false, precision = 9)),
			@AttributeOverride(name = "hsaEmplrContrib", column = @Column(name = "HSA_EMPLR_CONTRIB", nullable = false, precision = 9)),
			@AttributeOverride(name = "hireExemptWgs", column = @Column(name = "HIRE_EXEMPT_WGS", nullable = false, precision = 9)),
			@AttributeOverride(name = "emplrPrvdHlthcare", column = @Column(name = "EMPLR_PRVD_HLTHCARE", nullable = false, precision = 9)),
			@AttributeOverride(name = "emplrFicaTax", column = @Column(name = "EMPLR_FICA_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "emplrMedTax", column = @Column(name = "EMPLR_MED_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "annuityRoth457b", column = @Column(name = "ANNUITY_ROTH_457B", nullable = false, precision = 9)) })
	public BhrCalYtdBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrCalYtdBkupPaycalcs5Id id) {
		this.id = id;
	}

}
