package com.esc20.model;
// Generated Jan 4, 2019 3:38:35 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrCalYtd generated by hbm2java
 */
@Entity
@Table(name = "BHR_CAL_YTD", schema = "rsccc", catalog = "rsccc")
public class BhrCalYtd implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrCalYtdId id;
	private char ficaTyp;
	private BigDecimal contrAmt;
	private BigDecimal noncontrAmt;
	private BigDecimal supplPayAmt;
	private BigDecimal annuityDed;
	private BigDecimal ficaTax;
	private BigDecimal ficaGross;
	private BigDecimal unempIns;
	private BigDecimal unempGross;
	private BigDecimal eicAmt;
	private BigDecimal whGross;
	private BigDecimal whTax;
	private BigDecimal hlthInsDed;
	private BigDecimal dependCare;
	private BigDecimal taxedBenefits;
	private BigDecimal trsDeposit;
	private BigDecimal trsSalaryRed;
	private BigDecimal movingExpReimbr;
	private BigDecimal emplr457Contrib;
	private BigDecimal emp457Contrib;
	private BigDecimal withdraw457;
	private BigDecimal empBusinessExpense;
	private BigDecimal taxEmplrLife;
	private BigDecimal taxEmplrLifeGrp;
	private BigDecimal cafeAmt;
	private BigDecimal qtrUnemplGross;
	private BigDecimal medTax;
	private BigDecimal medGross;
	private BigDecimal nontrsReimbrExcess;
	private BigDecimal nontrsReimbrBase;
	private BigDecimal nontrsBusAllow;
	private BigDecimal nontrsNontaxBusAllow;
	private BigDecimal trsSupplComp;
	private BigDecimal teaHealthInsContrib;
	private BigDecimal nontrsNonpayBusAllow;
	private BigDecimal nontrsNontaxNonpayAllow;
	private BigDecimal emplrDependCare;
	private BigDecimal annuityRoth;
	private BigDecimal emplrDependCareTax;
	private BigDecimal hsaEmpSalRedctnContrib;
	private BigDecimal hsaEmplrContrib;
	private BigDecimal hireExemptWgs;
	private BigDecimal emplrPrvdHlthcare;
	private BigDecimal emplrFicaTax;
	private String module;
	private BigDecimal emplrMedTax;
	private BigDecimal annuityRoth457b;

	public BhrCalYtd() {
	}

	public BhrCalYtd(BhrCalYtdId id, char ficaTyp, BigDecimal contrAmt, BigDecimal noncontrAmt, BigDecimal supplPayAmt,
			BigDecimal annuityDed, BigDecimal ficaTax, BigDecimal ficaGross, BigDecimal unempIns, BigDecimal unempGross,
			BigDecimal eicAmt, BigDecimal whGross, BigDecimal whTax, BigDecimal hlthInsDed, BigDecimal dependCare,
			BigDecimal taxedBenefits, BigDecimal trsDeposit, BigDecimal trsSalaryRed, BigDecimal movingExpReimbr,
			BigDecimal emplr457Contrib, BigDecimal emp457Contrib, BigDecimal withdraw457, BigDecimal empBusinessExpense,
			BigDecimal taxEmplrLife, BigDecimal taxEmplrLifeGrp, BigDecimal cafeAmt, BigDecimal qtrUnemplGross,
			BigDecimal medTax, BigDecimal medGross, BigDecimal nontrsReimbrExcess, BigDecimal nontrsReimbrBase,
			BigDecimal nontrsBusAllow, BigDecimal nontrsNontaxBusAllow, BigDecimal trsSupplComp,
			BigDecimal teaHealthInsContrib, BigDecimal nontrsNonpayBusAllow, BigDecimal nontrsNontaxNonpayAllow,
			BigDecimal emplrDependCare, BigDecimal annuityRoth, BigDecimal emplrDependCareTax,
			BigDecimal hsaEmpSalRedctnContrib, BigDecimal hsaEmplrContrib, BigDecimal hireExemptWgs,
			BigDecimal emplrPrvdHlthcare, BigDecimal emplrFicaTax, String module, BigDecimal emplrMedTax,
			BigDecimal annuityRoth457b) {
		this.id = id;
		this.ficaTyp = ficaTyp;
		this.contrAmt = contrAmt;
		this.noncontrAmt = noncontrAmt;
		this.supplPayAmt = supplPayAmt;
		this.annuityDed = annuityDed;
		this.ficaTax = ficaTax;
		this.ficaGross = ficaGross;
		this.unempIns = unempIns;
		this.unempGross = unempGross;
		this.eicAmt = eicAmt;
		this.whGross = whGross;
		this.whTax = whTax;
		this.hlthInsDed = hlthInsDed;
		this.dependCare = dependCare;
		this.taxedBenefits = taxedBenefits;
		this.trsDeposit = trsDeposit;
		this.trsSalaryRed = trsSalaryRed;
		this.movingExpReimbr = movingExpReimbr;
		this.emplr457Contrib = emplr457Contrib;
		this.emp457Contrib = emp457Contrib;
		this.withdraw457 = withdraw457;
		this.empBusinessExpense = empBusinessExpense;
		this.taxEmplrLife = taxEmplrLife;
		this.taxEmplrLifeGrp = taxEmplrLifeGrp;
		this.cafeAmt = cafeAmt;
		this.qtrUnemplGross = qtrUnemplGross;
		this.medTax = medTax;
		this.medGross = medGross;
		this.nontrsReimbrExcess = nontrsReimbrExcess;
		this.nontrsReimbrBase = nontrsReimbrBase;
		this.nontrsBusAllow = nontrsBusAllow;
		this.nontrsNontaxBusAllow = nontrsNontaxBusAllow;
		this.trsSupplComp = trsSupplComp;
		this.teaHealthInsContrib = teaHealthInsContrib;
		this.nontrsNonpayBusAllow = nontrsNonpayBusAllow;
		this.nontrsNontaxNonpayAllow = nontrsNontaxNonpayAllow;
		this.emplrDependCare = emplrDependCare;
		this.annuityRoth = annuityRoth;
		this.emplrDependCareTax = emplrDependCareTax;
		this.hsaEmpSalRedctnContrib = hsaEmpSalRedctnContrib;
		this.hsaEmplrContrib = hsaEmplrContrib;
		this.hireExemptWgs = hireExemptWgs;
		this.emplrPrvdHlthcare = emplrPrvdHlthcare;
		this.emplrFicaTax = emplrFicaTax;
		this.module = module;
		this.emplrMedTax = emplrMedTax;
		this.annuityRoth457b = annuityRoth457b;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "calYr", column = @Column(name = "CAL_YR", nullable = false, length = 4)) })
	public BhrCalYtdId getId() {
		return this.id;
	}

	public void setId(BhrCalYtdId id) {
		this.id = id;
	}

	@Column(name = "FICA_TYP", nullable = false, length = 1)
	public char getFicaTyp() {
		return this.ficaTyp;
	}

	public void setFicaTyp(char ficaTyp) {
		this.ficaTyp = ficaTyp;
	}

	@Column(name = "CONTR_AMT", nullable = false, precision = 9)
	public BigDecimal getContrAmt() {
		return this.contrAmt;
	}

	public void setContrAmt(BigDecimal contrAmt) {
		this.contrAmt = contrAmt;
	}

	@Column(name = "NONCONTR_AMT", nullable = false, precision = 9)
	public BigDecimal getNoncontrAmt() {
		return this.noncontrAmt;
	}

	public void setNoncontrAmt(BigDecimal noncontrAmt) {
		this.noncontrAmt = noncontrAmt;
	}

	@Column(name = "SUPPL_PAY_AMT", nullable = false, precision = 9)
	public BigDecimal getSupplPayAmt() {
		return this.supplPayAmt;
	}

	public void setSupplPayAmt(BigDecimal supplPayAmt) {
		this.supplPayAmt = supplPayAmt;
	}

	@Column(name = "ANNUITY_DED", nullable = false, precision = 9)
	public BigDecimal getAnnuityDed() {
		return this.annuityDed;
	}

	public void setAnnuityDed(BigDecimal annuityDed) {
		this.annuityDed = annuityDed;
	}

	@Column(name = "FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getFicaTax() {
		return this.ficaTax;
	}

	public void setFicaTax(BigDecimal ficaTax) {
		this.ficaTax = ficaTax;
	}

	@Column(name = "FICA_GROSS", nullable = false, precision = 9)
	public BigDecimal getFicaGross() {
		return this.ficaGross;
	}

	public void setFicaGross(BigDecimal ficaGross) {
		this.ficaGross = ficaGross;
	}

	@Column(name = "UNEMP_INS", nullable = false, precision = 9)
	public BigDecimal getUnempIns() {
		return this.unempIns;
	}

	public void setUnempIns(BigDecimal unempIns) {
		this.unempIns = unempIns;
	}

	@Column(name = "UNEMP_GROSS", nullable = false, precision = 9)
	public BigDecimal getUnempGross() {
		return this.unempGross;
	}

	public void setUnempGross(BigDecimal unempGross) {
		this.unempGross = unempGross;
	}

	@Column(name = "EIC_AMT", nullable = false, precision = 9)
	public BigDecimal getEicAmt() {
		return this.eicAmt;
	}

	public void setEicAmt(BigDecimal eicAmt) {
		this.eicAmt = eicAmt;
	}

	@Column(name = "WH_GROSS", nullable = false, precision = 9)
	public BigDecimal getWhGross() {
		return this.whGross;
	}

	public void setWhGross(BigDecimal whGross) {
		this.whGross = whGross;
	}

	@Column(name = "WH_TAX", nullable = false, precision = 9)
	public BigDecimal getWhTax() {
		return this.whTax;
	}

	public void setWhTax(BigDecimal whTax) {
		this.whTax = whTax;
	}

	@Column(name = "HLTH_INS_DED", nullable = false, precision = 7)
	public BigDecimal getHlthInsDed() {
		return this.hlthInsDed;
	}

	public void setHlthInsDed(BigDecimal hlthInsDed) {
		this.hlthInsDed = hlthInsDed;
	}

	@Column(name = "DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getDependCare() {
		return this.dependCare;
	}

	public void setDependCare(BigDecimal dependCare) {
		this.dependCare = dependCare;
	}

	@Column(name = "TAXED_BENEFITS", nullable = false, precision = 9)
	public BigDecimal getTaxedBenefits() {
		return this.taxedBenefits;
	}

	public void setTaxedBenefits(BigDecimal taxedBenefits) {
		this.taxedBenefits = taxedBenefits;
	}

	@Column(name = "TRS_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getTrsDeposit() {
		return this.trsDeposit;
	}

	public void setTrsDeposit(BigDecimal trsDeposit) {
		this.trsDeposit = trsDeposit;
	}

	@Column(name = "TRS_SALARY_RED", nullable = false, precision = 9)
	public BigDecimal getTrsSalaryRed() {
		return this.trsSalaryRed;
	}

	public void setTrsSalaryRed(BigDecimal trsSalaryRed) {
		this.trsSalaryRed = trsSalaryRed;
	}

	@Column(name = "MOVING_EXP_REIMBR", nullable = false, precision = 9)
	public BigDecimal getMovingExpReimbr() {
		return this.movingExpReimbr;
	}

	public void setMovingExpReimbr(BigDecimal movingExpReimbr) {
		this.movingExpReimbr = movingExpReimbr;
	}

	@Column(name = "EMPLR_457_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getEmplr457Contrib() {
		return this.emplr457Contrib;
	}

	public void setEmplr457Contrib(BigDecimal emplr457Contrib) {
		this.emplr457Contrib = emplr457Contrib;
	}

	@Column(name = "EMP_457_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getEmp457Contrib() {
		return this.emp457Contrib;
	}

	public void setEmp457Contrib(BigDecimal emp457Contrib) {
		this.emp457Contrib = emp457Contrib;
	}

	@Column(name = "WITHDRAW_457", nullable = false, precision = 7)
	public BigDecimal getWithdraw457() {
		return this.withdraw457;
	}

	public void setWithdraw457(BigDecimal withdraw457) {
		this.withdraw457 = withdraw457;
	}

	@Column(name = "EMP_BUSINESS_EXPENSE", nullable = false, precision = 7)
	public BigDecimal getEmpBusinessExpense() {
		return this.empBusinessExpense;
	}

	public void setEmpBusinessExpense(BigDecimal empBusinessExpense) {
		this.empBusinessExpense = empBusinessExpense;
	}

	@Column(name = "TAX_EMPLR_LIFE", nullable = false, precision = 9)
	public BigDecimal getTaxEmplrLife() {
		return this.taxEmplrLife;
	}

	public void setTaxEmplrLife(BigDecimal taxEmplrLife) {
		this.taxEmplrLife = taxEmplrLife;
	}

	@Column(name = "TAX_EMPLR_LIFE_GRP", nullable = false, precision = 9)
	public BigDecimal getTaxEmplrLifeGrp() {
		return this.taxEmplrLifeGrp;
	}

	public void setTaxEmplrLifeGrp(BigDecimal taxEmplrLifeGrp) {
		this.taxEmplrLifeGrp = taxEmplrLifeGrp;
	}

	@Column(name = "CAFE_AMT", nullable = false, precision = 9)
	public BigDecimal getCafeAmt() {
		return this.cafeAmt;
	}

	public void setCafeAmt(BigDecimal cafeAmt) {
		this.cafeAmt = cafeAmt;
	}

	@Column(name = "QTR_UNEMPL_GROSS", nullable = false, precision = 9)
	public BigDecimal getQtrUnemplGross() {
		return this.qtrUnemplGross;
	}

	public void setQtrUnemplGross(BigDecimal qtrUnemplGross) {
		this.qtrUnemplGross = qtrUnemplGross;
	}

	@Column(name = "MED_TAX", nullable = false, precision = 9)
	public BigDecimal getMedTax() {
		return this.medTax;
	}

	public void setMedTax(BigDecimal medTax) {
		this.medTax = medTax;
	}

	@Column(name = "MED_GROSS", nullable = false, precision = 9)
	public BigDecimal getMedGross() {
		return this.medGross;
	}

	public void setMedGross(BigDecimal medGross) {
		this.medGross = medGross;
	}

	@Column(name = "NONTRS_REIMBR_EXCESS", nullable = false, precision = 9)
	public BigDecimal getNontrsReimbrExcess() {
		return this.nontrsReimbrExcess;
	}

	public void setNontrsReimbrExcess(BigDecimal nontrsReimbrExcess) {
		this.nontrsReimbrExcess = nontrsReimbrExcess;
	}

	@Column(name = "NONTRS_REIMBR_BASE", nullable = false, precision = 9)
	public BigDecimal getNontrsReimbrBase() {
		return this.nontrsReimbrBase;
	}

	public void setNontrsReimbrBase(BigDecimal nontrsReimbrBase) {
		this.nontrsReimbrBase = nontrsReimbrBase;
	}

	@Column(name = "NONTRS_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsBusAllow() {
		return this.nontrsBusAllow;
	}

	public void setNontrsBusAllow(BigDecimal nontrsBusAllow) {
		this.nontrsBusAllow = nontrsBusAllow;
	}

	@Column(name = "NONTRS_NONTAX_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsNontaxBusAllow() {
		return this.nontrsNontaxBusAllow;
	}

	public void setNontrsNontaxBusAllow(BigDecimal nontrsNontaxBusAllow) {
		this.nontrsNontaxBusAllow = nontrsNontaxBusAllow;
	}

	@Column(name = "TRS_SUPPL_COMP", nullable = false, precision = 7)
	public BigDecimal getTrsSupplComp() {
		return this.trsSupplComp;
	}

	public void setTrsSupplComp(BigDecimal trsSupplComp) {
		this.trsSupplComp = trsSupplComp;
	}

	@Column(name = "TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getTeaHealthInsContrib() {
		return this.teaHealthInsContrib;
	}

	public void setTeaHealthInsContrib(BigDecimal teaHealthInsContrib) {
		this.teaHealthInsContrib = teaHealthInsContrib;
	}

	@Column(name = "NONTRS_NONPAY_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsNonpayBusAllow() {
		return this.nontrsNonpayBusAllow;
	}

	public void setNontrsNonpayBusAllow(BigDecimal nontrsNonpayBusAllow) {
		this.nontrsNonpayBusAllow = nontrsNonpayBusAllow;
	}

	@Column(name = "NONTRS_NONTAX_NONPAY_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsNontaxNonpayAllow() {
		return this.nontrsNontaxNonpayAllow;
	}

	public void setNontrsNontaxNonpayAllow(BigDecimal nontrsNontaxNonpayAllow) {
		this.nontrsNontaxNonpayAllow = nontrsNontaxNonpayAllow;
	}

	@Column(name = "EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getEmplrDependCare() {
		return this.emplrDependCare;
	}

	public void setEmplrDependCare(BigDecimal emplrDependCare) {
		this.emplrDependCare = emplrDependCare;
	}

	@Column(name = "ANNUITY_ROTH", nullable = false, precision = 9)
	public BigDecimal getAnnuityRoth() {
		return this.annuityRoth;
	}

	public void setAnnuityRoth(BigDecimal annuityRoth) {
		this.annuityRoth = annuityRoth;
	}

	@Column(name = "EMPLR_DEPEND_CARE_TAX", nullable = false, precision = 7)
	public BigDecimal getEmplrDependCareTax() {
		return this.emplrDependCareTax;
	}

	public void setEmplrDependCareTax(BigDecimal emplrDependCareTax) {
		this.emplrDependCareTax = emplrDependCareTax;
	}

	@Column(name = "HSA_EMP_SAL_REDCTN_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getHsaEmpSalRedctnContrib() {
		return this.hsaEmpSalRedctnContrib;
	}

	public void setHsaEmpSalRedctnContrib(BigDecimal hsaEmpSalRedctnContrib) {
		this.hsaEmpSalRedctnContrib = hsaEmpSalRedctnContrib;
	}

	@Column(name = "HSA_EMPLR_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getHsaEmplrContrib() {
		return this.hsaEmplrContrib;
	}

	public void setHsaEmplrContrib(BigDecimal hsaEmplrContrib) {
		this.hsaEmplrContrib = hsaEmplrContrib;
	}

	@Column(name = "HIRE_EXEMPT_WGS", nullable = false, precision = 9)
	public BigDecimal getHireExemptWgs() {
		return this.hireExemptWgs;
	}

	public void setHireExemptWgs(BigDecimal hireExemptWgs) {
		this.hireExemptWgs = hireExemptWgs;
	}

	@Column(name = "EMPLR_PRVD_HLTHCARE", nullable = false, precision = 9)
	public BigDecimal getEmplrPrvdHlthcare() {
		return this.emplrPrvdHlthcare;
	}

	public void setEmplrPrvdHlthcare(BigDecimal emplrPrvdHlthcare) {
		this.emplrPrvdHlthcare = emplrPrvdHlthcare;
	}

	@Column(name = "EMPLR_FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getEmplrFicaTax() {
		return this.emplrFicaTax;
	}

	public void setEmplrFicaTax(BigDecimal emplrFicaTax) {
		this.emplrFicaTax = emplrFicaTax;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "EMPLR_MED_TAX", nullable = false, precision = 9)
	public BigDecimal getEmplrMedTax() {
		return this.emplrMedTax;
	}

	public void setEmplrMedTax(BigDecimal emplrMedTax) {
		this.emplrMedTax = emplrMedTax;
	}

	@Column(name = "ANNUITY_ROTH_457B", nullable = false, precision = 9)
	public BigDecimal getAnnuityRoth457b() {
		return this.annuityRoth457b;
	}

	public void setAnnuityRoth457b(BigDecimal annuityRoth457b) {
		this.annuityRoth457b = annuityRoth457b;
	}

}
