package com.esc20.model;
// Generated Jan 4, 2019 3:38:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrCalSchDaysBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_CAL_SCH_DAYS_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrCalSchDaysBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrCalSchDaysBkupPaycalcs5Id id;

	public BhrCalSchDaysBkupPaycalcs5() {
	}

	public BhrCalSchDaysBkupPaycalcs5(BhrCalSchDaysBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "calCd", column = @Column(name = "CAL_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dayDate", column = @Column(name = "DAY_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "dayTyp", column = @Column(name = "DAY_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "julDay", column = @Column(name = "JUL_DAY", nullable = false, length = 3)),
			@AttributeOverride(name = "julYr", column = @Column(name = "JUL_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BhrCalSchDaysBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrCalSchDaysBkupPaycalcs5Id id) {
		this.id = id;
	}

}
