package com.esc20.model;
// Generated Jan 4, 2019 3:39:11 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrDeductXmitalBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_DEDUCT_XMITAL_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrDeductXmitalBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrDeductXmitalBkupPaycalcs5Id id;

	public BhrDeductXmitalBkupPaycalcs5() {
	}

	public BhrDeductXmitalBkupPaycalcs5(BhrDeductXmitalBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "dts", column = @Column(name = "DTS", nullable = false, length = 16)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, length = 5)),
			@AttributeOverride(name = "dedCd", column = @Column(name = "DED_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "dedAmt", column = @Column(name = "DED_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "dedRefund", column = @Column(name = "DED_REFUND", nullable = false, length = 1)),
			@AttributeOverride(name = "cafeFlg", column = @Column(name = "CAFE_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "processDt", column = @Column(name = "PROCESS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 12)),
			@AttributeOverride(name = "rsn", column = @Column(name = "RSN", nullable = false, length = 30)),
			@AttributeOverride(name = "w2EmplrHlthcare", column = @Column(name = "W2_EMPLR_HLTHCARE", nullable = false, length = 1)),
			@AttributeOverride(name = "grossAmt", column = @Column(name = "GROSS_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BhrDeductXmitalBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrDeductXmitalBkupPaycalcs5Id id) {
		this.id = id;
	}

}
