package com.esc20.model;
// Generated Jan 4, 2019 3:39:45 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BhrEapPayAssgnGrp generated by hbm2java
 */
@Entity
@Table(name = "BHR_EAP_PAY_ASSGN_GRP", schema = "rsccc", catalog = "rsccc")
public class BhrEapPayAssgnGrp implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEapPayAssgnGrpId id;
	private char optCd;
	private char autoApprv;
	private int apprvrUsrId;
	private int seqNbr;
	private String module;
	private Set<BhrEapPayAssgnMbr> bhrEapPayAssgnMbrs = new HashSet<BhrEapPayAssgnMbr>(0);

	public BhrEapPayAssgnGrp() {
	}

	public BhrEapPayAssgnGrp(BhrEapPayAssgnGrpId id, char optCd, char autoApprv, int apprvrUsrId, int seqNbr,
			String module) {
		this.id = id;
		this.optCd = optCd;
		this.autoApprv = autoApprv;
		this.apprvrUsrId = apprvrUsrId;
		this.seqNbr = seqNbr;
		this.module = module;
	}

	public BhrEapPayAssgnGrp(BhrEapPayAssgnGrpId id, char optCd, char autoApprv, int apprvrUsrId, int seqNbr,
			String module, Set<BhrEapPayAssgnMbr> bhrEapPayAssgnMbrs) {
		this.id = id;
		this.optCd = optCd;
		this.autoApprv = autoApprv;
		this.apprvrUsrId = apprvrUsrId;
		this.seqNbr = seqNbr;
		this.module = module;
		this.bhrEapPayAssgnMbrs = bhrEapPayAssgnMbrs;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "grpName", column = @Column(name = "GRP_NAME", nullable = false, length = 35)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)) })
	public BhrEapPayAssgnGrpId getId() {
		return this.id;
	}

	public void setId(BhrEapPayAssgnGrpId id) {
		this.id = id;
	}

	@Column(name = "OPT_CD", nullable = false, length = 1)
	public char getOptCd() {
		return this.optCd;
	}

	public void setOptCd(char optCd) {
		this.optCd = optCd;
	}

	@Column(name = "AUTO_APPRV", nullable = false, length = 1)
	public char getAutoApprv() {
		return this.autoApprv;
	}

	public void setAutoApprv(char autoApprv) {
		this.autoApprv = autoApprv;
	}

	@Column(name = "APPRVR_USR_ID", nullable = false)
	public int getApprvrUsrId() {
		return this.apprvrUsrId;
	}

	public void setApprvrUsrId(int apprvrUsrId) {
		this.apprvrUsrId = apprvrUsrId;
	}

	@Column(name = "SEQ_NBR", nullable = false)
	public int getSeqNbr() {
		return this.seqNbr;
	}

	public void setSeqNbr(int seqNbr) {
		this.seqNbr = seqNbr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bhrEapPayAssgnGrp")
	public Set<BhrEapPayAssgnMbr> getBhrEapPayAssgnMbrs() {
		return this.bhrEapPayAssgnMbrs;
	}

	public void setBhrEapPayAssgnMbrs(Set<BhrEapPayAssgnMbr> bhrEapPayAssgnMbrs) {
		this.bhrEapPayAssgnMbrs = bhrEapPayAssgnMbrs;
	}

}
