package com.esc20.model;
// Generated Jan 4, 2019 3:40:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpLvDockHistBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_LV_DOCK_HIST_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrEmpLvDockHistBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpLvDockHistBkupPaycalcs5Id id;

	public BhrEmpLvDockHistBkupPaycalcs5() {
	}

	public BhrEmpLvDockHistBkupPaycalcs5(BhrEmpLvDockHistBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "voidOrIss", column = @Column(name = "VOID_OR_ISS", nullable = false, length = 1)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "lvAltTyp", column = @Column(name = "LV_ALT_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "lvSeqOrder", column = @Column(name = "LV_SEQ_ORDER", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "lvBeginBal", column = @Column(name = "LV_BEGIN_BAL", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "lvEarned", column = @Column(name = "LV_EARNED", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "lvUsed", column = @Column(name = "LV_USED", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "dockUnits", column = @Column(name = "DOCK_UNITS", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "dockAmt", column = @Column(name = "DOCK_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "lvEarnedUsed", column = @Column(name = "LV_EARNED_USED", nullable = false, length = 1)),
			@AttributeOverride(name = "cumulativeDockUnits", column = @Column(name = "CUMULATIVE_DOCK_UNITS", nullable = false, precision = 7, scale = 3)) })
	public BhrEmpLvDockHistBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrEmpLvDockHistBkupPaycalcs5Id id) {
		this.id = id;
	}

}
