package com.esc20.model;
// Generated Jan 4, 2019 3:40:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpLvHistBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_LV_HIST_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrEmpLvHistBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpLvHistBkupPaycalcs5Id id;

	public BhrEmpLvHistBkupPaycalcs5() {
	}

	public BhrEmpLvHistBkupPaycalcs5(BhrEmpLvHistBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "voidOrIss", column = @Column(name = "VOID_OR_ISS", nullable = false, length = 1)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "lvTaken", column = @Column(name = "LV_TAKEN", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "lvEarned", column = @Column(name = "LV_EARNED", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "rsn", column = @Column(name = "RSN", nullable = false, length = 20)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 12)),
			@AttributeOverride(name = "dtOfAbs", column = @Column(name = "DT_OF_ABS", nullable = false, length = 8)),
			@AttributeOverride(name = "tmOfDay", column = @Column(name = "TM_OF_DAY", nullable = false, length = 1)),
			@AttributeOverride(name = "subTyp", column = @Column(name = "SUB_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "absRsn", column = @Column(name = "ABS_RSN", nullable = false, length = 2)),
			@AttributeOverride(name = "servRecDaysDeduct", column = @Column(name = "SERV_REC_DAYS_DEDUCT", nullable = false, precision = 5)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "lvId", column = @Column(name = "LV_ID", nullable = false)) })
	public BhrEmpLvHistBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrEmpLvHistBkupPaycalcs5Id id) {
		this.id = id;
	}

}
