package com.esc20.model;
// Generated Jan 4, 2019 3:42:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEoyAccrualDataBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_EOY_ACCRUAL_DATA_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrEoyAccrualDataBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEoyAccrualDataBkupPaycalcs5Id id;

	public BhrEoyAccrualDataBkupPaycalcs5() {
	}

	public BhrEoyAccrualDataBkupPaycalcs5(BhrEoyAccrualDataBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "glFileId", column = @Column(name = "GL_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "fund", column = @Column(name = "FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "func", column = @Column(name = "FUNC", nullable = false, length = 2)),
			@AttributeOverride(name = "obj", column = @Column(name = "OBJ", nullable = false, length = 4)),
			@AttributeOverride(name = "sobj", column = @Column(name = "SOBJ", nullable = false, length = 2)),
			@AttributeOverride(name = "org", column = @Column(name = "ORG", nullable = false, length = 3)),
			@AttributeOverride(name = "fsclYr", column = @Column(name = "FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "pgm", column = @Column(name = "PGM", nullable = false, length = 2)),
			@AttributeOverride(name = "edSpan", column = @Column(name = "ED_SPAN", nullable = false, length = 1)),
			@AttributeOverride(name = "projDtl", column = @Column(name = "PROJ_DTL", nullable = false, length = 2)),
			@AttributeOverride(name = "accruUnits", column = @Column(name = "ACCRU_UNITS", nullable = false, precision = 5)),
			@AttributeOverride(name = "accruPayAmt", column = @Column(name = "ACCRU_PAY_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "dailyPayRate", column = @Column(name = "DAILY_PAY_RATE", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "payType", column = @Column(name = "PAY_TYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "trsGrantCd", column = @Column(name = "TRS_GRANT_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "accruFedGrant", column = @Column(name = "ACCRU_FED_GRANT", nullable = false, precision = 9)),
			@AttributeOverride(name = "accruFedCare", column = @Column(name = "ACCRU_FED_CARE", nullable = false, precision = 9)),
			@AttributeOverride(name = "accruFedIns", column = @Column(name = "ACCRU_FED_INS", nullable = false, precision = 9)),
			@AttributeOverride(name = "accruFicaTax", column = @Column(name = "ACCRU_FICA_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "accruUnempIns", column = @Column(name = "ACCRU_UNEMP_INS", nullable = false, precision = 9)),
			@AttributeOverride(name = "accruAbvSt", column = @Column(name = "ACCRU_ABV_ST", nullable = false, precision = 9)),
			@AttributeOverride(name = "dtCalculations", column = @Column(name = "DT_CALCULATIONS", nullable = false, length = 8)),
			@AttributeOverride(name = "dtCreated", column = @Column(name = "DT_CREATED", nullable = false, length = 8)),
			@AttributeOverride(name = "dtInterfaced", column = @Column(name = "DT_INTERFACED", nullable = false, length = 8)),
			@AttributeOverride(name = "dtPosted", column = @Column(name = "DT_POSTED", nullable = false, length = 8)),
			@AttributeOverride(name = "dtPostReversals", column = @Column(name = "DT_POST_REVERSALS", nullable = false, length = 8)),
			@AttributeOverride(name = "accruEmplrTrsCareContrib", column = @Column(name = "ACCRU_EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)),
			@AttributeOverride(name = "origFsclYr", column = @Column(name = "ORIG_FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "accruCafeAmt", column = @Column(name = "ACCRU_CAFE_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "accruEmplrRetPensnSurchg", column = @Column(name = "ACCRU_EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)),
			@AttributeOverride(name = "jvNbr", column = @Column(name = "JV_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "jvClearingFund", column = @Column(name = "JV_CLEARING_FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "jvClearingFsclYr", column = @Column(name = "JV_CLEARING_FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "jvFinFileId", column = @Column(name = "JV_FIN_FILE_ID", nullable = false, length = 1)) })
	public BhrEoyAccrualDataBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrEoyAccrualDataBkupPaycalcs5Id id) {
		this.id = id;
	}

}
