package com.esc20.model;
// Generated Jan 4, 2019 3:40:12 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpJob generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_JOB", schema = "rsccc", catalog = "rsccc")
public class BhrEmpJob implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpJobId id;
	private char primJob;
	private BigDecimal pctAssgnd;
	private String campusId;
	private char dept;
	private String eeoc;
	private BigDecimal contrAmt;
	private BigDecimal contrRemainAmt;
	private String calCd;
	private String contrDtBegin;
	private String contrDtEnd;
	private char contrNonStdFlg;
	private short contrDays;
	private String stStep;
	private BigDecimal stMinSalary;
	private boolean yrsCarLad;
	private char payType;
	private BigDecimal payRate;
	private String payGrd;
	private char paySched;
	private String payStep;
	private String maxDays;
	private char exemptStat;
	private BigDecimal dlyRateOfPay;
	private BigDecimal regHrsWrk;
	private BigDecimal hrsPerDay;
	private short nbrDaysEmpld;
	private short nbrDaysOff;
	private short nbrAnnualPymts;
	private short nbrRemainPymts;
	private short nbrMonContr;
	private char ovtmEligFlg;
	private BigDecimal ovtmRate;
	private char wrkComp;
	private short wrkCompRemain;
	private String trsPosCd;
	private BigDecimal stMinSalaryPct;
	private char accruJob;
	private BigDecimal accruRate;
	private String contrDaysLoc;
	private String dtPayoff;
	private String yrsExpJob;
	private char accruCd;
	private byte wrkCompAnnlPymts;
	private BigDecimal hrlyRate;
	private char incrPayStp;
	private String module;
	private char vacantPos;
	private byte wklyHrsSched;
	private BigDecimal whollySepAmt;

	public BhrEmpJob() {
	}

	public BhrEmpJob(BhrEmpJobId id, char primJob, BigDecimal pctAssgnd, String campusId, char dept, String eeoc,
			BigDecimal contrAmt, BigDecimal contrRemainAmt, String calCd, String contrDtBegin, String contrDtEnd,
			char contrNonStdFlg, short contrDays, String stStep, BigDecimal stMinSalary, boolean yrsCarLad,
			char payType, BigDecimal payRate, String payGrd, char paySched, String payStep, String maxDays,
			char exemptStat, BigDecimal dlyRateOfPay, BigDecimal regHrsWrk, BigDecimal hrsPerDay, short nbrDaysEmpld,
			short nbrDaysOff, short nbrAnnualPymts, short nbrRemainPymts, short nbrMonContr, char ovtmEligFlg,
			BigDecimal ovtmRate, char wrkComp, short wrkCompRemain, String trsPosCd, BigDecimal stMinSalaryPct,
			char accruJob, BigDecimal accruRate, String contrDaysLoc, String dtPayoff, String yrsExpJob, char accruCd,
			byte wrkCompAnnlPymts, BigDecimal hrlyRate, char incrPayStp, String module, char vacantPos,
			byte wklyHrsSched, BigDecimal whollySepAmt) {
		this.id = id;
		this.primJob = primJob;
		this.pctAssgnd = pctAssgnd;
		this.campusId = campusId;
		this.dept = dept;
		this.eeoc = eeoc;
		this.contrAmt = contrAmt;
		this.contrRemainAmt = contrRemainAmt;
		this.calCd = calCd;
		this.contrDtBegin = contrDtBegin;
		this.contrDtEnd = contrDtEnd;
		this.contrNonStdFlg = contrNonStdFlg;
		this.contrDays = contrDays;
		this.stStep = stStep;
		this.stMinSalary = stMinSalary;
		this.yrsCarLad = yrsCarLad;
		this.payType = payType;
		this.payRate = payRate;
		this.payGrd = payGrd;
		this.paySched = paySched;
		this.payStep = payStep;
		this.maxDays = maxDays;
		this.exemptStat = exemptStat;
		this.dlyRateOfPay = dlyRateOfPay;
		this.regHrsWrk = regHrsWrk;
		this.hrsPerDay = hrsPerDay;
		this.nbrDaysEmpld = nbrDaysEmpld;
		this.nbrDaysOff = nbrDaysOff;
		this.nbrAnnualPymts = nbrAnnualPymts;
		this.nbrRemainPymts = nbrRemainPymts;
		this.nbrMonContr = nbrMonContr;
		this.ovtmEligFlg = ovtmEligFlg;
		this.ovtmRate = ovtmRate;
		this.wrkComp = wrkComp;
		this.wrkCompRemain = wrkCompRemain;
		this.trsPosCd = trsPosCd;
		this.stMinSalaryPct = stMinSalaryPct;
		this.accruJob = accruJob;
		this.accruRate = accruRate;
		this.contrDaysLoc = contrDaysLoc;
		this.dtPayoff = dtPayoff;
		this.yrsExpJob = yrsExpJob;
		this.accruCd = accruCd;
		this.wrkCompAnnlPymts = wrkCompAnnlPymts;
		this.hrlyRate = hrlyRate;
		this.incrPayStp = incrPayStp;
		this.module = module;
		this.vacantPos = vacantPos;
		this.wklyHrsSched = wklyHrsSched;
		this.whollySepAmt = whollySepAmt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)) })
	public BhrEmpJobId getId() {
		return this.id;
	}

	public void setId(BhrEmpJobId id) {
		this.id = id;
	}

	@Column(name = "PRIM_JOB", nullable = false, length = 1)
	public char getPrimJob() {
		return this.primJob;
	}

	public void setPrimJob(char primJob) {
		this.primJob = primJob;
	}

	@Column(name = "PCT_ASSGND", nullable = false, precision = 3)
	public BigDecimal getPctAssgnd() {
		return this.pctAssgnd;
	}

	public void setPctAssgnd(BigDecimal pctAssgnd) {
		this.pctAssgnd = pctAssgnd;
	}

	@Column(name = "CAMPUS_ID", nullable = false, length = 3)
	public String getCampusId() {
		return this.campusId;
	}

	public void setCampusId(String campusId) {
		this.campusId = campusId;
	}

	@Column(name = "DEPT", nullable = false, length = 1)
	public char getDept() {
		return this.dept;
	}

	public void setDept(char dept) {
		this.dept = dept;
	}

	@Column(name = "EEOC", nullable = false, length = 2)
	public String getEeoc() {
		return this.eeoc;
	}

	public void setEeoc(String eeoc) {
		this.eeoc = eeoc;
	}

	@Column(name = "CONTR_AMT", nullable = false, precision = 9)
	public BigDecimal getContrAmt() {
		return this.contrAmt;
	}

	public void setContrAmt(BigDecimal contrAmt) {
		this.contrAmt = contrAmt;
	}

	@Column(name = "CONTR_REMAIN_AMT", nullable = false, precision = 9)
	public BigDecimal getContrRemainAmt() {
		return this.contrRemainAmt;
	}

	public void setContrRemainAmt(BigDecimal contrRemainAmt) {
		this.contrRemainAmt = contrRemainAmt;
	}

	@Column(name = "CAL_CD", nullable = false, length = 2)
	public String getCalCd() {
		return this.calCd;
	}

	public void setCalCd(String calCd) {
		this.calCd = calCd;
	}

	@Column(name = "CONTR_DT_BEGIN", nullable = false, length = 8)
	public String getContrDtBegin() {
		return this.contrDtBegin;
	}

	public void setContrDtBegin(String contrDtBegin) {
		this.contrDtBegin = contrDtBegin;
	}

	@Column(name = "CONTR_DT_END", nullable = false, length = 8)
	public String getContrDtEnd() {
		return this.contrDtEnd;
	}

	public void setContrDtEnd(String contrDtEnd) {
		this.contrDtEnd = contrDtEnd;
	}

	@Column(name = "CONTR_NON_STD_FLG", nullable = false, length = 1)
	public char getContrNonStdFlg() {
		return this.contrNonStdFlg;
	}

	public void setContrNonStdFlg(char contrNonStdFlg) {
		this.contrNonStdFlg = contrNonStdFlg;
	}

	@Column(name = "CONTR_DAYS", nullable = false, precision = 3, scale = 0)
	public short getContrDays() {
		return this.contrDays;
	}

	public void setContrDays(short contrDays) {
		this.contrDays = contrDays;
	}

	@Column(name = "ST_STEP", nullable = false, length = 2)
	public String getStStep() {
		return this.stStep;
	}

	public void setStStep(String stStep) {
		this.stStep = stStep;
	}

	@Column(name = "ST_MIN_SALARY", nullable = false, precision = 9)
	public BigDecimal getStMinSalary() {
		return this.stMinSalary;
	}

	public void setStMinSalary(BigDecimal stMinSalary) {
		this.stMinSalary = stMinSalary;
	}

	@Column(name = "YRS_CAR_LAD", nullable = false, precision = 1, scale = 0)
	public boolean isYrsCarLad() {
		return this.yrsCarLad;
	}

	public void setYrsCarLad(boolean yrsCarLad) {
		this.yrsCarLad = yrsCarLad;
	}

	@Column(name = "PAY_TYPE", nullable = false, length = 1)
	public char getPayType() {
		return this.payType;
	}

	public void setPayType(char payType) {
		this.payType = payType;
	}

	@Column(name = "PAY_RATE", nullable = false, precision = 9)
	public BigDecimal getPayRate() {
		return this.payRate;
	}

	public void setPayRate(BigDecimal payRate) {
		this.payRate = payRate;
	}

	@Column(name = "PAY_GRD", nullable = false, length = 3)
	public String getPayGrd() {
		return this.payGrd;
	}

	public void setPayGrd(String payGrd) {
		this.payGrd = payGrd;
	}

	@Column(name = "PAY_SCHED", nullable = false, length = 1)
	public char getPaySched() {
		return this.paySched;
	}

	public void setPaySched(char paySched) {
		this.paySched = paySched;
	}

	@Column(name = "PAY_STEP", nullable = false, length = 2)
	public String getPayStep() {
		return this.payStep;
	}

	public void setPayStep(String payStep) {
		this.payStep = payStep;
	}

	@Column(name = "MAX_DAYS", nullable = false, length = 3)
	public String getMaxDays() {
		return this.maxDays;
	}

	public void setMaxDays(String maxDays) {
		this.maxDays = maxDays;
	}

	@Column(name = "EXEMPT_STAT", nullable = false, length = 1)
	public char getExemptStat() {
		return this.exemptStat;
	}

	public void setExemptStat(char exemptStat) {
		this.exemptStat = exemptStat;
	}

	@Column(name = "DLY_RATE_OF_PAY", nullable = false, precision = 7, scale = 3)
	public BigDecimal getDlyRateOfPay() {
		return this.dlyRateOfPay;
	}

	public void setDlyRateOfPay(BigDecimal dlyRateOfPay) {
		this.dlyRateOfPay = dlyRateOfPay;
	}

	@Column(name = "REG_HRS_WRK", nullable = false, precision = 5)
	public BigDecimal getRegHrsWrk() {
		return this.regHrsWrk;
	}

	public void setRegHrsWrk(BigDecimal regHrsWrk) {
		this.regHrsWrk = regHrsWrk;
	}

	@Column(name = "HRS_PER_DAY", nullable = false, precision = 5, scale = 3)
	public BigDecimal getHrsPerDay() {
		return this.hrsPerDay;
	}

	public void setHrsPerDay(BigDecimal hrsPerDay) {
		this.hrsPerDay = hrsPerDay;
	}

	@Column(name = "NBR_DAYS_EMPLD", nullable = false, precision = 3, scale = 0)
	public short getNbrDaysEmpld() {
		return this.nbrDaysEmpld;
	}

	public void setNbrDaysEmpld(short nbrDaysEmpld) {
		this.nbrDaysEmpld = nbrDaysEmpld;
	}

	@Column(name = "NBR_DAYS_OFF", nullable = false, precision = 3, scale = 0)
	public short getNbrDaysOff() {
		return this.nbrDaysOff;
	}

	public void setNbrDaysOff(short nbrDaysOff) {
		this.nbrDaysOff = nbrDaysOff;
	}

	@Column(name = "NBR_ANNUAL_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getNbrAnnualPymts() {
		return this.nbrAnnualPymts;
	}

	public void setNbrAnnualPymts(short nbrAnnualPymts) {
		this.nbrAnnualPymts = nbrAnnualPymts;
	}

	@Column(name = "NBR_REMAIN_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getNbrRemainPymts() {
		return this.nbrRemainPymts;
	}

	public void setNbrRemainPymts(short nbrRemainPymts) {
		this.nbrRemainPymts = nbrRemainPymts;
	}

	@Column(name = "NBR_MON_CONTR", nullable = false, precision = 3, scale = 0)
	public short getNbrMonContr() {
		return this.nbrMonContr;
	}

	public void setNbrMonContr(short nbrMonContr) {
		this.nbrMonContr = nbrMonContr;
	}

	@Column(name = "OVTM_ELIG_FLG", nullable = false, length = 1)
	public char getOvtmEligFlg() {
		return this.ovtmEligFlg;
	}

	public void setOvtmEligFlg(char ovtmEligFlg) {
		this.ovtmEligFlg = ovtmEligFlg;
	}

	@Column(name = "OVTM_RATE", nullable = false, precision = 5)
	public BigDecimal getOvtmRate() {
		return this.ovtmRate;
	}

	public void setOvtmRate(BigDecimal ovtmRate) {
		this.ovtmRate = ovtmRate;
	}

	@Column(name = "WRK_COMP", nullable = false, length = 1)
	public char getWrkComp() {
		return this.wrkComp;
	}

	public void setWrkComp(char wrkComp) {
		this.wrkComp = wrkComp;
	}

	@Column(name = "WRK_COMP_REMAIN", nullable = false, precision = 3, scale = 0)
	public short getWrkCompRemain() {
		return this.wrkCompRemain;
	}

	public void setWrkCompRemain(short wrkCompRemain) {
		this.wrkCompRemain = wrkCompRemain;
	}

	@Column(name = "TRS_POS_CD", nullable = false, length = 2)
	public String getTrsPosCd() {
		return this.trsPosCd;
	}

	public void setTrsPosCd(String trsPosCd) {
		this.trsPosCd = trsPosCd;
	}

	@Column(name = "ST_MIN_SALARY_PCT", nullable = false, precision = 3)
	public BigDecimal getStMinSalaryPct() {
		return this.stMinSalaryPct;
	}

	public void setStMinSalaryPct(BigDecimal stMinSalaryPct) {
		this.stMinSalaryPct = stMinSalaryPct;
	}

	@Column(name = "ACCRU_JOB", nullable = false, length = 1)
	public char getAccruJob() {
		return this.accruJob;
	}

	public void setAccruJob(char accruJob) {
		this.accruJob = accruJob;
	}

	@Column(name = "ACCRU_RATE", nullable = false, precision = 7, scale = 3)
	public BigDecimal getAccruRate() {
		return this.accruRate;
	}

	public void setAccruRate(BigDecimal accruRate) {
		this.accruRate = accruRate;
	}

	@Column(name = "CONTR_DAYS_LOC", nullable = false, length = 3)
	public String getContrDaysLoc() {
		return this.contrDaysLoc;
	}

	public void setContrDaysLoc(String contrDaysLoc) {
		this.contrDaysLoc = contrDaysLoc;
	}

	@Column(name = "DT_PAYOFF", nullable = false, length = 8)
	public String getDtPayoff() {
		return this.dtPayoff;
	}

	public void setDtPayoff(String dtPayoff) {
		this.dtPayoff = dtPayoff;
	}

	@Column(name = "YRS_EXP_JOB", nullable = false, length = 2)
	public String getYrsExpJob() {
		return this.yrsExpJob;
	}

	public void setYrsExpJob(String yrsExpJob) {
		this.yrsExpJob = yrsExpJob;
	}

	@Column(name = "ACCRU_CD", nullable = false, length = 1)
	public char getAccruCd() {
		return this.accruCd;
	}

	public void setAccruCd(char accruCd) {
		this.accruCd = accruCd;
	}

	@Column(name = "WRK_COMP_ANNL_PYMTS", nullable = false, precision = 2, scale = 0)
	public byte getWrkCompAnnlPymts() {
		return this.wrkCompAnnlPymts;
	}

	public void setWrkCompAnnlPymts(byte wrkCompAnnlPymts) {
		this.wrkCompAnnlPymts = wrkCompAnnlPymts;
	}

	@Column(name = "HRLY_RATE", nullable = false, precision = 5)
	public BigDecimal getHrlyRate() {
		return this.hrlyRate;
	}

	public void setHrlyRate(BigDecimal hrlyRate) {
		this.hrlyRate = hrlyRate;
	}

	@Column(name = "INCR_PAY_STP", nullable = false, length = 1)
	public char getIncrPayStp() {
		return this.incrPayStp;
	}

	public void setIncrPayStp(char incrPayStp) {
		this.incrPayStp = incrPayStp;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "VACANT_POS", nullable = false, length = 1)
	public char getVacantPos() {
		return this.vacantPos;
	}

	public void setVacantPos(char vacantPos) {
		this.vacantPos = vacantPos;
	}

	@Column(name = "WKLY_HRS_SCHED", nullable = false, precision = 2, scale = 0)
	public byte getWklyHrsSched() {
		return this.wklyHrsSched;
	}

	public void setWklyHrsSched(byte wklyHrsSched) {
		this.wklyHrsSched = wklyHrsSched;
	}

	@Column(name = "WHOLLY_SEP_AMT", nullable = false, precision = 7)
	public BigDecimal getWhollySepAmt() {
		return this.whollySepAmt;
	}

	public void setWhollySepAmt(BigDecimal whollySepAmt) {
		this.whollySepAmt = whollySepAmt;
	}

}
