package com.esc20.model;
// Generated Jan 4, 2019 3:40:12 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * BhrEmpEmply generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_EMPLY", schema = "rsccc", catalog = "rsccc")
public class BhrEmpEmply implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private String empNbr;
	private BhrEmpDemo bhrEmpDemo;
	private Character statCdEmpl;
	private String dtOrgEmp;
	private String yrsExpDist;
	private String yrsExpDistLoc;
	private String yrsProExper;
	private String yrsProExperLoc;
	private String contrClass;
	private String contrTerm;
	private String contrYr;
	private String subTyp;
	private BigDecimal dayEmpldPct;
	private String dtReassign;
	private String dtTerm;
	private String termRea;
	private String dtReEmp;
	private String lvOfAbsBegin;
	private String lvOfAbsEnd;
	private String lvRsn;
	private Character yrRound;
	private String extractId;
	private Character eligRehire;
	private Character highDegree;
	private String gradesTaught;
	private Character campusCluster;
	private Character campusLvl;
	private String dtPhyExam;
	private String dtTbExam;
	private String totYrsExpClaim;
	private Short transReqNum;
	private Character transReqRsn;
	private Character verifyDob;
	private Character verifyService;
	private Character verifyTrans;
	private Character verifyRef;
	private Character verifyCert;
	private Character verifyOath;
	private String tcatYr;
	private Character tcatResult;
	private Short hrsAboveDegree;
	private Short hrsThisPer;
	private Short inserHrs;
	private String dtLInser;
	private String interviewCd;
	private String interviewLoc;
	private Character sourceNewPer;
	private Character noBudChg;
	private String campusIdAlt;
	private Character deptAlt;
	private String orgBud;
	private String crimeHistDt;
	private String crimeHistTyp;
	private Character crimeHistPost;
	private String evaluator;
	private Character receive13th;
	private Character trs118Sel;
	private Character yrsExpPayStep;
	private Integer estAnnualSalaryHrly;
	private String estAnnualPayActy;
	private String estAnnualFund;
	private String estAnnualFunc;
	private String estAnnualObj;
	private String estAnnualOrg;
	private String estAnnualPgm;
	private Character unempEligQtr1Mon1;
	private Character unempEligQtr1Mon2;
	private Character unempEligQtr1Mon3;
	private Character unempEligQtr2Mon1;
	private Character unempEligQtr2Mon2;
	private Character unempEligQtr2Mon3;
	private Character unempEligQtr3Mon1;
	private Character unempEligQtr3Mon2;
	private Character unempEligQtr3Mon3;
	private Character unempEligQtr4Mon1;
	private Character unempEligQtr4Mon2;
	private Character unempEligQtr4Mon3;
	private String dtRetire;
	private Character takeRetSurchg;
	private Character nyTakeRetSurchg;
	private Character fngrprtStat;
	private String dtExtr;
	private String dtFngrprt;
	private String module;
	private Character ersRetHlthElig;
	private Character nyErsRetHlthElig;
	private Character elecConsntW2;
	private Character elecConsnt1095;
	private Character emplmntTypCd;
	private Character retEmplmntTypCd;
	private Character fullSem;
	private String auxRoleId;

	public BhrEmpEmply() {
	}

	public BhrEmpEmply(BhrEmpDemo bhrEmpDemo, Character statCdEmpl, String dtOrgEmp, String yrsExpDist,
			String yrsExpDistLoc, String yrsProExper, String yrsProExperLoc, String contrClass, String contrTerm,
			String contrYr, String subTyp, BigDecimal dayEmpldPct, String dtReassign, String dtTerm, String termRea,
			String dtReEmp, String lvOfAbsBegin, String lvOfAbsEnd, String lvRsn, Character yrRound, String extractId,
			Character eligRehire, Character highDegree, String gradesTaught, Character campusCluster,
			Character campusLvl, String dtPhyExam, String dtTbExam, String totYrsExpClaim, Short transReqNum,
			Character transReqRsn, Character verifyDob, Character verifyService, Character verifyTrans,
			Character verifyRef, Character verifyCert, Character verifyOath, String tcatYr, Character tcatResult,
			Short hrsAboveDegree, Short hrsThisPer, Short inserHrs, String dtLInser, String interviewCd,
			String interviewLoc, Character sourceNewPer, Character noBudChg, String campusIdAlt, Character deptAlt,
			String orgBud, String crimeHistDt, String crimeHistTyp, Character crimeHistPost, String evaluator,
			Character receive13th, Character trs118Sel, Character yrsExpPayStep, Integer estAnnualSalaryHrly,
			String estAnnualPayActy, String estAnnualFund, String estAnnualFunc, String estAnnualObj,
			String estAnnualOrg, String estAnnualPgm, Character unempEligQtr1Mon1, Character unempEligQtr1Mon2,
			Character unempEligQtr1Mon3, Character unempEligQtr2Mon1, Character unempEligQtr2Mon2,
			Character unempEligQtr2Mon3, Character unempEligQtr3Mon1, Character unempEligQtr3Mon2,
			Character unempEligQtr3Mon3, Character unempEligQtr4Mon1, Character unempEligQtr4Mon2,
			Character unempEligQtr4Mon3, String dtRetire, Character takeRetSurchg, Character nyTakeRetSurchg,
			Character fngrprtStat, String dtExtr, String dtFngrprt, String module, Character ersRetHlthElig,
			Character nyErsRetHlthElig, Character elecConsntW2, Character elecConsnt1095, Character emplmntTypCd,
			Character retEmplmntTypCd, Character fullSem, String auxRoleId) {
		this.bhrEmpDemo = bhrEmpDemo;
		this.statCdEmpl = statCdEmpl;
		this.dtOrgEmp = dtOrgEmp;
		this.yrsExpDist = yrsExpDist;
		this.yrsExpDistLoc = yrsExpDistLoc;
		this.yrsProExper = yrsProExper;
		this.yrsProExperLoc = yrsProExperLoc;
		this.contrClass = contrClass;
		this.contrTerm = contrTerm;
		this.contrYr = contrYr;
		this.subTyp = subTyp;
		this.dayEmpldPct = dayEmpldPct;
		this.dtReassign = dtReassign;
		this.dtTerm = dtTerm;
		this.termRea = termRea;
		this.dtReEmp = dtReEmp;
		this.lvOfAbsBegin = lvOfAbsBegin;
		this.lvOfAbsEnd = lvOfAbsEnd;
		this.lvRsn = lvRsn;
		this.yrRound = yrRound;
		this.extractId = extractId;
		this.eligRehire = eligRehire;
		this.highDegree = highDegree;
		this.gradesTaught = gradesTaught;
		this.campusCluster = campusCluster;
		this.campusLvl = campusLvl;
		this.dtPhyExam = dtPhyExam;
		this.dtTbExam = dtTbExam;
		this.totYrsExpClaim = totYrsExpClaim;
		this.transReqNum = transReqNum;
		this.transReqRsn = transReqRsn;
		this.verifyDob = verifyDob;
		this.verifyService = verifyService;
		this.verifyTrans = verifyTrans;
		this.verifyRef = verifyRef;
		this.verifyCert = verifyCert;
		this.verifyOath = verifyOath;
		this.tcatYr = tcatYr;
		this.tcatResult = tcatResult;
		this.hrsAboveDegree = hrsAboveDegree;
		this.hrsThisPer = hrsThisPer;
		this.inserHrs = inserHrs;
		this.dtLInser = dtLInser;
		this.interviewCd = interviewCd;
		this.interviewLoc = interviewLoc;
		this.sourceNewPer = sourceNewPer;
		this.noBudChg = noBudChg;
		this.campusIdAlt = campusIdAlt;
		this.deptAlt = deptAlt;
		this.orgBud = orgBud;
		this.crimeHistDt = crimeHistDt;
		this.crimeHistTyp = crimeHistTyp;
		this.crimeHistPost = crimeHistPost;
		this.evaluator = evaluator;
		this.receive13th = receive13th;
		this.trs118Sel = trs118Sel;
		this.yrsExpPayStep = yrsExpPayStep;
		this.estAnnualSalaryHrly = estAnnualSalaryHrly;
		this.estAnnualPayActy = estAnnualPayActy;
		this.estAnnualFund = estAnnualFund;
		this.estAnnualFunc = estAnnualFunc;
		this.estAnnualObj = estAnnualObj;
		this.estAnnualOrg = estAnnualOrg;
		this.estAnnualPgm = estAnnualPgm;
		this.unempEligQtr1Mon1 = unempEligQtr1Mon1;
		this.unempEligQtr1Mon2 = unempEligQtr1Mon2;
		this.unempEligQtr1Mon3 = unempEligQtr1Mon3;
		this.unempEligQtr2Mon1 = unempEligQtr2Mon1;
		this.unempEligQtr2Mon2 = unempEligQtr2Mon2;
		this.unempEligQtr2Mon3 = unempEligQtr2Mon3;
		this.unempEligQtr3Mon1 = unempEligQtr3Mon1;
		this.unempEligQtr3Mon2 = unempEligQtr3Mon2;
		this.unempEligQtr3Mon3 = unempEligQtr3Mon3;
		this.unempEligQtr4Mon1 = unempEligQtr4Mon1;
		this.unempEligQtr4Mon2 = unempEligQtr4Mon2;
		this.unempEligQtr4Mon3 = unempEligQtr4Mon3;
		this.dtRetire = dtRetire;
		this.takeRetSurchg = takeRetSurchg;
		this.nyTakeRetSurchg = nyTakeRetSurchg;
		this.fngrprtStat = fngrprtStat;
		this.dtExtr = dtExtr;
		this.dtFngrprt = dtFngrprt;
		this.module = module;
		this.ersRetHlthElig = ersRetHlthElig;
		this.nyErsRetHlthElig = nyErsRetHlthElig;
		this.elecConsntW2 = elecConsntW2;
		this.elecConsnt1095 = elecConsnt1095;
		this.emplmntTypCd = emplmntTypCd;
		this.retEmplmntTypCd = retEmplmntTypCd;
		this.fullSem = fullSem;
		this.auxRoleId = auxRoleId;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "bhrEmpDemo"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public BhrEmpDemo getBhrEmpDemo() {
		return this.bhrEmpDemo;
	}

	public void setBhrEmpDemo(BhrEmpDemo bhrEmpDemo) {
		this.bhrEmpDemo = bhrEmpDemo;
	}

	@Column(name = "STAT_CD_EMPL", nullable = false, length = 1)
	public Character getStatCdEmpl() {
		return this.statCdEmpl;
	}

	public void setStatCdEmpl(Character statCdEmpl) {
		this.statCdEmpl = statCdEmpl;
	}

	@Column(name = "DT_ORG_EMP", nullable = false, length = 8)
	public String getDtOrgEmp() {
		return this.dtOrgEmp;
	}

	public void setDtOrgEmp(String dtOrgEmp) {
		this.dtOrgEmp = dtOrgEmp;
	}

	@Column(name = "YRS_EXP_DIST", nullable = false, length = 2)
	public String getYrsExpDist() {
		return this.yrsExpDist;
	}

	public void setYrsExpDist(String yrsExpDist) {
		this.yrsExpDist = yrsExpDist;
	}

	@Column(name = "YRS_EXP_DIST_LOC", nullable = false, length = 2)
	public String getYrsExpDistLoc() {
		return this.yrsExpDistLoc;
	}

	public void setYrsExpDistLoc(String yrsExpDistLoc) {
		this.yrsExpDistLoc = yrsExpDistLoc;
	}

	@Column(name = "YRS_PRO_EXPER", nullable = false, length = 2)
	public String getYrsProExper() {
		return this.yrsProExper;
	}

	public void setYrsProExper(String yrsProExper) {
		this.yrsProExper = yrsProExper;
	}

	@Column(name = "YRS_PRO_EXPER_LOC", nullable = false, length = 2)
	public String getYrsProExperLoc() {
		return this.yrsProExperLoc;
	}

	public void setYrsProExperLoc(String yrsProExperLoc) {
		this.yrsProExperLoc = yrsProExperLoc;
	}

	@Column(name = "CONTR_CLASS", nullable = false, length = 2)
	public String getContrClass() {
		return this.contrClass;
	}

	public void setContrClass(String contrClass) {
		this.contrClass = contrClass;
	}

	@Column(name = "CONTR_TERM", nullable = false, length = 2)
	public String getContrTerm() {
		return this.contrTerm;
	}

	public void setContrTerm(String contrTerm) {
		this.contrTerm = contrTerm;
	}

	@Column(name = "CONTR_YR", nullable = false, length = 2)
	public String getContrYr() {
		return this.contrYr;
	}

	public void setContrYr(String contrYr) {
		this.contrYr = contrYr;
	}

	@Column(name = "SUB_TYP", nullable = false, length = 2)
	public String getSubTyp() {
		return this.subTyp;
	}

	public void setSubTyp(String subTyp) {
		this.subTyp = subTyp;
	}

	@Column(name = "DAY_EMPLD_PCT", nullable = false, precision = 3)
	public BigDecimal getDayEmpldPct() {
		return this.dayEmpldPct;
	}

	public void setDayEmpldPct(BigDecimal dayEmpldPct) {
		this.dayEmpldPct = dayEmpldPct;
	}

	@Column(name = "DT_REASSIGN", nullable = false, length = 8)
	public String getDtReassign() {
		return this.dtReassign;
	}

	public void setDtReassign(String dtReassign) {
		this.dtReassign = dtReassign;
	}

	@Column(name = "DT_TERM", nullable = false, length = 8)
	public String getDtTerm() {
		return this.dtTerm;
	}

	public void setDtTerm(String dtTerm) {
		this.dtTerm = dtTerm;
	}

	@Column(name = "TERM_REA", nullable = false, length = 2)
	public String getTermRea() {
		return this.termRea;
	}

	public void setTermRea(String termRea) {
		this.termRea = termRea;
	}

	@Column(name = "DT_RE_EMP", nullable = false, length = 8)
	public String getDtReEmp() {
		return this.dtReEmp;
	}

	public void setDtReEmp(String dtReEmp) {
		this.dtReEmp = dtReEmp;
	}

	@Column(name = "LV_OF_ABS_BEGIN", nullable = false, length = 8)
	public String getLvOfAbsBegin() {
		return this.lvOfAbsBegin;
	}

	public void setLvOfAbsBegin(String lvOfAbsBegin) {
		this.lvOfAbsBegin = lvOfAbsBegin;
	}

	@Column(name = "LV_OF_ABS_END", nullable = false, length = 8)
	public String getLvOfAbsEnd() {
		return this.lvOfAbsEnd;
	}

	public void setLvOfAbsEnd(String lvOfAbsEnd) {
		this.lvOfAbsEnd = lvOfAbsEnd;
	}

	@Column(name = "LV_RSN", nullable = false, length = 3)
	public String getLvRsn() {
		return this.lvRsn;
	}

	public void setLvRsn(String lvRsn) {
		this.lvRsn = lvRsn;
	}

	@Column(name = "YR_ROUND", nullable = false, length = 1)
	public Character getYrRound() {
		return this.yrRound;
	}

	public void setYrRound(Character yrRound) {
		this.yrRound = yrRound;
	}

	@Column(name = "EXTRACT_ID", nullable = false, length = 3)
	public String getExtractId() {
		return this.extractId;
	}

	public void setExtractId(String extractId) {
		this.extractId = extractId;
	}

	@Column(name = "ELIG_REHIRE", nullable = false, length = 1)
	public Character getEligRehire() {
		return this.eligRehire;
	}

	public void setEligRehire(Character eligRehire) {
		this.eligRehire = eligRehire;
	}

	@Column(name = "HIGH_DEGREE", nullable = false, length = 1)
	public Character getHighDegree() {
		return this.highDegree;
	}

	public void setHighDegree(Character highDegree) {
		this.highDegree = highDegree;
	}

	@Column(name = "GRADES_TAUGHT", nullable = false, length = 7)
	public String getGradesTaught() {
		return this.gradesTaught;
	}

	public void setGradesTaught(String gradesTaught) {
		this.gradesTaught = gradesTaught;
	}

	@Column(name = "CAMPUS_CLUSTER", nullable = false, length = 1)
	public Character getCampusCluster() {
		return this.campusCluster;
	}

	public void setCampusCluster(Character campusCluster) {
		this.campusCluster = campusCluster;
	}

	@Column(name = "CAMPUS_LVL", nullable = false, length = 1)
	public Character getCampusLvl() {
		return this.campusLvl;
	}

	public void setCampusLvl(Character campusLvl) {
		this.campusLvl = campusLvl;
	}

	@Column(name = "DT_PHY_EXAM", nullable = false, length = 8)
	public String getDtPhyExam() {
		return this.dtPhyExam;
	}

	public void setDtPhyExam(String dtPhyExam) {
		this.dtPhyExam = dtPhyExam;
	}

	@Column(name = "DT_TB_EXAM", nullable = false, length = 8)
	public String getDtTbExam() {
		return this.dtTbExam;
	}

	public void setDtTbExam(String dtTbExam) {
		this.dtTbExam = dtTbExam;
	}

	@Column(name = "TOT_YRS_EXP_CLAIM", nullable = false, length = 2)
	public String getTotYrsExpClaim() {
		return this.totYrsExpClaim;
	}

	public void setTotYrsExpClaim(String totYrsExpClaim) {
		this.totYrsExpClaim = totYrsExpClaim;
	}

	@Column(name = "TRANS_REQ_NUM", nullable = false, precision = 3, scale = 0)
	public Short getTransReqNum() {
		return this.transReqNum;
	}

	public void setTransReqNum(Short transReqNum) {
		this.transReqNum = transReqNum;
	}

	@Column(name = "TRANS_REQ_RSN", nullable = false, length = 1)
	public Character getTransReqRsn() {
		return this.transReqRsn;
	}

	public void setTransReqRsn(Character transReqRsn) {
		this.transReqRsn = transReqRsn;
	}

	@Column(name = "VERIFY_DOB", nullable = false, length = 1)
	public Character getVerifyDob() {
		return this.verifyDob;
	}

	public void setVerifyDob(Character verifyDob) {
		this.verifyDob = verifyDob;
	}

	@Column(name = "VERIFY_SERVICE", nullable = false, length = 1)
	public Character getVerifyService() {
		return this.verifyService;
	}

	public void setVerifyService(Character verifyService) {
		this.verifyService = verifyService;
	}

	@Column(name = "VERIFY_TRANS", nullable = false, length = 1)
	public Character getVerifyTrans() {
		return this.verifyTrans;
	}

	public void setVerifyTrans(Character verifyTrans) {
		this.verifyTrans = verifyTrans;
	}

	@Column(name = "VERIFY_REF", nullable = false, length = 1)
	public Character getVerifyRef() {
		return this.verifyRef;
	}

	public void setVerifyRef(Character verifyRef) {
		this.verifyRef = verifyRef;
	}

	@Column(name = "VERIFY_CERT", nullable = false, length = 1)
	public Character getVerifyCert() {
		return this.verifyCert;
	}

	public void setVerifyCert(Character verifyCert) {
		this.verifyCert = verifyCert;
	}

	@Column(name = "VERIFY_OATH", nullable = false, length = 1)
	public Character getVerifyOath() {
		return this.verifyOath;
	}

	public void setVerifyOath(Character verifyOath) {
		this.verifyOath = verifyOath;
	}

	@Column(name = "TCAT_YR", nullable = false, length = 4)
	public String getTcatYr() {
		return this.tcatYr;
	}

	public void setTcatYr(String tcatYr) {
		this.tcatYr = tcatYr;
	}

	@Column(name = "TCAT_RESULT", nullable = false, length = 1)
	public Character getTcatResult() {
		return this.tcatResult;
	}

	public void setTcatResult(Character tcatResult) {
		this.tcatResult = tcatResult;
	}

	@Column(name = "HRS_ABOVE_DEGREE", nullable = false, precision = 3, scale = 0)
	public Short getHrsAboveDegree() {
		return this.hrsAboveDegree;
	}

	public void setHrsAboveDegree(Short hrsAboveDegree) {
		this.hrsAboveDegree = hrsAboveDegree;
	}

	@Column(name = "HRS_THIS_PER", nullable = false, precision = 3, scale = 0)
	public Short getHrsThisPer() {
		return this.hrsThisPer;
	}

	public void setHrsThisPer(Short hrsThisPer) {
		this.hrsThisPer = hrsThisPer;
	}

	@Column(name = "INSER_HRS", nullable = false, precision = 3, scale = 0)
	public Short getInserHrs() {
		return this.inserHrs;
	}

	public void setInserHrs(Short inserHrs) {
		this.inserHrs = inserHrs;
	}

	@Column(name = "DT_L_INSER", nullable = false, length = 8)
	public String getDtLInser() {
		return this.dtLInser;
	}

	public void setDtLInser(String dtLInser) {
		this.dtLInser = dtLInser;
	}

	@Column(name = "INTERVIEW_CD", nullable = false, length = 2)
	public String getInterviewCd() {
		return this.interviewCd;
	}

	public void setInterviewCd(String interviewCd) {
		this.interviewCd = interviewCd;
	}

	@Column(name = "INTERVIEW_LOC", nullable = false, length = 2)
	public String getInterviewLoc() {
		return this.interviewLoc;
	}

	public void setInterviewLoc(String interviewLoc) {
		this.interviewLoc = interviewLoc;
	}

	@Column(name = "SOURCE_NEW_PER", nullable = false, length = 1)
	public Character getSourceNewPer() {
		return this.sourceNewPer;
	}

	public void setSourceNewPer(Character sourceNewPer) {
		this.sourceNewPer = sourceNewPer;
	}

	@Column(name = "NO_BUD_CHG", nullable = false, length = 1)
	public Character getNoBudChg() {
		return this.noBudChg;
	}

	public void setNoBudChg(Character noBudChg) {
		this.noBudChg = noBudChg;
	}

	@Column(name = "CAMPUS_ID_ALT", nullable = false, length = 3)
	public String getCampusIdAlt() {
		return this.campusIdAlt;
	}

	public void setCampusIdAlt(String campusIdAlt) {
		this.campusIdAlt = campusIdAlt;
	}

	@Column(name = "DEPT_ALT", nullable = false, length = 1)
	public Character getDeptAlt() {
		return this.deptAlt;
	}

	public void setDeptAlt(Character deptAlt) {
		this.deptAlt = deptAlt;
	}

	@Column(name = "ORG_BUD", nullable = false, length = 3)
	public String getOrgBud() {
		return this.orgBud;
	}

	public void setOrgBud(String orgBud) {
		this.orgBud = orgBud;
	}

	@Column(name = "CRIME_HIST_DT", nullable = false, length = 8)
	public String getCrimeHistDt() {
		return this.crimeHistDt;
	}

	public void setCrimeHistDt(String crimeHistDt) {
		this.crimeHistDt = crimeHistDt;
	}

	@Column(name = "CRIME_HIST_TYP", nullable = false, length = 2)
	public String getCrimeHistTyp() {
		return this.crimeHistTyp;
	}

	public void setCrimeHistTyp(String crimeHistTyp) {
		this.crimeHistTyp = crimeHistTyp;
	}

	@Column(name = "CRIME_HIST_POST", nullable = false, length = 1)
	public Character getCrimeHistPost() {
		return this.crimeHistPost;
	}

	public void setCrimeHistPost(Character crimeHistPost) {
		this.crimeHistPost = crimeHistPost;
	}

	@Column(name = "EVALUATOR", nullable = false, length = 9)
	public String getEvaluator() {
		return this.evaluator;
	}

	public void setEvaluator(String evaluator) {
		this.evaluator = evaluator;
	}

	@Column(name = "RECEIVE_13TH", nullable = false, length = 1)
	public Character getReceive13th() {
		return this.receive13th;
	}

	public void setReceive13th(Character receive13th) {
		this.receive13th = receive13th;
	}

	@Column(name = "TRS_118_SEL", nullable = false, length = 1)
	public Character getTrs118Sel() {
		return this.trs118Sel;
	}

	public void setTrs118Sel(Character trs118Sel) {
		this.trs118Sel = trs118Sel;
	}

	@Column(name = "YRS_EXP_PAY_STEP", nullable = false, length = 1)
	public Character getYrsExpPayStep() {
		return this.yrsExpPayStep;
	}

	public void setYrsExpPayStep(Character yrsExpPayStep) {
		this.yrsExpPayStep = yrsExpPayStep;
	}

	@Column(name = "EST_ANNUAL_SALARY_HRLY", nullable = false, precision = 6, scale = 0)
	public Integer getEstAnnualSalaryHrly() {
		return this.estAnnualSalaryHrly;
	}

	public void setEstAnnualSalaryHrly(Integer estAnnualSalaryHrly) {
		this.estAnnualSalaryHrly = estAnnualSalaryHrly;
	}

	@Column(name = "EST_ANNUAL_PAY_ACTY", nullable = false, length = 2)
	public String getEstAnnualPayActy() {
		return this.estAnnualPayActy;
	}

	public void setEstAnnualPayActy(String estAnnualPayActy) {
		this.estAnnualPayActy = estAnnualPayActy;
	}

	@Column(name = "EST_ANNUAL_FUND", nullable = false, length = 3)
	public String getEstAnnualFund() {
		return this.estAnnualFund;
	}

	public void setEstAnnualFund(String estAnnualFund) {
		this.estAnnualFund = estAnnualFund;
	}

	@Column(name = "EST_ANNUAL_FUNC", nullable = false, length = 2)
	public String getEstAnnualFunc() {
		return this.estAnnualFunc;
	}

	public void setEstAnnualFunc(String estAnnualFunc) {
		this.estAnnualFunc = estAnnualFunc;
	}

	@Column(name = "EST_ANNUAL_OBJ", nullable = false, length = 4)
	public String getEstAnnualObj() {
		return this.estAnnualObj;
	}

	public void setEstAnnualObj(String estAnnualObj) {
		this.estAnnualObj = estAnnualObj;
	}

	@Column(name = "EST_ANNUAL_ORG", nullable = false, length = 3)
	public String getEstAnnualOrg() {
		return this.estAnnualOrg;
	}

	public void setEstAnnualOrg(String estAnnualOrg) {
		this.estAnnualOrg = estAnnualOrg;
	}

	@Column(name = "EST_ANNUAL_PGM", nullable = false, length = 2)
	public String getEstAnnualPgm() {
		return this.estAnnualPgm;
	}

	public void setEstAnnualPgm(String estAnnualPgm) {
		this.estAnnualPgm = estAnnualPgm;
	}

	@Column(name = "UNEMP_ELIG_QTR1_MON1", nullable = false, length = 1)
	public Character getUnempEligQtr1Mon1() {
		return this.unempEligQtr1Mon1;
	}

	public void setUnempEligQtr1Mon1(Character unempEligQtr1Mon1) {
		this.unempEligQtr1Mon1 = unempEligQtr1Mon1;
	}

	@Column(name = "UNEMP_ELIG_QTR1_MON2", nullable = false, length = 1)
	public Character getUnempEligQtr1Mon2() {
		return this.unempEligQtr1Mon2;
	}

	public void setUnempEligQtr1Mon2(Character unempEligQtr1Mon2) {
		this.unempEligQtr1Mon2 = unempEligQtr1Mon2;
	}

	@Column(name = "UNEMP_ELIG_QTR1_MON3", nullable = false, length = 1)
	public Character getUnempEligQtr1Mon3() {
		return this.unempEligQtr1Mon3;
	}

	public void setUnempEligQtr1Mon3(Character unempEligQtr1Mon3) {
		this.unempEligQtr1Mon3 = unempEligQtr1Mon3;
	}

	@Column(name = "UNEMP_ELIG_QTR2_MON1", nullable = false, length = 1)
	public Character getUnempEligQtr2Mon1() {
		return this.unempEligQtr2Mon1;
	}

	public void setUnempEligQtr2Mon1(Character unempEligQtr2Mon1) {
		this.unempEligQtr2Mon1 = unempEligQtr2Mon1;
	}

	@Column(name = "UNEMP_ELIG_QTR2_MON2", nullable = false, length = 1)
	public Character getUnempEligQtr2Mon2() {
		return this.unempEligQtr2Mon2;
	}

	public void setUnempEligQtr2Mon2(Character unempEligQtr2Mon2) {
		this.unempEligQtr2Mon2 = unempEligQtr2Mon2;
	}

	@Column(name = "UNEMP_ELIG_QTR2_MON3", nullable = false, length = 1)
	public Character getUnempEligQtr2Mon3() {
		return this.unempEligQtr2Mon3;
	}

	public void setUnempEligQtr2Mon3(Character unempEligQtr2Mon3) {
		this.unempEligQtr2Mon3 = unempEligQtr2Mon3;
	}

	@Column(name = "UNEMP_ELIG_QTR3_MON1", nullable = false, length = 1)
	public Character getUnempEligQtr3Mon1() {
		return this.unempEligQtr3Mon1;
	}

	public void setUnempEligQtr3Mon1(Character unempEligQtr3Mon1) {
		this.unempEligQtr3Mon1 = unempEligQtr3Mon1;
	}

	@Column(name = "UNEMP_ELIG_QTR3_MON2", nullable = false, length = 1)
	public Character getUnempEligQtr3Mon2() {
		return this.unempEligQtr3Mon2;
	}

	public void setUnempEligQtr3Mon2(Character unempEligQtr3Mon2) {
		this.unempEligQtr3Mon2 = unempEligQtr3Mon2;
	}

	@Column(name = "UNEMP_ELIG_QTR3_MON3", nullable = false, length = 1)
	public Character getUnempEligQtr3Mon3() {
		return this.unempEligQtr3Mon3;
	}

	public void setUnempEligQtr3Mon3(Character unempEligQtr3Mon3) {
		this.unempEligQtr3Mon3 = unempEligQtr3Mon3;
	}

	@Column(name = "UNEMP_ELIG_QTR4_MON1", nullable = false, length = 1)
	public Character getUnempEligQtr4Mon1() {
		return this.unempEligQtr4Mon1;
	}

	public void setUnempEligQtr4Mon1(Character unempEligQtr4Mon1) {
		this.unempEligQtr4Mon1 = unempEligQtr4Mon1;
	}

	@Column(name = "UNEMP_ELIG_QTR4_MON2", nullable = false, length = 1)
	public Character getUnempEligQtr4Mon2() {
		return this.unempEligQtr4Mon2;
	}

	public void setUnempEligQtr4Mon2(Character unempEligQtr4Mon2) {
		this.unempEligQtr4Mon2 = unempEligQtr4Mon2;
	}

	@Column(name = "UNEMP_ELIG_QTR4_MON3", nullable = false, length = 1)
	public Character getUnempEligQtr4Mon3() {
		return this.unempEligQtr4Mon3;
	}

	public void setUnempEligQtr4Mon3(Character unempEligQtr4Mon3) {
		this.unempEligQtr4Mon3 = unempEligQtr4Mon3;
	}

	@Column(name = "DT_RETIRE", nullable = false, length = 8)
	public String getDtRetire() {
		return this.dtRetire;
	}

	public void setDtRetire(String dtRetire) {
		this.dtRetire = dtRetire;
	}

	@Column(name = "TAKE_RET_SURCHG", nullable = false, length = 1)
	public Character getTakeRetSurchg() {
		return this.takeRetSurchg;
	}

	public void setTakeRetSurchg(Character takeRetSurchg) {
		this.takeRetSurchg = takeRetSurchg;
	}

	@Column(name = "NY_TAKE_RET_SURCHG", nullable = false, length = 1)
	public Character getNyTakeRetSurchg() {
		return this.nyTakeRetSurchg;
	}

	public void setNyTakeRetSurchg(Character nyTakeRetSurchg) {
		this.nyTakeRetSurchg = nyTakeRetSurchg;
	}

	@Column(name = "FNGRPRT_STAT", nullable = false, length = 1)
	public Character getFngrprtStat() {
		return this.fngrprtStat;
	}

	public void setFngrprtStat(Character fngrprtStat) {
		this.fngrprtStat = fngrprtStat;
	}

	@Column(name = "DT_EXTR", nullable = false, length = 8)
	public String getDtExtr() {
		return this.dtExtr;
	}

	public void setDtExtr(String dtExtr) {
		this.dtExtr = dtExtr;
	}

	@Column(name = "DT_FNGRPRT", nullable = false, length = 8)
	public String getDtFngrprt() {
		return this.dtFngrprt;
	}

	public void setDtFngrprt(String dtFngrprt) {
		this.dtFngrprt = dtFngrprt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "ERS_RET_HLTH_ELIG", nullable = false, length = 1)
	public Character getErsRetHlthElig() {
		return this.ersRetHlthElig;
	}

	public void setErsRetHlthElig(Character ersRetHlthElig) {
		this.ersRetHlthElig = ersRetHlthElig;
	}

	@Column(name = "NY_ERS_RET_HLTH_ELIG", nullable = false, length = 1)
	public Character getNyErsRetHlthElig() {
		return this.nyErsRetHlthElig;
	}

	public void setNyErsRetHlthElig(Character nyErsRetHlthElig) {
		this.nyErsRetHlthElig = nyErsRetHlthElig;
	}

	@Column(name = "ELEC_CONSNT_W2", nullable = false, length = 1)
	public Character getElecConsntW2() {
		return this.elecConsntW2;
	}

	public void setElecConsntW2(Character elecConsntW2) {
		this.elecConsntW2 = elecConsntW2;
	}

	@Column(name = "ELEC_CONSNT_1095", nullable = false, length = 1)
	public Character getElecConsnt1095() {
		return this.elecConsnt1095;
	}

	public void setElecConsnt1095(Character elecConsnt1095) {
		this.elecConsnt1095 = elecConsnt1095;
	}

	@Column(name = "EMPLMNT_TYP_CD", nullable = false, length = 1)
	public Character getEmplmntTypCd() {
		return this.emplmntTypCd;
	}

	public void setEmplmntTypCd(Character emplmntTypCd) {
		this.emplmntTypCd = emplmntTypCd;
	}

	@Column(name = "RET_EMPLMNT_TYP_CD", nullable = false, length = 1)
	public Character getRetEmplmntTypCd() {
		return this.retEmplmntTypCd;
	}

	public void setRetEmplmntTypCd(Character retEmplmntTypCd) {
		this.retEmplmntTypCd = retEmplmntTypCd;
	}

	@Column(name = "FULL_SEM", nullable = false, length = 1)
	public Character getFullSem() {
		return this.fullSem;
	}

	public void setFullSem(Character fullSem) {
		this.fullSem = fullSem;
	}

	@Column(name = "AUX_ROLE_ID", nullable = false, length = 3)
	public String getAuxRoleId() {
		return this.auxRoleId;
	}

	public void setAuxRoleId(String auxRoleId) {
		this.auxRoleId = auxRoleId;
	}

}
