package com.esc20.model;
// Generated Jan 4, 2019 3:40:36 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpLv generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_LV", schema = "rsccc", catalog = "rsccc")
public class BhrEmpLv implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpLvId id;
	private BigDecimal lvBeginBal;
	private BigDecimal lvEarned;
	private BigDecimal lvUsed;
	private BigDecimal lvEndBal;
	private String module;

	public BhrEmpLv() {
	}

	public BhrEmpLv(BhrEmpLvId id, BigDecimal lvBeginBal, BigDecimal lvEarned, BigDecimal lvUsed, BigDecimal lvEndBal,
			String module) {
		this.id = id;
		this.lvBeginBal = lvBeginBal;
		this.lvEarned = lvEarned;
		this.lvUsed = lvUsed;
		this.lvEndBal = lvEndBal;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)) })
	public BhrEmpLvId getId() {
		return this.id;
	}

	public void setId(BhrEmpLvId id) {
		this.id = id;
	}

	@Column(name = "LV_BEGIN_BAL", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvBeginBal() {
		return this.lvBeginBal;
	}

	public void setLvBeginBal(BigDecimal lvBeginBal) {
		this.lvBeginBal = lvBeginBal;
	}

	@Column(name = "LV_EARNED", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvEarned() {
		return this.lvEarned;
	}

	public void setLvEarned(BigDecimal lvEarned) {
		this.lvEarned = lvEarned;
	}

	@Column(name = "LV_USED", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvUsed() {
		return this.lvUsed;
	}

	public void setLvUsed(BigDecimal lvUsed) {
		this.lvUsed = lvUsed;
	}

	@Column(name = "LV_END_BAL", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvEndBal() {
		return this.lvEndBal;
	}

	public void setLvEndBal(BigDecimal lvEndBal) {
		this.lvEndBal = lvEndBal;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
