package com.esc20.model;
// Generated Jan 4, 2019 3:40:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpLvXmitalBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_LV_XMITAL_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrEmpLvXmitalBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpLvXmitalBkupPaycalcs5Id id;

	public BhrEmpLvXmitalBkupPaycalcs5() {
	}

	public BhrEmpLvXmitalBkupPaycalcs5(BhrEmpLvXmitalBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "lvSeq", column = @Column(name = "LV_SEQ", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "absRsn", column = @Column(name = "ABS_RSN", nullable = false, length = 2)),
			@AttributeOverride(name = "dtOfAbs", column = @Column(name = "DT_OF_ABS", nullable = false, length = 8)),
			@AttributeOverride(name = "begTime", column = @Column(name = "BEG_TIME", nullable = false, length = 6)),
			@AttributeOverride(name = "lvUnitsUsed", column = @Column(name = "LV_UNITS_USED", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "lvUnitsEarned", column = @Column(name = "LV_UNITS_EARNED", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "subst", column = @Column(name = "SUBST", nullable = false, length = 2)),
			@AttributeOverride(name = "rsn", column = @Column(name = "RSN", nullable = false, length = 20)),
			@AttributeOverride(name = "processDt", column = @Column(name = "PROCESS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 12)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "lvId", column = @Column(name = "LV_ID", nullable = false)) })
	public BhrEmpLvXmitalBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrEmpLvXmitalBkupPaycalcs5Id id) {
		this.id = id;
	}

}
