package com.esc20.model;
// Generated Jan 4, 2019 3:40:12 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpExtraDuty generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_EXTRA_DUTY", schema = "rsccc", catalog = "rsccc")
public class BhrEmpExtraDuty implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpExtraDutyId id;
	private BigDecimal extraDutyAmt;
	private BigDecimal remainAmt;
	private short remainPymts;
	private String module;

	public BhrEmpExtraDuty() {
	}

	public BhrEmpExtraDuty(BhrEmpExtraDutyId id, BigDecimal extraDutyAmt, BigDecimal remainAmt, short remainPymts,
			String module) {
		this.id = id;
		this.extraDutyAmt = extraDutyAmt;
		this.remainAmt = remainAmt;
		this.remainPymts = remainPymts;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "extraDutyCd", column = @Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)) })
	public BhrEmpExtraDutyId getId() {
		return this.id;
	}

	public void setId(BhrEmpExtraDutyId id) {
		this.id = id;
	}

	@Column(name = "EXTRA_DUTY_AMT", nullable = false, precision = 9)
	public BigDecimal getExtraDutyAmt() {
		return this.extraDutyAmt;
	}

	public void setExtraDutyAmt(BigDecimal extraDutyAmt) {
		this.extraDutyAmt = extraDutyAmt;
	}

	@Column(name = "REMAIN_AMT", nullable = false, precision = 9)
	public BigDecimal getRemainAmt() {
		return this.remainAmt;
	}

	public void setRemainAmt(BigDecimal remainAmt) {
		this.remainAmt = remainAmt;
	}

	@Column(name = "REMAIN_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getRemainPymts() {
		return this.remainPymts;
	}

	public void setRemainPymts(short remainPymts) {
		this.remainPymts = remainPymts;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
