package com.esc20.model;
// Generated Jan 4, 2019 3:42:57 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEoyAccrualData generated by hbm2java
 */
@Entity
@Table(name = "BHR_EOY_ACCRUAL_DATA", schema = "rsccc", catalog = "rsccc")
public class BhrEoyAccrualData implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEoyAccrualDataId id;
	private BigDecimal accruUnits;
	private BigDecimal accruPayAmt;
	private BigDecimal dailyPayRate;
	private char payType;
	private String trsGrantCd;
	private BigDecimal accruFedGrant;
	private BigDecimal accruFedCare;
	private BigDecimal accruFedIns;
	private BigDecimal accruFicaTax;
	private BigDecimal accruUnempIns;
	private BigDecimal accruAbvSt;
	private String dtCalculations;
	private String dtCreated;
	private String dtInterfaced;
	private String dtPosted;
	private String dtPostReversals;
	private BigDecimal accruEmplrTrsCareContrib;
	private char origFsclYr;
	private BigDecimal accruCafeAmt;
	private BigDecimal accruEmplrRetPensnSurchg;
	private String jvNbr;
	private String jvClearingFund;
	private char jvClearingFsclYr;
	private char jvFinFileId;

	public BhrEoyAccrualData() {
	}

	public BhrEoyAccrualData(BhrEoyAccrualDataId id, BigDecimal accruUnits, BigDecimal accruPayAmt,
			BigDecimal dailyPayRate, char payType, String trsGrantCd, BigDecimal accruFedGrant, BigDecimal accruFedCare,
			BigDecimal accruFedIns, BigDecimal accruFicaTax, BigDecimal accruUnempIns, BigDecimal accruAbvSt,
			String dtCalculations, String dtCreated, String dtInterfaced, String dtPosted, String dtPostReversals,
			BigDecimal accruEmplrTrsCareContrib, char origFsclYr, BigDecimal accruCafeAmt,
			BigDecimal accruEmplrRetPensnSurchg, String jvNbr, String jvClearingFund, char jvClearingFsclYr,
			char jvFinFileId) {
		this.id = id;
		this.accruUnits = accruUnits;
		this.accruPayAmt = accruPayAmt;
		this.dailyPayRate = dailyPayRate;
		this.payType = payType;
		this.trsGrantCd = trsGrantCd;
		this.accruFedGrant = accruFedGrant;
		this.accruFedCare = accruFedCare;
		this.accruFedIns = accruFedIns;
		this.accruFicaTax = accruFicaTax;
		this.accruUnempIns = accruUnempIns;
		this.accruAbvSt = accruAbvSt;
		this.dtCalculations = dtCalculations;
		this.dtCreated = dtCreated;
		this.dtInterfaced = dtInterfaced;
		this.dtPosted = dtPosted;
		this.dtPostReversals = dtPostReversals;
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
		this.origFsclYr = origFsclYr;
		this.accruCafeAmt = accruCafeAmt;
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
		this.jvNbr = jvNbr;
		this.jvClearingFund = jvClearingFund;
		this.jvClearingFsclYr = jvClearingFsclYr;
		this.jvFinFileId = jvFinFileId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)),
			@AttributeOverride(name = "fund", column = @Column(name = "FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "func", column = @Column(name = "FUNC", nullable = false, length = 2)),
			@AttributeOverride(name = "obj", column = @Column(name = "OBJ", nullable = false, length = 4)),
			@AttributeOverride(name = "sobj", column = @Column(name = "SOBJ", nullable = false, length = 2)),
			@AttributeOverride(name = "org", column = @Column(name = "ORG", nullable = false, length = 3)),
			@AttributeOverride(name = "fsclYr", column = @Column(name = "FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "pgm", column = @Column(name = "PGM", nullable = false, length = 2)),
			@AttributeOverride(name = "edSpan", column = @Column(name = "ED_SPAN", nullable = false, length = 1)),
			@AttributeOverride(name = "projDtl", column = @Column(name = "PROJ_DTL", nullable = false, length = 2)),
			@AttributeOverride(name = "glFileId", column = @Column(name = "GL_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, precision = 3, scale = 0)) })
	public BhrEoyAccrualDataId getId() {
		return this.id;
	}

	public void setId(BhrEoyAccrualDataId id) {
		this.id = id;
	}

	@Column(name = "ACCRU_UNITS", nullable = false, precision = 5)
	public BigDecimal getAccruUnits() {
		return this.accruUnits;
	}

	public void setAccruUnits(BigDecimal accruUnits) {
		this.accruUnits = accruUnits;
	}

	@Column(name = "ACCRU_PAY_AMT", nullable = false, precision = 9)
	public BigDecimal getAccruPayAmt() {
		return this.accruPayAmt;
	}

	public void setAccruPayAmt(BigDecimal accruPayAmt) {
		this.accruPayAmt = accruPayAmt;
	}

	@Column(name = "DAILY_PAY_RATE", nullable = false, precision = 7, scale = 3)
	public BigDecimal getDailyPayRate() {
		return this.dailyPayRate;
	}

	public void setDailyPayRate(BigDecimal dailyPayRate) {
		this.dailyPayRate = dailyPayRate;
	}

	@Column(name = "PAY_TYPE", nullable = false, length = 1)
	public char getPayType() {
		return this.payType;
	}

	public void setPayType(char payType) {
		this.payType = payType;
	}

	@Column(name = "TRS_GRANT_CD", nullable = false, length = 2)
	public String getTrsGrantCd() {
		return this.trsGrantCd;
	}

	public void setTrsGrantCd(String trsGrantCd) {
		this.trsGrantCd = trsGrantCd;
	}

	@Column(name = "ACCRU_FED_GRANT", nullable = false, precision = 9)
	public BigDecimal getAccruFedGrant() {
		return this.accruFedGrant;
	}

	public void setAccruFedGrant(BigDecimal accruFedGrant) {
		this.accruFedGrant = accruFedGrant;
	}

	@Column(name = "ACCRU_FED_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruFedCare() {
		return this.accruFedCare;
	}

	public void setAccruFedCare(BigDecimal accruFedCare) {
		this.accruFedCare = accruFedCare;
	}

	@Column(name = "ACCRU_FED_INS", nullable = false, precision = 9)
	public BigDecimal getAccruFedIns() {
		return this.accruFedIns;
	}

	public void setAccruFedIns(BigDecimal accruFedIns) {
		this.accruFedIns = accruFedIns;
	}

	@Column(name = "ACCRU_FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getAccruFicaTax() {
		return this.accruFicaTax;
	}

	public void setAccruFicaTax(BigDecimal accruFicaTax) {
		this.accruFicaTax = accruFicaTax;
	}

	@Column(name = "ACCRU_UNEMP_INS", nullable = false, precision = 9)
	public BigDecimal getAccruUnempIns() {
		return this.accruUnempIns;
	}

	public void setAccruUnempIns(BigDecimal accruUnempIns) {
		this.accruUnempIns = accruUnempIns;
	}

	@Column(name = "ACCRU_ABV_ST", nullable = false, precision = 9)
	public BigDecimal getAccruAbvSt() {
		return this.accruAbvSt;
	}

	public void setAccruAbvSt(BigDecimal accruAbvSt) {
		this.accruAbvSt = accruAbvSt;
	}

	@Column(name = "DT_CALCULATIONS", nullable = false, length = 8)
	public String getDtCalculations() {
		return this.dtCalculations;
	}

	public void setDtCalculations(String dtCalculations) {
		this.dtCalculations = dtCalculations;
	}

	@Column(name = "DT_CREATED", nullable = false, length = 8)
	public String getDtCreated() {
		return this.dtCreated;
	}

	public void setDtCreated(String dtCreated) {
		this.dtCreated = dtCreated;
	}

	@Column(name = "DT_INTERFACED", nullable = false, length = 8)
	public String getDtInterfaced() {
		return this.dtInterfaced;
	}

	public void setDtInterfaced(String dtInterfaced) {
		this.dtInterfaced = dtInterfaced;
	}

	@Column(name = "DT_POSTED", nullable = false, length = 8)
	public String getDtPosted() {
		return this.dtPosted;
	}

	public void setDtPosted(String dtPosted) {
		this.dtPosted = dtPosted;
	}

	@Column(name = "DT_POST_REVERSALS", nullable = false, length = 8)
	public String getDtPostReversals() {
		return this.dtPostReversals;
	}

	public void setDtPostReversals(String dtPostReversals) {
		this.dtPostReversals = dtPostReversals;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrTrsCareContrib() {
		return this.accruEmplrTrsCareContrib;
	}

	public void setAccruEmplrTrsCareContrib(BigDecimal accruEmplrTrsCareContrib) {
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
	}

	@Column(name = "ORIG_FSCL_YR", nullable = false, length = 1)
	public char getOrigFsclYr() {
		return this.origFsclYr;
	}

	public void setOrigFsclYr(char origFsclYr) {
		this.origFsclYr = origFsclYr;
	}

	@Column(name = "ACCRU_CAFE_AMT", nullable = false, precision = 9)
	public BigDecimal getAccruCafeAmt() {
		return this.accruCafeAmt;
	}

	public void setAccruCafeAmt(BigDecimal accruCafeAmt) {
		this.accruCafeAmt = accruCafeAmt;
	}

	@Column(name = "ACCRU_EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrRetPensnSurchg() {
		return this.accruEmplrRetPensnSurchg;
	}

	public void setAccruEmplrRetPensnSurchg(BigDecimal accruEmplrRetPensnSurchg) {
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
	}

	@Column(name = "JV_NBR", nullable = false, length = 6)
	public String getJvNbr() {
		return this.jvNbr;
	}

	public void setJvNbr(String jvNbr) {
		this.jvNbr = jvNbr;
	}

	@Column(name = "JV_CLEARING_FUND", nullable = false, length = 3)
	public String getJvClearingFund() {
		return this.jvClearingFund;
	}

	public void setJvClearingFund(String jvClearingFund) {
		this.jvClearingFund = jvClearingFund;
	}

	@Column(name = "JV_CLEARING_FSCL_YR", nullable = false, length = 1)
	public char getJvClearingFsclYr() {
		return this.jvClearingFsclYr;
	}

	public void setJvClearingFsclYr(char jvClearingFsclYr) {
		this.jvClearingFsclYr = jvClearingFsclYr;
	}

	@Column(name = "JV_FIN_FILE_ID", nullable = false, length = 1)
	public char getJvFinFileId() {
		return this.jvFinFileId;
	}

	public void setJvFinFileId(char jvFinFileId) {
		this.jvFinFileId = jvFinFileId;
	}

}
