package com.esc20.model;
// Generated Jan 4, 2019 3:40:12 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * BhrEmpEmply generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_EMPLY", schema = "rsccc", catalog = "rsccc")
public class BhrEmpEmply implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private String empNbr;
	private BhrEmpDemo bhrEmpDemo;
	private String statCdEmpl;
	private String dtOrgEmp;
	private String yrsExpDist;
	private String yrsExpDistLoc;
	private String yrsProExper;
	private String yrsProExperLoc;
	private String contrClass;
	private String contrTerm;
	private String contrYr;
	private String subTyp;
	private BigDecimal dayEmpldPct;
	private String dtReassign;
	private String dtTerm;
	private String termRea;
	private String dtReEmp;
	private String lvOfAbsBegin;
	private String lvOfAbsEnd;
	private String lvRsn;
	private String yrRound;
	private String extractId;
	private String eligRehire;
	private String highDegree;
	private String gradesTaught;
	private String campusCluster;
	private String campusLvl;
	private String dtPhyExam;
	private String dtTbExam;
	private String totYrsExpClaim;
	private short transReqNum;
	private String transReqRsn;
	private String verifyDob;
	private String verifyService;
	private String verifyTrans;
	private String verifyRef;
	private String verifyCert;
	private String verifyOath;
	private String tcatYr;
	private String tcatResult;
	private short hrsAboveDegree;
	private short hrsThisPer;
	private short inserHrs;
	private String dtLInser;
	private String interviewCd;
	private String interviewLoc;
	private String sourceNewPer;
	private String noBudChg;
	private String campusIdAlt;
	private String deptAlt;
	private String orgBud;
	private String crimeHistDt;
	private String crimeHistTyp;
	private String crimeHistPost;
	private String evaluator;
	private String receive13th;
	private String trs118Sel;
	private String yrsExpPayStep;
	private int estAnnualSalaryHrly;
	private String estAnnualPayActy;
	private String estAnnualFund;
	private String estAnnualFunc;
	private String estAnnualObj;
	private String estAnnualOrg;
	private String estAnnualPgm;
	private String unempEligQtr1Mon1;
	private String unempEligQtr1Mon2;
	private String unempEligQtr1Mon3;
	private String unempEligQtr2Mon1;
	private String unempEligQtr2Mon2;
	private String unempEligQtr2Mon3;
	private String unempEligQtr3Mon1;
	private String unempEligQtr3Mon2;
	private String unempEligQtr3Mon3;
	private String unempEligQtr4Mon1;
	private String unempEligQtr4Mon2;
	private String unempEligQtr4Mon3;
	private String dtRetire;
	private String takeRetSurchg;
	private String nyTakeRetSurchg;
	private String fngrprtStat;
	private String dtExtr;
	private String dtFngrprt;
	private String module;
	private String ersRetHlthElig;
	private String nyErsRetHlthElig;
	private String elecConsntW2;
	private String elecConsnt1095;
	private String emplmntTypCd;
	private String retEmplmntTypCd;
	private String fullSem;
	private String auxRoleId;

	public BhrEmpEmply() {
	}

	public BhrEmpEmply(BhrEmpDemo bhrEmpDemo, String statCdEmpl, String dtOrgEmp, String yrsExpDist, String yrsExpDistLoc,
			String yrsProExper, String yrsProExperLoc, String contrClass, String contrTerm, String contrYr,
			String subTyp, BigDecimal dayEmpldPct, String dtReassign, String dtTerm, String termRea, String dtReEmp,
			String lvOfAbsBegin, String lvOfAbsEnd, String lvRsn, String yrRound, String extractId, String eligRehire,
			String highDegree, String gradesTaught, String campusCluster, String campusLvl, String dtPhyExam, String dtTbExam,
			String totYrsExpClaim, short transReqNum, String transReqRsn, String verifyDob, String verifyService,
			String verifyTrans, String verifyRef, String verifyCert, String verifyOath, String tcatYr, String tcatResult,
			short hrsAboveDegree, short hrsThisPer, short inserHrs, String dtLInser, String interviewCd,
			String interviewLoc, String sourceNewPer, String noBudChg, String campusIdAlt, String deptAlt, String orgBud,
			String crimeHistDt, String crimeHistTyp, String crimeHistPost, String evaluator, String receive13th,
			String trs118Sel, String yrsExpPayStep, int estAnnualSalaryHrly, String estAnnualPayActy, String estAnnualFund,
			String estAnnualFunc, String estAnnualObj, String estAnnualOrg, String estAnnualPgm, String unempEligQtr1Mon1,
			String unempEligQtr1Mon2, String unempEligQtr1Mon3, String unempEligQtr2Mon1, String unempEligQtr2Mon2,
			String unempEligQtr2Mon3, String unempEligQtr3Mon1, String unempEligQtr3Mon2, String unempEligQtr3Mon3,
			String unempEligQtr4Mon1, String unempEligQtr4Mon2, String unempEligQtr4Mon3, String dtRetire, String takeRetSurchg,
			String nyTakeRetSurchg, String fngrprtStat, String dtExtr, String dtFngrprt, String module, String ersRetHlthElig,
			String nyErsRetHlthElig, String elecConsntW2, String elecConsnt1095, String emplmntTypCd, String retEmplmntTypCd,
			String fullSem, String auxRoleId) {
		this.bhrEmpDemo = bhrEmpDemo;
		this.statCdEmpl = statCdEmpl;
		this.dtOrgEmp = dtOrgEmp;
		this.yrsExpDist = yrsExpDist;
		this.yrsExpDistLoc = yrsExpDistLoc;
		this.yrsProExper = yrsProExper;
		this.yrsProExperLoc = yrsProExperLoc;
		this.contrClass = contrClass;
		this.contrTerm = contrTerm;
		this.contrYr = contrYr;
		this.subTyp = subTyp;
		this.dayEmpldPct = dayEmpldPct;
		this.dtReassign = dtReassign;
		this.dtTerm = dtTerm;
		this.termRea = termRea;
		this.dtReEmp = dtReEmp;
		this.lvOfAbsBegin = lvOfAbsBegin;
		this.lvOfAbsEnd = lvOfAbsEnd;
		this.lvRsn = lvRsn;
		this.yrRound = yrRound;
		this.extractId = extractId;
		this.eligRehire = eligRehire;
		this.highDegree = highDegree;
		this.gradesTaught = gradesTaught;
		this.campusCluster = campusCluster;
		this.campusLvl = campusLvl;
		this.dtPhyExam = dtPhyExam;
		this.dtTbExam = dtTbExam;
		this.totYrsExpClaim = totYrsExpClaim;
		this.transReqNum = transReqNum;
		this.transReqRsn = transReqRsn;
		this.verifyDob = verifyDob;
		this.verifyService = verifyService;
		this.verifyTrans = verifyTrans;
		this.verifyRef = verifyRef;
		this.verifyCert = verifyCert;
		this.verifyOath = verifyOath;
		this.tcatYr = tcatYr;
		this.tcatResult = tcatResult;
		this.hrsAboveDegree = hrsAboveDegree;
		this.hrsThisPer = hrsThisPer;
		this.inserHrs = inserHrs;
		this.dtLInser = dtLInser;
		this.interviewCd = interviewCd;
		this.interviewLoc = interviewLoc;
		this.sourceNewPer = sourceNewPer;
		this.noBudChg = noBudChg;
		this.campusIdAlt = campusIdAlt;
		this.deptAlt = deptAlt;
		this.orgBud = orgBud;
		this.crimeHistDt = crimeHistDt;
		this.crimeHistTyp = crimeHistTyp;
		this.crimeHistPost = crimeHistPost;
		this.evaluator = evaluator;
		this.receive13th = receive13th;
		this.trs118Sel = trs118Sel;
		this.yrsExpPayStep = yrsExpPayStep;
		this.estAnnualSalaryHrly = estAnnualSalaryHrly;
		this.estAnnualPayActy = estAnnualPayActy;
		this.estAnnualFund = estAnnualFund;
		this.estAnnualFunc = estAnnualFunc;
		this.estAnnualObj = estAnnualObj;
		this.estAnnualOrg = estAnnualOrg;
		this.estAnnualPgm = estAnnualPgm;
		this.unempEligQtr1Mon1 = unempEligQtr1Mon1;
		this.unempEligQtr1Mon2 = unempEligQtr1Mon2;
		this.unempEligQtr1Mon3 = unempEligQtr1Mon3;
		this.unempEligQtr2Mon1 = unempEligQtr2Mon1;
		this.unempEligQtr2Mon2 = unempEligQtr2Mon2;
		this.unempEligQtr2Mon3 = unempEligQtr2Mon3;
		this.unempEligQtr3Mon1 = unempEligQtr3Mon1;
		this.unempEligQtr3Mon2 = unempEligQtr3Mon2;
		this.unempEligQtr3Mon3 = unempEligQtr3Mon3;
		this.unempEligQtr4Mon1 = unempEligQtr4Mon1;
		this.unempEligQtr4Mon2 = unempEligQtr4Mon2;
		this.unempEligQtr4Mon3 = unempEligQtr4Mon3;
		this.dtRetire = dtRetire;
		this.takeRetSurchg = takeRetSurchg;
		this.nyTakeRetSurchg = nyTakeRetSurchg;
		this.fngrprtStat = fngrprtStat;
		this.dtExtr = dtExtr;
		this.dtFngrprt = dtFngrprt;
		this.module = module;
		this.ersRetHlthElig = ersRetHlthElig;
		this.nyErsRetHlthElig = nyErsRetHlthElig;
		this.elecConsntW2 = elecConsntW2;
		this.elecConsnt1095 = elecConsnt1095;
		this.emplmntTypCd = emplmntTypCd;
		this.retEmplmntTypCd = retEmplmntTypCd;
		this.fullSem = fullSem;
		this.auxRoleId = auxRoleId;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "bhrEmpDemo"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public BhrEmpDemo getBhrEmpDemo() {
		return this.bhrEmpDemo;
	}

	public void setBhrEmpDemo(BhrEmpDemo bhrEmpDemo) {
		this.bhrEmpDemo = bhrEmpDemo;
	}

	@Column(name = "STAT_CD_EMPL", nullable = false, length = 1)
	public String getStatCdEmpl() {
		return this.statCdEmpl;
	}

	public void setStatCdEmpl(String statCdEmpl) {
		this.statCdEmpl = statCdEmpl;
	}

	@Column(name = "DT_ORG_EMP", nullable = false, length = 8)
	public String getDtOrgEmp() {
		return this.dtOrgEmp;
	}

	public void setDtOrgEmp(String dtOrgEmp) {
		this.dtOrgEmp = dtOrgEmp;
	}

	@Column(name = "YRS_EXP_DIST", nullable = false, length = 2)
	public String getYrsExpDist() {
		return this.yrsExpDist;
	}

	public void setYrsExpDist(String yrsExpDist) {
		this.yrsExpDist = yrsExpDist;
	}

	@Column(name = "YRS_EXP_DIST_LOC", nullable = false, length = 2)
	public String getYrsExpDistLoc() {
		return this.yrsExpDistLoc;
	}

	public void setYrsExpDistLoc(String yrsExpDistLoc) {
		this.yrsExpDistLoc = yrsExpDistLoc;
	}

	@Column(name = "YRS_PRO_EXPER", nullable = false, length = 2)
	public String getYrsProExper() {
		return this.yrsProExper;
	}

	public void setYrsProExper(String yrsProExper) {
		this.yrsProExper = yrsProExper;
	}

	@Column(name = "YRS_PRO_EXPER_LOC", nullable = false, length = 2)
	public String getYrsProExperLoc() {
		return this.yrsProExperLoc;
	}

	public void setYrsProExperLoc(String yrsProExperLoc) {
		this.yrsProExperLoc = yrsProExperLoc;
	}

	@Column(name = "CONTR_CLASS", nullable = false, length = 2)
	public String getContrClass() {
		return this.contrClass;
	}

	public void setContrClass(String contrClass) {
		this.contrClass = contrClass;
	}

	@Column(name = "CONTR_TERM", nullable = false, length = 2)
	public String getContrTerm() {
		return this.contrTerm;
	}

	public void setContrTerm(String contrTerm) {
		this.contrTerm = contrTerm;
	}

	@Column(name = "CONTR_YR", nullable = false, length = 2)
	public String getContrYr() {
		return this.contrYr;
	}

	public void setContrYr(String contrYr) {
		this.contrYr = contrYr;
	}

	@Column(name = "SUB_TYP", nullable = false, length = 2)
	public String getSubTyp() {
		return this.subTyp;
	}

	public void setSubTyp(String subTyp) {
		this.subTyp = subTyp;
	}

	@Column(name = "DAY_EMPLD_PCT", nullable = false, precision = 3)
	public BigDecimal getDayEmpldPct() {
		return this.dayEmpldPct;
	}

	public void setDayEmpldPct(BigDecimal dayEmpldPct) {
		this.dayEmpldPct = dayEmpldPct;
	}

	@Column(name = "DT_REASSIGN", nullable = false, length = 8)
	public String getDtReassign() {
		return this.dtReassign;
	}

	public void setDtReassign(String dtReassign) {
		this.dtReassign = dtReassign;
	}

	@Column(name = "DT_TERM", nullable = false, length = 8)
	public String getDtTerm() {
		return this.dtTerm;
	}

	public void setDtTerm(String dtTerm) {
		this.dtTerm = dtTerm;
	}

	@Column(name = "TERM_REA", nullable = false, length = 2)
	public String getTermRea() {
		return this.termRea;
	}

	public void setTermRea(String termRea) {
		this.termRea = termRea;
	}

	@Column(name = "DT_RE_EMP", nullable = false, length = 8)
	public String getDtReEmp() {
		return this.dtReEmp;
	}

	public void setDtReEmp(String dtReEmp) {
		this.dtReEmp = dtReEmp;
	}

	@Column(name = "LV_OF_ABS_BEGIN", nullable = false, length = 8)
	public String getLvOfAbsBegin() {
		return this.lvOfAbsBegin;
	}

	public void setLvOfAbsBegin(String lvOfAbsBegin) {
		this.lvOfAbsBegin = lvOfAbsBegin;
	}

	@Column(name = "LV_OF_ABS_END", nullable = false, length = 8)
	public String getLvOfAbsEnd() {
		return this.lvOfAbsEnd;
	}

	public void setLvOfAbsEnd(String lvOfAbsEnd) {
		this.lvOfAbsEnd = lvOfAbsEnd;
	}

	@Column(name = "LV_RSN", nullable = false, length = 3)
	public String getLvRsn() {
		return this.lvRsn;
	}

	public void setLvRsn(String lvRsn) {
		this.lvRsn = lvRsn;
	}

	@Column(name = "YR_ROUND", nullable = false, length = 1)
	public String getYrRound() {
		return this.yrRound;
	}

	public void setYrRound(String yrRound) {
		this.yrRound = yrRound;
	}

	@Column(name = "EXTRACT_ID", nullable = false, length = 3)
	public String getExtractId() {
		return this.extractId;
	}

	public void setExtractId(String extractId) {
		this.extractId = extractId;
	}

	@Column(name = "ELIG_REHIRE", nullable = false, length = 1)
	public String getEligRehire() {
		return this.eligRehire;
	}

	public void setEligRehire(String eligRehire) {
		this.eligRehire = eligRehire;
	}

	@Column(name = "HIGH_DEGREE", nullable = false, length = 1)
	public String getHighDegree() {
		return this.highDegree;
	}

	public void setHighDegree(String highDegree) {
		this.highDegree = highDegree;
	}

	@Column(name = "GRADES_TAUGHT", nullable = false, length = 7)
	public String getGradesTaught() {
		return this.gradesTaught;
	}

	public void setGradesTaught(String gradesTaught) {
		this.gradesTaught = gradesTaught;
	}

	@Column(name = "CAMPUS_CLUSTER", nullable = false, length = 1)
	public String getCampusCluster() {
		return this.campusCluster;
	}

	public void setCampusCluster(String campusCluster) {
		this.campusCluster = campusCluster;
	}

	@Column(name = "CAMPUS_LVL", nullable = false, length = 1)
	public String getCampusLvl() {
		return this.campusLvl;
	}

	public void setCampusLvl(String campusLvl) {
		this.campusLvl = campusLvl;
	}

	@Column(name = "DT_PHY_EXAM", nullable = false, length = 8)
	public String getDtPhyExam() {
		return this.dtPhyExam;
	}

	public void setDtPhyExam(String dtPhyExam) {
		this.dtPhyExam = dtPhyExam;
	}

	@Column(name = "DT_TB_EXAM", nullable = false, length = 8)
	public String getDtTbExam() {
		return this.dtTbExam;
	}

	public void setDtTbExam(String dtTbExam) {
		this.dtTbExam = dtTbExam;
	}

	@Column(name = "TOT_YRS_EXP_CLAIM", nullable = false, length = 2)
	public String getTotYrsExpClaim() {
		return this.totYrsExpClaim;
	}

	public void setTotYrsExpClaim(String totYrsExpClaim) {
		this.totYrsExpClaim = totYrsExpClaim;
	}

	@Column(name = "TRANS_REQ_NUM", nullable = false, precision = 3, scale = 0)
	public short getTransReqNum() {
		return this.transReqNum;
	}

	public void setTransReqNum(short transReqNum) {
		this.transReqNum = transReqNum;
	}

	@Column(name = "TRANS_REQ_RSN", nullable = false, length = 1)
	public String getTransReqRsn() {
		return this.transReqRsn;
	}

	public void setTransReqRsn(String transReqRsn) {
		this.transReqRsn = transReqRsn;
	}

	@Column(name = "VERIFY_DOB", nullable = false, length = 1)
	public String getVerifyDob() {
		return this.verifyDob;
	}

	public void setVerifyDob(String verifyDob) {
		this.verifyDob = verifyDob;
	}

	@Column(name = "VERIFY_SERVICE", nullable = false, length = 1)
	public String getVerifyService() {
		return this.verifyService;
	}

	public void setVerifyService(String verifyService) {
		this.verifyService = verifyService;
	}

	@Column(name = "VERIFY_TRANS", nullable = false, length = 1)
	public String getVerifyTrans() {
		return this.verifyTrans;
	}

	public void setVerifyTrans(String verifyTrans) {
		this.verifyTrans = verifyTrans;
	}

	@Column(name = "VERIFY_REF", nullable = false, length = 1)
	public String getVerifyRef() {
		return this.verifyRef;
	}

	public void setVerifyRef(String verifyRef) {
		this.verifyRef = verifyRef;
	}

	@Column(name = "VERIFY_CERT", nullable = false, length = 1)
	public String getVerifyCert() {
		return this.verifyCert;
	}

	public void setVerifyCert(String verifyCert) {
		this.verifyCert = verifyCert;
	}

	@Column(name = "VERIFY_OATH", nullable = false, length = 1)
	public String getVerifyOath() {
		return this.verifyOath;
	}

	public void setVerifyOath(String verifyOath) {
		this.verifyOath = verifyOath;
	}

	@Column(name = "TCAT_YR", nullable = false, length = 4)
	public String getTcatYr() {
		return this.tcatYr;
	}

	public void setTcatYr(String tcatYr) {
		this.tcatYr = tcatYr;
	}

	@Column(name = "TCAT_RESULT", nullable = false, length = 1)
	public String getTcatResult() {
		return this.tcatResult;
	}

	public void setTcatResult(String tcatResult) {
		this.tcatResult = tcatResult;
	}

	@Column(name = "HRS_ABOVE_DEGREE", nullable = false, precision = 3, scale = 0)
	public short getHrsAboveDegree() {
		return this.hrsAboveDegree;
	}

	public void setHrsAboveDegree(short hrsAboveDegree) {
		this.hrsAboveDegree = hrsAboveDegree;
	}

	@Column(name = "HRS_THIS_PER", nullable = false, precision = 3, scale = 0)
	public short getHrsThisPer() {
		return this.hrsThisPer;
	}

	public void setHrsThisPer(short hrsThisPer) {
		this.hrsThisPer = hrsThisPer;
	}

	@Column(name = "INSER_HRS", nullable = false, precision = 3, scale = 0)
	public short getInserHrs() {
		return this.inserHrs;
	}

	public void setInserHrs(short inserHrs) {
		this.inserHrs = inserHrs;
	}

	@Column(name = "DT_L_INSER", nullable = false, length = 8)
	public String getDtLInser() {
		return this.dtLInser;
	}

	public void setDtLInser(String dtLInser) {
		this.dtLInser = dtLInser;
	}

	@Column(name = "INTERVIEW_CD", nullable = false, length = 2)
	public String getInterviewCd() {
		return this.interviewCd;
	}

	public void setInterviewCd(String interviewCd) {
		this.interviewCd = interviewCd;
	}

	@Column(name = "INTERVIEW_LOC", nullable = false, length = 2)
	public String getInterviewLoc() {
		return this.interviewLoc;
	}

	public void setInterviewLoc(String interviewLoc) {
		this.interviewLoc = interviewLoc;
	}

	@Column(name = "SOURCE_NEW_PER", nullable = false, length = 1)
	public String getSourceNewPer() {
		return this.sourceNewPer;
	}

	public void setSourceNewPer(String sourceNewPer) {
		this.sourceNewPer = sourceNewPer;
	}

	@Column(name = "NO_BUD_CHG", nullable = false, length = 1)
	public String getNoBudChg() {
		return this.noBudChg;
	}

	public void setNoBudChg(String noBudChg) {
		this.noBudChg = noBudChg;
	}

	@Column(name = "CAMPUS_ID_ALT", nullable = false, length = 3)
	public String getCampusIdAlt() {
		return this.campusIdAlt;
	}

	public void setCampusIdAlt(String campusIdAlt) {
		this.campusIdAlt = campusIdAlt;
	}

	@Column(name = "DEPT_ALT", nullable = false, length = 1)
	public String getDeptAlt() {
		return this.deptAlt;
	}

	public void setDeptAlt(String deptAlt) {
		this.deptAlt = deptAlt;
	}

	@Column(name = "ORG_BUD", nullable = false, length = 3)
	public String getOrgBud() {
		return this.orgBud;
	}

	public void setOrgBud(String orgBud) {
		this.orgBud = orgBud;
	}

	@Column(name = "CRIME_HIST_DT", nullable = false, length = 8)
	public String getCrimeHistDt() {
		return this.crimeHistDt;
	}

	public void setCrimeHistDt(String crimeHistDt) {
		this.crimeHistDt = crimeHistDt;
	}

	@Column(name = "CRIME_HIST_TYP", nullable = false, length = 2)
	public String getCrimeHistTyp() {
		return this.crimeHistTyp;
	}

	public void setCrimeHistTyp(String crimeHistTyp) {
		this.crimeHistTyp = crimeHistTyp;
	}

	@Column(name = "CRIME_HIST_POST", nullable = false, length = 1)
	public String getCrimeHistPost() {
		return this.crimeHistPost;
	}

	public void setCrimeHistPost(String crimeHistPost) {
		this.crimeHistPost = crimeHistPost;
	}

	@Column(name = "EVALUATOR", nullable = false, length = 9)
	public String getEvaluator() {
		return this.evaluator;
	}

	public void setEvaluator(String evaluator) {
		this.evaluator = evaluator;
	}

	@Column(name = "RECEIVE_13TH", nullable = false, length = 1)
	public String getReceive13th() {
		return this.receive13th;
	}

	public void setReceive13th(String receive13th) {
		this.receive13th = receive13th;
	}

	@Column(name = "TRS_118_SEL", nullable = false, length = 1)
	public String getTrs118Sel() {
		return this.trs118Sel;
	}

	public void setTrs118Sel(String trs118Sel) {
		this.trs118Sel = trs118Sel;
	}

	@Column(name = "YRS_EXP_PAY_STEP", nullable = false, length = 1)
	public String getYrsExpPayStep() {
		return this.yrsExpPayStep;
	}

	public void setYrsExpPayStep(String yrsExpPayStep) {
		this.yrsExpPayStep = yrsExpPayStep;
	}

	@Column(name = "EST_ANNUAL_SALARY_HRLY", nullable = false, precision = 6, scale = 0)
	public int getEstAnnualSalaryHrly() {
		return this.estAnnualSalaryHrly;
	}

	public void setEstAnnualSalaryHrly(int estAnnualSalaryHrly) {
		this.estAnnualSalaryHrly = estAnnualSalaryHrly;
	}

	@Column(name = "EST_ANNUAL_PAY_ACTY", nullable = false, length = 2)
	public String getEstAnnualPayActy() {
		return this.estAnnualPayActy;
	}

	public void setEstAnnualPayActy(String estAnnualPayActy) {
		this.estAnnualPayActy = estAnnualPayActy;
	}

	@Column(name = "EST_ANNUAL_FUND", nullable = false, length = 3)
	public String getEstAnnualFund() {
		return this.estAnnualFund;
	}

	public void setEstAnnualFund(String estAnnualFund) {
		this.estAnnualFund = estAnnualFund;
	}

	@Column(name = "EST_ANNUAL_FUNC", nullable = false, length = 2)
	public String getEstAnnualFunc() {
		return this.estAnnualFunc;
	}

	public void setEstAnnualFunc(String estAnnualFunc) {
		this.estAnnualFunc = estAnnualFunc;
	}

	@Column(name = "EST_ANNUAL_OBJ", nullable = false, length = 4)
	public String getEstAnnualObj() {
		return this.estAnnualObj;
	}

	public void setEstAnnualObj(String estAnnualObj) {
		this.estAnnualObj = estAnnualObj;
	}

	@Column(name = "EST_ANNUAL_ORG", nullable = false, length = 3)
	public String getEstAnnualOrg() {
		return this.estAnnualOrg;
	}

	public void setEstAnnualOrg(String estAnnualOrg) {
		this.estAnnualOrg = estAnnualOrg;
	}

	@Column(name = "EST_ANNUAL_PGM", nullable = false, length = 2)
	public String getEstAnnualPgm() {
		return this.estAnnualPgm;
	}

	public void setEstAnnualPgm(String estAnnualPgm) {
		this.estAnnualPgm = estAnnualPgm;
	}

	@Column(name = "UNEMP_ELIG_QTR1_MON1", nullable = false, length = 1)
	public String getUnempEligQtr1Mon1() {
		return this.unempEligQtr1Mon1;
	}

	public void setUnempEligQtr1Mon1(String unempEligQtr1Mon1) {
		this.unempEligQtr1Mon1 = unempEligQtr1Mon1;
	}

	@Column(name = "UNEMP_ELIG_QTR1_MON2", nullable = false, length = 1)
	public String getUnempEligQtr1Mon2() {
		return this.unempEligQtr1Mon2;
	}

	public void setUnempEligQtr1Mon2(String unempEligQtr1Mon2) {
		this.unempEligQtr1Mon2 = unempEligQtr1Mon2;
	}

	@Column(name = "UNEMP_ELIG_QTR1_MON3", nullable = false, length = 1)
	public String getUnempEligQtr1Mon3() {
		return this.unempEligQtr1Mon3;
	}

	public void setUnempEligQtr1Mon3(String unempEligQtr1Mon3) {
		this.unempEligQtr1Mon3 = unempEligQtr1Mon3;
	}

	@Column(name = "UNEMP_ELIG_QTR2_MON1", nullable = false, length = 1)
	public String getUnempEligQtr2Mon1() {
		return this.unempEligQtr2Mon1;
	}

	public void setUnempEligQtr2Mon1(String unempEligQtr2Mon1) {
		this.unempEligQtr2Mon1 = unempEligQtr2Mon1;
	}

	@Column(name = "UNEMP_ELIG_QTR2_MON2", nullable = false, length = 1)
	public String getUnempEligQtr2Mon2() {
		return this.unempEligQtr2Mon2;
	}

	public void setUnempEligQtr2Mon2(String unempEligQtr2Mon2) {
		this.unempEligQtr2Mon2 = unempEligQtr2Mon2;
	}

	@Column(name = "UNEMP_ELIG_QTR2_MON3", nullable = false, length = 1)
	public String getUnempEligQtr2Mon3() {
		return this.unempEligQtr2Mon3;
	}

	public void setUnempEligQtr2Mon3(String unempEligQtr2Mon3) {
		this.unempEligQtr2Mon3 = unempEligQtr2Mon3;
	}

	@Column(name = "UNEMP_ELIG_QTR3_MON1", nullable = false, length = 1)
	public String getUnempEligQtr3Mon1() {
		return this.unempEligQtr3Mon1;
	}

	public void setUnempEligQtr3Mon1(String unempEligQtr3Mon1) {
		this.unempEligQtr3Mon1 = unempEligQtr3Mon1;
	}

	@Column(name = "UNEMP_ELIG_QTR3_MON2", nullable = false, length = 1)
	public String getUnempEligQtr3Mon2() {
		return this.unempEligQtr3Mon2;
	}

	public void setUnempEligQtr3Mon2(String unempEligQtr3Mon2) {
		this.unempEligQtr3Mon2 = unempEligQtr3Mon2;
	}

	@Column(name = "UNEMP_ELIG_QTR3_MON3", nullable = false, length = 1)
	public String getUnempEligQtr3Mon3() {
		return this.unempEligQtr3Mon3;
	}

	public void setUnempEligQtr3Mon3(String unempEligQtr3Mon3) {
		this.unempEligQtr3Mon3 = unempEligQtr3Mon3;
	}

	@Column(name = "UNEMP_ELIG_QTR4_MON1", nullable = false, length = 1)
	public String getUnempEligQtr4Mon1() {
		return this.unempEligQtr4Mon1;
	}

	public void setUnempEligQtr4Mon1(String unempEligQtr4Mon1) {
		this.unempEligQtr4Mon1 = unempEligQtr4Mon1;
	}

	@Column(name = "UNEMP_ELIG_QTR4_MON2", nullable = false, length = 1)
	public String getUnempEligQtr4Mon2() {
		return this.unempEligQtr4Mon2;
	}

	public void setUnempEligQtr4Mon2(String unempEligQtr4Mon2) {
		this.unempEligQtr4Mon2 = unempEligQtr4Mon2;
	}

	@Column(name = "UNEMP_ELIG_QTR4_MON3", nullable = false, length = 1)
	public String getUnempEligQtr4Mon3() {
		return this.unempEligQtr4Mon3;
	}

	public void setUnempEligQtr4Mon3(String unempEligQtr4Mon3) {
		this.unempEligQtr4Mon3 = unempEligQtr4Mon3;
	}

	@Column(name = "DT_RETIRE", nullable = false, length = 8)
	public String getDtRetire() {
		return this.dtRetire;
	}

	public void setDtRetire(String dtRetire) {
		this.dtRetire = dtRetire;
	}

	@Column(name = "TAKE_RET_SURCHG", nullable = false, length = 1)
	public String getTakeRetSurchg() {
		return this.takeRetSurchg;
	}

	public void setTakeRetSurchg(String takeRetSurchg) {
		this.takeRetSurchg = takeRetSurchg;
	}

	@Column(name = "NY_TAKE_RET_SURCHG", nullable = false, length = 1)
	public String getNyTakeRetSurchg() {
		return this.nyTakeRetSurchg;
	}

	public void setNyTakeRetSurchg(String nyTakeRetSurchg) {
		this.nyTakeRetSurchg = nyTakeRetSurchg;
	}

	@Column(name = "FNGRPRT_STAT", nullable = false, length = 1)
	public String getFngrprtStat() {
		return this.fngrprtStat;
	}

	public void setFngrprtStat(String fngrprtStat) {
		this.fngrprtStat = fngrprtStat;
	}

	@Column(name = "DT_EXTR", nullable = false, length = 8)
	public String getDtExtr() {
		return this.dtExtr;
	}

	public void setDtExtr(String dtExtr) {
		this.dtExtr = dtExtr;
	}

	@Column(name = "DT_FNGRPRT", nullable = false, length = 8)
	public String getDtFngrprt() {
		return this.dtFngrprt;
	}

	public void setDtFngrprt(String dtFngrprt) {
		this.dtFngrprt = dtFngrprt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "ERS_RET_HLTH_ELIG", nullable = false, length = 1)
	public String getErsRetHlthElig() {
		return this.ersRetHlthElig;
	}

	public void setErsRetHlthElig(String ersRetHlthElig) {
		this.ersRetHlthElig = ersRetHlthElig;
	}

	@Column(name = "NY_ERS_RET_HLTH_ELIG", nullable = false, length = 1)
	public String getNyErsRetHlthElig() {
		return this.nyErsRetHlthElig;
	}

	public void setNyErsRetHlthElig(String nyErsRetHlthElig) {
		this.nyErsRetHlthElig = nyErsRetHlthElig;
	}

	@Column(name = "ELEC_CONSNT_W2", nullable = false, length = 1)
	public String getElecConsntW2() {
		return this.elecConsntW2;
	}

	public void setElecConsntW2(String elecConsntW2) {
		this.elecConsntW2 = elecConsntW2;
	}

	@Column(name = "ELEC_CONSNT_1095", nullable = false, length = 1)
	public String getElecConsnt1095() {
		return this.elecConsnt1095;
	}

	public void setElecConsnt1095(String elecConsnt1095) {
		this.elecConsnt1095 = elecConsnt1095;
	}

	@Column(name = "EMPLMNT_TYP_CD", nullable = false, length = 1)
	public String getEmplmntTypCd() {
		return this.emplmntTypCd;
	}

	public void setEmplmntTypCd(String emplmntTypCd) {
		this.emplmntTypCd = emplmntTypCd;
	}

	@Column(name = "RET_EMPLMNT_TYP_CD", nullable = false, length = 1)
	public String getRetEmplmntTypCd() {
		return this.retEmplmntTypCd;
	}

	public void setRetEmplmntTypCd(String retEmplmntTypCd) {
		this.retEmplmntTypCd = retEmplmntTypCd;
	}

	@Column(name = "FULL_SEM", nullable = false, length = 1)
	public String getFullSem() {
		return this.fullSem;
	}

	public void setFullSem(String fullSem) {
		this.fullSem = fullSem;
	}

	@Column(name = "AUX_ROLE_ID", nullable = false, length = 3)
	public String getAuxRoleId() {
		return this.auxRoleId;
	}

	public void setAuxRoleId(String auxRoleId) {
		this.auxRoleId = auxRoleId;
	}

}
