package com.esc20.model;
// Generated Jan 4, 2019 3:42:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrOptionsBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_OPTIONS_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrOptionsBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrOptionsBkupPaycalcs5Id id;

	public BhrOptionsBkupPaycalcs5() {
	}

	public BhrOptionsBkupPaycalcs5(BhrOptionsBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "distId", column = @Column(name = "DIST_ID", nullable = false, length = 6)),
			@AttributeOverride(name = "trsDistId", column = @Column(name = "TRS_DIST_ID", nullable = false, length = 4)),
			@AttributeOverride(name = "twcId", column = @Column(name = "TWC_ID", nullable = false, length = 9)),
			@AttributeOverride(name = "useDirectDeposit", column = @Column(name = "USE_DIRECT_DEPOSIT", nullable = false, length = 1)),
			@AttributeOverride(name = "calcAccruSalary", column = @Column(name = "CALC_ACCRU_SALARY", nullable = false, length = 1)),
			@AttributeOverride(name = "fundToTrsGrant", column = @Column(name = "FUND_TO_TRS_GRANT", nullable = false, length = 1)),
			@AttributeOverride(name = "trsCei", column = @Column(name = "TRS_CEI", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "numericChkAmt", column = @Column(name = "NUMERIC_CHK_AMT", nullable = false, length = 1)),
			@AttributeOverride(name = "distryByAmtPer", column = @Column(name = "DISTRY_BY_AMT_PER", nullable = false, length = 1)),
			@AttributeOverride(name = "reducFicaGross", column = @Column(name = "REDUC_FICA_GROSS", nullable = false, length = 1)),
			@AttributeOverride(name = "autoPayrate", column = @Column(name = "AUTO_PAYRATE", nullable = false, length = 1)),
			@AttributeOverride(name = "autoDaily", column = @Column(name = "AUTO_DAILY", nullable = false, length = 1)),
			@AttributeOverride(name = "autoAbsence", column = @Column(name = "AUTO_ABSENCE", nullable = false, length = 1)),
			@AttributeOverride(name = "autoAccrual", column = @Column(name = "AUTO_ACCRUAL", nullable = false, length = 1)),
			@AttributeOverride(name = "autoOvertime", column = @Column(name = "AUTO_OVERTIME", nullable = false, length = 1)),
			@AttributeOverride(name = "autoAssignEmp", column = @Column(name = "AUTO_ASSIGN_EMP", nullable = false, length = 1)),
			@AttributeOverride(name = "lvEarnedUsed", column = @Column(name = "LV_EARNED_USED", nullable = false, length = 1)),
			@AttributeOverride(name = "standardHrs", column = @Column(name = "STANDARD_HRS", nullable = false, precision = 2, scale = 1)),
			@AttributeOverride(name = "lvTypSick", column = @Column(name = "LV_TYP_SICK", nullable = false, length = 2)),
			@AttributeOverride(name = "lvTypPerson", column = @Column(name = "LV_TYP_PERSON", nullable = false, length = 2)),
			@AttributeOverride(name = "sumBenefits", column = @Column(name = "SUM_BENEFITS", nullable = false, length = 1)),
			@AttributeOverride(name = "maxGross", column = @Column(name = "MAX_GROSS", nullable = false, precision = 9)),
			@AttributeOverride(name = "expenseEmplrContrib", column = @Column(name = "EXPENSE_EMPLR_CONTRIB", nullable = false, length = 1)),
			@AttributeOverride(name = "glFileId", column = @Column(name = "GL_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "ovtObjPro", column = @Column(name = "OVT_OBJ_PRO", nullable = false, length = 4)),
			@AttributeOverride(name = "ovtObjPara", column = @Column(name = "OVT_OBJ_PARA", nullable = false, length = 4)),
			@AttributeOverride(name = "ovtObjOther", column = @Column(name = "OVT_OBJ_OTHER", nullable = false, length = 4)),
			@AttributeOverride(name = "nxtAvailEmpNbr", column = @Column(name = "NXT_AVAIL_EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "payClearingFund", column = @Column(name = "PAY_CLEARING_FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "payClearingFundYr", column = @Column(name = "PAY_CLEARING_FUND_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "teaHlthInsContribPay4", column = @Column(name = "TEA_HLTH_INS_CONTRIB_PAY4", nullable = false, precision = 9)),
			@AttributeOverride(name = "teaHlthInsContribObjPay4", column = @Column(name = "TEA_HLTH_INS_CONTRIB_OBJ_PAY4", nullable = false, length = 4)),
			@AttributeOverride(name = "teaHlthInsContribSobjPay4", column = @Column(name = "TEA_HLTH_INS_CONTRIB_SOBJ_PAY4", nullable = false, length = 2)),
			@AttributeOverride(name = "teaHlthInsContribPay5", column = @Column(name = "TEA_HLTH_INS_CONTRIB_PAY5", nullable = false, precision = 9)),
			@AttributeOverride(name = "teaHlthInsContribObjPay5", column = @Column(name = "TEA_HLTH_INS_CONTRIB_OBJ_PAY5", nullable = false, length = 4)),
			@AttributeOverride(name = "teaHlthInsContribSobjPay5", column = @Column(name = "TEA_HLTH_INS_CONTRIB_SOBJ_PAY5", nullable = false, length = 2)),
			@AttributeOverride(name = "automateTraqsRec", column = @Column(name = "AUTOMATE_TRAQS_REC", nullable = false, length = 1)),
			@AttributeOverride(name = "automateTrsRptYr", column = @Column(name = "AUTOMATE_TRS_RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "automateTrsRptMon", column = @Column(name = "AUTOMATE_TRS_RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "teaHealthInsContribDedCd", column = @Column(name = "TEA_HEALTH_INS_CONTRIB_DED_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "teaHlthInsContribPay6", column = @Column(name = "TEA_HLTH_INS_CONTRIB_PAY6", nullable = false, precision = 9)),
			@AttributeOverride(name = "teaHlthInsContribObjPay6", column = @Column(name = "TEA_HLTH_INS_CONTRIB_OBJ_PAY6", nullable = false, length = 4)),
			@AttributeOverride(name = "teaHlthInsContribSobjPay6", column = @Column(name = "TEA_HLTH_INS_CONTRIB_SOBJ_PAY6", nullable = false, length = 2)),
			@AttributeOverride(name = "trsSupplCompFund", column = @Column(name = "TRS_SUPPL_COMP_FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "trsSupplCompFunc", column = @Column(name = "TRS_SUPPL_COMP_FUNC", nullable = false, length = 2)),
			@AttributeOverride(name = "trsSupplCompObj", column = @Column(name = "TRS_SUPPL_COMP_OBJ", nullable = false, length = 4)),
			@AttributeOverride(name = "trsSupplCompSobj", column = @Column(name = "TRS_SUPPL_COMP_SOBJ", nullable = false, length = 2)),
			@AttributeOverride(name = "trsSupplCompOrg", column = @Column(name = "TRS_SUPPL_COMP_ORG", nullable = false, length = 3)),
			@AttributeOverride(name = "trsSupplCompFsclYr", column = @Column(name = "TRS_SUPPL_COMP_FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "trsSupplCompPgm", column = @Column(name = "TRS_SUPPL_COMP_PGM", nullable = false, length = 2)),
			@AttributeOverride(name = "trsSupplCompEdSpan", column = @Column(name = "TRS_SUPPL_COMP_ED_SPAN", nullable = false, length = 1)),
			@AttributeOverride(name = "trsSupplCompProjDtl", column = @Column(name = "TRS_SUPPL_COMP_PROJ_DTL", nullable = false, length = 2)),
			@AttributeOverride(name = "trsSupplCompWrkComp", column = @Column(name = "TRS_SUPPL_COMP_WRK_COMP", nullable = false, length = 1)),
			@AttributeOverride(name = "supplTaxRate", column = @Column(name = "SUPPL_TAX_RATE", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "emplrContribFund", column = @Column(name = "EMPLR_CONTRIB_FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "emplrContribFunc", column = @Column(name = "EMPLR_CONTRIB_FUNC", nullable = false, length = 2)),
			@AttributeOverride(name = "emplrContribObj", column = @Column(name = "EMPLR_CONTRIB_OBJ", nullable = false, length = 4)),
			@AttributeOverride(name = "emplrContribSobj", column = @Column(name = "EMPLR_CONTRIB_SOBJ", nullable = false, length = 2)),
			@AttributeOverride(name = "emplrContribOrg", column = @Column(name = "EMPLR_CONTRIB_ORG", nullable = false, length = 3)),
			@AttributeOverride(name = "emplrContribFsclYr", column = @Column(name = "EMPLR_CONTRIB_FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "emplrContribPgm", column = @Column(name = "EMPLR_CONTRIB_PGM", nullable = false, length = 2)),
			@AttributeOverride(name = "emplrContribEdSpan", column = @Column(name = "EMPLR_CONTRIB_ED_SPAN", nullable = false, length = 1)),
			@AttributeOverride(name = "emplrContribProjDtl", column = @Column(name = "EMPLR_CONTRIB_PROJ_DTL", nullable = false, length = 2)),
			@AttributeOverride(name = "firstPaydateSchYrPay4", column = @Column(name = "FIRST_PAYDATE_SCH_YR_PAY4", nullable = false, length = 8)),
			@AttributeOverride(name = "firstPaydateSchYrPay5", column = @Column(name = "FIRST_PAYDATE_SCH_YR_PAY5", nullable = false, length = 8)),
			@AttributeOverride(name = "firstPaydateSchYrPay6", column = @Column(name = "FIRST_PAYDATE_SCH_YR_PAY6", nullable = false, length = 8)),
			@AttributeOverride(name = "peimsCdYr", column = @Column(name = "PEIMS_CD_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "nyAutomateTraqsRec", column = @Column(name = "NY_AUTOMATE_TRAQS_REC", nullable = false, length = 1)),
			@AttributeOverride(name = "nyAutomateTrsRptYr", column = @Column(name = "NY_AUTOMATE_TRS_RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "nyAutomateTrsRptMon", column = @Column(name = "NY_AUTOMATE_TRS_RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "nyTrsOnbehalfAcctCd", column = @Column(name = "NY_TRS_ONBEHALF_ACCT_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "simUpdt", column = @Column(name = "SIM_UPDT", nullable = false, length = 1)),
			@AttributeOverride(name = "nyExclTrsOnbehalf", column = @Column(name = "NY_EXCL_TRS_ONBEHALF", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "eftOpt", column = @Column(name = "EFT_OPT", nullable = false, length = 1)),
			@AttributeOverride(name = "teamPaydtTrsMonActDt", column = @Column(name = "TEAM_PAYDT_TRS_MON_ACT_DT", nullable = false, length = 1)),
			@AttributeOverride(name = "teamActHrsSchedHrs", column = @Column(name = "TEAM_ACT_HRS_SCHED_HRS", nullable = false, length = 1)) })
	public BhrOptionsBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrOptionsBkupPaycalcs5Id id) {
		this.id = id;
	}

}
