package com.esc20.model;
// Generated Jan 4, 2019 3:44:27 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayDistrHist generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAY_DISTR_HIST", schema = "rsccc", catalog = "rsccc")
public class BhrPayDistrHist implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayDistrHistId id;
	private char acctTyp;
	private String payActy;
	private char glFileId;
	private String fund;
	private String func;
	private String obj;
	private String sobj;
	private String org;
	private char fsclYr;
	private String pgm;
	private char edSpan;
	private String projDtl;
	private char wrkComp;
	private BigDecimal acctAmt;
	private BigDecimal acctPct;
	private short acctPymts;
	private String extraDutyCd;
	private String trsGrantCd;
	private char expense373;
	private char contribAcctFlg;
	private char blkIns;
	private char ovtmCd;
	private BigDecimal contrRemainAmt;
	private BigDecimal unempIns;
	private BigDecimal whTax;
	private BigDecimal netPay;
	private BigDecimal earnPay;
	private BigDecimal trsCare;
	private BigDecimal trsGrantDeposit;
	private BigDecimal trsGross;
	private BigDecimal trsInsDeposit;
	private BigDecimal lifeInsContrib;
	private BigDecimal accruEmplrNonAnnuitContrib;
	private BigDecimal accruEmplrAnnuityContrib;
	private BigDecimal accruEmplr457Contrib;
	private BigDecimal accruFedGrant;
	private BigDecimal accruFedCare;
	private BigDecimal accruFedIns;
	private BigDecimal accruFicaTax;
	private BigDecimal accruPay;
	private BigDecimal accruUnempIns;
	private BigDecimal ficaTax;
	private BigDecimal wrkCompIns;
	private BigDecimal emplrAnnuityContrib;
	private BigDecimal emplrNonAnnuityContrib;
	private BigDecimal emplr457Contrib;
	private short acctSeq;
	private BigDecimal trsSupplComp;
	private BigDecimal teaHealthInsContrib;
	private BigDecimal accruTeaHealthInsContrib;
	private BigDecimal emplrTrsCareContrib;
	private BigDecimal accruEmplrTrsCareContrib;
	private char perforPay;
	private BigDecimal wrkCompGross;
	private char accruFsclYr;
	private BigDecimal accruCafeAmt;
	private BigDecimal trsGrantGross;
	private BigDecimal expense373Gross;
	private BigDecimal expPay;
	private BigDecimal expEmplrNonAnnuitContrib;
	private BigDecimal expEmplrAnnuityContrib;
	private BigDecimal expEmplr457Contrib;
	private BigDecimal expFedGrant;
	private BigDecimal expFedCare;
	private BigDecimal expFicaTax;
	private BigDecimal expUnempIns;
	private BigDecimal expTeaHealthInsContrib;
	private BigDecimal expEmplrTrsCareContrib;
	private BigDecimal emplrRetGross;
	private BigDecimal emplrRetPensnSurchg;
	private BigDecimal accruEmplrRetPensnSurchg;
	private BigDecimal expEmplrRetPensnSurchg;
	private BigDecimal emplrTrsCareSurchg;
	private BigDecimal accruEmplrTrsCareSurchg;
	private BigDecimal expEmplrTrsCareSurchg;
	private BigDecimal emplrNewTrsGross;
	private BigDecimal emplrNewTrsPensnContrib;
	private BigDecimal emplrDependCare;
	private BigDecimal accruEmplrDependCare;
	private BigDecimal expEmplrDependCare;
	private BigDecimal hsaEmplrContrib;
	private BigDecimal emplrMiscDedContrib;
	private BigDecimal accruEmplrMiscDedContrib;
	private BigDecimal expEmplrMiscDedContrib;
	private char createdCip;
	private char createdXmital;
	private String module;

	public BhrPayDistrHist() {
	}

	public BhrPayDistrHist(BhrPayDistrHistId id, char acctTyp, String payActy, char glFileId, String fund, String func,
			String obj, String sobj, String org, char fsclYr, String pgm, char edSpan, String projDtl, char wrkComp,
			BigDecimal acctAmt, BigDecimal acctPct, short acctPymts, String extraDutyCd, String trsGrantCd,
			char expense373, char contribAcctFlg, char blkIns, char ovtmCd, BigDecimal contrRemainAmt,
			BigDecimal unempIns, BigDecimal whTax, BigDecimal netPay, BigDecimal earnPay, BigDecimal trsCare,
			BigDecimal trsGrantDeposit, BigDecimal trsGross, BigDecimal trsInsDeposit, BigDecimal lifeInsContrib,
			BigDecimal accruEmplrNonAnnuitContrib, BigDecimal accruEmplrAnnuityContrib, BigDecimal accruEmplr457Contrib,
			BigDecimal accruFedGrant, BigDecimal accruFedCare, BigDecimal accruFedIns, BigDecimal accruFicaTax,
			BigDecimal accruPay, BigDecimal accruUnempIns, BigDecimal ficaTax, BigDecimal wrkCompIns,
			BigDecimal emplrAnnuityContrib, BigDecimal emplrNonAnnuityContrib, BigDecimal emplr457Contrib,
			short acctSeq, BigDecimal trsSupplComp, BigDecimal teaHealthInsContrib, BigDecimal accruTeaHealthInsContrib,
			BigDecimal emplrTrsCareContrib, BigDecimal accruEmplrTrsCareContrib, char perforPay,
			BigDecimal wrkCompGross, char accruFsclYr, BigDecimal accruCafeAmt, BigDecimal trsGrantGross,
			BigDecimal expense373Gross, BigDecimal expPay, BigDecimal expEmplrNonAnnuitContrib,
			BigDecimal expEmplrAnnuityContrib, BigDecimal expEmplr457Contrib, BigDecimal expFedGrant,
			BigDecimal expFedCare, BigDecimal expFicaTax, BigDecimal expUnempIns, BigDecimal expTeaHealthInsContrib,
			BigDecimal expEmplrTrsCareContrib, BigDecimal emplrRetGross, BigDecimal emplrRetPensnSurchg,
			BigDecimal accruEmplrRetPensnSurchg, BigDecimal expEmplrRetPensnSurchg, BigDecimal emplrTrsCareSurchg,
			BigDecimal accruEmplrTrsCareSurchg, BigDecimal expEmplrTrsCareSurchg, BigDecimal emplrNewTrsGross,
			BigDecimal emplrNewTrsPensnContrib, BigDecimal emplrDependCare, BigDecimal accruEmplrDependCare,
			BigDecimal expEmplrDependCare, BigDecimal hsaEmplrContrib, BigDecimal emplrMiscDedContrib,
			BigDecimal accruEmplrMiscDedContrib, BigDecimal expEmplrMiscDedContrib, char createdCip, char createdXmital,
			String module) {
		this.id = id;
		this.acctTyp = acctTyp;
		this.payActy = payActy;
		this.glFileId = glFileId;
		this.fund = fund;
		this.func = func;
		this.obj = obj;
		this.sobj = sobj;
		this.org = org;
		this.fsclYr = fsclYr;
		this.pgm = pgm;
		this.edSpan = edSpan;
		this.projDtl = projDtl;
		this.wrkComp = wrkComp;
		this.acctAmt = acctAmt;
		this.acctPct = acctPct;
		this.acctPymts = acctPymts;
		this.extraDutyCd = extraDutyCd;
		this.trsGrantCd = trsGrantCd;
		this.expense373 = expense373;
		this.contribAcctFlg = contribAcctFlg;
		this.blkIns = blkIns;
		this.ovtmCd = ovtmCd;
		this.contrRemainAmt = contrRemainAmt;
		this.unempIns = unempIns;
		this.whTax = whTax;
		this.netPay = netPay;
		this.earnPay = earnPay;
		this.trsCare = trsCare;
		this.trsGrantDeposit = trsGrantDeposit;
		this.trsGross = trsGross;
		this.trsInsDeposit = trsInsDeposit;
		this.lifeInsContrib = lifeInsContrib;
		this.accruEmplrNonAnnuitContrib = accruEmplrNonAnnuitContrib;
		this.accruEmplrAnnuityContrib = accruEmplrAnnuityContrib;
		this.accruEmplr457Contrib = accruEmplr457Contrib;
		this.accruFedGrant = accruFedGrant;
		this.accruFedCare = accruFedCare;
		this.accruFedIns = accruFedIns;
		this.accruFicaTax = accruFicaTax;
		this.accruPay = accruPay;
		this.accruUnempIns = accruUnempIns;
		this.ficaTax = ficaTax;
		this.wrkCompIns = wrkCompIns;
		this.emplrAnnuityContrib = emplrAnnuityContrib;
		this.emplrNonAnnuityContrib = emplrNonAnnuityContrib;
		this.emplr457Contrib = emplr457Contrib;
		this.acctSeq = acctSeq;
		this.trsSupplComp = trsSupplComp;
		this.teaHealthInsContrib = teaHealthInsContrib;
		this.accruTeaHealthInsContrib = accruTeaHealthInsContrib;
		this.emplrTrsCareContrib = emplrTrsCareContrib;
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
		this.perforPay = perforPay;
		this.wrkCompGross = wrkCompGross;
		this.accruFsclYr = accruFsclYr;
		this.accruCafeAmt = accruCafeAmt;
		this.trsGrantGross = trsGrantGross;
		this.expense373Gross = expense373Gross;
		this.expPay = expPay;
		this.expEmplrNonAnnuitContrib = expEmplrNonAnnuitContrib;
		this.expEmplrAnnuityContrib = expEmplrAnnuityContrib;
		this.expEmplr457Contrib = expEmplr457Contrib;
		this.expFedGrant = expFedGrant;
		this.expFedCare = expFedCare;
		this.expFicaTax = expFicaTax;
		this.expUnempIns = expUnempIns;
		this.expTeaHealthInsContrib = expTeaHealthInsContrib;
		this.expEmplrTrsCareContrib = expEmplrTrsCareContrib;
		this.emplrRetGross = emplrRetGross;
		this.emplrRetPensnSurchg = emplrRetPensnSurchg;
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
		this.expEmplrRetPensnSurchg = expEmplrRetPensnSurchg;
		this.emplrTrsCareSurchg = emplrTrsCareSurchg;
		this.accruEmplrTrsCareSurchg = accruEmplrTrsCareSurchg;
		this.expEmplrTrsCareSurchg = expEmplrTrsCareSurchg;
		this.emplrNewTrsGross = emplrNewTrsGross;
		this.emplrNewTrsPensnContrib = emplrNewTrsPensnContrib;
		this.emplrDependCare = emplrDependCare;
		this.accruEmplrDependCare = accruEmplrDependCare;
		this.expEmplrDependCare = expEmplrDependCare;
		this.hsaEmplrContrib = hsaEmplrContrib;
		this.emplrMiscDedContrib = emplrMiscDedContrib;
		this.accruEmplrMiscDedContrib = accruEmplrMiscDedContrib;
		this.expEmplrMiscDedContrib = expEmplrMiscDedContrib;
		this.createdCip = createdCip;
		this.createdXmital = createdXmital;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "voidOrIss", column = @Column(name = "VOID_OR_ISS", nullable = false, length = 1)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "distrSeq", column = @Column(name = "DISTR_SEQ", nullable = false, length = 3)) })
	public BhrPayDistrHistId getId() {
		return this.id;
	}

	public void setId(BhrPayDistrHistId id) {
		this.id = id;
	}

	@Column(name = "ACCT_TYP", nullable = false, length = 1)
	public char getAcctTyp() {
		return this.acctTyp;
	}

	public void setAcctTyp(char acctTyp) {
		this.acctTyp = acctTyp;
	}

	@Column(name = "PAY_ACTY", nullable = false, length = 2)
	public String getPayActy() {
		return this.payActy;
	}

	public void setPayActy(String payActy) {
		this.payActy = payActy;
	}

	@Column(name = "GL_FILE_ID", nullable = false, length = 1)
	public char getGlFileId() {
		return this.glFileId;
	}

	public void setGlFileId(char glFileId) {
		this.glFileId = glFileId;
	}

	@Column(name = "FUND", nullable = false, length = 3)
	public String getFund() {
		return this.fund;
	}

	public void setFund(String fund) {
		this.fund = fund;
	}

	@Column(name = "FUNC", nullable = false, length = 2)
	public String getFunc() {
		return this.func;
	}

	public void setFunc(String func) {
		this.func = func;
	}

	@Column(name = "OBJ", nullable = false, length = 4)
	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	@Column(name = "SOBJ", nullable = false, length = 2)
	public String getSobj() {
		return this.sobj;
	}

	public void setSobj(String sobj) {
		this.sobj = sobj;
	}

	@Column(name = "ORG", nullable = false, length = 3)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "FSCL_YR", nullable = false, length = 1)
	public char getFsclYr() {
		return this.fsclYr;
	}

	public void setFsclYr(char fsclYr) {
		this.fsclYr = fsclYr;
	}

	@Column(name = "PGM", nullable = false, length = 2)
	public String getPgm() {
		return this.pgm;
	}

	public void setPgm(String pgm) {
		this.pgm = pgm;
	}

	@Column(name = "ED_SPAN", nullable = false, length = 1)
	public char getEdSpan() {
		return this.edSpan;
	}

	public void setEdSpan(char edSpan) {
		this.edSpan = edSpan;
	}

	@Column(name = "PROJ_DTL", nullable = false, length = 2)
	public String getProjDtl() {
		return this.projDtl;
	}

	public void setProjDtl(String projDtl) {
		this.projDtl = projDtl;
	}

	@Column(name = "WRK_COMP", nullable = false, length = 1)
	public char getWrkComp() {
		return this.wrkComp;
	}

	public void setWrkComp(char wrkComp) {
		this.wrkComp = wrkComp;
	}

	@Column(name = "ACCT_AMT", nullable = false, precision = 9)
	public BigDecimal getAcctAmt() {
		return this.acctAmt;
	}

	public void setAcctAmt(BigDecimal acctAmt) {
		this.acctAmt = acctAmt;
	}

	@Column(name = "ACCT_PCT", nullable = false, precision = 7, scale = 5)
	public BigDecimal getAcctPct() {
		return this.acctPct;
	}

	public void setAcctPct(BigDecimal acctPct) {
		this.acctPct = acctPct;
	}

	@Column(name = "ACCT_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getAcctPymts() {
		return this.acctPymts;
	}

	public void setAcctPymts(short acctPymts) {
		this.acctPymts = acctPymts;
	}

	@Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)
	public String getExtraDutyCd() {
		return this.extraDutyCd;
	}

	public void setExtraDutyCd(String extraDutyCd) {
		this.extraDutyCd = extraDutyCd;
	}

	@Column(name = "TRS_GRANT_CD", nullable = false, length = 2)
	public String getTrsGrantCd() {
		return this.trsGrantCd;
	}

	public void setTrsGrantCd(String trsGrantCd) {
		this.trsGrantCd = trsGrantCd;
	}

	@Column(name = "EXPENSE_373", nullable = false, length = 1)
	public char getExpense373() {
		return this.expense373;
	}

	public void setExpense373(char expense373) {
		this.expense373 = expense373;
	}

	@Column(name = "CONTRIB_ACCT_FLG", nullable = false, length = 1)
	public char getContribAcctFlg() {
		return this.contribAcctFlg;
	}

	public void setContribAcctFlg(char contribAcctFlg) {
		this.contribAcctFlg = contribAcctFlg;
	}

	@Column(name = "BLK_INS", nullable = false, length = 1)
	public char getBlkIns() {
		return this.blkIns;
	}

	public void setBlkIns(char blkIns) {
		this.blkIns = blkIns;
	}

	@Column(name = "OVTM_CD", nullable = false, length = 1)
	public char getOvtmCd() {
		return this.ovtmCd;
	}

	public void setOvtmCd(char ovtmCd) {
		this.ovtmCd = ovtmCd;
	}

	@Column(name = "CONTR_REMAIN_AMT", nullable = false, precision = 9)
	public BigDecimal getContrRemainAmt() {
		return this.contrRemainAmt;
	}

	public void setContrRemainAmt(BigDecimal contrRemainAmt) {
		this.contrRemainAmt = contrRemainAmt;
	}

	@Column(name = "UNEMP_INS", nullable = false, precision = 9)
	public BigDecimal getUnempIns() {
		return this.unempIns;
	}

	public void setUnempIns(BigDecimal unempIns) {
		this.unempIns = unempIns;
	}

	@Column(name = "WH_TAX", nullable = false, precision = 9)
	public BigDecimal getWhTax() {
		return this.whTax;
	}

	public void setWhTax(BigDecimal whTax) {
		this.whTax = whTax;
	}

	@Column(name = "NET_PAY", nullable = false, precision = 9)
	public BigDecimal getNetPay() {
		return this.netPay;
	}

	public void setNetPay(BigDecimal netPay) {
		this.netPay = netPay;
	}

	@Column(name = "EARN_PAY", nullable = false, precision = 9)
	public BigDecimal getEarnPay() {
		return this.earnPay;
	}

	public void setEarnPay(BigDecimal earnPay) {
		this.earnPay = earnPay;
	}

	@Column(name = "TRS_CARE", nullable = false, precision = 7)
	public BigDecimal getTrsCare() {
		return this.trsCare;
	}

	public void setTrsCare(BigDecimal trsCare) {
		this.trsCare = trsCare;
	}

	@Column(name = "TRS_GRANT_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getTrsGrantDeposit() {
		return this.trsGrantDeposit;
	}

	public void setTrsGrantDeposit(BigDecimal trsGrantDeposit) {
		this.trsGrantDeposit = trsGrantDeposit;
	}

	@Column(name = "TRS_GROSS", nullable = false, precision = 9)
	public BigDecimal getTrsGross() {
		return this.trsGross;
	}

	public void setTrsGross(BigDecimal trsGross) {
		this.trsGross = trsGross;
	}

	@Column(name = "TRS_INS_DEPOSIT", nullable = false, precision = 7)
	public BigDecimal getTrsInsDeposit() {
		return this.trsInsDeposit;
	}

	public void setTrsInsDeposit(BigDecimal trsInsDeposit) {
		this.trsInsDeposit = trsInsDeposit;
	}

	@Column(name = "LIFE_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getLifeInsContrib() {
		return this.lifeInsContrib;
	}

	public void setLifeInsContrib(BigDecimal lifeInsContrib) {
		this.lifeInsContrib = lifeInsContrib;
	}

	@Column(name = "ACCRU_EMPLR_NON_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrNonAnnuitContrib() {
		return this.accruEmplrNonAnnuitContrib;
	}

	public void setAccruEmplrNonAnnuitContrib(BigDecimal accruEmplrNonAnnuitContrib) {
		this.accruEmplrNonAnnuitContrib = accruEmplrNonAnnuitContrib;
	}

	@Column(name = "ACCRU_EMPLR_ANNUITY_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrAnnuityContrib() {
		return this.accruEmplrAnnuityContrib;
	}

	public void setAccruEmplrAnnuityContrib(BigDecimal accruEmplrAnnuityContrib) {
		this.accruEmplrAnnuityContrib = accruEmplrAnnuityContrib;
	}

	@Column(name = "ACCRU_EMPLR_457_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplr457Contrib() {
		return this.accruEmplr457Contrib;
	}

	public void setAccruEmplr457Contrib(BigDecimal accruEmplr457Contrib) {
		this.accruEmplr457Contrib = accruEmplr457Contrib;
	}

	@Column(name = "ACCRU_FED_GRANT", nullable = false, precision = 9)
	public BigDecimal getAccruFedGrant() {
		return this.accruFedGrant;
	}

	public void setAccruFedGrant(BigDecimal accruFedGrant) {
		this.accruFedGrant = accruFedGrant;
	}

	@Column(name = "ACCRU_FED_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruFedCare() {
		return this.accruFedCare;
	}

	public void setAccruFedCare(BigDecimal accruFedCare) {
		this.accruFedCare = accruFedCare;
	}

	@Column(name = "ACCRU_FED_INS", nullable = false, precision = 9)
	public BigDecimal getAccruFedIns() {
		return this.accruFedIns;
	}

	public void setAccruFedIns(BigDecimal accruFedIns) {
		this.accruFedIns = accruFedIns;
	}

	@Column(name = "ACCRU_FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getAccruFicaTax() {
		return this.accruFicaTax;
	}

	public void setAccruFicaTax(BigDecimal accruFicaTax) {
		this.accruFicaTax = accruFicaTax;
	}

	@Column(name = "ACCRU_PAY", nullable = false, precision = 9)
	public BigDecimal getAccruPay() {
		return this.accruPay;
	}

	public void setAccruPay(BigDecimal accruPay) {
		this.accruPay = accruPay;
	}

	@Column(name = "ACCRU_UNEMP_INS", nullable = false, precision = 9)
	public BigDecimal getAccruUnempIns() {
		return this.accruUnempIns;
	}

	public void setAccruUnempIns(BigDecimal accruUnempIns) {
		this.accruUnempIns = accruUnempIns;
	}

	@Column(name = "FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getFicaTax() {
		return this.ficaTax;
	}

	public void setFicaTax(BigDecimal ficaTax) {
		this.ficaTax = ficaTax;
	}

	@Column(name = "WRK_COMP_INS", nullable = false, precision = 9)
	public BigDecimal getWrkCompIns() {
		return this.wrkCompIns;
	}

	public void setWrkCompIns(BigDecimal wrkCompIns) {
		this.wrkCompIns = wrkCompIns;
	}

	@Column(name = "EMPLR_ANNUITY_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrAnnuityContrib() {
		return this.emplrAnnuityContrib;
	}

	public void setEmplrAnnuityContrib(BigDecimal emplrAnnuityContrib) {
		this.emplrAnnuityContrib = emplrAnnuityContrib;
	}

	@Column(name = "EMPLR_NON_ANNUITY_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrNonAnnuityContrib() {
		return this.emplrNonAnnuityContrib;
	}

	public void setEmplrNonAnnuityContrib(BigDecimal emplrNonAnnuityContrib) {
		this.emplrNonAnnuityContrib = emplrNonAnnuityContrib;
	}

	@Column(name = "EMPLR_457_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplr457Contrib() {
		return this.emplr457Contrib;
	}

	public void setEmplr457Contrib(BigDecimal emplr457Contrib) {
		this.emplr457Contrib = emplr457Contrib;
	}

	@Column(name = "ACCT_SEQ", nullable = false, precision = 3, scale = 0)
	public short getAcctSeq() {
		return this.acctSeq;
	}

	public void setAcctSeq(short acctSeq) {
		this.acctSeq = acctSeq;
	}

	@Column(name = "TRS_SUPPL_COMP", nullable = false, precision = 7)
	public BigDecimal getTrsSupplComp() {
		return this.trsSupplComp;
	}

	public void setTrsSupplComp(BigDecimal trsSupplComp) {
		this.trsSupplComp = trsSupplComp;
	}

	@Column(name = "TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getTeaHealthInsContrib() {
		return this.teaHealthInsContrib;
	}

	public void setTeaHealthInsContrib(BigDecimal teaHealthInsContrib) {
		this.teaHealthInsContrib = teaHealthInsContrib;
	}

	@Column(name = "ACCRU_TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getAccruTeaHealthInsContrib() {
		return this.accruTeaHealthInsContrib;
	}

	public void setAccruTeaHealthInsContrib(BigDecimal accruTeaHealthInsContrib) {
		this.accruTeaHealthInsContrib = accruTeaHealthInsContrib;
	}

	@Column(name = "EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrTrsCareContrib() {
		return this.emplrTrsCareContrib;
	}

	public void setEmplrTrsCareContrib(BigDecimal emplrTrsCareContrib) {
		this.emplrTrsCareContrib = emplrTrsCareContrib;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrTrsCareContrib() {
		return this.accruEmplrTrsCareContrib;
	}

	public void setAccruEmplrTrsCareContrib(BigDecimal accruEmplrTrsCareContrib) {
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
	}

	@Column(name = "PERFOR_PAY", nullable = false, length = 1)
	public char getPerforPay() {
		return this.perforPay;
	}

	public void setPerforPay(char perforPay) {
		this.perforPay = perforPay;
	}

	@Column(name = "WRK_COMP_GROSS", nullable = false, precision = 9)
	public BigDecimal getWrkCompGross() {
		return this.wrkCompGross;
	}

	public void setWrkCompGross(BigDecimal wrkCompGross) {
		this.wrkCompGross = wrkCompGross;
	}

	@Column(name = "ACCRU_FSCL_YR", nullable = false, length = 1)
	public char getAccruFsclYr() {
		return this.accruFsclYr;
	}

	public void setAccruFsclYr(char accruFsclYr) {
		this.accruFsclYr = accruFsclYr;
	}

	@Column(name = "ACCRU_CAFE_AMT", nullable = false, precision = 9)
	public BigDecimal getAccruCafeAmt() {
		return this.accruCafeAmt;
	}

	public void setAccruCafeAmt(BigDecimal accruCafeAmt) {
		this.accruCafeAmt = accruCafeAmt;
	}

	@Column(name = "TRS_GRANT_GROSS", nullable = false, precision = 9)
	public BigDecimal getTrsGrantGross() {
		return this.trsGrantGross;
	}

	public void setTrsGrantGross(BigDecimal trsGrantGross) {
		this.trsGrantGross = trsGrantGross;
	}

	@Column(name = "EXPENSE_373_GROSS", nullable = false, precision = 9)
	public BigDecimal getExpense373Gross() {
		return this.expense373Gross;
	}

	public void setExpense373Gross(BigDecimal expense373Gross) {
		this.expense373Gross = expense373Gross;
	}

	@Column(name = "EXP_PAY", nullable = false, precision = 9)
	public BigDecimal getExpPay() {
		return this.expPay;
	}

	public void setExpPay(BigDecimal expPay) {
		this.expPay = expPay;
	}

	@Column(name = "EXP_EMPLR_NON_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getExpEmplrNonAnnuitContrib() {
		return this.expEmplrNonAnnuitContrib;
	}

	public void setExpEmplrNonAnnuitContrib(BigDecimal expEmplrNonAnnuitContrib) {
		this.expEmplrNonAnnuitContrib = expEmplrNonAnnuitContrib;
	}

	@Column(name = "EXP_EMPLR_ANNUITY_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getExpEmplrAnnuityContrib() {
		return this.expEmplrAnnuityContrib;
	}

	public void setExpEmplrAnnuityContrib(BigDecimal expEmplrAnnuityContrib) {
		this.expEmplrAnnuityContrib = expEmplrAnnuityContrib;
	}

	@Column(name = "EXP_EMPLR_457_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getExpEmplr457Contrib() {
		return this.expEmplr457Contrib;
	}

	public void setExpEmplr457Contrib(BigDecimal expEmplr457Contrib) {
		this.expEmplr457Contrib = expEmplr457Contrib;
	}

	@Column(name = "EXP_FED_GRANT", nullable = false, precision = 9)
	public BigDecimal getExpFedGrant() {
		return this.expFedGrant;
	}

	public void setExpFedGrant(BigDecimal expFedGrant) {
		this.expFedGrant = expFedGrant;
	}

	@Column(name = "EXP_FED_CARE", nullable = false, precision = 9)
	public BigDecimal getExpFedCare() {
		return this.expFedCare;
	}

	public void setExpFedCare(BigDecimal expFedCare) {
		this.expFedCare = expFedCare;
	}

	@Column(name = "EXP_FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getExpFicaTax() {
		return this.expFicaTax;
	}

	public void setExpFicaTax(BigDecimal expFicaTax) {
		this.expFicaTax = expFicaTax;
	}

	@Column(name = "EXP_UNEMP_INS", nullable = false, precision = 9)
	public BigDecimal getExpUnempIns() {
		return this.expUnempIns;
	}

	public void setExpUnempIns(BigDecimal expUnempIns) {
		this.expUnempIns = expUnempIns;
	}

	@Column(name = "EXP_TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getExpTeaHealthInsContrib() {
		return this.expTeaHealthInsContrib;
	}

	public void setExpTeaHealthInsContrib(BigDecimal expTeaHealthInsContrib) {
		this.expTeaHealthInsContrib = expTeaHealthInsContrib;
	}

	@Column(name = "EXP_EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getExpEmplrTrsCareContrib() {
		return this.expEmplrTrsCareContrib;
	}

	public void setExpEmplrTrsCareContrib(BigDecimal expEmplrTrsCareContrib) {
		this.expEmplrTrsCareContrib = expEmplrTrsCareContrib;
	}

	@Column(name = "EMPLR_RET_GROSS", nullable = false, precision = 9)
	public BigDecimal getEmplrRetGross() {
		return this.emplrRetGross;
	}

	public void setEmplrRetGross(BigDecimal emplrRetGross) {
		this.emplrRetGross = emplrRetGross;
	}

	@Column(name = "EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getEmplrRetPensnSurchg() {
		return this.emplrRetPensnSurchg;
	}

	public void setEmplrRetPensnSurchg(BigDecimal emplrRetPensnSurchg) {
		this.emplrRetPensnSurchg = emplrRetPensnSurchg;
	}

	@Column(name = "ACCRU_EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrRetPensnSurchg() {
		return this.accruEmplrRetPensnSurchg;
	}

	public void setAccruEmplrRetPensnSurchg(BigDecimal accruEmplrRetPensnSurchg) {
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
	}

	@Column(name = "EXP_EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getExpEmplrRetPensnSurchg() {
		return this.expEmplrRetPensnSurchg;
	}

	public void setExpEmplrRetPensnSurchg(BigDecimal expEmplrRetPensnSurchg) {
		this.expEmplrRetPensnSurchg = expEmplrRetPensnSurchg;
	}

	@Column(name = "EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getEmplrTrsCareSurchg() {
		return this.emplrTrsCareSurchg;
	}

	public void setEmplrTrsCareSurchg(BigDecimal emplrTrsCareSurchg) {
		this.emplrTrsCareSurchg = emplrTrsCareSurchg;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrTrsCareSurchg() {
		return this.accruEmplrTrsCareSurchg;
	}

	public void setAccruEmplrTrsCareSurchg(BigDecimal accruEmplrTrsCareSurchg) {
		this.accruEmplrTrsCareSurchg = accruEmplrTrsCareSurchg;
	}

	@Column(name = "EXP_EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getExpEmplrTrsCareSurchg() {
		return this.expEmplrTrsCareSurchg;
	}

	public void setExpEmplrTrsCareSurchg(BigDecimal expEmplrTrsCareSurchg) {
		this.expEmplrTrsCareSurchg = expEmplrTrsCareSurchg;
	}

	@Column(name = "EMPLR_NEW_TRS_GROSS", nullable = false, precision = 9)
	public BigDecimal getEmplrNewTrsGross() {
		return this.emplrNewTrsGross;
	}

	public void setEmplrNewTrsGross(BigDecimal emplrNewTrsGross) {
		this.emplrNewTrsGross = emplrNewTrsGross;
	}

	@Column(name = "EMPLR_NEW_TRS_PENSN_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getEmplrNewTrsPensnContrib() {
		return this.emplrNewTrsPensnContrib;
	}

	public void setEmplrNewTrsPensnContrib(BigDecimal emplrNewTrsPensnContrib) {
		this.emplrNewTrsPensnContrib = emplrNewTrsPensnContrib;
	}

	@Column(name = "EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getEmplrDependCare() {
		return this.emplrDependCare;
	}

	public void setEmplrDependCare(BigDecimal emplrDependCare) {
		this.emplrDependCare = emplrDependCare;
	}

	@Column(name = "ACCRU_EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrDependCare() {
		return this.accruEmplrDependCare;
	}

	public void setAccruEmplrDependCare(BigDecimal accruEmplrDependCare) {
		this.accruEmplrDependCare = accruEmplrDependCare;
	}

	@Column(name = "EXP_EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getExpEmplrDependCare() {
		return this.expEmplrDependCare;
	}

	public void setExpEmplrDependCare(BigDecimal expEmplrDependCare) {
		this.expEmplrDependCare = expEmplrDependCare;
	}

	@Column(name = "HSA_EMPLR_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getHsaEmplrContrib() {
		return this.hsaEmplrContrib;
	}

	public void setHsaEmplrContrib(BigDecimal hsaEmplrContrib) {
		this.hsaEmplrContrib = hsaEmplrContrib;
	}

	@Column(name = "EMPLR_MISC_DED_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrMiscDedContrib() {
		return this.emplrMiscDedContrib;
	}

	public void setEmplrMiscDedContrib(BigDecimal emplrMiscDedContrib) {
		this.emplrMiscDedContrib = emplrMiscDedContrib;
	}

	@Column(name = "ACCRU_EMPLR_MISC_DED_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrMiscDedContrib() {
		return this.accruEmplrMiscDedContrib;
	}

	public void setAccruEmplrMiscDedContrib(BigDecimal accruEmplrMiscDedContrib) {
		this.accruEmplrMiscDedContrib = accruEmplrMiscDedContrib;
	}

	@Column(name = "EXP_EMPLR_MISC_DED_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getExpEmplrMiscDedContrib() {
		return this.expEmplrMiscDedContrib;
	}

	public void setExpEmplrMiscDedContrib(BigDecimal expEmplrMiscDedContrib) {
		this.expEmplrMiscDedContrib = expEmplrMiscDedContrib;
	}

	@Column(name = "CREATED_CIP", nullable = false, length = 1)
	public char getCreatedCip() {
		return this.createdCip;
	}

	public void setCreatedCip(char createdCip) {
		this.createdCip = createdCip;
	}

	@Column(name = "CREATED_XMITAL", nullable = false, length = 1)
	public char getCreatedXmital() {
		return this.createdXmital;
	}

	public void setCreatedXmital(char createdXmital) {
		this.createdXmital = createdXmital;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
