package com.esc20.model;
// Generated Jan 4, 2019 3:44:13 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrPayrunOptionsLvId generated by hbm2java
 */
@Embeddable
public class BhrPayrunOptionsLvId implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private char payFreq;
	private String dtOfPay;
	private String schYr;
	private short adjNbr;
	private String lvTyp;

	public BhrPayrunOptionsLvId() {
	}

	public BhrPayrunOptionsLvId(char payFreq, String dtOfPay, String schYr, short adjNbr, String lvTyp) {
		this.payFreq = payFreq;
		this.dtOfPay = dtOfPay;
		this.schYr = schYr;
		this.adjNbr = adjNbr;
		this.lvTyp = lvTyp;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "DT_OF_PAY", nullable = false, length = 8)
	public String getDtOfPay() {
		return this.dtOfPay;
	}

	public void setDtOfPay(String dtOfPay) {
		this.dtOfPay = dtOfPay;
	}

	@Column(name = "SCH_YR", nullable = false, length = 4)
	public String getSchYr() {
		return this.schYr;
	}

	public void setSchYr(String schYr) {
		this.schYr = schYr;
	}

	@Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)
	public short getAdjNbr() {
		return this.adjNbr;
	}

	public void setAdjNbr(short adjNbr) {
		this.adjNbr = adjNbr;
	}

	@Column(name = "LV_TYP", nullable = false, length = 2)
	public String getLvTyp() {
		return this.lvTyp;
	}

	public void setLvTyp(String lvTyp) {
		this.lvTyp = lvTyp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrPayrunOptionsLvId))
			return false;
		BhrPayrunOptionsLvId castOther = (BhrPayrunOptionsLvId) other;

		return (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getDtOfPay() == castOther.getDtOfPay()) || (this.getDtOfPay() != null
						&& castOther.getDtOfPay() != null && this.getDtOfPay().equals(castOther.getDtOfPay())))
				&& ((this.getSchYr() == castOther.getSchYr()) || (this.getSchYr() != null
						&& castOther.getSchYr() != null && this.getSchYr().equals(castOther.getSchYr())))
				&& (this.getAdjNbr() == castOther.getAdjNbr())
				&& ((this.getLvTyp() == castOther.getLvTyp()) || (this.getLvTyp() != null
						&& castOther.getLvTyp() != null && this.getLvTyp().equals(castOther.getLvTyp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getDtOfPay() == null ? 0 : this.getDtOfPay().hashCode());
		result = 37 * result + (getSchYr() == null ? 0 : this.getSchYr().hashCode());
		result = 37 * result + this.getAdjNbr();
		result = 37 * result + (getLvTyp() == null ? 0 : this.getLvTyp().hashCode());
		return result;
	}

}
