package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrPmisPosDistrId generated by hbm2java
 */
@Embeddable
public class BhrPmisPosDistrId implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private char cyrNyrFlg;
	private String posNbr;
	private String billetNbr;
	private char posTyp;
	private short distrSeq;

	public BhrPmisPosDistrId() {
	}

	public BhrPmisPosDistrId(char cyrNyrFlg, String posNbr, String billetNbr, char posTyp, short distrSeq) {
		this.cyrNyrFlg = cyrNyrFlg;
		this.posNbr = posNbr;
		this.billetNbr = billetNbr;
		this.posTyp = posTyp;
		this.distrSeq = distrSeq;
	}

	@Column(name = "CYR_NYR_FLG", nullable = false, length = 1)
	public char getCyrNyrFlg() {
		return this.cyrNyrFlg;
	}

	public void setCyrNyrFlg(char cyrNyrFlg) {
		this.cyrNyrFlg = cyrNyrFlg;
	}

	@Column(name = "POS_NBR", nullable = false, length = 13)
	public String getPosNbr() {
		return this.posNbr;
	}

	public void setPosNbr(String posNbr) {
		this.posNbr = posNbr;
	}

	@Column(name = "BILLET_NBR", nullable = false, length = 5)
	public String getBilletNbr() {
		return this.billetNbr;
	}

	public void setBilletNbr(String billetNbr) {
		this.billetNbr = billetNbr;
	}

	@Column(name = "POS_TYP", nullable = false, length = 1)
	public char getPosTyp() {
		return this.posTyp;
	}

	public void setPosTyp(char posTyp) {
		this.posTyp = posTyp;
	}

	@Column(name = "DISTR_SEQ", nullable = false, precision = 3, scale = 0)
	public short getDistrSeq() {
		return this.distrSeq;
	}

	public void setDistrSeq(short distrSeq) {
		this.distrSeq = distrSeq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrPmisPosDistrId))
			return false;
		BhrPmisPosDistrId castOther = (BhrPmisPosDistrId) other;

		return (this.getCyrNyrFlg() == castOther.getCyrNyrFlg())
				&& ((this.getPosNbr() == castOther.getPosNbr()) || (this.getPosNbr() != null
						&& castOther.getPosNbr() != null && this.getPosNbr().equals(castOther.getPosNbr())))
				&& ((this.getBilletNbr() == castOther.getBilletNbr()) || (this.getBilletNbr() != null
						&& castOther.getBilletNbr() != null && this.getBilletNbr().equals(castOther.getBilletNbr())))
				&& (this.getPosTyp() == castOther.getPosTyp()) && (this.getDistrSeq() == castOther.getDistrSeq());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCyrNyrFlg();
		result = 37 * result + (getPosNbr() == null ? 0 : this.getPosNbr().hashCode());
		result = 37 * result + (getBilletNbr() == null ? 0 : this.getBilletNbr().hashCode());
		result = 37 * result + this.getPosTyp();
		result = 37 * result + this.getDistrSeq();
		return result;
	}

}
