package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPmisCip generated by hbm2java
 */
@Entity
@Table(name = "BHR_PMIS_CIP", schema = "rsccc", catalog = "rsccc")
public class BhrPmisCip implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPmisCipId id;
	private String posSchYr;
	private String dtCipRvw;
	private String usrId;
	private String actnRsn;
	private String campusId;
	private char dept;
	private char primJob;
	private BigDecimal pctAssgnd;
	private String contrDtBeg;
	private String contrDtEnd;
	private String dtTerm;
	private String dtPayoff;
	private char payTyp;
	private String payGrd;
	private String payStp;
	private char paySched;
	private BigDecimal maxDays;
	private BigDecimal contrAmt;
	private BigDecimal contrRemainAmt;
	private short nbrAnnualPymts;
	private short nbrRemainPymts;
	private char payConcpt;
	private short nbrDaysEmpld;
	private short nbrMonContr;
	private short stMinDays;
	private BigDecimal dlyRateOfPay;
	private BigDecimal payRate;
	private BigDecimal hrlyPayRate;
	private BigDecimal dockRate;
	private char ovtmEligFlg;
	private BigDecimal ovtmRate;
	private String eeocCd;
	private char wrkComp;
	private BigDecimal hrsPerDay;
	private String stStp;
	private String trsPosCd;
	private char trsStatCd;
	private BigDecimal stMinSal;
	private BigDecimal dayEmpldPct;
	private String calCd;
	private char ficaElig;
	private char unempEligFlg;
	private char accruCd;
	private BigDecimal accruRate;
	private String createdBy;
	private String dtPyrlApprov;
	private String dtRej;
	private String acptRejUsrId;
	private BigDecimal nbrDaysOff;
	private BigDecimal daysEarnedAdj;
	private String dtOrigEmp;
	private char earlyContrPayoff;
	private String supplToPosNbr;
	private String supplToPosBillet;
	private String suppl1timePaydt;
	private char vacate;
	private char supplTyp;
	private BigDecimal whollySepAmt;
	private String module;
	private char supplRecalc;
	private char ignPctDayForSalCalcs;
	private char ignPctYrForSalCalcs;

	public BhrPmisCip() {
	}

	public BhrPmisCip(BhrPmisCipId id, String posSchYr, String dtCipRvw, String usrId, String actnRsn, String campusId,
			char dept, char primJob, BigDecimal pctAssgnd, String contrDtBeg, String contrDtEnd, String dtTerm,
			String dtPayoff, char payTyp, String payGrd, String payStp, char paySched, BigDecimal maxDays,
			BigDecimal contrAmt, BigDecimal contrRemainAmt, short nbrAnnualPymts, short nbrRemainPymts, char payConcpt,
			short nbrDaysEmpld, short nbrMonContr, short stMinDays, BigDecimal dlyRateOfPay, BigDecimal payRate,
			BigDecimal hrlyPayRate, BigDecimal dockRate, char ovtmEligFlg, BigDecimal ovtmRate, String eeocCd,
			char wrkComp, BigDecimal hrsPerDay, String stStp, String trsPosCd, char trsStatCd, BigDecimal stMinSal,
			BigDecimal dayEmpldPct, String calCd, char ficaElig, char unempEligFlg, char accruCd, BigDecimal accruRate,
			String createdBy, String dtPyrlApprov, String dtRej, String acptRejUsrId, BigDecimal nbrDaysOff,
			BigDecimal daysEarnedAdj, String dtOrigEmp, char earlyContrPayoff, String supplToPosNbr,
			String supplToPosBillet, String suppl1timePaydt, char vacate, char supplTyp, BigDecimal whollySepAmt,
			String module, char supplRecalc, char ignPctDayForSalCalcs, char ignPctYrForSalCalcs) {
		this.id = id;
		this.posSchYr = posSchYr;
		this.dtCipRvw = dtCipRvw;
		this.usrId = usrId;
		this.actnRsn = actnRsn;
		this.campusId = campusId;
		this.dept = dept;
		this.primJob = primJob;
		this.pctAssgnd = pctAssgnd;
		this.contrDtBeg = contrDtBeg;
		this.contrDtEnd = contrDtEnd;
		this.dtTerm = dtTerm;
		this.dtPayoff = dtPayoff;
		this.payTyp = payTyp;
		this.payGrd = payGrd;
		this.payStp = payStp;
		this.paySched = paySched;
		this.maxDays = maxDays;
		this.contrAmt = contrAmt;
		this.contrRemainAmt = contrRemainAmt;
		this.nbrAnnualPymts = nbrAnnualPymts;
		this.nbrRemainPymts = nbrRemainPymts;
		this.payConcpt = payConcpt;
		this.nbrDaysEmpld = nbrDaysEmpld;
		this.nbrMonContr = nbrMonContr;
		this.stMinDays = stMinDays;
		this.dlyRateOfPay = dlyRateOfPay;
		this.payRate = payRate;
		this.hrlyPayRate = hrlyPayRate;
		this.dockRate = dockRate;
		this.ovtmEligFlg = ovtmEligFlg;
		this.ovtmRate = ovtmRate;
		this.eeocCd = eeocCd;
		this.wrkComp = wrkComp;
		this.hrsPerDay = hrsPerDay;
		this.stStp = stStp;
		this.trsPosCd = trsPosCd;
		this.trsStatCd = trsStatCd;
		this.stMinSal = stMinSal;
		this.dayEmpldPct = dayEmpldPct;
		this.calCd = calCd;
		this.ficaElig = ficaElig;
		this.unempEligFlg = unempEligFlg;
		this.accruCd = accruCd;
		this.accruRate = accruRate;
		this.createdBy = createdBy;
		this.dtPyrlApprov = dtPyrlApprov;
		this.dtRej = dtRej;
		this.acptRejUsrId = acptRejUsrId;
		this.nbrDaysOff = nbrDaysOff;
		this.daysEarnedAdj = daysEarnedAdj;
		this.dtOrigEmp = dtOrigEmp;
		this.earlyContrPayoff = earlyContrPayoff;
		this.supplToPosNbr = supplToPosNbr;
		this.supplToPosBillet = supplToPosBillet;
		this.suppl1timePaydt = suppl1timePaydt;
		this.vacate = vacate;
		this.supplTyp = supplTyp;
		this.whollySepAmt = whollySepAmt;
		this.module = module;
		this.supplRecalc = supplRecalc;
		this.ignPctDayForSalCalcs = ignPctDayForSalCalcs;
		this.ignPctYrForSalCalcs = ignPctYrForSalCalcs;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dtEff", column = @Column(name = "DT_EFF", nullable = false, length = 8)),
			@AttributeOverride(name = "dtsCipTrans", column = @Column(name = "DTS_CIP_TRANS", nullable = false, length = 16)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)),
			@AttributeOverride(name = "extraDutyCd", column = @Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "posNbr", column = @Column(name = "POS_NBR", nullable = false, length = 13)),
			@AttributeOverride(name = "billetNbr", column = @Column(name = "BILLET_NBR", nullable = false, length = 5)),
			@AttributeOverride(name = "posTyp", column = @Column(name = "POS_TYP", nullable = false, length = 1)) })
	public BhrPmisCipId getId() {
		return this.id;
	}

	public void setId(BhrPmisCipId id) {
		this.id = id;
	}

	@Column(name = "POS_SCH_YR", nullable = false, length = 4)
	public String getPosSchYr() {
		return this.posSchYr;
	}

	public void setPosSchYr(String posSchYr) {
		this.posSchYr = posSchYr;
	}

	@Column(name = "DT_CIP_RVW", nullable = false, length = 8)
	public String getDtCipRvw() {
		return this.dtCipRvw;
	}

	public void setDtCipRvw(String dtCipRvw) {
		this.dtCipRvw = dtCipRvw;
	}

	@Column(name = "USR_ID", nullable = false, length = 12)
	public String getUsrId() {
		return this.usrId;
	}

	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}

	@Column(name = "ACTN_RSN", nullable = false, length = 2)
	public String getActnRsn() {
		return this.actnRsn;
	}

	public void setActnRsn(String actnRsn) {
		this.actnRsn = actnRsn;
	}

	@Column(name = "CAMPUS_ID", nullable = false, length = 3)
	public String getCampusId() {
		return this.campusId;
	}

	public void setCampusId(String campusId) {
		this.campusId = campusId;
	}

	@Column(name = "DEPT", nullable = false, length = 1)
	public char getDept() {
		return this.dept;
	}

	public void setDept(char dept) {
		this.dept = dept;
	}

	@Column(name = "PRIM_JOB", nullable = false, length = 1)
	public char getPrimJob() {
		return this.primJob;
	}

	public void setPrimJob(char primJob) {
		this.primJob = primJob;
	}

	@Column(name = "PCT_ASSGND", nullable = false, precision = 3)
	public BigDecimal getPctAssgnd() {
		return this.pctAssgnd;
	}

	public void setPctAssgnd(BigDecimal pctAssgnd) {
		this.pctAssgnd = pctAssgnd;
	}

	@Column(name = "CONTR_DT_BEG", nullable = false, length = 8)
	public String getContrDtBeg() {
		return this.contrDtBeg;
	}

	public void setContrDtBeg(String contrDtBeg) {
		this.contrDtBeg = contrDtBeg;
	}

	@Column(name = "CONTR_DT_END", nullable = false, length = 8)
	public String getContrDtEnd() {
		return this.contrDtEnd;
	}

	public void setContrDtEnd(String contrDtEnd) {
		this.contrDtEnd = contrDtEnd;
	}

	@Column(name = "DT_TERM", nullable = false, length = 8)
	public String getDtTerm() {
		return this.dtTerm;
	}

	public void setDtTerm(String dtTerm) {
		this.dtTerm = dtTerm;
	}

	@Column(name = "DT_PAYOFF", nullable = false, length = 8)
	public String getDtPayoff() {
		return this.dtPayoff;
	}

	public void setDtPayoff(String dtPayoff) {
		this.dtPayoff = dtPayoff;
	}

	@Column(name = "PAY_TYP", nullable = false, length = 1)
	public char getPayTyp() {
		return this.payTyp;
	}

	public void setPayTyp(char payTyp) {
		this.payTyp = payTyp;
	}

	@Column(name = "PAY_GRD", nullable = false, length = 3)
	public String getPayGrd() {
		return this.payGrd;
	}

	public void setPayGrd(String payGrd) {
		this.payGrd = payGrd;
	}

	@Column(name = "PAY_STP", nullable = false, length = 2)
	public String getPayStp() {
		return this.payStp;
	}

	public void setPayStp(String payStp) {
		this.payStp = payStp;
	}

	@Column(name = "PAY_SCHED", nullable = false, length = 1)
	public char getPaySched() {
		return this.paySched;
	}

	public void setPaySched(char paySched) {
		this.paySched = paySched;
	}

	@Column(name = "MAX_DAYS", nullable = false, precision = 5, scale = 1)
	public BigDecimal getMaxDays() {
		return this.maxDays;
	}

	public void setMaxDays(BigDecimal maxDays) {
		this.maxDays = maxDays;
	}

	@Column(name = "CONTR_AMT", nullable = false, precision = 9)
	public BigDecimal getContrAmt() {
		return this.contrAmt;
	}

	public void setContrAmt(BigDecimal contrAmt) {
		this.contrAmt = contrAmt;
	}

	@Column(name = "CONTR_REMAIN_AMT", nullable = false, precision = 9)
	public BigDecimal getContrRemainAmt() {
		return this.contrRemainAmt;
	}

	public void setContrRemainAmt(BigDecimal contrRemainAmt) {
		this.contrRemainAmt = contrRemainAmt;
	}

	@Column(name = "NBR_ANNUAL_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getNbrAnnualPymts() {
		return this.nbrAnnualPymts;
	}

	public void setNbrAnnualPymts(short nbrAnnualPymts) {
		this.nbrAnnualPymts = nbrAnnualPymts;
	}

	@Column(name = "NBR_REMAIN_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getNbrRemainPymts() {
		return this.nbrRemainPymts;
	}

	public void setNbrRemainPymts(short nbrRemainPymts) {
		this.nbrRemainPymts = nbrRemainPymts;
	}

	@Column(name = "PAY_CONCPT", nullable = false, length = 1)
	public char getPayConcpt() {
		return this.payConcpt;
	}

	public void setPayConcpt(char payConcpt) {
		this.payConcpt = payConcpt;
	}

	@Column(name = "NBR_DAYS_EMPLD", nullable = false, precision = 3, scale = 0)
	public short getNbrDaysEmpld() {
		return this.nbrDaysEmpld;
	}

	public void setNbrDaysEmpld(short nbrDaysEmpld) {
		this.nbrDaysEmpld = nbrDaysEmpld;
	}

	@Column(name = "NBR_MON_CONTR", nullable = false, precision = 3, scale = 0)
	public short getNbrMonContr() {
		return this.nbrMonContr;
	}

	public void setNbrMonContr(short nbrMonContr) {
		this.nbrMonContr = nbrMonContr;
	}

	@Column(name = "ST_MIN_DAYS", nullable = false, precision = 3, scale = 0)
	public short getStMinDays() {
		return this.stMinDays;
	}

	public void setStMinDays(short stMinDays) {
		this.stMinDays = stMinDays;
	}

	@Column(name = "DLY_RATE_OF_PAY", nullable = false, precision = 7, scale = 3)
	public BigDecimal getDlyRateOfPay() {
		return this.dlyRateOfPay;
	}

	public void setDlyRateOfPay(BigDecimal dlyRateOfPay) {
		this.dlyRateOfPay = dlyRateOfPay;
	}

	@Column(name = "PAY_RATE", nullable = false, precision = 7)
	public BigDecimal getPayRate() {
		return this.payRate;
	}

	public void setPayRate(BigDecimal payRate) {
		this.payRate = payRate;
	}

	@Column(name = "HRLY_PAY_RATE", nullable = false, precision = 7, scale = 3)
	public BigDecimal getHrlyPayRate() {
		return this.hrlyPayRate;
	}

	public void setHrlyPayRate(BigDecimal hrlyPayRate) {
		this.hrlyPayRate = hrlyPayRate;
	}

	@Column(name = "DOCK_RATE", nullable = false, precision = 7, scale = 3)
	public BigDecimal getDockRate() {
		return this.dockRate;
	}

	public void setDockRate(BigDecimal dockRate) {
		this.dockRate = dockRate;
	}

	@Column(name = "OVTM_ELIG_FLG", nullable = false, length = 1)
	public char getOvtmEligFlg() {
		return this.ovtmEligFlg;
	}

	public void setOvtmEligFlg(char ovtmEligFlg) {
		this.ovtmEligFlg = ovtmEligFlg;
	}

	@Column(name = "OVTM_RATE", nullable = false, precision = 5)
	public BigDecimal getOvtmRate() {
		return this.ovtmRate;
	}

	public void setOvtmRate(BigDecimal ovtmRate) {
		this.ovtmRate = ovtmRate;
	}

	@Column(name = "EEOC_CD", nullable = false, length = 2)
	public String getEeocCd() {
		return this.eeocCd;
	}

	public void setEeocCd(String eeocCd) {
		this.eeocCd = eeocCd;
	}

	@Column(name = "WRK_COMP", nullable = false, length = 1)
	public char getWrkComp() {
		return this.wrkComp;
	}

	public void setWrkComp(char wrkComp) {
		this.wrkComp = wrkComp;
	}

	@Column(name = "HRS_PER_DAY", nullable = false, precision = 5, scale = 3)
	public BigDecimal getHrsPerDay() {
		return this.hrsPerDay;
	}

	public void setHrsPerDay(BigDecimal hrsPerDay) {
		this.hrsPerDay = hrsPerDay;
	}

	@Column(name = "ST_STP", nullable = false, length = 2)
	public String getStStp() {
		return this.stStp;
	}

	public void setStStp(String stStp) {
		this.stStp = stStp;
	}

	@Column(name = "TRS_POS_CD", nullable = false, length = 2)
	public String getTrsPosCd() {
		return this.trsPosCd;
	}

	public void setTrsPosCd(String trsPosCd) {
		this.trsPosCd = trsPosCd;
	}

	@Column(name = "TRS_STAT_CD", nullable = false, length = 1)
	public char getTrsStatCd() {
		return this.trsStatCd;
	}

	public void setTrsStatCd(char trsStatCd) {
		this.trsStatCd = trsStatCd;
	}

	@Column(name = "ST_MIN_SAL", nullable = false, precision = 9)
	public BigDecimal getStMinSal() {
		return this.stMinSal;
	}

	public void setStMinSal(BigDecimal stMinSal) {
		this.stMinSal = stMinSal;
	}

	@Column(name = "DAY_EMPLD_PCT", nullable = false, precision = 3)
	public BigDecimal getDayEmpldPct() {
		return this.dayEmpldPct;
	}

	public void setDayEmpldPct(BigDecimal dayEmpldPct) {
		this.dayEmpldPct = dayEmpldPct;
	}

	@Column(name = "CAL_CD", nullable = false, length = 2)
	public String getCalCd() {
		return this.calCd;
	}

	public void setCalCd(String calCd) {
		this.calCd = calCd;
	}

	@Column(name = "FICA_ELIG", nullable = false, length = 1)
	public char getFicaElig() {
		return this.ficaElig;
	}

	public void setFicaElig(char ficaElig) {
		this.ficaElig = ficaElig;
	}

	@Column(name = "UNEMP_ELIG_FLG", nullable = false, length = 1)
	public char getUnempEligFlg() {
		return this.unempEligFlg;
	}

	public void setUnempEligFlg(char unempEligFlg) {
		this.unempEligFlg = unempEligFlg;
	}

	@Column(name = "ACCRU_CD", nullable = false, length = 1)
	public char getAccruCd() {
		return this.accruCd;
	}

	public void setAccruCd(char accruCd) {
		this.accruCd = accruCd;
	}

	@Column(name = "ACCRU_RATE", nullable = false, precision = 7, scale = 3)
	public BigDecimal getAccruRate() {
		return this.accruRate;
	}

	public void setAccruRate(BigDecimal accruRate) {
		this.accruRate = accruRate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 3)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "DT_PYRL_APPROV", nullable = false, length = 8)
	public String getDtPyrlApprov() {
		return this.dtPyrlApprov;
	}

	public void setDtPyrlApprov(String dtPyrlApprov) {
		this.dtPyrlApprov = dtPyrlApprov;
	}

	@Column(name = "DT_REJ", nullable = false, length = 8)
	public String getDtRej() {
		return this.dtRej;
	}

	public void setDtRej(String dtRej) {
		this.dtRej = dtRej;
	}

	@Column(name = "ACPT_REJ_USR_ID", nullable = false, length = 12)
	public String getAcptRejUsrId() {
		return this.acptRejUsrId;
	}

	public void setAcptRejUsrId(String acptRejUsrId) {
		this.acptRejUsrId = acptRejUsrId;
	}

	@Column(name = "NBR_DAYS_OFF", nullable = false, precision = 3, scale = 1)
	public BigDecimal getNbrDaysOff() {
		return this.nbrDaysOff;
	}

	public void setNbrDaysOff(BigDecimal nbrDaysOff) {
		this.nbrDaysOff = nbrDaysOff;
	}

	@Column(name = "DAYS_EARNED_ADJ", nullable = false, precision = 5)
	public BigDecimal getDaysEarnedAdj() {
		return this.daysEarnedAdj;
	}

	public void setDaysEarnedAdj(BigDecimal daysEarnedAdj) {
		this.daysEarnedAdj = daysEarnedAdj;
	}

	@Column(name = "DT_ORIG_EMP", nullable = false, length = 8)
	public String getDtOrigEmp() {
		return this.dtOrigEmp;
	}

	public void setDtOrigEmp(String dtOrigEmp) {
		this.dtOrigEmp = dtOrigEmp;
	}

	@Column(name = "EARLY_CONTR_PAYOFF", nullable = false, length = 1)
	public char getEarlyContrPayoff() {
		return this.earlyContrPayoff;
	}

	public void setEarlyContrPayoff(char earlyContrPayoff) {
		this.earlyContrPayoff = earlyContrPayoff;
	}

	@Column(name = "SUPPL_TO_POS_NBR", nullable = false, length = 13)
	public String getSupplToPosNbr() {
		return this.supplToPosNbr;
	}

	public void setSupplToPosNbr(String supplToPosNbr) {
		this.supplToPosNbr = supplToPosNbr;
	}

	@Column(name = "SUPPL_TO_POS_BILLET", nullable = false, length = 5)
	public String getSupplToPosBillet() {
		return this.supplToPosBillet;
	}

	public void setSupplToPosBillet(String supplToPosBillet) {
		this.supplToPosBillet = supplToPosBillet;
	}

	@Column(name = "SUPPL_1TIME_PAYDT", nullable = false, length = 8)
	public String getSuppl1timePaydt() {
		return this.suppl1timePaydt;
	}

	public void setSuppl1timePaydt(String suppl1timePaydt) {
		this.suppl1timePaydt = suppl1timePaydt;
	}

	@Column(name = "VACATE", nullable = false, length = 1)
	public char getVacate() {
		return this.vacate;
	}

	public void setVacate(char vacate) {
		this.vacate = vacate;
	}

	@Column(name = "SUPPL_TYP", nullable = false, length = 1)
	public char getSupplTyp() {
		return this.supplTyp;
	}

	public void setSupplTyp(char supplTyp) {
		this.supplTyp = supplTyp;
	}

	@Column(name = "WHOLLY_SEP_AMT", nullable = false, precision = 7)
	public BigDecimal getWhollySepAmt() {
		return this.whollySepAmt;
	}

	public void setWhollySepAmt(BigDecimal whollySepAmt) {
		this.whollySepAmt = whollySepAmt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "SUPPL_RECALC", nullable = false, length = 1)
	public char getSupplRecalc() {
		return this.supplRecalc;
	}

	public void setSupplRecalc(char supplRecalc) {
		this.supplRecalc = supplRecalc;
	}

	@Column(name = "IGN_PCT_DAY_FOR_SAL_CALCS", nullable = false, length = 1)
	public char getIgnPctDayForSalCalcs() {
		return this.ignPctDayForSalCalcs;
	}

	public void setIgnPctDayForSalCalcs(char ignPctDayForSalCalcs) {
		this.ignPctDayForSalCalcs = ignPctDayForSalCalcs;
	}

	@Column(name = "IGN_PCT_YR_FOR_SAL_CALCS", nullable = false, length = 1)
	public char getIgnPctYrForSalCalcs() {
		return this.ignPctYrForSalCalcs;
	}

	public void setIgnPctYrForSalCalcs(char ignPctYrForSalCalcs) {
		this.ignPctYrForSalCalcs = ignPctYrForSalCalcs;
	}

}
