package com.esc20.model;
// Generated Jan 4, 2019 3:43:59 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayrunOptionsBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAYRUN_OPTIONS_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrPayrunOptionsBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayrunOptionsBkupPaycalcs5Id id;

	public BhrPayrunOptionsBkupPaycalcs5() {
	}

	public BhrPayrunOptionsBkupPaycalcs5(BhrPayrunOptionsBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "zeroSchYtd", column = @Column(name = "ZERO_SCH_YTD", nullable = false, length = 1)),
			@AttributeOverride(name = "wageEarnOnly", column = @Column(name = "WAGE_EARN_ONLY", nullable = false, length = 1)),
			@AttributeOverride(name = "prtBankCks", column = @Column(name = "PRT_BANK_CKS", nullable = false, length = 1)),
			@AttributeOverride(name = "begCkNbr", column = @Column(name = "BEG_CK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "begRefNbr", column = @Column(name = "BEG_REF_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "eft", column = @Column(name = "EFT", nullable = false, length = 1)),
			@AttributeOverride(name = "supplCalcIncomeTax", column = @Column(name = "SUPPL_CALC_INCOME_TAX", nullable = false, length = 1)),
			@AttributeOverride(name = "supplCalcSocialSec", column = @Column(name = "SUPPL_CALC_SOCIAL_SEC", nullable = false, length = 1)),
			@AttributeOverride(name = "supplCalcTrs", column = @Column(name = "SUPPL_CALC_TRS", nullable = false, length = 1)),
			@AttributeOverride(name = "supplCalcWrkComp", column = @Column(name = "SUPPL_CALC_WRK_COMP", nullable = false, length = 1)),
			@AttributeOverride(name = "supplCalcUnempl", column = @Column(name = "SUPPL_CALC_UNEMPL", nullable = false, length = 1)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 12)),
			@AttributeOverride(name = "processDt", column = @Column(name = "PROCESS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "prtVoidCks", column = @Column(name = "PRT_VOID_CKS", nullable = false, length = 1)),
			@AttributeOverride(name = "calcTrsSupplComp", column = @Column(name = "CALC_TRS_SUPPL_COMP", nullable = false, length = 1)),
			@AttributeOverride(name = "wageEarnBankAcct", column = @Column(name = "WAGE_EARN_BANK_ACCT", nullable = false, length = 1)),
			@AttributeOverride(name = "dedRptSsn", column = @Column(name = "DED_RPT_SSN", nullable = false, length = 1)),
			@AttributeOverride(name = "reducFicaGross", column = @Column(name = "REDUC_FICA_GROSS", nullable = false, length = 1)),
			@AttributeOverride(name = "calcAccruSalary", column = @Column(name = "CALC_ACCRU_SALARY", nullable = false, length = 1)),
			@AttributeOverride(name = "sumBenefits", column = @Column(name = "SUM_BENEFITS", nullable = false, length = 1)),
			@AttributeOverride(name = "maxGross", column = @Column(name = "MAX_GROSS", nullable = false, precision = 9)),
			@AttributeOverride(name = "trsPct", column = @Column(name = "TRS_PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "ficaRate", column = @Column(name = "FICA_RATE", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "ficaMaxSalary", column = @Column(name = "FICA_MAX_SALARY", nullable = false, precision = 9)),
			@AttributeOverride(name = "expenseUnemployTax", column = @Column(name = "EXPENSE_UNEMPLOY_TAX", nullable = false, length = 1)),
			@AttributeOverride(name = "unemployRate", column = @Column(name = "UNEMPLOY_RATE", nullable = false, precision = 7, scale = 6)),
			@AttributeOverride(name = "unemployGrossSalary", column = @Column(name = "UNEMPLOY_GROSS_SALARY", nullable = false, precision = 9)),
			@AttributeOverride(name = "emplrTyp", column = @Column(name = "EMPLR_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "wrkCompNetRateA", column = @Column(name = "WRK_COMP_NET_RATE_A", nullable = false, precision = 9, scale = 6)),
			@AttributeOverride(name = "wrkCompNetRateB", column = @Column(name = "WRK_COMP_NET_RATE_B", nullable = false, precision = 9, scale = 6)),
			@AttributeOverride(name = "wrkCompNetRateC", column = @Column(name = "WRK_COMP_NET_RATE_C", nullable = false, precision = 9, scale = 6)),
			@AttributeOverride(name = "wrkCompNetRateD", column = @Column(name = "WRK_COMP_NET_RATE_D", nullable = false, precision = 9, scale = 6)),
			@AttributeOverride(name = "firstPaydateSchYr", column = @Column(name = "FIRST_PAYDATE_SCH_YR", nullable = false, length = 8)),
			@AttributeOverride(name = "srtCkAlphCampus", column = @Column(name = "SRT_CK_ALPH_CAMPUS", nullable = false, length = 1)),
			@AttributeOverride(name = "wrkCompNetRateE", column = @Column(name = "WRK_COMP_NET_RATE_E", nullable = false, precision = 9, scale = 6)),
			@AttributeOverride(name = "wrkCompNetRateF", column = @Column(name = "WRK_COMP_NET_RATE_F", nullable = false, precision = 9, scale = 6)),
			@AttributeOverride(name = "supplCalc457", column = @Column(name = "SUPPL_CALC_457", nullable = false, length = 1)),
			@AttributeOverride(name = "trsIrsSalCap", column = @Column(name = "TRS_IRS_SAL_CAP", nullable = false, precision = 9)),
			@AttributeOverride(name = "medRate", column = @Column(name = "MED_RATE", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "eicMaxSal", column = @Column(name = "EIC_MAX_SAL", nullable = false, precision = 7)),
			@AttributeOverride(name = "emplrFicaRate", column = @Column(name = "EMPLR_FICA_RATE", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "emplrTrsNonOasdiPct", column = @Column(name = "EMPLR_TRS_NON_OASDI_PCT", nullable = false, precision = 6, scale = 5)) })
	public BhrPayrunOptionsBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrPayrunOptionsBkupPaycalcs5Id id) {
		this.id = id;
	}

}
