package com.esc20.model;
// Generated Jan 4, 2019 3:44:13 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayrunOptionsLvBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAYRUN_OPTIONS_LV_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrPayrunOptionsLvBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayrunOptionsLvBkupPaycalcs5Id id;

	public BhrPayrunOptionsLvBkupPaycalcs5() {
	}

	public BhrPayrunOptionsLvBkupPaycalcs5(BhrPayrunOptionsLvBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "incrementFlg", column = @Column(name = "INCREMENT_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "incrementAmt", column = @Column(name = "INCREMENT_AMT", nullable = false, precision = 7, scale = 3)) })
	public BhrPayrunOptionsLvBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrPayrunOptionsLvBkupPaycalcs5Id id) {
		this.id = id;
	}

}
