package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BhrPermitArea generated by hbm2java
 */
@Entity
@Table(name = "BHR_PERMIT_AREA", schema = "rsccc", catalog = "rsccc")
public class BhrPermitArea implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPermitAreaId id;
	private BhrPermit bhrPermit;
	private String nbrHrsSubjArea;
	private String module;

	public BhrPermitArea() {
	}

	public BhrPermitArea(BhrPermitAreaId id, BhrPermit bhrPermit, String nbrHrsSubjArea, String module) {
		this.id = id;
		this.bhrPermit = bhrPermit;
		this.nbrHrsSubjArea = nbrHrsSubjArea;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "prmtTyp", column = @Column(name = "PRMT_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "prmtIssueDt", column = @Column(name = "PRMT_ISSUE_DT", nullable = false, length = 6)),
			@AttributeOverride(name = "prmtIssueStat", column = @Column(name = "PRMT_ISSUE_STAT", nullable = false, length = 2)),
			@AttributeOverride(name = "roleId", column = @Column(name = "ROLE_ID", nullable = false, length = 3)),
			@AttributeOverride(name = "popSrvd", column = @Column(name = "POP_SRVD", nullable = false, length = 2)),
			@AttributeOverride(name = "prmtGrdRnge", column = @Column(name = "PRMT_GRD_RNGE", nullable = false, length = 2)),
			@AttributeOverride(name = "prmtSubjArea", column = @Column(name = "PRMT_SUBJ_AREA", nullable = false, length = 2)) })
	public BhrPermitAreaId getId() {
		return this.id;
	}

	public void setId(BhrPermitAreaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "EMP_NBR", referencedColumnName = "EMP_NBR", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRMT_TYP", referencedColumnName = "PRMT_TYP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRMT_ISSUE_DT", referencedColumnName = "PRMT_ISSUE_DT", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRMT_ISSUE_STAT", referencedColumnName = "PRMT_ISSUE_STAT", nullable = false, insertable = false, updatable = false) })
	public BhrPermit getBhrPermit() {
		return this.bhrPermit;
	}

	public void setBhrPermit(BhrPermit bhrPermit) {
		this.bhrPermit = bhrPermit;
	}

	@Column(name = "NBR_HRS_SUBJ_AREA", nullable = false, length = 2)
	public String getNbrHrsSubjArea() {
		return this.nbrHrsSubjArea;
	}

	public void setNbrHrsSubjArea(String nbrHrsSubjArea) {
		this.nbrHrsSubjArea = nbrHrsSubjArea;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
