package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrPermitId generated by hbm2java
 */
@Embeddable
public class BhrPermitId implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private String empNbr;
	private String prmtTyp;
	private String prmtIssueDt;
	private String prmtIssueStat;

	public BhrPermitId() {
	}

	public BhrPermitId(String empNbr, String prmtTyp, String prmtIssueDt, String prmtIssueStat) {
		this.empNbr = empNbr;
		this.prmtTyp = prmtTyp;
		this.prmtIssueDt = prmtIssueDt;
		this.prmtIssueStat = prmtIssueStat;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "PRMT_TYP", nullable = false, length = 2)
	public String getPrmtTyp() {
		return this.prmtTyp;
	}

	public void setPrmtTyp(String prmtTyp) {
		this.prmtTyp = prmtTyp;
	}

	@Column(name = "PRMT_ISSUE_DT", nullable = false, length = 6)
	public String getPrmtIssueDt() {
		return this.prmtIssueDt;
	}

	public void setPrmtIssueDt(String prmtIssueDt) {
		this.prmtIssueDt = prmtIssueDt;
	}

	@Column(name = "PRMT_ISSUE_STAT", nullable = false, length = 2)
	public String getPrmtIssueStat() {
		return this.prmtIssueStat;
	}

	public void setPrmtIssueStat(String prmtIssueStat) {
		this.prmtIssueStat = prmtIssueStat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrPermitId))
			return false;
		BhrPermitId castOther = (BhrPermitId) other;

		return ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
				&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& ((this.getPrmtTyp() == castOther.getPrmtTyp()) || (this.getPrmtTyp() != null
						&& castOther.getPrmtTyp() != null && this.getPrmtTyp().equals(castOther.getPrmtTyp())))
				&& ((this.getPrmtIssueDt() == castOther.getPrmtIssueDt())
						|| (this.getPrmtIssueDt() != null && castOther.getPrmtIssueDt() != null
								&& this.getPrmtIssueDt().equals(castOther.getPrmtIssueDt())))
				&& ((this.getPrmtIssueStat() == castOther.getPrmtIssueStat())
						|| (this.getPrmtIssueStat() != null && castOther.getPrmtIssueStat() != null
								&& this.getPrmtIssueStat().equals(castOther.getPrmtIssueStat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + (getPrmtTyp() == null ? 0 : this.getPrmtTyp().hashCode());
		result = 37 * result + (getPrmtIssueDt() == null ? 0 : this.getPrmtIssueDt().hashCode());
		result = 37 * result + (getPrmtIssueStat() == null ? 0 : this.getPrmtIssueStat().hashCode());
		return result;
	}

}
