package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPmisPosCtrl generated by hbm2java
 */
@Entity
@Table(name = "BHR_PMIS_POS_CTRL", schema = "rsccc", catalog = "rsccc")
public class BhrPmisPosCtrl implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPmisPosCtrlId id;
	private String posDescr;
	private char posStat;
	private String posSchYr;
	private char payFreq;
	private String occEmpNbr;
	private char primJob;
	private char incrElig;
	private String occPayGrd;
	private String occPayStp;
	private char occPaySched;
	private String stStp;
	private String contrDtBeg;
	private String contrDtEnd;
	private String dtPayoff;
	private BigDecimal nbrDaysOff;
	private BigDecimal actHrlyDlyRate;
	private BigDecimal salAmt;
	private short nbrRemainPymts;
	private String jobCateg;
	private char supplAtch;
	private String jobCd;
	private String frstPaydtCd;
	private String calCd;
	private String campusId;
	private char dept;
	private BigDecimal hrsPerDay;
	private BigDecimal dayEmpldPct;
	private BigDecimal pctOfYr;
	private char payConcpt;
	private String eeocCd;
	private char wrkComp;
	private String trsPosCd;
	private BigDecimal maxDays;
	private short maxPymts;
	private char ovtmEligFlg;
	private short stMinDays;
	private String spvsrPosNbr;
	private String spvsrBilletNbr;
	private BigDecimal supplExtraDays;
	private String supplToPosNbr;
	private String supplToPosBillet;
	private String extraDutyCd;
	private char supplTyp;
	private BigDecimal supplMaxAmt;
	private char basSupplOnDlyRate;
	private char supplPay1time;
	private String dtSuppl1time;
	private char acptChg;
	private String dtCreateUpdt;
	private String dtFill;
	private String fillPosRsn;
	private String dtCriteria;
	private String dtAuth;
	private String dtAuthEnd;
	private String dtEntry;
	private String dtInactv;
	private String inactvRsnCd;
	private String vacRsn;
	private String payGrd;
	private String payStp;
	private char paySched;
	private BigDecimal equivUnts;
	private char midpntBas;
	private BigDecimal pctOfMidpnt;
	private char unempEligFlg;
	private char ficaElig;
	private char trsStatCd;
	private BigDecimal budAmt;
	private char budSalOvrrid;
	private char actBudInd;
	private char payTyp;
	private char occPayTyp;
	private String module;
	private BigDecimal nbrDaysEmpld;
	private char supplRecalc;
	private char ignPctDayForSalCalcs;
	private char ignPctYrForSalCalcs;

	public BhrPmisPosCtrl() {
	}

	public BhrPmisPosCtrl(BhrPmisPosCtrlId id, String posDescr, char posStat, String posSchYr, char payFreq,
			String occEmpNbr, char primJob, char incrElig, String occPayGrd, String occPayStp, char occPaySched,
			String stStp, String contrDtBeg, String contrDtEnd, String dtPayoff, BigDecimal nbrDaysOff,
			BigDecimal actHrlyDlyRate, BigDecimal salAmt, short nbrRemainPymts, String jobCateg, char supplAtch,
			String jobCd, String frstPaydtCd, String calCd, String campusId, char dept, BigDecimal hrsPerDay,
			BigDecimal dayEmpldPct, BigDecimal pctOfYr, char payConcpt, String eeocCd, char wrkComp, String trsPosCd,
			BigDecimal maxDays, short maxPymts, char ovtmEligFlg, short stMinDays, String spvsrPosNbr,
			String spvsrBilletNbr, BigDecimal supplExtraDays, String supplToPosNbr, String supplToPosBillet,
			String extraDutyCd, char supplTyp, BigDecimal supplMaxAmt, char basSupplOnDlyRate, char supplPay1time,
			String dtSuppl1time, char acptChg, String dtCreateUpdt, String dtFill, String fillPosRsn, String dtCriteria,
			String dtAuth, String dtAuthEnd, String dtEntry, String dtInactv, String inactvRsnCd, String vacRsn,
			String payGrd, String payStp, char paySched, BigDecimal equivUnts, char midpntBas, BigDecimal pctOfMidpnt,
			char unempEligFlg, char ficaElig, char trsStatCd, BigDecimal budAmt, char budSalOvrrid, char actBudInd,
			char payTyp, char occPayTyp, String module, BigDecimal nbrDaysEmpld, char supplRecalc,
			char ignPctDayForSalCalcs, char ignPctYrForSalCalcs) {
		this.id = id;
		this.posDescr = posDescr;
		this.posStat = posStat;
		this.posSchYr = posSchYr;
		this.payFreq = payFreq;
		this.occEmpNbr = occEmpNbr;
		this.primJob = primJob;
		this.incrElig = incrElig;
		this.occPayGrd = occPayGrd;
		this.occPayStp = occPayStp;
		this.occPaySched = occPaySched;
		this.stStp = stStp;
		this.contrDtBeg = contrDtBeg;
		this.contrDtEnd = contrDtEnd;
		this.dtPayoff = dtPayoff;
		this.nbrDaysOff = nbrDaysOff;
		this.actHrlyDlyRate = actHrlyDlyRate;
		this.salAmt = salAmt;
		this.nbrRemainPymts = nbrRemainPymts;
		this.jobCateg = jobCateg;
		this.supplAtch = supplAtch;
		this.jobCd = jobCd;
		this.frstPaydtCd = frstPaydtCd;
		this.calCd = calCd;
		this.campusId = campusId;
		this.dept = dept;
		this.hrsPerDay = hrsPerDay;
		this.dayEmpldPct = dayEmpldPct;
		this.pctOfYr = pctOfYr;
		this.payConcpt = payConcpt;
		this.eeocCd = eeocCd;
		this.wrkComp = wrkComp;
		this.trsPosCd = trsPosCd;
		this.maxDays = maxDays;
		this.maxPymts = maxPymts;
		this.ovtmEligFlg = ovtmEligFlg;
		this.stMinDays = stMinDays;
		this.spvsrPosNbr = spvsrPosNbr;
		this.spvsrBilletNbr = spvsrBilletNbr;
		this.supplExtraDays = supplExtraDays;
		this.supplToPosNbr = supplToPosNbr;
		this.supplToPosBillet = supplToPosBillet;
		this.extraDutyCd = extraDutyCd;
		this.supplTyp = supplTyp;
		this.supplMaxAmt = supplMaxAmt;
		this.basSupplOnDlyRate = basSupplOnDlyRate;
		this.supplPay1time = supplPay1time;
		this.dtSuppl1time = dtSuppl1time;
		this.acptChg = acptChg;
		this.dtCreateUpdt = dtCreateUpdt;
		this.dtFill = dtFill;
		this.fillPosRsn = fillPosRsn;
		this.dtCriteria = dtCriteria;
		this.dtAuth = dtAuth;
		this.dtAuthEnd = dtAuthEnd;
		this.dtEntry = dtEntry;
		this.dtInactv = dtInactv;
		this.inactvRsnCd = inactvRsnCd;
		this.vacRsn = vacRsn;
		this.payGrd = payGrd;
		this.payStp = payStp;
		this.paySched = paySched;
		this.equivUnts = equivUnts;
		this.midpntBas = midpntBas;
		this.pctOfMidpnt = pctOfMidpnt;
		this.unempEligFlg = unempEligFlg;
		this.ficaElig = ficaElig;
		this.trsStatCd = trsStatCd;
		this.budAmt = budAmt;
		this.budSalOvrrid = budSalOvrrid;
		this.actBudInd = actBudInd;
		this.payTyp = payTyp;
		this.occPayTyp = occPayTyp;
		this.module = module;
		this.nbrDaysEmpld = nbrDaysEmpld;
		this.supplRecalc = supplRecalc;
		this.ignPctDayForSalCalcs = ignPctDayForSalCalcs;
		this.ignPctYrForSalCalcs = ignPctYrForSalCalcs;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "posNbr", column = @Column(name = "POS_NBR", nullable = false, length = 13)),
			@AttributeOverride(name = "billetNbr", column = @Column(name = "BILLET_NBR", nullable = false, length = 5)),
			@AttributeOverride(name = "posTyp", column = @Column(name = "POS_TYP", nullable = false, length = 1)) })
	public BhrPmisPosCtrlId getId() {
		return this.id;
	}

	public void setId(BhrPmisPosCtrlId id) {
		this.id = id;
	}

	@Column(name = "POS_DESCR", nullable = false, length = 30)
	public String getPosDescr() {
		return this.posDescr;
	}

	public void setPosDescr(String posDescr) {
		this.posDescr = posDescr;
	}

	@Column(name = "POS_STAT", nullable = false, length = 1)
	public char getPosStat() {
		return this.posStat;
	}

	public void setPosStat(char posStat) {
		this.posStat = posStat;
	}

	@Column(name = "POS_SCH_YR", nullable = false, length = 4)
	public String getPosSchYr() {
		return this.posSchYr;
	}

	public void setPosSchYr(String posSchYr) {
		this.posSchYr = posSchYr;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "OCC_EMP_NBR", nullable = false, length = 6)
	public String getOccEmpNbr() {
		return this.occEmpNbr;
	}

	public void setOccEmpNbr(String occEmpNbr) {
		this.occEmpNbr = occEmpNbr;
	}

	@Column(name = "PRIM_JOB", nullable = false, length = 1)
	public char getPrimJob() {
		return this.primJob;
	}

	public void setPrimJob(char primJob) {
		this.primJob = primJob;
	}

	@Column(name = "INCR_ELIG", nullable = false, length = 1)
	public char getIncrElig() {
		return this.incrElig;
	}

	public void setIncrElig(char incrElig) {
		this.incrElig = incrElig;
	}

	@Column(name = "OCC_PAY_GRD", nullable = false, length = 3)
	public String getOccPayGrd() {
		return this.occPayGrd;
	}

	public void setOccPayGrd(String occPayGrd) {
		this.occPayGrd = occPayGrd;
	}

	@Column(name = "OCC_PAY_STP", nullable = false, length = 2)
	public String getOccPayStp() {
		return this.occPayStp;
	}

	public void setOccPayStp(String occPayStp) {
		this.occPayStp = occPayStp;
	}

	@Column(name = "OCC_PAY_SCHED", nullable = false, length = 1)
	public char getOccPaySched() {
		return this.occPaySched;
	}

	public void setOccPaySched(char occPaySched) {
		this.occPaySched = occPaySched;
	}

	@Column(name = "ST_STP", nullable = false, length = 2)
	public String getStStp() {
		return this.stStp;
	}

	public void setStStp(String stStp) {
		this.stStp = stStp;
	}

	@Column(name = "CONTR_DT_BEG", nullable = false, length = 8)
	public String getContrDtBeg() {
		return this.contrDtBeg;
	}

	public void setContrDtBeg(String contrDtBeg) {
		this.contrDtBeg = contrDtBeg;
	}

	@Column(name = "CONTR_DT_END", nullable = false, length = 8)
	public String getContrDtEnd() {
		return this.contrDtEnd;
	}

	public void setContrDtEnd(String contrDtEnd) {
		this.contrDtEnd = contrDtEnd;
	}

	@Column(name = "DT_PAYOFF", nullable = false, length = 8)
	public String getDtPayoff() {
		return this.dtPayoff;
	}

	public void setDtPayoff(String dtPayoff) {
		this.dtPayoff = dtPayoff;
	}

	@Column(name = "NBR_DAYS_OFF", nullable = false, precision = 3, scale = 1)
	public BigDecimal getNbrDaysOff() {
		return this.nbrDaysOff;
	}

	public void setNbrDaysOff(BigDecimal nbrDaysOff) {
		this.nbrDaysOff = nbrDaysOff;
	}

	@Column(name = "ACT_HRLY_DLY_RATE", nullable = false, precision = 7, scale = 3)
	public BigDecimal getActHrlyDlyRate() {
		return this.actHrlyDlyRate;
	}

	public void setActHrlyDlyRate(BigDecimal actHrlyDlyRate) {
		this.actHrlyDlyRate = actHrlyDlyRate;
	}

	@Column(name = "SAL_AMT", nullable = false, precision = 9)
	public BigDecimal getSalAmt() {
		return this.salAmt;
	}

	public void setSalAmt(BigDecimal salAmt) {
		this.salAmt = salAmt;
	}

	@Column(name = "NBR_REMAIN_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getNbrRemainPymts() {
		return this.nbrRemainPymts;
	}

	public void setNbrRemainPymts(short nbrRemainPymts) {
		this.nbrRemainPymts = nbrRemainPymts;
	}

	@Column(name = "JOB_CATEG", nullable = false, length = 5)
	public String getJobCateg() {
		return this.jobCateg;
	}

	public void setJobCateg(String jobCateg) {
		this.jobCateg = jobCateg;
	}

	@Column(name = "SUPPL_ATCH", nullable = false, length = 1)
	public char getSupplAtch() {
		return this.supplAtch;
	}

	public void setSupplAtch(char supplAtch) {
		this.supplAtch = supplAtch;
	}

	@Column(name = "JOB_CD", nullable = false, length = 4)
	public String getJobCd() {
		return this.jobCd;
	}

	public void setJobCd(String jobCd) {
		this.jobCd = jobCd;
	}

	@Column(name = "FRST_PAYDT_CD", nullable = false, length = 3)
	public String getFrstPaydtCd() {
		return this.frstPaydtCd;
	}

	public void setFrstPaydtCd(String frstPaydtCd) {
		this.frstPaydtCd = frstPaydtCd;
	}

	@Column(name = "CAL_CD", nullable = false, length = 2)
	public String getCalCd() {
		return this.calCd;
	}

	public void setCalCd(String calCd) {
		this.calCd = calCd;
	}

	@Column(name = "CAMPUS_ID", nullable = false, length = 3)
	public String getCampusId() {
		return this.campusId;
	}

	public void setCampusId(String campusId) {
		this.campusId = campusId;
	}

	@Column(name = "DEPT", nullable = false, length = 1)
	public char getDept() {
		return this.dept;
	}

	public void setDept(char dept) {
		this.dept = dept;
	}

	@Column(name = "HRS_PER_DAY", nullable = false, precision = 5, scale = 3)
	public BigDecimal getHrsPerDay() {
		return this.hrsPerDay;
	}

	public void setHrsPerDay(BigDecimal hrsPerDay) {
		this.hrsPerDay = hrsPerDay;
	}

	@Column(name = "DAY_EMPLD_PCT", nullable = false, precision = 3)
	public BigDecimal getDayEmpldPct() {
		return this.dayEmpldPct;
	}

	public void setDayEmpldPct(BigDecimal dayEmpldPct) {
		this.dayEmpldPct = dayEmpldPct;
	}

	@Column(name = "PCT_OF_YR", nullable = false, precision = 3)
	public BigDecimal getPctOfYr() {
		return this.pctOfYr;
	}

	public void setPctOfYr(BigDecimal pctOfYr) {
		this.pctOfYr = pctOfYr;
	}

	@Column(name = "PAY_CONCPT", nullable = false, length = 1)
	public char getPayConcpt() {
		return this.payConcpt;
	}

	public void setPayConcpt(char payConcpt) {
		this.payConcpt = payConcpt;
	}

	@Column(name = "EEOC_CD", nullable = false, length = 2)
	public String getEeocCd() {
		return this.eeocCd;
	}

	public void setEeocCd(String eeocCd) {
		this.eeocCd = eeocCd;
	}

	@Column(name = "WRK_COMP", nullable = false, length = 1)
	public char getWrkComp() {
		return this.wrkComp;
	}

	public void setWrkComp(char wrkComp) {
		this.wrkComp = wrkComp;
	}

	@Column(name = "TRS_POS_CD", nullable = false, length = 2)
	public String getTrsPosCd() {
		return this.trsPosCd;
	}

	public void setTrsPosCd(String trsPosCd) {
		this.trsPosCd = trsPosCd;
	}

	@Column(name = "MAX_DAYS", nullable = false, precision = 5, scale = 1)
	public BigDecimal getMaxDays() {
		return this.maxDays;
	}

	public void setMaxDays(BigDecimal maxDays) {
		this.maxDays = maxDays;
	}

	@Column(name = "MAX_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getMaxPymts() {
		return this.maxPymts;
	}

	public void setMaxPymts(short maxPymts) {
		this.maxPymts = maxPymts;
	}

	@Column(name = "OVTM_ELIG_FLG", nullable = false, length = 1)
	public char getOvtmEligFlg() {
		return this.ovtmEligFlg;
	}

	public void setOvtmEligFlg(char ovtmEligFlg) {
		this.ovtmEligFlg = ovtmEligFlg;
	}

	@Column(name = "ST_MIN_DAYS", nullable = false, precision = 3, scale = 0)
	public short getStMinDays() {
		return this.stMinDays;
	}

	public void setStMinDays(short stMinDays) {
		this.stMinDays = stMinDays;
	}

	@Column(name = "SPVSR_POS_NBR", nullable = false, length = 13)
	public String getSpvsrPosNbr() {
		return this.spvsrPosNbr;
	}

	public void setSpvsrPosNbr(String spvsrPosNbr) {
		this.spvsrPosNbr = spvsrPosNbr;
	}

	@Column(name = "SPVSR_BILLET_NBR", nullable = false, length = 5)
	public String getSpvsrBilletNbr() {
		return this.spvsrBilletNbr;
	}

	public void setSpvsrBilletNbr(String spvsrBilletNbr) {
		this.spvsrBilletNbr = spvsrBilletNbr;
	}

	@Column(name = "SUPPL_EXTRA_DAYS", nullable = false, precision = 3, scale = 1)
	public BigDecimal getSupplExtraDays() {
		return this.supplExtraDays;
	}

	public void setSupplExtraDays(BigDecimal supplExtraDays) {
		this.supplExtraDays = supplExtraDays;
	}

	@Column(name = "SUPPL_TO_POS_NBR", nullable = false, length = 13)
	public String getSupplToPosNbr() {
		return this.supplToPosNbr;
	}

	public void setSupplToPosNbr(String supplToPosNbr) {
		this.supplToPosNbr = supplToPosNbr;
	}

	@Column(name = "SUPPL_TO_POS_BILLET", nullable = false, length = 5)
	public String getSupplToPosBillet() {
		return this.supplToPosBillet;
	}

	public void setSupplToPosBillet(String supplToPosBillet) {
		this.supplToPosBillet = supplToPosBillet;
	}

	@Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)
	public String getExtraDutyCd() {
		return this.extraDutyCd;
	}

	public void setExtraDutyCd(String extraDutyCd) {
		this.extraDutyCd = extraDutyCd;
	}

	@Column(name = "SUPPL_TYP", nullable = false, length = 1)
	public char getSupplTyp() {
		return this.supplTyp;
	}

	public void setSupplTyp(char supplTyp) {
		this.supplTyp = supplTyp;
	}

	@Column(name = "SUPPL_MAX_AMT", nullable = false, precision = 7)
	public BigDecimal getSupplMaxAmt() {
		return this.supplMaxAmt;
	}

	public void setSupplMaxAmt(BigDecimal supplMaxAmt) {
		this.supplMaxAmt = supplMaxAmt;
	}

	@Column(name = "BAS_SUPPL_ON_DLY_RATE", nullable = false, length = 1)
	public char getBasSupplOnDlyRate() {
		return this.basSupplOnDlyRate;
	}

	public void setBasSupplOnDlyRate(char basSupplOnDlyRate) {
		this.basSupplOnDlyRate = basSupplOnDlyRate;
	}

	@Column(name = "SUPPL_PAY_1TIME", nullable = false, length = 1)
	public char getSupplPay1time() {
		return this.supplPay1time;
	}

	public void setSupplPay1time(char supplPay1time) {
		this.supplPay1time = supplPay1time;
	}

	@Column(name = "DT_SUPPL_1TIME", nullable = false, length = 8)
	public String getDtSuppl1time() {
		return this.dtSuppl1time;
	}

	public void setDtSuppl1time(String dtSuppl1time) {
		this.dtSuppl1time = dtSuppl1time;
	}

	@Column(name = "ACPT_CHG", nullable = false, length = 1)
	public char getAcptChg() {
		return this.acptChg;
	}

	public void setAcptChg(char acptChg) {
		this.acptChg = acptChg;
	}

	@Column(name = "DT_CREATE_UPDT", nullable = false, length = 8)
	public String getDtCreateUpdt() {
		return this.dtCreateUpdt;
	}

	public void setDtCreateUpdt(String dtCreateUpdt) {
		this.dtCreateUpdt = dtCreateUpdt;
	}

	@Column(name = "DT_FILL", nullable = false, length = 8)
	public String getDtFill() {
		return this.dtFill;
	}

	public void setDtFill(String dtFill) {
		this.dtFill = dtFill;
	}

	@Column(name = "FILL_POS_RSN", nullable = false, length = 2)
	public String getFillPosRsn() {
		return this.fillPosRsn;
	}

	public void setFillPosRsn(String fillPosRsn) {
		this.fillPosRsn = fillPosRsn;
	}

	@Column(name = "DT_CRITERIA", nullable = false, length = 8)
	public String getDtCriteria() {
		return this.dtCriteria;
	}

	public void setDtCriteria(String dtCriteria) {
		this.dtCriteria = dtCriteria;
	}

	@Column(name = "DT_AUTH", nullable = false, length = 8)
	public String getDtAuth() {
		return this.dtAuth;
	}

	public void setDtAuth(String dtAuth) {
		this.dtAuth = dtAuth;
	}

	@Column(name = "DT_AUTH_END", nullable = false, length = 8)
	public String getDtAuthEnd() {
		return this.dtAuthEnd;
	}

	public void setDtAuthEnd(String dtAuthEnd) {
		this.dtAuthEnd = dtAuthEnd;
	}

	@Column(name = "DT_ENTRY", nullable = false, length = 8)
	public String getDtEntry() {
		return this.dtEntry;
	}

	public void setDtEntry(String dtEntry) {
		this.dtEntry = dtEntry;
	}

	@Column(name = "DT_INACTV", nullable = false, length = 8)
	public String getDtInactv() {
		return this.dtInactv;
	}

	public void setDtInactv(String dtInactv) {
		this.dtInactv = dtInactv;
	}

	@Column(name = "INACTV_RSN_CD", nullable = false, length = 2)
	public String getInactvRsnCd() {
		return this.inactvRsnCd;
	}

	public void setInactvRsnCd(String inactvRsnCd) {
		this.inactvRsnCd = inactvRsnCd;
	}

	@Column(name = "VAC_RSN", nullable = false, length = 2)
	public String getVacRsn() {
		return this.vacRsn;
	}

	public void setVacRsn(String vacRsn) {
		this.vacRsn = vacRsn;
	}

	@Column(name = "PAY_GRD", nullable = false, length = 3)
	public String getPayGrd() {
		return this.payGrd;
	}

	public void setPayGrd(String payGrd) {
		this.payGrd = payGrd;
	}

	@Column(name = "PAY_STP", nullable = false, length = 2)
	public String getPayStp() {
		return this.payStp;
	}

	public void setPayStp(String payStp) {
		this.payStp = payStp;
	}

	@Column(name = "PAY_SCHED", nullable = false, length = 1)
	public char getPaySched() {
		return this.paySched;
	}

	public void setPaySched(char paySched) {
		this.paySched = paySched;
	}

	@Column(name = "EQUIV_UNTS", nullable = false, precision = 3)
	public BigDecimal getEquivUnts() {
		return this.equivUnts;
	}

	public void setEquivUnts(BigDecimal equivUnts) {
		this.equivUnts = equivUnts;
	}

	@Column(name = "MIDPNT_BAS", nullable = false, length = 1)
	public char getMidpntBas() {
		return this.midpntBas;
	}

	public void setMidpntBas(char midpntBas) {
		this.midpntBas = midpntBas;
	}

	@Column(name = "PCT_OF_MIDPNT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getPctOfMidpnt() {
		return this.pctOfMidpnt;
	}

	public void setPctOfMidpnt(BigDecimal pctOfMidpnt) {
		this.pctOfMidpnt = pctOfMidpnt;
	}

	@Column(name = "UNEMP_ELIG_FLG", nullable = false, length = 1)
	public char getUnempEligFlg() {
		return this.unempEligFlg;
	}

	public void setUnempEligFlg(char unempEligFlg) {
		this.unempEligFlg = unempEligFlg;
	}

	@Column(name = "FICA_ELIG", nullable = false, length = 1)
	public char getFicaElig() {
		return this.ficaElig;
	}

	public void setFicaElig(char ficaElig) {
		this.ficaElig = ficaElig;
	}

	@Column(name = "TRS_STAT_CD", nullable = false, length = 1)
	public char getTrsStatCd() {
		return this.trsStatCd;
	}

	public void setTrsStatCd(char trsStatCd) {
		this.trsStatCd = trsStatCd;
	}

	@Column(name = "BUD_AMT", nullable = false, precision = 9)
	public BigDecimal getBudAmt() {
		return this.budAmt;
	}

	public void setBudAmt(BigDecimal budAmt) {
		this.budAmt = budAmt;
	}

	@Column(name = "BUD_SAL_OVRRID", nullable = false, length = 1)
	public char getBudSalOvrrid() {
		return this.budSalOvrrid;
	}

	public void setBudSalOvrrid(char budSalOvrrid) {
		this.budSalOvrrid = budSalOvrrid;
	}

	@Column(name = "ACT_BUD_IND", nullable = false, length = 1)
	public char getActBudInd() {
		return this.actBudInd;
	}

	public void setActBudInd(char actBudInd) {
		this.actBudInd = actBudInd;
	}

	@Column(name = "PAY_TYP", nullable = false, length = 1)
	public char getPayTyp() {
		return this.payTyp;
	}

	public void setPayTyp(char payTyp) {
		this.payTyp = payTyp;
	}

	@Column(name = "OCC_PAY_TYP", nullable = false, length = 1)
	public char getOccPayTyp() {
		return this.occPayTyp;
	}

	public void setOccPayTyp(char occPayTyp) {
		this.occPayTyp = occPayTyp;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "NBR_DAYS_EMPLD", nullable = false, precision = 5, scale = 1)
	public BigDecimal getNbrDaysEmpld() {
		return this.nbrDaysEmpld;
	}

	public void setNbrDaysEmpld(BigDecimal nbrDaysEmpld) {
		this.nbrDaysEmpld = nbrDaysEmpld;
	}

	@Column(name = "SUPPL_RECALC", nullable = false, length = 1)
	public char getSupplRecalc() {
		return this.supplRecalc;
	}

	public void setSupplRecalc(char supplRecalc) {
		this.supplRecalc = supplRecalc;
	}

	@Column(name = "IGN_PCT_DAY_FOR_SAL_CALCS", nullable = false, length = 1)
	public char getIgnPctDayForSalCalcs() {
		return this.ignPctDayForSalCalcs;
	}

	public void setIgnPctDayForSalCalcs(char ignPctDayForSalCalcs) {
		this.ignPctDayForSalCalcs = ignPctDayForSalCalcs;
	}

	@Column(name = "IGN_PCT_YR_FOR_SAL_CALCS", nullable = false, length = 1)
	public char getIgnPctYrForSalCalcs() {
		return this.ignPctYrForSalCalcs;
	}

	public void setIgnPctYrForSalCalcs(char ignPctYrForSalCalcs) {
		this.ignPctYrForSalCalcs = ignPctYrForSalCalcs;
	}

}
