package com.esc20.model;
// Generated Jan 4, 2019 3:44:13 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayrunOptionsLv generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAYRUN_OPTIONS_LV", schema = "rsccc", catalog = "rsccc")
public class BhrPayrunOptionsLv implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayrunOptionsLvId id;
	private char incrementFlg;
	private BigDecimal incrementAmt;

	public BhrPayrunOptionsLv() {
	}

	public BhrPayrunOptionsLv(BhrPayrunOptionsLvId id, char incrementFlg, BigDecimal incrementAmt) {
		this.id = id;
		this.incrementFlg = incrementFlg;
		this.incrementAmt = incrementAmt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)) })
	public BhrPayrunOptionsLvId getId() {
		return this.id;
	}

	public void setId(BhrPayrunOptionsLvId id) {
		this.id = id;
	}

	@Column(name = "INCREMENT_FLG", nullable = false, length = 1)
	public char getIncrementFlg() {
		return this.incrementFlg;
	}

	public void setIncrementFlg(char incrementFlg) {
		this.incrementFlg = incrementFlg;
	}

	@Column(name = "INCREMENT_AMT", nullable = false, precision = 7, scale = 3)
	public BigDecimal getIncrementAmt() {
		return this.incrementAmt;
	}

	public void setIncrementAmt(BigDecimal incrementAmt) {
		this.incrementAmt = incrementAmt;
	}

}
