package com.esc20.model;
// Generated Jan 4, 2019 3:45:09 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrSchYtdJobAccru generated by hbm2java
 */
@Entity
@Table(name = "BHR_SCH_YTD_JOB_ACCRU", schema = "rsccc", catalog = "rsccc")
public class BhrSchYtdJobAccru implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrSchYtdJobAccruId id;
	private BigDecimal daysEarned;
	private BigDecimal accruPay;
	private BigDecimal accruFedGrant;
	private BigDecimal accruFicaTax;
	private BigDecimal accruUnemplIns;
	private BigDecimal accruEmplrAnnuitContrib;
	private BigDecimal accruEmplrNonAnnuitContrib;
	private BigDecimal accruFedCare;
	private BigDecimal accruEmplr457Contrib;
	private BigDecimal accruTeaHealthInsContrib;
	private BigDecimal accruEmplrTrsCareContrib;
	private BigDecimal accruEmplrRetPensnSurchg;
	private BigDecimal accruEmplrTrsCareSurchg;
	private BigDecimal accruEmplrDependCare;
	private BigDecimal accruEmplrMiscDedContrib;
	private String module;

	public BhrSchYtdJobAccru() {
	}

	public BhrSchYtdJobAccru(BhrSchYtdJobAccruId id, BigDecimal daysEarned, BigDecimal accruPay,
			BigDecimal accruFedGrant, BigDecimal accruFicaTax, BigDecimal accruUnemplIns,
			BigDecimal accruEmplrAnnuitContrib, BigDecimal accruEmplrNonAnnuitContrib, BigDecimal accruFedCare,
			BigDecimal accruEmplr457Contrib, BigDecimal accruTeaHealthInsContrib, BigDecimal accruEmplrTrsCareContrib,
			BigDecimal accruEmplrRetPensnSurchg, BigDecimal accruEmplrTrsCareSurchg, BigDecimal accruEmplrDependCare,
			BigDecimal accruEmplrMiscDedContrib, String module) {
		this.id = id;
		this.daysEarned = daysEarned;
		this.accruPay = accruPay;
		this.accruFedGrant = accruFedGrant;
		this.accruFicaTax = accruFicaTax;
		this.accruUnemplIns = accruUnemplIns;
		this.accruEmplrAnnuitContrib = accruEmplrAnnuitContrib;
		this.accruEmplrNonAnnuitContrib = accruEmplrNonAnnuitContrib;
		this.accruFedCare = accruFedCare;
		this.accruEmplr457Contrib = accruEmplr457Contrib;
		this.accruTeaHealthInsContrib = accruTeaHealthInsContrib;
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
		this.accruEmplrTrsCareSurchg = accruEmplrTrsCareSurchg;
		this.accruEmplrDependCare = accruEmplrDependCare;
		this.accruEmplrMiscDedContrib = accruEmplrMiscDedContrib;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)) })
	public BhrSchYtdJobAccruId getId() {
		return this.id;
	}

	public void setId(BhrSchYtdJobAccruId id) {
		this.id = id;
	}

	@Column(name = "DAYS_EARNED", nullable = false, precision = 5)
	public BigDecimal getDaysEarned() {
		return this.daysEarned;
	}

	public void setDaysEarned(BigDecimal daysEarned) {
		this.daysEarned = daysEarned;
	}

	@Column(name = "ACCRU_PAY", nullable = false, precision = 9)
	public BigDecimal getAccruPay() {
		return this.accruPay;
	}

	public void setAccruPay(BigDecimal accruPay) {
		this.accruPay = accruPay;
	}

	@Column(name = "ACCRU_FED_GRANT", nullable = false, precision = 9)
	public BigDecimal getAccruFedGrant() {
		return this.accruFedGrant;
	}

	public void setAccruFedGrant(BigDecimal accruFedGrant) {
		this.accruFedGrant = accruFedGrant;
	}

	@Column(name = "ACCRU_FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getAccruFicaTax() {
		return this.accruFicaTax;
	}

	public void setAccruFicaTax(BigDecimal accruFicaTax) {
		this.accruFicaTax = accruFicaTax;
	}

	@Column(name = "ACCRU_UNEMPL_INS", nullable = false, precision = 9)
	public BigDecimal getAccruUnemplIns() {
		return this.accruUnemplIns;
	}

	public void setAccruUnemplIns(BigDecimal accruUnemplIns) {
		this.accruUnemplIns = accruUnemplIns;
	}

	@Column(name = "ACCRU_EMPLR_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrAnnuitContrib() {
		return this.accruEmplrAnnuitContrib;
	}

	public void setAccruEmplrAnnuitContrib(BigDecimal accruEmplrAnnuitContrib) {
		this.accruEmplrAnnuitContrib = accruEmplrAnnuitContrib;
	}

	@Column(name = "ACCRU_EMPLR_NON_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrNonAnnuitContrib() {
		return this.accruEmplrNonAnnuitContrib;
	}

	public void setAccruEmplrNonAnnuitContrib(BigDecimal accruEmplrNonAnnuitContrib) {
		this.accruEmplrNonAnnuitContrib = accruEmplrNonAnnuitContrib;
	}

	@Column(name = "ACCRU_FED_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruFedCare() {
		return this.accruFedCare;
	}

	public void setAccruFedCare(BigDecimal accruFedCare) {
		this.accruFedCare = accruFedCare;
	}

	@Column(name = "ACCRU_EMPLR_457_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplr457Contrib() {
		return this.accruEmplr457Contrib;
	}

	public void setAccruEmplr457Contrib(BigDecimal accruEmplr457Contrib) {
		this.accruEmplr457Contrib = accruEmplr457Contrib;
	}

	@Column(name = "ACCRU_TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getAccruTeaHealthInsContrib() {
		return this.accruTeaHealthInsContrib;
	}

	public void setAccruTeaHealthInsContrib(BigDecimal accruTeaHealthInsContrib) {
		this.accruTeaHealthInsContrib = accruTeaHealthInsContrib;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrTrsCareContrib() {
		return this.accruEmplrTrsCareContrib;
	}

	public void setAccruEmplrTrsCareContrib(BigDecimal accruEmplrTrsCareContrib) {
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
	}

	@Column(name = "ACCRU_EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrRetPensnSurchg() {
		return this.accruEmplrRetPensnSurchg;
	}

	public void setAccruEmplrRetPensnSurchg(BigDecimal accruEmplrRetPensnSurchg) {
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrTrsCareSurchg() {
		return this.accruEmplrTrsCareSurchg;
	}

	public void setAccruEmplrTrsCareSurchg(BigDecimal accruEmplrTrsCareSurchg) {
		this.accruEmplrTrsCareSurchg = accruEmplrTrsCareSurchg;
	}

	@Column(name = "ACCRU_EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrDependCare() {
		return this.accruEmplrDependCare;
	}

	public void setAccruEmplrDependCare(BigDecimal accruEmplrDependCare) {
		this.accruEmplrDependCare = accruEmplrDependCare;
	}

	@Column(name = "ACCRU_EMPLR_MISC_DED_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrMiscDedContrib() {
		return this.accruEmplrMiscDedContrib;
	}

	public void setAccruEmplrMiscDedContrib(BigDecimal accruEmplrMiscDedContrib) {
		this.accruEmplrMiscDedContrib = accruEmplrMiscDedContrib;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
