package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrSavingsBonds generated by hbm2java
 */
@Entity
@Table(name = "BHR_SAVINGS_BONDS", schema = "rsccc", catalog = "rsccc")
public class BhrSavingsBonds implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrSavingsBondsId id;
	private String ownerSsn;
	private String owner;
	private String ownerAddrNbr;
	private String ownerAddrStr;
	private String ownerAddrApt;
	private String ownerAddrCity;
	private String ownerAddrSt;
	private String ownerAddrZip;
	private String ownerAddrZip4;
	private String benificiary;
	private String benificiarySsan;
	private String relationship;
	private int faceValue;
	private char statusFlg;
	private String seriesTyp;

	public BhrSavingsBonds() {
	}

	public BhrSavingsBonds(BhrSavingsBondsId id, String ownerSsn, String owner, String ownerAddrNbr,
			String ownerAddrStr, String ownerAddrApt, String ownerAddrCity, String ownerAddrSt, String ownerAddrZip,
			String ownerAddrZip4, String benificiary, String benificiarySsan, String relationship, int faceValue,
			char statusFlg, String seriesTyp) {
		this.id = id;
		this.ownerSsn = ownerSsn;
		this.owner = owner;
		this.ownerAddrNbr = ownerAddrNbr;
		this.ownerAddrStr = ownerAddrStr;
		this.ownerAddrApt = ownerAddrApt;
		this.ownerAddrCity = ownerAddrCity;
		this.ownerAddrSt = ownerAddrSt;
		this.ownerAddrZip = ownerAddrZip;
		this.ownerAddrZip4 = ownerAddrZip4;
		this.benificiary = benificiary;
		this.benificiarySsan = benificiarySsan;
		this.relationship = relationship;
		this.faceValue = faceValue;
		this.statusFlg = statusFlg;
		this.seriesTyp = seriesTyp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dedCd", column = @Column(name = "DED_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "dedSeq", column = @Column(name = "DED_SEQ", nullable = false, length = 1)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)) })
	public BhrSavingsBondsId getId() {
		return this.id;
	}

	public void setId(BhrSavingsBondsId id) {
		this.id = id;
	}

	@Column(name = "OWNER_SSN", nullable = false, length = 9)
	public String getOwnerSsn() {
		return this.ownerSsn;
	}

	public void setOwnerSsn(String ownerSsn) {
		this.ownerSsn = ownerSsn;
	}

	@Column(name = "OWNER", nullable = false, length = 32)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "OWNER_ADDR_NBR", nullable = false, length = 8)
	public String getOwnerAddrNbr() {
		return this.ownerAddrNbr;
	}

	public void setOwnerAddrNbr(String ownerAddrNbr) {
		this.ownerAddrNbr = ownerAddrNbr;
	}

	@Column(name = "OWNER_ADDR_STR", nullable = false, length = 20)
	public String getOwnerAddrStr() {
		return this.ownerAddrStr;
	}

	public void setOwnerAddrStr(String ownerAddrStr) {
		this.ownerAddrStr = ownerAddrStr;
	}

	@Column(name = "OWNER_ADDR_APT", nullable = false, length = 7)
	public String getOwnerAddrApt() {
		return this.ownerAddrApt;
	}

	public void setOwnerAddrApt(String ownerAddrApt) {
		this.ownerAddrApt = ownerAddrApt;
	}

	@Column(name = "OWNER_ADDR_CITY", nullable = false, length = 25)
	public String getOwnerAddrCity() {
		return this.ownerAddrCity;
	}

	public void setOwnerAddrCity(String ownerAddrCity) {
		this.ownerAddrCity = ownerAddrCity;
	}

	@Column(name = "OWNER_ADDR_ST", nullable = false, length = 2)
	public String getOwnerAddrSt() {
		return this.ownerAddrSt;
	}

	public void setOwnerAddrSt(String ownerAddrSt) {
		this.ownerAddrSt = ownerAddrSt;
	}

	@Column(name = "OWNER_ADDR_ZIP", nullable = false, length = 5)
	public String getOwnerAddrZip() {
		return this.ownerAddrZip;
	}

	public void setOwnerAddrZip(String ownerAddrZip) {
		this.ownerAddrZip = ownerAddrZip;
	}

	@Column(name = "OWNER_ADDR_ZIP4", nullable = false, length = 4)
	public String getOwnerAddrZip4() {
		return this.ownerAddrZip4;
	}

	public void setOwnerAddrZip4(String ownerAddrZip4) {
		this.ownerAddrZip4 = ownerAddrZip4;
	}

	@Column(name = "BENIFICIARY", nullable = false, length = 35)
	public String getBenificiary() {
		return this.benificiary;
	}

	public void setBenificiary(String benificiary) {
		this.benificiary = benificiary;
	}

	@Column(name = "BENIFICIARY_SSAN", nullable = false, length = 9)
	public String getBenificiarySsan() {
		return this.benificiarySsan;
	}

	public void setBenificiarySsan(String benificiarySsan) {
		this.benificiarySsan = benificiarySsan;
	}

	@Column(name = "RELATIONSHIP", nullable = false, length = 3)
	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	@Column(name = "FACE_VALUE", nullable = false, precision = 5, scale = 0)
	public int getFaceValue() {
		return this.faceValue;
	}

	public void setFaceValue(int faceValue) {
		this.faceValue = faceValue;
	}

	@Column(name = "STATUS_FLG", nullable = false, length = 1)
	public char getStatusFlg() {
		return this.statusFlg;
	}

	public void setStatusFlg(char statusFlg) {
		this.statusFlg = statusFlg;
	}

	@Column(name = "SERIES_TYP", nullable = false, length = 2)
	public String getSeriesTyp() {
		return this.seriesTyp;
	}

	public void setSeriesTyp(String seriesTyp) {
		this.seriesTyp = seriesTyp;
	}

}
