package com.esc20.model;
// Generated Jan 4, 2019 3:45:09 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrSchYtdWrkCmpBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_SCH_YTD_WRK_CMP_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrSchYtdWrkCmpBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrSchYtdWrkCmpBkupPaycalcs5Id id;

	public BhrSchYtdWrkCmpBkupPaycalcs5() {
	}

	public BhrSchYtdWrkCmpBkupPaycalcs5(BhrSchYtdWrkCmpBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "wrkComp", column = @Column(name = "WRK_COMP", nullable = false, length = 1)),
			@AttributeOverride(name = "wrkCompIns", column = @Column(name = "WRK_COMP_INS", nullable = false, precision = 9)),
			@AttributeOverride(name = "wrkCompGross", column = @Column(name = "WRK_COMP_GROSS", nullable = false, precision = 11)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BhrSchYtdWrkCmpBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrSchYtdWrkCmpBkupPaycalcs5Id id) {
		this.id = id;
	}

}
