package com.esc20.model;
// Generated Jan 4, 2019 3:45:09 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrSchYtdBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BhrSchYtdBkupPaycalcs5Id implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private char cyrNyrFlg;
	private char payFreq;
	private String empNbr;
	private String schYr;
	private BigDecimal contrAmt;
	private BigDecimal noncontrAmt;
	private BigDecimal extraDutyAmt;
	private BigDecimal ficaTax;
	private BigDecimal trsDeposit;
	private BigDecimal absDedAmt;
	private BigDecimal regHrsWrk;
	private BigDecimal regGrossAmt;
	private BigDecimal ovtmHrsWrk;
	private BigDecimal ovtmGross;
	private BigDecimal emplrAnnuitContrib;
	private BigDecimal emplr457Contrib;
	private BigDecimal medTax;
	private BigDecimal accruPay;
	private BigDecimal accruFedGrant;
	private BigDecimal accruFicaTax;
	private BigDecimal accruUnemplIns;
	private BigDecimal accruEmplrAnnuitContrib;
	private BigDecimal accruEmplrNonAnnuitContrib;
	private BigDecimal accruFedCare;
	private BigDecimal accruFedIns;
	private BigDecimal accruEmplr457Contrib;
	private BigDecimal daysEarned;
	private BigDecimal nontrsReimbrExcess;
	private BigDecimal nontrsReimbrBase;
	private BigDecimal nontrsBusAllow;
	private BigDecimal nontrsNontaxBusAllow;
	private BigDecimal trsSupplComp;
	private BigDecimal teaHealthInsContrib;
	private BigDecimal accruTeaHealthInsContrib;
	private BigDecimal emplrTrsCareContrib;
	private BigDecimal accruEmplrTrsCareContrib;
	private BigDecimal accruCafeAmt;
	private BigDecimal nontrsNonpayBusAllow;
	private BigDecimal nontrsNontaxNonpayAllow;
	private BigDecimal emplrRetPensnSurchg;
	private BigDecimal accruEmplrRetPensnSurchg;
	private BigDecimal emplrTrsCareSurchg;
	private BigDecimal accruEmplrTrsCareSurchg;
	private BigDecimal emplrNewTrsPensnContrib;
	private BigDecimal emplrDependCare;
	private BigDecimal accruEmplrDependCare;
	private BigDecimal emplrMiscDedContrib;
	private BigDecimal accruEmplrMiscDedContrib;
	private String module;

	public BhrSchYtdBkupPaycalcs5Id() {
	}

	public BhrSchYtdBkupPaycalcs5Id(char cyrNyrFlg, char payFreq, String empNbr, String schYr, BigDecimal contrAmt,
			BigDecimal noncontrAmt, BigDecimal extraDutyAmt, BigDecimal ficaTax, BigDecimal trsDeposit,
			BigDecimal absDedAmt, BigDecimal regHrsWrk, BigDecimal regGrossAmt, BigDecimal ovtmHrsWrk,
			BigDecimal ovtmGross, BigDecimal emplrAnnuitContrib, BigDecimal emplr457Contrib, BigDecimal medTax,
			BigDecimal accruPay, BigDecimal accruFedGrant, BigDecimal accruFicaTax, BigDecimal accruUnemplIns,
			BigDecimal accruEmplrAnnuitContrib, BigDecimal accruEmplrNonAnnuitContrib, BigDecimal accruFedCare,
			BigDecimal accruFedIns, BigDecimal accruEmplr457Contrib, BigDecimal daysEarned,
			BigDecimal nontrsReimbrExcess, BigDecimal nontrsReimbrBase, BigDecimal nontrsBusAllow,
			BigDecimal nontrsNontaxBusAllow, BigDecimal trsSupplComp, BigDecimal teaHealthInsContrib,
			BigDecimal accruTeaHealthInsContrib, BigDecimal emplrTrsCareContrib, BigDecimal accruEmplrTrsCareContrib,
			BigDecimal accruCafeAmt, BigDecimal nontrsNonpayBusAllow, BigDecimal nontrsNontaxNonpayAllow,
			BigDecimal emplrRetPensnSurchg, BigDecimal accruEmplrRetPensnSurchg, BigDecimal emplrTrsCareSurchg,
			BigDecimal accruEmplrTrsCareSurchg, BigDecimal emplrNewTrsPensnContrib, BigDecimal emplrDependCare,
			BigDecimal accruEmplrDependCare, BigDecimal emplrMiscDedContrib, BigDecimal accruEmplrMiscDedContrib,
			String module) {
		this.cyrNyrFlg = cyrNyrFlg;
		this.payFreq = payFreq;
		this.empNbr = empNbr;
		this.schYr = schYr;
		this.contrAmt = contrAmt;
		this.noncontrAmt = noncontrAmt;
		this.extraDutyAmt = extraDutyAmt;
		this.ficaTax = ficaTax;
		this.trsDeposit = trsDeposit;
		this.absDedAmt = absDedAmt;
		this.regHrsWrk = regHrsWrk;
		this.regGrossAmt = regGrossAmt;
		this.ovtmHrsWrk = ovtmHrsWrk;
		this.ovtmGross = ovtmGross;
		this.emplrAnnuitContrib = emplrAnnuitContrib;
		this.emplr457Contrib = emplr457Contrib;
		this.medTax = medTax;
		this.accruPay = accruPay;
		this.accruFedGrant = accruFedGrant;
		this.accruFicaTax = accruFicaTax;
		this.accruUnemplIns = accruUnemplIns;
		this.accruEmplrAnnuitContrib = accruEmplrAnnuitContrib;
		this.accruEmplrNonAnnuitContrib = accruEmplrNonAnnuitContrib;
		this.accruFedCare = accruFedCare;
		this.accruFedIns = accruFedIns;
		this.accruEmplr457Contrib = accruEmplr457Contrib;
		this.daysEarned = daysEarned;
		this.nontrsReimbrExcess = nontrsReimbrExcess;
		this.nontrsReimbrBase = nontrsReimbrBase;
		this.nontrsBusAllow = nontrsBusAllow;
		this.nontrsNontaxBusAllow = nontrsNontaxBusAllow;
		this.trsSupplComp = trsSupplComp;
		this.teaHealthInsContrib = teaHealthInsContrib;
		this.accruTeaHealthInsContrib = accruTeaHealthInsContrib;
		this.emplrTrsCareContrib = emplrTrsCareContrib;
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
		this.accruCafeAmt = accruCafeAmt;
		this.nontrsNonpayBusAllow = nontrsNonpayBusAllow;
		this.nontrsNontaxNonpayAllow = nontrsNontaxNonpayAllow;
		this.emplrRetPensnSurchg = emplrRetPensnSurchg;
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
		this.emplrTrsCareSurchg = emplrTrsCareSurchg;
		this.accruEmplrTrsCareSurchg = accruEmplrTrsCareSurchg;
		this.emplrNewTrsPensnContrib = emplrNewTrsPensnContrib;
		this.emplrDependCare = emplrDependCare;
		this.accruEmplrDependCare = accruEmplrDependCare;
		this.emplrMiscDedContrib = emplrMiscDedContrib;
		this.accruEmplrMiscDedContrib = accruEmplrMiscDedContrib;
		this.module = module;
	}

	@Column(name = "CYR_NYR_FLG", nullable = false, length = 1)
	public char getCyrNyrFlg() {
		return this.cyrNyrFlg;
	}

	public void setCyrNyrFlg(char cyrNyrFlg) {
		this.cyrNyrFlg = cyrNyrFlg;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "SCH_YR", nullable = false, length = 4)
	public String getSchYr() {
		return this.schYr;
	}

	public void setSchYr(String schYr) {
		this.schYr = schYr;
	}

	@Column(name = "CONTR_AMT", nullable = false, precision = 9)
	public BigDecimal getContrAmt() {
		return this.contrAmt;
	}

	public void setContrAmt(BigDecimal contrAmt) {
		this.contrAmt = contrAmt;
	}

	@Column(name = "NONCONTR_AMT", nullable = false, precision = 9)
	public BigDecimal getNoncontrAmt() {
		return this.noncontrAmt;
	}

	public void setNoncontrAmt(BigDecimal noncontrAmt) {
		this.noncontrAmt = noncontrAmt;
	}

	@Column(name = "EXTRA_DUTY_AMT", nullable = false, precision = 9)
	public BigDecimal getExtraDutyAmt() {
		return this.extraDutyAmt;
	}

	public void setExtraDutyAmt(BigDecimal extraDutyAmt) {
		this.extraDutyAmt = extraDutyAmt;
	}

	@Column(name = "FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getFicaTax() {
		return this.ficaTax;
	}

	public void setFicaTax(BigDecimal ficaTax) {
		this.ficaTax = ficaTax;
	}

	@Column(name = "TRS_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getTrsDeposit() {
		return this.trsDeposit;
	}

	public void setTrsDeposit(BigDecimal trsDeposit) {
		this.trsDeposit = trsDeposit;
	}

	@Column(name = "ABS_DED_AMT", nullable = false, precision = 7)
	public BigDecimal getAbsDedAmt() {
		return this.absDedAmt;
	}

	public void setAbsDedAmt(BigDecimal absDedAmt) {
		this.absDedAmt = absDedAmt;
	}

	@Column(name = "REG_HRS_WRK", nullable = false, precision = 7)
	public BigDecimal getRegHrsWrk() {
		return this.regHrsWrk;
	}

	public void setRegHrsWrk(BigDecimal regHrsWrk) {
		this.regHrsWrk = regHrsWrk;
	}

	@Column(name = "REG_GROSS_AMT", nullable = false, precision = 9)
	public BigDecimal getRegGrossAmt() {
		return this.regGrossAmt;
	}

	public void setRegGrossAmt(BigDecimal regGrossAmt) {
		this.regGrossAmt = regGrossAmt;
	}

	@Column(name = "OVTM_HRS_WRK", nullable = false, precision = 6)
	public BigDecimal getOvtmHrsWrk() {
		return this.ovtmHrsWrk;
	}

	public void setOvtmHrsWrk(BigDecimal ovtmHrsWrk) {
		this.ovtmHrsWrk = ovtmHrsWrk;
	}

	@Column(name = "OVTM_GROSS", nullable = false, precision = 9)
	public BigDecimal getOvtmGross() {
		return this.ovtmGross;
	}

	public void setOvtmGross(BigDecimal ovtmGross) {
		this.ovtmGross = ovtmGross;
	}

	@Column(name = "EMPLR_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrAnnuitContrib() {
		return this.emplrAnnuitContrib;
	}

	public void setEmplrAnnuitContrib(BigDecimal emplrAnnuitContrib) {
		this.emplrAnnuitContrib = emplrAnnuitContrib;
	}

	@Column(name = "EMPLR_457_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplr457Contrib() {
		return this.emplr457Contrib;
	}

	public void setEmplr457Contrib(BigDecimal emplr457Contrib) {
		this.emplr457Contrib = emplr457Contrib;
	}

	@Column(name = "MED_TAX", nullable = false, precision = 9)
	public BigDecimal getMedTax() {
		return this.medTax;
	}

	public void setMedTax(BigDecimal medTax) {
		this.medTax = medTax;
	}

	@Column(name = "ACCRU_PAY", nullable = false, precision = 9)
	public BigDecimal getAccruPay() {
		return this.accruPay;
	}

	public void setAccruPay(BigDecimal accruPay) {
		this.accruPay = accruPay;
	}

	@Column(name = "ACCRU_FED_GRANT", nullable = false, precision = 9)
	public BigDecimal getAccruFedGrant() {
		return this.accruFedGrant;
	}

	public void setAccruFedGrant(BigDecimal accruFedGrant) {
		this.accruFedGrant = accruFedGrant;
	}

	@Column(name = "ACCRU_FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getAccruFicaTax() {
		return this.accruFicaTax;
	}

	public void setAccruFicaTax(BigDecimal accruFicaTax) {
		this.accruFicaTax = accruFicaTax;
	}

	@Column(name = "ACCRU_UNEMPL_INS", nullable = false, precision = 9)
	public BigDecimal getAccruUnemplIns() {
		return this.accruUnemplIns;
	}

	public void setAccruUnemplIns(BigDecimal accruUnemplIns) {
		this.accruUnemplIns = accruUnemplIns;
	}

	@Column(name = "ACCRU_EMPLR_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrAnnuitContrib() {
		return this.accruEmplrAnnuitContrib;
	}

	public void setAccruEmplrAnnuitContrib(BigDecimal accruEmplrAnnuitContrib) {
		this.accruEmplrAnnuitContrib = accruEmplrAnnuitContrib;
	}

	@Column(name = "ACCRU_EMPLR_NON_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrNonAnnuitContrib() {
		return this.accruEmplrNonAnnuitContrib;
	}

	public void setAccruEmplrNonAnnuitContrib(BigDecimal accruEmplrNonAnnuitContrib) {
		this.accruEmplrNonAnnuitContrib = accruEmplrNonAnnuitContrib;
	}

	@Column(name = "ACCRU_FED_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruFedCare() {
		return this.accruFedCare;
	}

	public void setAccruFedCare(BigDecimal accruFedCare) {
		this.accruFedCare = accruFedCare;
	}

	@Column(name = "ACCRU_FED_INS", nullable = false, precision = 9)
	public BigDecimal getAccruFedIns() {
		return this.accruFedIns;
	}

	public void setAccruFedIns(BigDecimal accruFedIns) {
		this.accruFedIns = accruFedIns;
	}

	@Column(name = "ACCRU_EMPLR_457_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplr457Contrib() {
		return this.accruEmplr457Contrib;
	}

	public void setAccruEmplr457Contrib(BigDecimal accruEmplr457Contrib) {
		this.accruEmplr457Contrib = accruEmplr457Contrib;
	}

	@Column(name = "DAYS_EARNED", nullable = false, precision = 5)
	public BigDecimal getDaysEarned() {
		return this.daysEarned;
	}

	public void setDaysEarned(BigDecimal daysEarned) {
		this.daysEarned = daysEarned;
	}

	@Column(name = "NONTRS_REIMBR_EXCESS", nullable = false, precision = 9)
	public BigDecimal getNontrsReimbrExcess() {
		return this.nontrsReimbrExcess;
	}

	public void setNontrsReimbrExcess(BigDecimal nontrsReimbrExcess) {
		this.nontrsReimbrExcess = nontrsReimbrExcess;
	}

	@Column(name = "NONTRS_REIMBR_BASE", nullable = false, precision = 9)
	public BigDecimal getNontrsReimbrBase() {
		return this.nontrsReimbrBase;
	}

	public void setNontrsReimbrBase(BigDecimal nontrsReimbrBase) {
		this.nontrsReimbrBase = nontrsReimbrBase;
	}

	@Column(name = "NONTRS_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsBusAllow() {
		return this.nontrsBusAllow;
	}

	public void setNontrsBusAllow(BigDecimal nontrsBusAllow) {
		this.nontrsBusAllow = nontrsBusAllow;
	}

	@Column(name = "NONTRS_NONTAX_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsNontaxBusAllow() {
		return this.nontrsNontaxBusAllow;
	}

	public void setNontrsNontaxBusAllow(BigDecimal nontrsNontaxBusAllow) {
		this.nontrsNontaxBusAllow = nontrsNontaxBusAllow;
	}

	@Column(name = "TRS_SUPPL_COMP", nullable = false, precision = 7)
	public BigDecimal getTrsSupplComp() {
		return this.trsSupplComp;
	}

	public void setTrsSupplComp(BigDecimal trsSupplComp) {
		this.trsSupplComp = trsSupplComp;
	}

	@Column(name = "TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getTeaHealthInsContrib() {
		return this.teaHealthInsContrib;
	}

	public void setTeaHealthInsContrib(BigDecimal teaHealthInsContrib) {
		this.teaHealthInsContrib = teaHealthInsContrib;
	}

	@Column(name = "ACCRU_TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getAccruTeaHealthInsContrib() {
		return this.accruTeaHealthInsContrib;
	}

	public void setAccruTeaHealthInsContrib(BigDecimal accruTeaHealthInsContrib) {
		this.accruTeaHealthInsContrib = accruTeaHealthInsContrib;
	}

	@Column(name = "EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrTrsCareContrib() {
		return this.emplrTrsCareContrib;
	}

	public void setEmplrTrsCareContrib(BigDecimal emplrTrsCareContrib) {
		this.emplrTrsCareContrib = emplrTrsCareContrib;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrTrsCareContrib() {
		return this.accruEmplrTrsCareContrib;
	}

	public void setAccruEmplrTrsCareContrib(BigDecimal accruEmplrTrsCareContrib) {
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
	}

	@Column(name = "ACCRU_CAFE_AMT", nullable = false, precision = 9)
	public BigDecimal getAccruCafeAmt() {
		return this.accruCafeAmt;
	}

	public void setAccruCafeAmt(BigDecimal accruCafeAmt) {
		this.accruCafeAmt = accruCafeAmt;
	}

	@Column(name = "NONTRS_NONPAY_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsNonpayBusAllow() {
		return this.nontrsNonpayBusAllow;
	}

	public void setNontrsNonpayBusAllow(BigDecimal nontrsNonpayBusAllow) {
		this.nontrsNonpayBusAllow = nontrsNonpayBusAllow;
	}

	@Column(name = "NONTRS_NONTAX_NONPAY_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsNontaxNonpayAllow() {
		return this.nontrsNontaxNonpayAllow;
	}

	public void setNontrsNontaxNonpayAllow(BigDecimal nontrsNontaxNonpayAllow) {
		this.nontrsNontaxNonpayAllow = nontrsNontaxNonpayAllow;
	}

	@Column(name = "EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getEmplrRetPensnSurchg() {
		return this.emplrRetPensnSurchg;
	}

	public void setEmplrRetPensnSurchg(BigDecimal emplrRetPensnSurchg) {
		this.emplrRetPensnSurchg = emplrRetPensnSurchg;
	}

	@Column(name = "ACCRU_EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrRetPensnSurchg() {
		return this.accruEmplrRetPensnSurchg;
	}

	public void setAccruEmplrRetPensnSurchg(BigDecimal accruEmplrRetPensnSurchg) {
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
	}

	@Column(name = "EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getEmplrTrsCareSurchg() {
		return this.emplrTrsCareSurchg;
	}

	public void setEmplrTrsCareSurchg(BigDecimal emplrTrsCareSurchg) {
		this.emplrTrsCareSurchg = emplrTrsCareSurchg;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrTrsCareSurchg() {
		return this.accruEmplrTrsCareSurchg;
	}

	public void setAccruEmplrTrsCareSurchg(BigDecimal accruEmplrTrsCareSurchg) {
		this.accruEmplrTrsCareSurchg = accruEmplrTrsCareSurchg;
	}

	@Column(name = "EMPLR_NEW_TRS_PENSN_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getEmplrNewTrsPensnContrib() {
		return this.emplrNewTrsPensnContrib;
	}

	public void setEmplrNewTrsPensnContrib(BigDecimal emplrNewTrsPensnContrib) {
		this.emplrNewTrsPensnContrib = emplrNewTrsPensnContrib;
	}

	@Column(name = "EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getEmplrDependCare() {
		return this.emplrDependCare;
	}

	public void setEmplrDependCare(BigDecimal emplrDependCare) {
		this.emplrDependCare = emplrDependCare;
	}

	@Column(name = "ACCRU_EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrDependCare() {
		return this.accruEmplrDependCare;
	}

	public void setAccruEmplrDependCare(BigDecimal accruEmplrDependCare) {
		this.accruEmplrDependCare = accruEmplrDependCare;
	}

	@Column(name = "EMPLR_MISC_DED_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrMiscDedContrib() {
		return this.emplrMiscDedContrib;
	}

	public void setEmplrMiscDedContrib(BigDecimal emplrMiscDedContrib) {
		this.emplrMiscDedContrib = emplrMiscDedContrib;
	}

	@Column(name = "ACCRU_EMPLR_MISC_DED_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrMiscDedContrib() {
		return this.accruEmplrMiscDedContrib;
	}

	public void setAccruEmplrMiscDedContrib(BigDecimal accruEmplrMiscDedContrib) {
		this.accruEmplrMiscDedContrib = accruEmplrMiscDedContrib;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrSchYtdBkupPaycalcs5Id))
			return false;
		BhrSchYtdBkupPaycalcs5Id castOther = (BhrSchYtdBkupPaycalcs5Id) other;

		return (this.getCyrNyrFlg() == castOther.getCyrNyrFlg()) && (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
						&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& ((this.getSchYr() == castOther.getSchYr()) || (this.getSchYr() != null
						&& castOther.getSchYr() != null && this.getSchYr().equals(castOther.getSchYr())))
				&& ((this.getContrAmt() == castOther.getContrAmt()) || (this.getContrAmt() != null
						&& castOther.getContrAmt() != null && this.getContrAmt().equals(castOther.getContrAmt())))
				&& ((this.getNoncontrAmt() == castOther.getNoncontrAmt())
						|| (this.getNoncontrAmt() != null && castOther.getNoncontrAmt() != null
								&& this.getNoncontrAmt().equals(castOther.getNoncontrAmt())))
				&& ((this.getExtraDutyAmt() == castOther.getExtraDutyAmt())
						|| (this.getExtraDutyAmt() != null && castOther.getExtraDutyAmt() != null
								&& this.getExtraDutyAmt().equals(castOther.getExtraDutyAmt())))
				&& ((this.getFicaTax() == castOther.getFicaTax()) || (this.getFicaTax() != null
						&& castOther.getFicaTax() != null && this.getFicaTax().equals(castOther.getFicaTax())))
				&& ((this.getTrsDeposit() == castOther.getTrsDeposit()) || (this.getTrsDeposit() != null
						&& castOther.getTrsDeposit() != null && this.getTrsDeposit().equals(castOther.getTrsDeposit())))
				&& ((this.getAbsDedAmt() == castOther.getAbsDedAmt()) || (this.getAbsDedAmt() != null
						&& castOther.getAbsDedAmt() != null && this.getAbsDedAmt().equals(castOther.getAbsDedAmt())))
				&& ((this.getRegHrsWrk() == castOther.getRegHrsWrk()) || (this.getRegHrsWrk() != null
						&& castOther.getRegHrsWrk() != null && this.getRegHrsWrk().equals(castOther.getRegHrsWrk())))
				&& ((this.getRegGrossAmt() == castOther.getRegGrossAmt())
						|| (this.getRegGrossAmt() != null && castOther.getRegGrossAmt() != null
								&& this.getRegGrossAmt().equals(castOther.getRegGrossAmt())))
				&& ((this.getOvtmHrsWrk() == castOther.getOvtmHrsWrk()) || (this.getOvtmHrsWrk() != null
						&& castOther.getOvtmHrsWrk() != null && this.getOvtmHrsWrk().equals(castOther.getOvtmHrsWrk())))
				&& ((this.getOvtmGross() == castOther.getOvtmGross()) || (this.getOvtmGross() != null
						&& castOther.getOvtmGross() != null && this.getOvtmGross().equals(castOther.getOvtmGross())))
				&& ((this.getEmplrAnnuitContrib() == castOther.getEmplrAnnuitContrib())
						|| (this.getEmplrAnnuitContrib() != null && castOther.getEmplrAnnuitContrib() != null
								&& this.getEmplrAnnuitContrib().equals(castOther.getEmplrAnnuitContrib())))
				&& ((this.getEmplr457Contrib() == castOther.getEmplr457Contrib())
						|| (this.getEmplr457Contrib() != null && castOther.getEmplr457Contrib() != null
								&& this.getEmplr457Contrib().equals(castOther.getEmplr457Contrib())))
				&& ((this.getMedTax() == castOther.getMedTax()) || (this.getMedTax() != null
						&& castOther.getMedTax() != null && this.getMedTax().equals(castOther.getMedTax())))
				&& ((this.getAccruPay() == castOther.getAccruPay()) || (this.getAccruPay() != null
						&& castOther.getAccruPay() != null && this.getAccruPay().equals(castOther.getAccruPay())))
				&& ((this.getAccruFedGrant() == castOther.getAccruFedGrant())
						|| (this.getAccruFedGrant() != null && castOther.getAccruFedGrant() != null
								&& this.getAccruFedGrant().equals(castOther.getAccruFedGrant())))
				&& ((this.getAccruFicaTax() == castOther.getAccruFicaTax())
						|| (this.getAccruFicaTax() != null && castOther.getAccruFicaTax() != null
								&& this.getAccruFicaTax().equals(castOther.getAccruFicaTax())))
				&& ((this.getAccruUnemplIns() == castOther.getAccruUnemplIns())
						|| (this.getAccruUnemplIns() != null && castOther.getAccruUnemplIns() != null
								&& this.getAccruUnemplIns().equals(castOther.getAccruUnemplIns())))
				&& ((this.getAccruEmplrAnnuitContrib() == castOther.getAccruEmplrAnnuitContrib())
						|| (this.getAccruEmplrAnnuitContrib() != null && castOther.getAccruEmplrAnnuitContrib() != null
								&& this.getAccruEmplrAnnuitContrib().equals(castOther.getAccruEmplrAnnuitContrib())))
				&& ((this.getAccruEmplrNonAnnuitContrib() == castOther.getAccruEmplrNonAnnuitContrib())
						|| (this.getAccruEmplrNonAnnuitContrib() != null
								&& castOther.getAccruEmplrNonAnnuitContrib() != null
								&& this.getAccruEmplrNonAnnuitContrib()
										.equals(castOther.getAccruEmplrNonAnnuitContrib())))
				&& ((this.getAccruFedCare() == castOther.getAccruFedCare())
						|| (this.getAccruFedCare() != null && castOther.getAccruFedCare() != null
								&& this.getAccruFedCare().equals(castOther.getAccruFedCare())))
				&& ((this.getAccruFedIns() == castOther.getAccruFedIns())
						|| (this.getAccruFedIns() != null && castOther.getAccruFedIns() != null
								&& this.getAccruFedIns().equals(castOther.getAccruFedIns())))
				&& ((this.getAccruEmplr457Contrib() == castOther.getAccruEmplr457Contrib())
						|| (this.getAccruEmplr457Contrib() != null && castOther.getAccruEmplr457Contrib() != null
								&& this.getAccruEmplr457Contrib().equals(castOther.getAccruEmplr457Contrib())))
				&& ((this.getDaysEarned() == castOther.getDaysEarned()) || (this.getDaysEarned() != null
						&& castOther.getDaysEarned() != null && this.getDaysEarned().equals(castOther.getDaysEarned())))
				&& ((this.getNontrsReimbrExcess() == castOther.getNontrsReimbrExcess())
						|| (this.getNontrsReimbrExcess() != null && castOther.getNontrsReimbrExcess() != null
								&& this.getNontrsReimbrExcess().equals(castOther.getNontrsReimbrExcess())))
				&& ((this.getNontrsReimbrBase() == castOther.getNontrsReimbrBase())
						|| (this.getNontrsReimbrBase() != null && castOther.getNontrsReimbrBase() != null
								&& this.getNontrsReimbrBase().equals(castOther.getNontrsReimbrBase())))
				&& ((this.getNontrsBusAllow() == castOther.getNontrsBusAllow())
						|| (this.getNontrsBusAllow() != null && castOther.getNontrsBusAllow() != null
								&& this.getNontrsBusAllow().equals(castOther.getNontrsBusAllow())))
				&& ((this.getNontrsNontaxBusAllow() == castOther.getNontrsNontaxBusAllow())
						|| (this.getNontrsNontaxBusAllow() != null && castOther.getNontrsNontaxBusAllow() != null
								&& this.getNontrsNontaxBusAllow().equals(castOther.getNontrsNontaxBusAllow())))
				&& ((this.getTrsSupplComp() == castOther.getTrsSupplComp())
						|| (this.getTrsSupplComp() != null && castOther.getTrsSupplComp() != null
								&& this.getTrsSupplComp().equals(castOther.getTrsSupplComp())))
				&& ((this.getTeaHealthInsContrib() == castOther.getTeaHealthInsContrib())
						|| (this.getTeaHealthInsContrib() != null && castOther.getTeaHealthInsContrib() != null
								&& this.getTeaHealthInsContrib().equals(castOther.getTeaHealthInsContrib())))
				&& ((this.getAccruTeaHealthInsContrib() == castOther.getAccruTeaHealthInsContrib())
						|| (this.getAccruTeaHealthInsContrib() != null
								&& castOther.getAccruTeaHealthInsContrib() != null
								&& this.getAccruTeaHealthInsContrib().equals(castOther.getAccruTeaHealthInsContrib())))
				&& ((this.getEmplrTrsCareContrib() == castOther.getEmplrTrsCareContrib())
						|| (this.getEmplrTrsCareContrib() != null && castOther.getEmplrTrsCareContrib() != null
								&& this.getEmplrTrsCareContrib().equals(castOther.getEmplrTrsCareContrib())))
				&& ((this.getAccruEmplrTrsCareContrib() == castOther.getAccruEmplrTrsCareContrib())
						|| (this.getAccruEmplrTrsCareContrib() != null
								&& castOther.getAccruEmplrTrsCareContrib() != null
								&& this.getAccruEmplrTrsCareContrib().equals(castOther.getAccruEmplrTrsCareContrib())))
				&& ((this.getAccruCafeAmt() == castOther.getAccruCafeAmt())
						|| (this.getAccruCafeAmt() != null && castOther.getAccruCafeAmt() != null
								&& this.getAccruCafeAmt().equals(castOther.getAccruCafeAmt())))
				&& ((this.getNontrsNonpayBusAllow() == castOther.getNontrsNonpayBusAllow())
						|| (this.getNontrsNonpayBusAllow() != null && castOther.getNontrsNonpayBusAllow() != null
								&& this.getNontrsNonpayBusAllow().equals(castOther.getNontrsNonpayBusAllow())))
				&& ((this.getNontrsNontaxNonpayAllow() == castOther.getNontrsNontaxNonpayAllow())
						|| (this.getNontrsNontaxNonpayAllow() != null && castOther.getNontrsNontaxNonpayAllow() != null
								&& this.getNontrsNontaxNonpayAllow().equals(castOther.getNontrsNontaxNonpayAllow())))
				&& ((this.getEmplrRetPensnSurchg() == castOther.getEmplrRetPensnSurchg())
						|| (this.getEmplrRetPensnSurchg() != null && castOther.getEmplrRetPensnSurchg() != null
								&& this.getEmplrRetPensnSurchg().equals(castOther.getEmplrRetPensnSurchg())))
				&& ((this.getAccruEmplrRetPensnSurchg() == castOther.getAccruEmplrRetPensnSurchg())
						|| (this.getAccruEmplrRetPensnSurchg() != null
								&& castOther.getAccruEmplrRetPensnSurchg() != null
								&& this.getAccruEmplrRetPensnSurchg().equals(castOther.getAccruEmplrRetPensnSurchg())))
				&& ((this.getEmplrTrsCareSurchg() == castOther.getEmplrTrsCareSurchg())
						|| (this.getEmplrTrsCareSurchg() != null && castOther.getEmplrTrsCareSurchg() != null
								&& this.getEmplrTrsCareSurchg().equals(castOther.getEmplrTrsCareSurchg())))
				&& ((this.getAccruEmplrTrsCareSurchg() == castOther.getAccruEmplrTrsCareSurchg())
						|| (this.getAccruEmplrTrsCareSurchg() != null && castOther.getAccruEmplrTrsCareSurchg() != null
								&& this.getAccruEmplrTrsCareSurchg().equals(castOther.getAccruEmplrTrsCareSurchg())))
				&& ((this.getEmplrNewTrsPensnContrib() == castOther.getEmplrNewTrsPensnContrib())
						|| (this.getEmplrNewTrsPensnContrib() != null && castOther.getEmplrNewTrsPensnContrib() != null
								&& this.getEmplrNewTrsPensnContrib().equals(castOther.getEmplrNewTrsPensnContrib())))
				&& ((this.getEmplrDependCare() == castOther.getEmplrDependCare())
						|| (this.getEmplrDependCare() != null && castOther.getEmplrDependCare() != null
								&& this.getEmplrDependCare().equals(castOther.getEmplrDependCare())))
				&& ((this.getAccruEmplrDependCare() == castOther.getAccruEmplrDependCare())
						|| (this.getAccruEmplrDependCare() != null && castOther.getAccruEmplrDependCare() != null
								&& this.getAccruEmplrDependCare().equals(castOther.getAccruEmplrDependCare())))
				&& ((this.getEmplrMiscDedContrib() == castOther.getEmplrMiscDedContrib())
						|| (this.getEmplrMiscDedContrib() != null && castOther.getEmplrMiscDedContrib() != null
								&& this.getEmplrMiscDedContrib().equals(castOther.getEmplrMiscDedContrib())))
				&& ((this.getAccruEmplrMiscDedContrib() == castOther.getAccruEmplrMiscDedContrib())
						|| (this.getAccruEmplrMiscDedContrib() != null
								&& castOther.getAccruEmplrMiscDedContrib() != null
								&& this.getAccruEmplrMiscDedContrib().equals(castOther.getAccruEmplrMiscDedContrib())))
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCyrNyrFlg();
		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + (getSchYr() == null ? 0 : this.getSchYr().hashCode());
		result = 37 * result + (getContrAmt() == null ? 0 : this.getContrAmt().hashCode());
		result = 37 * result + (getNoncontrAmt() == null ? 0 : this.getNoncontrAmt().hashCode());
		result = 37 * result + (getExtraDutyAmt() == null ? 0 : this.getExtraDutyAmt().hashCode());
		result = 37 * result + (getFicaTax() == null ? 0 : this.getFicaTax().hashCode());
		result = 37 * result + (getTrsDeposit() == null ? 0 : this.getTrsDeposit().hashCode());
		result = 37 * result + (getAbsDedAmt() == null ? 0 : this.getAbsDedAmt().hashCode());
		result = 37 * result + (getRegHrsWrk() == null ? 0 : this.getRegHrsWrk().hashCode());
		result = 37 * result + (getRegGrossAmt() == null ? 0 : this.getRegGrossAmt().hashCode());
		result = 37 * result + (getOvtmHrsWrk() == null ? 0 : this.getOvtmHrsWrk().hashCode());
		result = 37 * result + (getOvtmGross() == null ? 0 : this.getOvtmGross().hashCode());
		result = 37 * result + (getEmplrAnnuitContrib() == null ? 0 : this.getEmplrAnnuitContrib().hashCode());
		result = 37 * result + (getEmplr457Contrib() == null ? 0 : this.getEmplr457Contrib().hashCode());
		result = 37 * result + (getMedTax() == null ? 0 : this.getMedTax().hashCode());
		result = 37 * result + (getAccruPay() == null ? 0 : this.getAccruPay().hashCode());
		result = 37 * result + (getAccruFedGrant() == null ? 0 : this.getAccruFedGrant().hashCode());
		result = 37 * result + (getAccruFicaTax() == null ? 0 : this.getAccruFicaTax().hashCode());
		result = 37 * result + (getAccruUnemplIns() == null ? 0 : this.getAccruUnemplIns().hashCode());
		result = 37 * result
				+ (getAccruEmplrAnnuitContrib() == null ? 0 : this.getAccruEmplrAnnuitContrib().hashCode());
		result = 37 * result
				+ (getAccruEmplrNonAnnuitContrib() == null ? 0 : this.getAccruEmplrNonAnnuitContrib().hashCode());
		result = 37 * result + (getAccruFedCare() == null ? 0 : this.getAccruFedCare().hashCode());
		result = 37 * result + (getAccruFedIns() == null ? 0 : this.getAccruFedIns().hashCode());
		result = 37 * result + (getAccruEmplr457Contrib() == null ? 0 : this.getAccruEmplr457Contrib().hashCode());
		result = 37 * result + (getDaysEarned() == null ? 0 : this.getDaysEarned().hashCode());
		result = 37 * result + (getNontrsReimbrExcess() == null ? 0 : this.getNontrsReimbrExcess().hashCode());
		result = 37 * result + (getNontrsReimbrBase() == null ? 0 : this.getNontrsReimbrBase().hashCode());
		result = 37 * result + (getNontrsBusAllow() == null ? 0 : this.getNontrsBusAllow().hashCode());
		result = 37 * result + (getNontrsNontaxBusAllow() == null ? 0 : this.getNontrsNontaxBusAllow().hashCode());
		result = 37 * result + (getTrsSupplComp() == null ? 0 : this.getTrsSupplComp().hashCode());
		result = 37 * result + (getTeaHealthInsContrib() == null ? 0 : this.getTeaHealthInsContrib().hashCode());
		result = 37 * result
				+ (getAccruTeaHealthInsContrib() == null ? 0 : this.getAccruTeaHealthInsContrib().hashCode());
		result = 37 * result + (getEmplrTrsCareContrib() == null ? 0 : this.getEmplrTrsCareContrib().hashCode());
		result = 37 * result
				+ (getAccruEmplrTrsCareContrib() == null ? 0 : this.getAccruEmplrTrsCareContrib().hashCode());
		result = 37 * result + (getAccruCafeAmt() == null ? 0 : this.getAccruCafeAmt().hashCode());
		result = 37 * result + (getNontrsNonpayBusAllow() == null ? 0 : this.getNontrsNonpayBusAllow().hashCode());
		result = 37 * result
				+ (getNontrsNontaxNonpayAllow() == null ? 0 : this.getNontrsNontaxNonpayAllow().hashCode());
		result = 37 * result + (getEmplrRetPensnSurchg() == null ? 0 : this.getEmplrRetPensnSurchg().hashCode());
		result = 37 * result
				+ (getAccruEmplrRetPensnSurchg() == null ? 0 : this.getAccruEmplrRetPensnSurchg().hashCode());
		result = 37 * result + (getEmplrTrsCareSurchg() == null ? 0 : this.getEmplrTrsCareSurchg().hashCode());
		result = 37 * result
				+ (getAccruEmplrTrsCareSurchg() == null ? 0 : this.getAccruEmplrTrsCareSurchg().hashCode());
		result = 37 * result
				+ (getEmplrNewTrsPensnContrib() == null ? 0 : this.getEmplrNewTrsPensnContrib().hashCode());
		result = 37 * result + (getEmplrDependCare() == null ? 0 : this.getEmplrDependCare().hashCode());
		result = 37 * result + (getAccruEmplrDependCare() == null ? 0 : this.getAccruEmplrDependCare().hashCode());
		result = 37 * result + (getEmplrMiscDedContrib() == null ? 0 : this.getEmplrMiscDedContrib().hashCode());
		result = 37 * result
				+ (getAccruEmplrMiscDedContrib() == null ? 0 : this.getAccruEmplrMiscDedContrib().hashCode());
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		return result;
	}

}
