package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrSavingsBondsId generated by hbm2java
 */
@Embeddable
public class BhrSavingsBondsId implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private char payFreq;
	private String empNbr;
	private String dedCd;
	private char dedSeq;
	private char cyrNyrFlg;

	public BhrSavingsBondsId() {
	}

	public BhrSavingsBondsId(char payFreq, String empNbr, String dedCd, char dedSeq, char cyrNyrFlg) {
		this.payFreq = payFreq;
		this.empNbr = empNbr;
		this.dedCd = dedCd;
		this.dedSeq = dedSeq;
		this.cyrNyrFlg = cyrNyrFlg;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "DED_CD", nullable = false, length = 3)
	public String getDedCd() {
		return this.dedCd;
	}

	public void setDedCd(String dedCd) {
		this.dedCd = dedCd;
	}

	@Column(name = "DED_SEQ", nullable = false, length = 1)
	public char getDedSeq() {
		return this.dedSeq;
	}

	public void setDedSeq(char dedSeq) {
		this.dedSeq = dedSeq;
	}

	@Column(name = "CYR_NYR_FLG", nullable = false, length = 1)
	public char getCyrNyrFlg() {
		return this.cyrNyrFlg;
	}

	public void setCyrNyrFlg(char cyrNyrFlg) {
		this.cyrNyrFlg = cyrNyrFlg;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrSavingsBondsId))
			return false;
		BhrSavingsBondsId castOther = (BhrSavingsBondsId) other;

		return (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
						&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& ((this.getDedCd() == castOther.getDedCd()) || (this.getDedCd() != null
						&& castOther.getDedCd() != null && this.getDedCd().equals(castOther.getDedCd())))
				&& (this.getDedSeq() == castOther.getDedSeq()) && (this.getCyrNyrFlg() == castOther.getCyrNyrFlg());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + (getDedCd() == null ? 0 : this.getDedCd().hashCode());
		result = 37 * result + this.getDedSeq();
		result = 37 * result + this.getCyrNyrFlg();
		return result;
	}

}
