package com.esc20.model;
// Generated Jan 4, 2019 3:46:11 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrSpecialCred generated by hbm2java
 */
@Entity
@Table(name = "BHR_SPECIAL_CRED", schema = "rsccc", catalog = "rsccc")
public class BhrSpecialCred implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrSpecialCredId id;
	private String yr;
	private BigDecimal classroomHrs;
	private String module;

	public BhrSpecialCred() {
	}

	public BhrSpecialCred(BhrSpecialCredId id, String yr, BigDecimal classroomHrs, String module) {
		this.id = id;
		this.yr = yr;
		this.classroomHrs = classroomHrs;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "typ", column = @Column(name = "TYP", nullable = false, length = 20)) })
	public BhrSpecialCredId getId() {
		return this.id;
	}

	public void setId(BhrSpecialCredId id) {
		this.id = id;
	}

	@Column(name = "YR", nullable = false, length = 4)
	public String getYr() {
		return this.yr;
	}

	public void setYr(String yr) {
		this.yr = yr;
	}

	@Column(name = "CLASSROOM_HRS", nullable = false, precision = 5)
	public BigDecimal getClassroomHrs() {
		return this.classroomHrs;
	}

	public void setClassroomHrs(BigDecimal classroomHrs) {
		this.classroomHrs = classroomHrs;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
