package com.esc20.model;
// Generated Jan 4, 2019 3:45:09 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrSchYtdWrkCmp generated by hbm2java
 */
@Entity
@Table(name = "BHR_SCH_YTD_WRK_CMP", schema = "rsccc", catalog = "rsccc")
public class BhrSchYtdWrkCmp implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrSchYtdWrkCmpId id;
	private BigDecimal wrkCompIns;
	private BigDecimal wrkCompGross;
	private String module;

	public BhrSchYtdWrkCmp() {
	}

	public BhrSchYtdWrkCmp(BhrSchYtdWrkCmpId id, BigDecimal wrkCompIns, BigDecimal wrkCompGross, String module) {
		this.id = id;
		this.wrkCompIns = wrkCompIns;
		this.wrkCompGross = wrkCompGross;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "wrkComp", column = @Column(name = "WRK_COMP", nullable = false, length = 1)) })
	public BhrSchYtdWrkCmpId getId() {
		return this.id;
	}

	public void setId(BhrSchYtdWrkCmpId id) {
		this.id = id;
	}

	@Column(name = "WRK_COMP_INS", nullable = false, precision = 9)
	public BigDecimal getWrkCompIns() {
		return this.wrkCompIns;
	}

	public void setWrkCompIns(BigDecimal wrkCompIns) {
		this.wrkCompIns = wrkCompIns;
	}

	@Column(name = "WRK_COMP_GROSS", nullable = false, precision = 11)
	public BigDecimal getWrkCompGross() {
		return this.wrkCompGross;
	}

	public void setWrkCompGross(BigDecimal wrkCompGross) {
		this.wrkCompGross = wrkCompGross;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
