package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTrsDeposits generated by hbm2java
 */
@Entity
@Table(name = "BHR_TRS_DEPOSITS", schema = "rsccc", catalog = "rsccc")
public class BhrTrsDeposits implements java.io.Serializable {

	private BhrTrsDepositsId id;
	private BigDecimal trsGross;
	private BigDecimal trsDeposit;
	private BigDecimal trsDepositCare;
	private BigDecimal trsDepositIns;
	private BigDecimal trsFee;
	private BigDecimal monSupplSalary;
	private BigDecimal monStMinSalary;
	private BigDecimal monWhollySepSalary;
	private BigDecimal monTrsDock;
	private BigDecimal perforPayGross;
	private BigDecimal perforPayDeposit;
	private BigDecimal perforPayIns;
	private BigDecimal emplrNewTrsGross;
	private BigDecimal emplrNewTrsPensnContrib;
	private BigDecimal emplrTrsCareContrib;
	private String module;

	public BhrTrsDeposits() {
	}

	public BhrTrsDeposits(BhrTrsDepositsId id, BigDecimal trsGross, BigDecimal trsDeposit, BigDecimal trsDepositCare,
			BigDecimal trsDepositIns, BigDecimal trsFee, BigDecimal monSupplSalary, BigDecimal monStMinSalary,
			BigDecimal monWhollySepSalary, BigDecimal monTrsDock, BigDecimal perforPayGross,
			BigDecimal perforPayDeposit, BigDecimal perforPayIns, BigDecimal emplrNewTrsGross,
			BigDecimal emplrNewTrsPensnContrib, BigDecimal emplrTrsCareContrib, String module) {
		this.id = id;
		this.trsGross = trsGross;
		this.trsDeposit = trsDeposit;
		this.trsDepositCare = trsDepositCare;
		this.trsDepositIns = trsDepositIns;
		this.trsFee = trsFee;
		this.monSupplSalary = monSupplSalary;
		this.monStMinSalary = monStMinSalary;
		this.monWhollySepSalary = monWhollySepSalary;
		this.monTrsDock = monTrsDock;
		this.perforPayGross = perforPayGross;
		this.perforPayDeposit = perforPayDeposit;
		this.perforPayIns = perforPayIns;
		this.emplrNewTrsGross = emplrNewTrsGross;
		this.emplrNewTrsPensnContrib = emplrNewTrsPensnContrib;
		this.emplrTrsCareContrib = emplrTrsCareContrib;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "trsMonth", column = @Column(name = "TRS_MONTH", nullable = false, length = 2)) })
	public BhrTrsDepositsId getId() {
		return this.id;
	}

	public void setId(BhrTrsDepositsId id) {
		this.id = id;
	}

	@Column(name = "TRS_GROSS", nullable = false, precision = 9)
	public BigDecimal getTrsGross() {
		return this.trsGross;
	}

	public void setTrsGross(BigDecimal trsGross) {
		this.trsGross = trsGross;
	}

	@Column(name = "TRS_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getTrsDeposit() {
		return this.trsDeposit;
	}

	public void setTrsDeposit(BigDecimal trsDeposit) {
		this.trsDeposit = trsDeposit;
	}

	@Column(name = "TRS_DEPOSIT_CARE", nullable = false, precision = 7)
	public BigDecimal getTrsDepositCare() {
		return this.trsDepositCare;
	}

	public void setTrsDepositCare(BigDecimal trsDepositCare) {
		this.trsDepositCare = trsDepositCare;
	}

	@Column(name = "TRS_DEPOSIT_INS", nullable = false, precision = 7)
	public BigDecimal getTrsDepositIns() {
		return this.trsDepositIns;
	}

	public void setTrsDepositIns(BigDecimal trsDepositIns) {
		this.trsDepositIns = trsDepositIns;
	}

	@Column(name = "TRS_FEE", nullable = false, precision = 5)
	public BigDecimal getTrsFee() {
		return this.trsFee;
	}

	public void setTrsFee(BigDecimal trsFee) {
		this.trsFee = trsFee;
	}

	@Column(name = "MON_SUPPL_SALARY", nullable = false, precision = 9)
	public BigDecimal getMonSupplSalary() {
		return this.monSupplSalary;
	}

	public void setMonSupplSalary(BigDecimal monSupplSalary) {
		this.monSupplSalary = monSupplSalary;
	}

	@Column(name = "MON_ST_MIN_SALARY", nullable = false, precision = 9)
	public BigDecimal getMonStMinSalary() {
		return this.monStMinSalary;
	}

	public void setMonStMinSalary(BigDecimal monStMinSalary) {
		this.monStMinSalary = monStMinSalary;
	}

	@Column(name = "MON_WHOLLY_SEP_SALARY", nullable = false, precision = 9)
	public BigDecimal getMonWhollySepSalary() {
		return this.monWhollySepSalary;
	}

	public void setMonWhollySepSalary(BigDecimal monWhollySepSalary) {
		this.monWhollySepSalary = monWhollySepSalary;
	}

	@Column(name = "MON_TRS_DOCK", nullable = false, precision = 7)
	public BigDecimal getMonTrsDock() {
		return this.monTrsDock;
	}

	public void setMonTrsDock(BigDecimal monTrsDock) {
		this.monTrsDock = monTrsDock;
	}

	@Column(name = "PERFOR_PAY_GROSS", nullable = false, precision = 9)
	public BigDecimal getPerforPayGross() {
		return this.perforPayGross;
	}

	public void setPerforPayGross(BigDecimal perforPayGross) {
		this.perforPayGross = perforPayGross;
	}

	@Column(name = "PERFOR_PAY_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getPerforPayDeposit() {
		return this.perforPayDeposit;
	}

	public void setPerforPayDeposit(BigDecimal perforPayDeposit) {
		this.perforPayDeposit = perforPayDeposit;
	}

	@Column(name = "PERFOR_PAY_INS", nullable = false, precision = 7)
	public BigDecimal getPerforPayIns() {
		return this.perforPayIns;
	}

	public void setPerforPayIns(BigDecimal perforPayIns) {
		this.perforPayIns = perforPayIns;
	}

	@Column(name = "EMPLR_NEW_TRS_GROSS", nullable = false, precision = 9)
	public BigDecimal getEmplrNewTrsGross() {
		return this.emplrNewTrsGross;
	}

	public void setEmplrNewTrsGross(BigDecimal emplrNewTrsGross) {
		this.emplrNewTrsGross = emplrNewTrsGross;
	}

	@Column(name = "EMPLR_NEW_TRS_PENSN_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getEmplrNewTrsPensnContrib() {
		return this.emplrNewTrsPensnContrib;
	}

	public void setEmplrNewTrsPensnContrib(BigDecimal emplrNewTrsPensnContrib) {
		this.emplrNewTrsPensnContrib = emplrNewTrsPensnContrib;
	}

	@Column(name = "EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getEmplrTrsCareContrib() {
		return this.emplrTrsCareContrib;
	}

	public void setEmplrTrsCareContrib(BigDecimal emplrTrsCareContrib) {
		this.emplrTrsCareContrib = emplrTrsCareContrib;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
