package com.esc20.model;
// Generated Jan 4, 2019 3:47:38 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTeamEr25 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TEAM_ER25", schema = "rsccc", catalog = "rsccc")
public class BhrTeamEr25 implements java.io.Serializable {

	private BhrTeamEr25Id id;
	private String trsPosCd;
	private char retEmplmntTypCd;
	private short actHrsWrked;
	private byte daysWrked;
	private char zeroDaysRsnCd;
	private BigDecimal grosPayTot;
	private BigDecimal emplrRetPensnSurchg;
	private BigDecimal emplrTrsCareSurchg;
	private String contrDtBegin;
	private String contrDtEnd;
	private char thrdPartyPay;
	private String module;

	public BhrTeamEr25() {
	}

	public BhrTeamEr25(BhrTeamEr25Id id, String trsPosCd, char retEmplmntTypCd, short actHrsWrked, byte daysWrked,
			char zeroDaysRsnCd, BigDecimal grosPayTot, BigDecimal emplrRetPensnSurchg, BigDecimal emplrTrsCareSurchg,
			String contrDtBegin, String contrDtEnd, char thrdPartyPay, String module) {
		this.id = id;
		this.trsPosCd = trsPosCd;
		this.retEmplmntTypCd = retEmplmntTypCd;
		this.actHrsWrked = actHrsWrked;
		this.daysWrked = daysWrked;
		this.zeroDaysRsnCd = zeroDaysRsnCd;
		this.grosPayTot = grosPayTot;
		this.emplrRetPensnSurchg = emplrRetPensnSurchg;
		this.emplrTrsCareSurchg = emplrTrsCareSurchg;
		this.contrDtBegin = contrDtBegin;
		this.contrDtEnd = contrDtEnd;
		this.thrdPartyPay = thrdPartyPay;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "adjRptYr", column = @Column(name = "ADJ_RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "adjRptMon", column = @Column(name = "ADJ_RPT_MON", nullable = false, length = 2)) })
	public BhrTeamEr25Id getId() {
		return this.id;
	}

	public void setId(BhrTeamEr25Id id) {
		this.id = id;
	}

	@Column(name = "TRS_POS_CD", nullable = false, length = 2)
	public String getTrsPosCd() {
		return this.trsPosCd;
	}

	public void setTrsPosCd(String trsPosCd) {
		this.trsPosCd = trsPosCd;
	}

	@Column(name = "RET_EMPLMNT_TYP_CD", nullable = false, length = 1)
	public char getRetEmplmntTypCd() {
		return this.retEmplmntTypCd;
	}

	public void setRetEmplmntTypCd(char retEmplmntTypCd) {
		this.retEmplmntTypCd = retEmplmntTypCd;
	}

	@Column(name = "ACT_HRS_WRKED", nullable = false, precision = 3, scale = 0)
	public short getActHrsWrked() {
		return this.actHrsWrked;
	}

	public void setActHrsWrked(short actHrsWrked) {
		this.actHrsWrked = actHrsWrked;
	}

	@Column(name = "DAYS_WRKED", nullable = false, precision = 2, scale = 0)
	public byte getDaysWrked() {
		return this.daysWrked;
	}

	public void setDaysWrked(byte daysWrked) {
		this.daysWrked = daysWrked;
	}

	@Column(name = "ZERO_DAYS_RSN_CD", nullable = false, length = 1)
	public char getZeroDaysRsnCd() {
		return this.zeroDaysRsnCd;
	}

	public void setZeroDaysRsnCd(char zeroDaysRsnCd) {
		this.zeroDaysRsnCd = zeroDaysRsnCd;
	}

	@Column(name = "GROS_PAY_TOT", nullable = false, precision = 9)
	public BigDecimal getGrosPayTot() {
		return this.grosPayTot;
	}

	public void setGrosPayTot(BigDecimal grosPayTot) {
		this.grosPayTot = grosPayTot;
	}

	@Column(name = "EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getEmplrRetPensnSurchg() {
		return this.emplrRetPensnSurchg;
	}

	public void setEmplrRetPensnSurchg(BigDecimal emplrRetPensnSurchg) {
		this.emplrRetPensnSurchg = emplrRetPensnSurchg;
	}

	@Column(name = "EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getEmplrTrsCareSurchg() {
		return this.emplrTrsCareSurchg;
	}

	public void setEmplrTrsCareSurchg(BigDecimal emplrTrsCareSurchg) {
		this.emplrTrsCareSurchg = emplrTrsCareSurchg;
	}

	@Column(name = "CONTR_DT_BEGIN", nullable = false, length = 8)
	public String getContrDtBegin() {
		return this.contrDtBegin;
	}

	public void setContrDtBegin(String contrDtBegin) {
		this.contrDtBegin = contrDtBegin;
	}

	@Column(name = "CONTR_DT_END", nullable = false, length = 8)
	public String getContrDtEnd() {
		return this.contrDtEnd;
	}

	public void setContrDtEnd(String contrDtEnd) {
		this.contrDtEnd = contrDtEnd;
	}

	@Column(name = "THRD_PARTY_PAY", nullable = false, length = 1)
	public char getThrdPartyPay() {
		return this.thrdPartyPay;
	}

	public void setThrdPartyPay(char thrdPartyPay) {
		this.thrdPartyPay = thrdPartyPay;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
