package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTrsGrants generated by hbm2java
 */
@Entity
@Table(name = "BHR_TRS_GRANTS", schema = "rsccc", catalog = "rsccc")
public class BhrTrsGrants implements java.io.Serializable {

	private BhrTrsGrantsId id;
	private BigDecimal trsGrantGross;
	private BigDecimal trsGrantDeposit;
	private BigDecimal trsGrantCare;
	private BigDecimal trsGrantIns;
	private BigDecimal emplrNewTrsGross;

	public BhrTrsGrants() {
	}

	public BhrTrsGrants(BhrTrsGrantsId id, BigDecimal trsGrantGross, BigDecimal trsGrantDeposit,
			BigDecimal trsGrantCare, BigDecimal trsGrantIns, BigDecimal emplrNewTrsGross) {
		this.id = id;
		this.trsGrantGross = trsGrantGross;
		this.trsGrantDeposit = trsGrantDeposit;
		this.trsGrantCare = trsGrantCare;
		this.trsGrantIns = trsGrantIns;
		this.emplrNewTrsGross = emplrNewTrsGross;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "trsMonth", column = @Column(name = "TRS_MONTH", nullable = false, length = 2)),
			@AttributeOverride(name = "trsGrantCd", column = @Column(name = "TRS_GRANT_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "fromChildNutr", column = @Column(name = "FROM_CHILD_NUTR", nullable = false, length = 1)) })
	public BhrTrsGrantsId getId() {
		return this.id;
	}

	public void setId(BhrTrsGrantsId id) {
		this.id = id;
	}

	@Column(name = "TRS_GRANT_GROSS", nullable = false, precision = 9)
	public BigDecimal getTrsGrantGross() {
		return this.trsGrantGross;
	}

	public void setTrsGrantGross(BigDecimal trsGrantGross) {
		this.trsGrantGross = trsGrantGross;
	}

	@Column(name = "TRS_GRANT_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getTrsGrantDeposit() {
		return this.trsGrantDeposit;
	}

	public void setTrsGrantDeposit(BigDecimal trsGrantDeposit) {
		this.trsGrantDeposit = trsGrantDeposit;
	}

	@Column(name = "TRS_GRANT_CARE", nullable = false, precision = 7)
	public BigDecimal getTrsGrantCare() {
		return this.trsGrantCare;
	}

	public void setTrsGrantCare(BigDecimal trsGrantCare) {
		this.trsGrantCare = trsGrantCare;
	}

	@Column(name = "TRS_GRANT_INS", nullable = false, precision = 7)
	public BigDecimal getTrsGrantIns() {
		return this.trsGrantIns;
	}

	public void setTrsGrantIns(BigDecimal trsGrantIns) {
		this.trsGrantIns = trsGrantIns;
	}

	@Column(name = "EMPLR_NEW_TRS_GROSS", nullable = false, precision = 9)
	public BigDecimal getEmplrNewTrsGross() {
		return this.emplrNewTrsGross;
	}

	public void setEmplrNewTrsGross(BigDecimal emplrNewTrsGross) {
		this.emplrNewTrsGross = emplrNewTrsGross;
	}

}
