package com.esc20.model;
// Generated Jan 4, 2019 3:47:38 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTeamRp25 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TEAM_RP25", schema = "rsccc", catalog = "rsccc")
public class BhrTeamRp25 implements java.io.Serializable {

	private BhrTeamRp25Id id;
	private short netDiffActHrsWrked;
	private byte netDiffHrsSched;
	private byte netDiffDaysWrked;
	private char zeroDaysRsnCd;
	private BigDecimal netDiffTrsGros;
	private BigDecimal netDiffPerforPayGros;
	private BigDecimal netDiffGrosPayTot;
	private BigDecimal netDiffTrsSalRed;
	private BigDecimal netDiffTrsCare;
	private BigDecimal netDiffEmplrTrsCareContrib;
	private BigDecimal netDiffSpecSvcDedAmt;
	private char specSvcShelt;
	private BigDecimal netDiffTrsGrantGros;
	private BigDecimal netDiffTrsGrantDpst;
	private BigDecimal netDiffTrsGrantCare;
	private BigDecimal netDiffEmplrNewTrsPensnContrib;
	private BigDecimal netDiffEmplrTrsNonOasdiContrib;
	private BigDecimal netDiffAdjStMin;
	private BigDecimal netDiffDistContribAboveSt;
	private String module;

	public BhrTeamRp25() {
	}

	public BhrTeamRp25(BhrTeamRp25Id id, short netDiffActHrsWrked, byte netDiffHrsSched, byte netDiffDaysWrked,
			char zeroDaysRsnCd, BigDecimal netDiffTrsGros, BigDecimal netDiffPerforPayGros,
			BigDecimal netDiffGrosPayTot, BigDecimal netDiffTrsSalRed, BigDecimal netDiffTrsCare,
			BigDecimal netDiffEmplrTrsCareContrib, BigDecimal netDiffSpecSvcDedAmt, char specSvcShelt,
			BigDecimal netDiffTrsGrantGros, BigDecimal netDiffTrsGrantDpst, BigDecimal netDiffTrsGrantCare,
			BigDecimal netDiffEmplrNewTrsPensnContrib, BigDecimal netDiffEmplrTrsNonOasdiContrib,
			BigDecimal netDiffAdjStMin, BigDecimal netDiffDistContribAboveSt, String module) {
		this.id = id;
		this.netDiffActHrsWrked = netDiffActHrsWrked;
		this.netDiffHrsSched = netDiffHrsSched;
		this.netDiffDaysWrked = netDiffDaysWrked;
		this.zeroDaysRsnCd = zeroDaysRsnCd;
		this.netDiffTrsGros = netDiffTrsGros;
		this.netDiffPerforPayGros = netDiffPerforPayGros;
		this.netDiffGrosPayTot = netDiffGrosPayTot;
		this.netDiffTrsSalRed = netDiffTrsSalRed;
		this.netDiffTrsCare = netDiffTrsCare;
		this.netDiffEmplrTrsCareContrib = netDiffEmplrTrsCareContrib;
		this.netDiffSpecSvcDedAmt = netDiffSpecSvcDedAmt;
		this.specSvcShelt = specSvcShelt;
		this.netDiffTrsGrantGros = netDiffTrsGrantGros;
		this.netDiffTrsGrantDpst = netDiffTrsGrantDpst;
		this.netDiffTrsGrantCare = netDiffTrsGrantCare;
		this.netDiffEmplrNewTrsPensnContrib = netDiffEmplrNewTrsPensnContrib;
		this.netDiffEmplrTrsNonOasdiContrib = netDiffEmplrTrsNonOasdiContrib;
		this.netDiffAdjStMin = netDiffAdjStMin;
		this.netDiffDistContribAboveSt = netDiffDistContribAboveSt;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "trsPosCd", column = @Column(name = "TRS_POS_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "adjRptYr", column = @Column(name = "ADJ_RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "adjRptMon", column = @Column(name = "ADJ_RPT_MON", nullable = false, length = 2)) })
	public BhrTeamRp25Id getId() {
		return this.id;
	}

	public void setId(BhrTeamRp25Id id) {
		this.id = id;
	}

	@Column(name = "NET_DIFF_ACT_HRS_WRKED", nullable = false, precision = 3, scale = 0)
	public short getNetDiffActHrsWrked() {
		return this.netDiffActHrsWrked;
	}

	public void setNetDiffActHrsWrked(short netDiffActHrsWrked) {
		this.netDiffActHrsWrked = netDiffActHrsWrked;
	}

	@Column(name = "NET_DIFF_HRS_SCHED", nullable = false, precision = 2, scale = 0)
	public byte getNetDiffHrsSched() {
		return this.netDiffHrsSched;
	}

	public void setNetDiffHrsSched(byte netDiffHrsSched) {
		this.netDiffHrsSched = netDiffHrsSched;
	}

	@Column(name = "NET_DIFF_DAYS_WRKED", nullable = false, precision = 2, scale = 0)
	public byte getNetDiffDaysWrked() {
		return this.netDiffDaysWrked;
	}

	public void setNetDiffDaysWrked(byte netDiffDaysWrked) {
		this.netDiffDaysWrked = netDiffDaysWrked;
	}

	@Column(name = "ZERO_DAYS_RSN_CD", nullable = false, length = 1)
	public char getZeroDaysRsnCd() {
		return this.zeroDaysRsnCd;
	}

	public void setZeroDaysRsnCd(char zeroDaysRsnCd) {
		this.zeroDaysRsnCd = zeroDaysRsnCd;
	}

	@Column(name = "NET_DIFF_TRS_GROS", nullable = false, precision = 9)
	public BigDecimal getNetDiffTrsGros() {
		return this.netDiffTrsGros;
	}

	public void setNetDiffTrsGros(BigDecimal netDiffTrsGros) {
		this.netDiffTrsGros = netDiffTrsGros;
	}

	@Column(name = "NET_DIFF_PERFOR_PAY_GROS", nullable = false, precision = 9)
	public BigDecimal getNetDiffPerforPayGros() {
		return this.netDiffPerforPayGros;
	}

	public void setNetDiffPerforPayGros(BigDecimal netDiffPerforPayGros) {
		this.netDiffPerforPayGros = netDiffPerforPayGros;
	}

	@Column(name = "NET_DIFF_GROS_PAY_TOT", nullable = false, precision = 9)
	public BigDecimal getNetDiffGrosPayTot() {
		return this.netDiffGrosPayTot;
	}

	public void setNetDiffGrosPayTot(BigDecimal netDiffGrosPayTot) {
		this.netDiffGrosPayTot = netDiffGrosPayTot;
	}

	@Column(name = "NET_DIFF_TRS_SAL_RED", nullable = false, precision = 9)
	public BigDecimal getNetDiffTrsSalRed() {
		return this.netDiffTrsSalRed;
	}

	public void setNetDiffTrsSalRed(BigDecimal netDiffTrsSalRed) {
		this.netDiffTrsSalRed = netDiffTrsSalRed;
	}

	@Column(name = "NET_DIFF_TRS_CARE", nullable = false, precision = 7)
	public BigDecimal getNetDiffTrsCare() {
		return this.netDiffTrsCare;
	}

	public void setNetDiffTrsCare(BigDecimal netDiffTrsCare) {
		this.netDiffTrsCare = netDiffTrsCare;
	}

	@Column(name = "NET_DIFF_EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getNetDiffEmplrTrsCareContrib() {
		return this.netDiffEmplrTrsCareContrib;
	}

	public void setNetDiffEmplrTrsCareContrib(BigDecimal netDiffEmplrTrsCareContrib) {
		this.netDiffEmplrTrsCareContrib = netDiffEmplrTrsCareContrib;
	}

	@Column(name = "NET_DIFF_SPEC_SVC_DED_AMT", nullable = false, precision = 9)
	public BigDecimal getNetDiffSpecSvcDedAmt() {
		return this.netDiffSpecSvcDedAmt;
	}

	public void setNetDiffSpecSvcDedAmt(BigDecimal netDiffSpecSvcDedAmt) {
		this.netDiffSpecSvcDedAmt = netDiffSpecSvcDedAmt;
	}

	@Column(name = "SPEC_SVC_SHELT", nullable = false, length = 1)
	public char getSpecSvcShelt() {
		return this.specSvcShelt;
	}

	public void setSpecSvcShelt(char specSvcShelt) {
		this.specSvcShelt = specSvcShelt;
	}

	@Column(name = "NET_DIFF_TRS_GRANT_GROS", nullable = false, precision = 9)
	public BigDecimal getNetDiffTrsGrantGros() {
		return this.netDiffTrsGrantGros;
	}

	public void setNetDiffTrsGrantGros(BigDecimal netDiffTrsGrantGros) {
		this.netDiffTrsGrantGros = netDiffTrsGrantGros;
	}

	@Column(name = "NET_DIFF_TRS_GRANT_DPST", nullable = false, precision = 9)
	public BigDecimal getNetDiffTrsGrantDpst() {
		return this.netDiffTrsGrantDpst;
	}

	public void setNetDiffTrsGrantDpst(BigDecimal netDiffTrsGrantDpst) {
		this.netDiffTrsGrantDpst = netDiffTrsGrantDpst;
	}

	@Column(name = "NET_DIFF_TRS_GRANT_CARE", nullable = false, precision = 9)
	public BigDecimal getNetDiffTrsGrantCare() {
		return this.netDiffTrsGrantCare;
	}

	public void setNetDiffTrsGrantCare(BigDecimal netDiffTrsGrantCare) {
		this.netDiffTrsGrantCare = netDiffTrsGrantCare;
	}

	@Column(name = "NET_DIFF_EMPLR_NEW_TRS_PENSN_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getNetDiffEmplrNewTrsPensnContrib() {
		return this.netDiffEmplrNewTrsPensnContrib;
	}

	public void setNetDiffEmplrNewTrsPensnContrib(BigDecimal netDiffEmplrNewTrsPensnContrib) {
		this.netDiffEmplrNewTrsPensnContrib = netDiffEmplrNewTrsPensnContrib;
	}

	@Column(name = "NET_DIFF_EMPLR_TRS_NON_OASDI_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getNetDiffEmplrTrsNonOasdiContrib() {
		return this.netDiffEmplrTrsNonOasdiContrib;
	}

	public void setNetDiffEmplrTrsNonOasdiContrib(BigDecimal netDiffEmplrTrsNonOasdiContrib) {
		this.netDiffEmplrTrsNonOasdiContrib = netDiffEmplrTrsNonOasdiContrib;
	}

	@Column(name = "NET_DIFF_ADJ_ST_MIN", nullable = false, precision = 9)
	public BigDecimal getNetDiffAdjStMin() {
		return this.netDiffAdjStMin;
	}

	public void setNetDiffAdjStMin(BigDecimal netDiffAdjStMin) {
		this.netDiffAdjStMin = netDiffAdjStMin;
	}

	@Column(name = "NET_DIFF_DIST_CONTRIB_ABOVE_ST", nullable = false, precision = 9)
	public BigDecimal getNetDiffDistContribAboveSt() {
		return this.netDiffDistContribAboveSt;
	}

	public void setNetDiffDistContribAboveSt(BigDecimal netDiffDistContribAboveSt) {
		this.netDiffDistContribAboveSt = netDiffDistContribAboveSt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
