package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTransferTransBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TRANSFER_TRANS_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrTransferTransBkupPaycalcs5 implements java.io.Serializable {

	private BhrTransferTransBkupPaycalcs5Id id;

	public BhrTransferTransBkupPaycalcs5() {
	}

	public BhrTransferTransBkupPaycalcs5(BhrTransferTransBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "dts", column = @Column(name = "DTS", nullable = false, length = 16)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "dedCd", column = @Column(name = "DED_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "dedAmt", column = @Column(name = "DED_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "vendorNbr", column = @Column(name = "VENDOR_NBR", nullable = false, length = 5)),
			@AttributeOverride(name = "glFileId", column = @Column(name = "GL_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "fund", column = @Column(name = "FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "func", column = @Column(name = "FUNC", nullable = false, length = 2)),
			@AttributeOverride(name = "obj", column = @Column(name = "OBJ", nullable = false, length = 4)),
			@AttributeOverride(name = "sobj", column = @Column(name = "SOBJ", nullable = false, length = 2)),
			@AttributeOverride(name = "org", column = @Column(name = "ORG", nullable = false, length = 3)),
			@AttributeOverride(name = "fsclYr", column = @Column(name = "FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "pgm", column = @Column(name = "PGM", nullable = false, length = 2)),
			@AttributeOverride(name = "edSpan", column = @Column(name = "ED_SPAN", nullable = false, length = 1)),
			@AttributeOverride(name = "projDtl", column = @Column(name = "PROJ_DTL", nullable = false, length = 2)),
			@AttributeOverride(name = "indivSumFlg", column = @Column(name = "INDIV_SUM_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "caseNbr", column = @Column(name = "CASE_NBR", nullable = false, length = 20)),
			@AttributeOverride(name = "causeNbr", column = @Column(name = "CAUSE_NBR", nullable = false, length = 12)),
			@AttributeOverride(name = "liabTyp", column = @Column(name = "LIAB_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "checkDt", column = @Column(name = "CHECK_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "checkType", column = @Column(name = "CHECK_TYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 12)),
			@AttributeOverride(name = "chkCleared", column = @Column(name = "CHK_CLEARED", nullable = false, length = 1)),
			@AttributeOverride(name = "reconDts", column = @Column(name = "RECON_DTS", nullable = false, length = 16)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BhrTransferTransBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrTransferTransBkupPaycalcs5Id id) {
		this.id = id;
	}

}
