package com.esc20.model;
// Generated Jan 4, 2019 3:47:38 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTeamEd40 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TEAM_ED40", schema = "rsccc", catalog = "rsccc")
public class BhrTeamEd40 implements java.io.Serializable {

	private BhrTeamEd40Id id;
	private char eligFlg;
	private char ersRetHlthElig;
	private String emplmntStrtDt;
	private String contrDtBegin;
	private String contrDtEnd;
	private byte fteHrs;
	private char emplmntTypCd;
	private char emplrPaysFica;
	private char payUnit;
	private BigDecimal hrlyPayRate;
	private char nonStdWrkWk;
	private String module;

	public BhrTeamEd40() {
	}

	public BhrTeamEd40(BhrTeamEd40Id id, char eligFlg, char ersRetHlthElig, String emplmntStrtDt, String contrDtBegin,
			String contrDtEnd, byte fteHrs, char emplmntTypCd, char emplrPaysFica, char payUnit, BigDecimal hrlyPayRate,
			char nonStdWrkWk, String module) {
		this.id = id;
		this.eligFlg = eligFlg;
		this.ersRetHlthElig = ersRetHlthElig;
		this.emplmntStrtDt = emplmntStrtDt;
		this.contrDtBegin = contrDtBegin;
		this.contrDtEnd = contrDtEnd;
		this.fteHrs = fteHrs;
		this.emplmntTypCd = emplmntTypCd;
		this.emplrPaysFica = emplrPaysFica;
		this.payUnit = payUnit;
		this.hrlyPayRate = hrlyPayRate;
		this.nonStdWrkWk = nonStdWrkWk;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "trsPosCd", column = @Column(name = "TRS_POS_CD", nullable = false, length = 2)) })
	public BhrTeamEd40Id getId() {
		return this.id;
	}

	public void setId(BhrTeamEd40Id id) {
		this.id = id;
	}

	@Column(name = "ELIG_FLG", nullable = false, length = 1)
	public char getEligFlg() {
		return this.eligFlg;
	}

	public void setEligFlg(char eligFlg) {
		this.eligFlg = eligFlg;
	}

	@Column(name = "ERS_RET_HLTH_ELIG", nullable = false, length = 1)
	public char getErsRetHlthElig() {
		return this.ersRetHlthElig;
	}

	public void setErsRetHlthElig(char ersRetHlthElig) {
		this.ersRetHlthElig = ersRetHlthElig;
	}

	@Column(name = "EMPLMNT_STRT_DT", nullable = false, length = 8)
	public String getEmplmntStrtDt() {
		return this.emplmntStrtDt;
	}

	public void setEmplmntStrtDt(String emplmntStrtDt) {
		this.emplmntStrtDt = emplmntStrtDt;
	}

	@Column(name = "CONTR_DT_BEGIN", nullable = false, length = 8)
	public String getContrDtBegin() {
		return this.contrDtBegin;
	}

	public void setContrDtBegin(String contrDtBegin) {
		this.contrDtBegin = contrDtBegin;
	}

	@Column(name = "CONTR_DT_END", nullable = false, length = 8)
	public String getContrDtEnd() {
		return this.contrDtEnd;
	}

	public void setContrDtEnd(String contrDtEnd) {
		this.contrDtEnd = contrDtEnd;
	}

	@Column(name = "FTE_HRS", nullable = false, precision = 2, scale = 0)
	public byte getFteHrs() {
		return this.fteHrs;
	}

	public void setFteHrs(byte fteHrs) {
		this.fteHrs = fteHrs;
	}

	@Column(name = "EMPLMNT_TYP_CD", nullable = false, length = 1)
	public char getEmplmntTypCd() {
		return this.emplmntTypCd;
	}

	public void setEmplmntTypCd(char emplmntTypCd) {
		this.emplmntTypCd = emplmntTypCd;
	}

	@Column(name = "EMPLR_PAYS_FICA", nullable = false, length = 1)
	public char getEmplrPaysFica() {
		return this.emplrPaysFica;
	}

	public void setEmplrPaysFica(char emplrPaysFica) {
		this.emplrPaysFica = emplrPaysFica;
	}

	@Column(name = "PAY_UNIT", nullable = false, length = 1)
	public char getPayUnit() {
		return this.payUnit;
	}

	public void setPayUnit(char payUnit) {
		this.payUnit = payUnit;
	}

	@Column(name = "HRLY_PAY_RATE", nullable = false, precision = 5)
	public BigDecimal getHrlyPayRate() {
		return this.hrlyPayRate;
	}

	public void setHrlyPayRate(BigDecimal hrlyPayRate) {
		this.hrlyPayRate = hrlyPayRate;
	}

	@Column(name = "NON_STD_WRK_WK", nullable = false, length = 1)
	public char getNonStdWrkWk() {
		return this.nonStdWrkWk;
	}

	public void setNonStdWrkWk(char nonStdWrkWk) {
		this.nonStdWrkWk = nonStdWrkWk;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
