package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTrsMd30Md31 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TRS_MD30_MD31", schema = "rsccc", catalog = "rsccc")
public class BhrTrsMd30Md31 implements java.io.Serializable {

	private BhrTrsMd30Md31Id id;
	private String addrNbr;
	private String addrStr;
	private String addrApt;
	private String addrCity;
	private String addrSt;
	private String addrZip;
	private String addrZip4;
	private String phoneArea;
	private String phoneNbr;
	private String supplAddr;
	private String supplCntry;
	private String supplDelivName;
	private String module;

	public BhrTrsMd30Md31() {
	}

	public BhrTrsMd30Md31(BhrTrsMd30Md31Id id, String addrNbr, String addrStr, String addrApt, String addrCity,
			String addrSt, String addrZip, String addrZip4, String phoneArea, String phoneNbr, String supplAddr,
			String supplCntry, String supplDelivName, String module) {
		this.id = id;
		this.addrNbr = addrNbr;
		this.addrStr = addrStr;
		this.addrApt = addrApt;
		this.addrCity = addrCity;
		this.addrSt = addrSt;
		this.addrZip = addrZip;
		this.addrZip4 = addrZip4;
		this.phoneArea = phoneArea;
		this.phoneNbr = phoneNbr;
		this.supplAddr = supplAddr;
		this.supplCntry = supplCntry;
		this.supplDelivName = supplDelivName;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "staffId", column = @Column(name = "STAFF_ID", nullable = false, length = 9)) })
	public BhrTrsMd30Md31Id getId() {
		return this.id;
	}

	public void setId(BhrTrsMd30Md31Id id) {
		this.id = id;
	}

	@Column(name = "ADDR_NBR", nullable = false, length = 10)
	public String getAddrNbr() {
		return this.addrNbr;
	}

	public void setAddrNbr(String addrNbr) {
		this.addrNbr = addrNbr;
	}

	@Column(name = "ADDR_STR", nullable = false, length = 30)
	public String getAddrStr() {
		return this.addrStr;
	}

	public void setAddrStr(String addrStr) {
		this.addrStr = addrStr;
	}

	@Column(name = "ADDR_APT", nullable = false, length = 7)
	public String getAddrApt() {
		return this.addrApt;
	}

	public void setAddrApt(String addrApt) {
		this.addrApt = addrApt;
	}

	@Column(name = "ADDR_CITY", nullable = false, length = 25)
	public String getAddrCity() {
		return this.addrCity;
	}

	public void setAddrCity(String addrCity) {
		this.addrCity = addrCity;
	}

	@Column(name = "ADDR_ST", nullable = false, length = 2)
	public String getAddrSt() {
		return this.addrSt;
	}

	public void setAddrSt(String addrSt) {
		this.addrSt = addrSt;
	}

	@Column(name = "ADDR_ZIP", nullable = false, length = 5)
	public String getAddrZip() {
		return this.addrZip;
	}

	public void setAddrZip(String addrZip) {
		this.addrZip = addrZip;
	}

	@Column(name = "ADDR_ZIP4", nullable = false, length = 4)
	public String getAddrZip4() {
		return this.addrZip4;
	}

	public void setAddrZip4(String addrZip4) {
		this.addrZip4 = addrZip4;
	}

	@Column(name = "PHONE_AREA", nullable = false, length = 3)
	public String getPhoneArea() {
		return this.phoneArea;
	}

	public void setPhoneArea(String phoneArea) {
		this.phoneArea = phoneArea;
	}

	@Column(name = "PHONE_NBR", nullable = false, length = 7)
	public String getPhoneNbr() {
		return this.phoneNbr;
	}

	public void setPhoneNbr(String phoneNbr) {
		this.phoneNbr = phoneNbr;
	}

	@Column(name = "SUPPL_ADDR", nullable = false, length = 40)
	public String getSupplAddr() {
		return this.supplAddr;
	}

	public void setSupplAddr(String supplAddr) {
		this.supplAddr = supplAddr;
	}

	@Column(name = "SUPPL_CNTRY", nullable = false, length = 40)
	public String getSupplCntry() {
		return this.supplCntry;
	}

	public void setSupplCntry(String supplCntry) {
		this.supplCntry = supplCntry;
	}

	@Column(name = "SUPPL_DELIV_NAME", nullable = false, length = 40)
	public String getSupplDelivName() {
		return this.supplDelivName;
	}

	public void setSupplDelivName(String supplDelivName) {
		this.supplDelivName = supplDelivName;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
