package com.esc20.model;
// Generated Jan 4, 2019 3:47:38 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTeamEd20 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TEAM_ED20", schema = "rsccc", catalog = "rsccc")
public class BhrTeamEd20 implements java.io.Serializable {

	private BhrTeamEd20Id id;
	private String staffId;
	private String dob;
	private char sex;
	private String nameL;
	private String nameF;
	private String nameM;
	private char nameGen;
	private String addrNbr;
	private String addrStr;
	private String addrApt;
	private String addrCity;
	private String addrSt;
	private String addrZip;
	private String addrZip4;
	private String addrProvince;
	private String addrCtry;
	private String postalCd;
	private String email;
	private String phoneArea;
	private String phoneNbr;
	private String module;

	public BhrTeamEd20() {
	}

	public BhrTeamEd20(BhrTeamEd20Id id, String staffId, String dob, char sex, String nameL, String nameF, String nameM,
			char nameGen, String addrNbr, String addrStr, String addrApt, String addrCity, String addrSt,
			String addrZip, String addrZip4, String addrProvince, String addrCtry, String postalCd, String email,
			String phoneArea, String phoneNbr, String module) {
		this.id = id;
		this.staffId = staffId;
		this.dob = dob;
		this.sex = sex;
		this.nameL = nameL;
		this.nameF = nameF;
		this.nameM = nameM;
		this.nameGen = nameGen;
		this.addrNbr = addrNbr;
		this.addrStr = addrStr;
		this.addrApt = addrApt;
		this.addrCity = addrCity;
		this.addrSt = addrSt;
		this.addrZip = addrZip;
		this.addrZip4 = addrZip4;
		this.addrProvince = addrProvince;
		this.addrCtry = addrCtry;
		this.postalCd = postalCd;
		this.email = email;
		this.phoneArea = phoneArea;
		this.phoneNbr = phoneNbr;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)) })
	public BhrTeamEd20Id getId() {
		return this.id;
	}

	public void setId(BhrTeamEd20Id id) {
		this.id = id;
	}

	@Column(name = "STAFF_ID", nullable = false, length = 9)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "DOB", nullable = false, length = 8)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "SEX", nullable = false, length = 1)
	public char getSex() {
		return this.sex;
	}

	public void setSex(char sex) {
		this.sex = sex;
	}

	@Column(name = "NAME_L", nullable = false, length = 30)
	public String getNameL() {
		return this.nameL;
	}

	public void setNameL(String nameL) {
		this.nameL = nameL;
	}

	@Column(name = "NAME_F", nullable = false, length = 25)
	public String getNameF() {
		return this.nameF;
	}

	public void setNameF(String nameF) {
		this.nameF = nameF;
	}

	@Column(name = "NAME_M", nullable = false, length = 25)
	public String getNameM() {
		return this.nameM;
	}

	public void setNameM(String nameM) {
		this.nameM = nameM;
	}

	@Column(name = "NAME_GEN", nullable = false, length = 1)
	public char getNameGen() {
		return this.nameGen;
	}

	public void setNameGen(char nameGen) {
		this.nameGen = nameGen;
	}

	@Column(name = "ADDR_NBR", nullable = false, length = 10)
	public String getAddrNbr() {
		return this.addrNbr;
	}

	public void setAddrNbr(String addrNbr) {
		this.addrNbr = addrNbr;
	}

	@Column(name = "ADDR_STR", nullable = false, length = 39)
	public String getAddrStr() {
		return this.addrStr;
	}

	public void setAddrStr(String addrStr) {
		this.addrStr = addrStr;
	}

	@Column(name = "ADDR_APT", nullable = false, length = 50)
	public String getAddrApt() {
		return this.addrApt;
	}

	public void setAddrApt(String addrApt) {
		this.addrApt = addrApt;
	}

	@Column(name = "ADDR_CITY", nullable = false, length = 20)
	public String getAddrCity() {
		return this.addrCity;
	}

	public void setAddrCity(String addrCity) {
		this.addrCity = addrCity;
	}

	@Column(name = "ADDR_ST", nullable = false, length = 2)
	public String getAddrSt() {
		return this.addrSt;
	}

	public void setAddrSt(String addrSt) {
		this.addrSt = addrSt;
	}

	@Column(name = "ADDR_ZIP", nullable = false, length = 5)
	public String getAddrZip() {
		return this.addrZip;
	}

	public void setAddrZip(String addrZip) {
		this.addrZip = addrZip;
	}

	@Column(name = "ADDR_ZIP4", nullable = false, length = 4)
	public String getAddrZip4() {
		return this.addrZip4;
	}

	public void setAddrZip4(String addrZip4) {
		this.addrZip4 = addrZip4;
	}

	@Column(name = "ADDR_PROVINCE", nullable = false, length = 20)
	public String getAddrProvince() {
		return this.addrProvince;
	}

	public void setAddrProvince(String addrProvince) {
		this.addrProvince = addrProvince;
	}

	@Column(name = "ADDR_CTRY", nullable = false, length = 3)
	public String getAddrCtry() {
		return this.addrCtry;
	}

	public void setAddrCtry(String addrCtry) {
		this.addrCtry = addrCtry;
	}

	@Column(name = "POSTAL_CD", nullable = false, length = 10)
	public String getPostalCd() {
		return this.postalCd;
	}

	public void setPostalCd(String postalCd) {
		this.postalCd = postalCd;
	}

	@Column(name = "EMAIL", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONE_AREA", nullable = false, length = 3)
	public String getPhoneArea() {
		return this.phoneArea;
	}

	public void setPhoneArea(String phoneArea) {
		this.phoneArea = phoneArea;
	}

	@Column(name = "PHONE_NBR", nullable = false, length = 7)
	public String getPhoneNbr() {
		return this.phoneNbr;
	}

	public void setPhoneNbr(String phoneNbr) {
		this.phoneNbr = phoneNbr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
