package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTrsMd45 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TRS_MD45", schema = "rsccc", catalog = "rsccc")
public class BhrTrsMd45 implements java.io.Serializable {

	private BhrTrsMd45Id id;
	private char payUnit;
	private BigDecimal hourlyRate;
	private char yrRoundTeachFlg;
	private char contrNonStdFlg;
	private String contrDtBegin;
	private String contrDtEnd;
	private BigDecimal trsGrossJul;
	private BigDecimal trsGrossAug;
	private String nbrDaysEmpld;
	private short pctDaysEmpld;
	private char memPaysFica;
	private char adjRsnCd;
	private String origPosCd;
	private String trsEligDt;
	private String module;

	public BhrTrsMd45() {
	}

	public BhrTrsMd45(BhrTrsMd45Id id, char payUnit, BigDecimal hourlyRate, char yrRoundTeachFlg, char contrNonStdFlg,
			String contrDtBegin, String contrDtEnd, BigDecimal trsGrossJul, BigDecimal trsGrossAug, String nbrDaysEmpld,
			short pctDaysEmpld, char memPaysFica, char adjRsnCd, String origPosCd, String trsEligDt, String module) {
		this.id = id;
		this.payUnit = payUnit;
		this.hourlyRate = hourlyRate;
		this.yrRoundTeachFlg = yrRoundTeachFlg;
		this.contrNonStdFlg = contrNonStdFlg;
		this.contrDtBegin = contrDtBegin;
		this.contrDtEnd = contrDtEnd;
		this.trsGrossJul = trsGrossJul;
		this.trsGrossAug = trsGrossAug;
		this.nbrDaysEmpld = nbrDaysEmpld;
		this.pctDaysEmpld = pctDaysEmpld;
		this.memPaysFica = memPaysFica;
		this.adjRsnCd = adjRsnCd;
		this.origPosCd = origPosCd;
		this.trsEligDt = trsEligDt;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "staffId", column = @Column(name = "STAFF_ID", nullable = false, length = 9)),
			@AttributeOverride(name = "trsPosCd", column = @Column(name = "TRS_POS_CD", nullable = false, length = 2)) })
	public BhrTrsMd45Id getId() {
		return this.id;
	}

	public void setId(BhrTrsMd45Id id) {
		this.id = id;
	}

	@Column(name = "PAY_UNIT", nullable = false, length = 1)
	public char getPayUnit() {
		return this.payUnit;
	}

	public void setPayUnit(char payUnit) {
		this.payUnit = payUnit;
	}

	@Column(name = "HOURLY_RATE", nullable = false, precision = 5)
	public BigDecimal getHourlyRate() {
		return this.hourlyRate;
	}

	public void setHourlyRate(BigDecimal hourlyRate) {
		this.hourlyRate = hourlyRate;
	}

	@Column(name = "YR_ROUND_TEACH_FLG", nullable = false, length = 1)
	public char getYrRoundTeachFlg() {
		return this.yrRoundTeachFlg;
	}

	public void setYrRoundTeachFlg(char yrRoundTeachFlg) {
		this.yrRoundTeachFlg = yrRoundTeachFlg;
	}

	@Column(name = "CONTR_NON_STD_FLG", nullable = false, length = 1)
	public char getContrNonStdFlg() {
		return this.contrNonStdFlg;
	}

	public void setContrNonStdFlg(char contrNonStdFlg) {
		this.contrNonStdFlg = contrNonStdFlg;
	}

	@Column(name = "CONTR_DT_BEGIN", nullable = false, length = 8)
	public String getContrDtBegin() {
		return this.contrDtBegin;
	}

	public void setContrDtBegin(String contrDtBegin) {
		this.contrDtBegin = contrDtBegin;
	}

	@Column(name = "CONTR_DT_END", nullable = false, length = 8)
	public String getContrDtEnd() {
		return this.contrDtEnd;
	}

	public void setContrDtEnd(String contrDtEnd) {
		this.contrDtEnd = contrDtEnd;
	}

	@Column(name = "TRS_GROSS_JUL", nullable = false, precision = 9)
	public BigDecimal getTrsGrossJul() {
		return this.trsGrossJul;
	}

	public void setTrsGrossJul(BigDecimal trsGrossJul) {
		this.trsGrossJul = trsGrossJul;
	}

	@Column(name = "TRS_GROSS_AUG", nullable = false, precision = 9)
	public BigDecimal getTrsGrossAug() {
		return this.trsGrossAug;
	}

	public void setTrsGrossAug(BigDecimal trsGrossAug) {
		this.trsGrossAug = trsGrossAug;
	}

	@Column(name = "NBR_DAYS_EMPLD", nullable = false, length = 3)
	public String getNbrDaysEmpld() {
		return this.nbrDaysEmpld;
	}

	public void setNbrDaysEmpld(String nbrDaysEmpld) {
		this.nbrDaysEmpld = nbrDaysEmpld;
	}

	@Column(name = "PCT_DAYS_EMPLD", nullable = false, precision = 3, scale = 0)
	public short getPctDaysEmpld() {
		return this.pctDaysEmpld;
	}

	public void setPctDaysEmpld(short pctDaysEmpld) {
		this.pctDaysEmpld = pctDaysEmpld;
	}

	@Column(name = "MEM_PAYS_FICA", nullable = false, length = 1)
	public char getMemPaysFica() {
		return this.memPaysFica;
	}

	public void setMemPaysFica(char memPaysFica) {
		this.memPaysFica = memPaysFica;
	}

	@Column(name = "ADJ_RSN_CD", nullable = false, length = 1)
	public char getAdjRsnCd() {
		return this.adjRsnCd;
	}

	public void setAdjRsnCd(char adjRsnCd) {
		this.adjRsnCd = adjRsnCd;
	}

	@Column(name = "ORIG_POS_CD", nullable = false, length = 2)
	public String getOrigPosCd() {
		return this.origPosCd;
	}

	public void setOrigPosCd(String origPosCd) {
		this.origPosCd = origPosCd;
	}

	@Column(name = "TRS_ELIG_DT", nullable = false, length = 8)
	public String getTrsEligDt() {
		return this.trsEligDt;
	}

	public void setTrsEligDt(String trsEligDt) {
		this.trsEligDt = trsEligDt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
