package com.esc20.model;
// Generated Jan 4, 2019 3:48:53 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BteaApprvlStat generated by hbm2java
 */
@Entity
@Table(name = "BTEA_APPRVL_STAT", schema = "rsccc", catalog = "rsccc")
public class BteaApprvlStat implements java.io.Serializable {

	private char statCd;
	private String statDescr;

	public BteaApprvlStat() {
	}

	public BteaApprvlStat(char statCd, String statDescr) {
		this.statCd = statCd;
		this.statDescr = statDescr;
	}

	@Id

	@Column(name = "STAT_CD", nullable = false, length = 1)
	public char getStatCd() {
		return this.statCd;
	}

	public void setStatCd(char statCd) {
		this.statCd = statCd;
	}

	@Column(name = "STAT_DESCR", nullable = false, length = 25)
	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

}
