package com.esc20.model;
// Generated Jan 4, 2019 3:50:32 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrAdjRsnCd generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ADJ_RSN_CD", schema = "rsccc", catalog = "rsccc")
public class BthrAdjRsnCd implements java.io.Serializable {

	private BthrAdjRsnCdId id;
	private String adjRsnDesc;

	public BthrAdjRsnCd() {
	}

	public BthrAdjRsnCd(BthrAdjRsnCdId id, String adjRsnDesc) {
		this.id = id;
		this.adjRsnDesc = adjRsnDesc;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "adjRsnRecTyp", column = @Column(name = "ADJ_RSN_REC_TYP", nullable = false, length = 4)),
			@AttributeOverride(name = "adjRsnCd", column = @Column(name = "ADJ_RSN_CD", nullable = false, length = 1)) })
	public BthrAdjRsnCdId getId() {
		return this.id;
	}

	public void setId(BthrAdjRsnCdId id) {
		this.id = id;
	}

	@Column(name = "ADJ_RSN_DESC", nullable = false, length = 50)
	public String getAdjRsnDesc() {
		return this.adjRsnDesc;
	}

	public void setAdjRsnDesc(String adjRsnDesc) {
		this.adjRsnDesc = adjRsnDesc;
	}

}
