package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BthrLvSeq generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LV_SEQ", schema = "rsccc", catalog = "rsccc")
public class BthrLvSeq implements java.io.Serializable {

	private BthrLvSeqId id;
	private BthrLvTyp bthrLvTypByFkBthrLvRefLvSeqTyp;
	private BthrLvTyp bthrLvTypByFkBthrLvRefBwdLv;
	private BthrLvTyp bthrLvTypByFkBthrLvRefBthrLvTyp;
	private short lvSeqOrder;
	private char balSeq;
	private String module;

	public BthrLvSeq() {
	}

	public BthrLvSeq(BthrLvSeqId id, BthrLvTyp bthrLvTypByFkBthrLvRefLvSeqTyp, BthrLvTyp bthrLvTypByFkBthrLvRefBwdLv,
			BthrLvTyp bthrLvTypByFkBthrLvRefBthrLvTyp, short lvSeqOrder, char balSeq, String module) {
		this.id = id;
		this.bthrLvTypByFkBthrLvRefLvSeqTyp = bthrLvTypByFkBthrLvRefLvSeqTyp;
		this.bthrLvTypByFkBthrLvRefBwdLv = bthrLvTypByFkBthrLvRefBwdLv;
		this.bthrLvTypByFkBthrLvRefBthrLvTyp = bthrLvTypByFkBthrLvRefBthrLvTyp;
		this.lvSeqOrder = lvSeqOrder;
		this.balSeq = balSeq;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "lvAltTyp", column = @Column(name = "LV_ALT_TYP", nullable = false, length = 2)) })
	public BthrLvSeqId getId() {
		return this.id;
	}

	public void setId(BthrLvSeqId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PAY_FREQ", referencedColumnName = "LV_TYP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "LV_ALT_TYP", referencedColumnName = "PAY_FREQ", nullable = false, insertable = false, updatable = false) })
	public BthrLvTyp getBthrLvTypByFkBthrLvRefLvSeqTyp() {
		return this.bthrLvTypByFkBthrLvRefLvSeqTyp;
	}

	public void setBthrLvTypByFkBthrLvRefLvSeqTyp(BthrLvTyp bthrLvTypByFkBthrLvRefLvSeqTyp) {
		this.bthrLvTypByFkBthrLvRefLvSeqTyp = bthrLvTypByFkBthrLvRefLvSeqTyp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PAY_FREQ", referencedColumnName = "LV_TYP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "BWD_LV_TYP", referencedColumnName = "PAY_FREQ", nullable = false, insertable = false, updatable = false) })
	public BthrLvTyp getBthrLvTypByFkBthrLvRefBwdLv() {
		return this.bthrLvTypByFkBthrLvRefBwdLv;
	}

	public void setBthrLvTypByFkBthrLvRefBwdLv(BthrLvTyp bthrLvTypByFkBthrLvRefBwdLv) {
		this.bthrLvTypByFkBthrLvRefBwdLv = bthrLvTypByFkBthrLvRefBwdLv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PAY_FREQ", referencedColumnName = "LV_TYP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "LV_TYP", referencedColumnName = "PAY_FREQ", nullable = false, insertable = false, updatable = false) })
	public BthrLvTyp getBthrLvTypByFkBthrLvRefBthrLvTyp() {
		return this.bthrLvTypByFkBthrLvRefBthrLvTyp;
	}

	public void setBthrLvTypByFkBthrLvRefBthrLvTyp(BthrLvTyp bthrLvTypByFkBthrLvRefBthrLvTyp) {
		this.bthrLvTypByFkBthrLvRefBthrLvTyp = bthrLvTypByFkBthrLvRefBthrLvTyp;
	}

	@Column(name = "LV_SEQ_ORDER", nullable = false, precision = 3, scale = 0)
	public short getLvSeqOrder() {
		return this.lvSeqOrder;
	}

	public void setLvSeqOrder(short lvSeqOrder) {
		this.lvSeqOrder = lvSeqOrder;
	}

	@Column(name = "BAL_SEQ", nullable = false, length = 1)
	public char getBalSeq() {
		return this.balSeq;
	}

	public void setBalSeq(char balSeq) {
		this.balSeq = balSeq;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
