package com.esc20.model;
// Generated Jan 4, 2019 3:54:39 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrStSlry generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ST_SLRY", schema = "rsccc", catalog = "rsccc")
public class BthrStSlry implements java.io.Serializable {

	private BthrStSlryId id;
	private String stSalaryDescr;
	private BigDecimal dailyRate;
	private String module;

	public BthrStSlry() {
	}

	public BthrStSlry(BthrStSlryId id, String stSalaryDescr, BigDecimal dailyRate, String module) {
		this.id = id;
		this.stSalaryDescr = stSalaryDescr;
		this.dailyRate = dailyRate;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "stSalaryTyp", column = @Column(name = "ST_SALARY_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "stStp", column = @Column(name = "ST_STP", nullable = false, length = 2)) })
	public BthrStSlryId getId() {
		return this.id;
	}

	public void setId(BthrStSlryId id) {
		this.id = id;
	}

	@Column(name = "ST_SALARY_DESCR", nullable = false, length = 20)
	public String getStSalaryDescr() {
		return this.stSalaryDescr;
	}

	public void setStSalaryDescr(String stSalaryDescr) {
		this.stSalaryDescr = stSalaryDescr;
	}

	@Column(name = "DAILY_RATE", nullable = false, precision = 6, scale = 3)
	public BigDecimal getDailyRate() {
		return this.dailyRate;
	}

	public void setDailyRate(BigDecimal dailyRate) {
		this.dailyRate = dailyRate;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
