package com.esc20.model;
// Generated Jan 4, 2019 3:51:06 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrEarnIncome generated by hbm2java
 */
@Entity
@Table(name = "BTHR_EARN_INCOME", schema = "rsccc", catalog = "rsccc")
public class BthrEarnIncome implements java.io.Serializable {

	private BthrEarnIncomeId id;
	private BigDecimal overAmt;
	private BigDecimal notOver;
	private BigDecimal pctOfWgs;
	private BigDecimal adv;
	private BigDecimal pctOfReductn;
	private String module;

	public BthrEarnIncome() {
	}

	public BthrEarnIncome(BthrEarnIncomeId id, BigDecimal overAmt, BigDecimal notOver, BigDecimal pctOfWgs,
			BigDecimal adv, BigDecimal pctOfReductn, String module) {
		this.id = id;
		this.overAmt = overAmt;
		this.notOver = notOver;
		this.pctOfWgs = pctOfWgs;
		this.adv = adv;
		this.pctOfReductn = pctOfReductn;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "taxYr", column = @Column(name = "TAX_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "marriedSingleFlg", column = @Column(name = "MARRIED_SINGLE_FLG", nullable = false, length = 1)) })
	public BthrEarnIncomeId getId() {
		return this.id;
	}

	public void setId(BthrEarnIncomeId id) {
		this.id = id;
	}

	@Column(name = "OVER_AMT", nullable = false, precision = 6)
	public BigDecimal getOverAmt() {
		return this.overAmt;
	}

	public void setOverAmt(BigDecimal overAmt) {
		this.overAmt = overAmt;
	}

	@Column(name = "NOT_OVER", nullable = false, precision = 6)
	public BigDecimal getNotOver() {
		return this.notOver;
	}

	public void setNotOver(BigDecimal notOver) {
		this.notOver = notOver;
	}

	@Column(name = "PCT_OF_WGS", nullable = false, precision = 5, scale = 4)
	public BigDecimal getPctOfWgs() {
		return this.pctOfWgs;
	}

	public void setPctOfWgs(BigDecimal pctOfWgs) {
		this.pctOfWgs = pctOfWgs;
	}

	@Column(name = "ADV", nullable = false, precision = 6)
	public BigDecimal getAdv() {
		return this.adv;
	}

	public void setAdv(BigDecimal adv) {
		this.adv = adv;
	}

	@Column(name = "PCT_OF_REDUCTN", nullable = false, precision = 6, scale = 5)
	public BigDecimal getPctOfReductn() {
		return this.pctOfReductn;
	}

	public void setPctOfReductn(BigDecimal pctOfReductn) {
		this.pctOfReductn = pctOfReductn;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
