package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrFicaTaxRatesBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_FICA_TAX_RATES_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrFicaTaxRatesBkupPaycalcs5 implements java.io.Serializable {

	private BthrFicaTaxRatesBkupPaycalcs5Id id;

	public BthrFicaTaxRatesBkupPaycalcs5() {
	}

	public BthrFicaTaxRatesBkupPaycalcs5(BthrFicaTaxRatesBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxYr", column = @Column(name = "TAX_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "ficaRate", column = @Column(name = "FICA_RATE", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "ficaMaxSalary", column = @Column(name = "FICA_MAX_SALARY", nullable = false, precision = 9)),
			@AttributeOverride(name = "ficaMaxTax", column = @Column(name = "FICA_MAX_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "medRate", column = @Column(name = "MED_RATE", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "medMaxSalary", column = @Column(name = "MED_MAX_SALARY", nullable = false, precision = 9)),
			@AttributeOverride(name = "medMaxTax", column = @Column(name = "MED_MAX_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "eicMaxSal", column = @Column(name = "EIC_MAX_SAL", nullable = false, precision = 7)),
			@AttributeOverride(name = "emplrFicaRate", column = @Column(name = "EMPLR_FICA_RATE", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "emplrFicaMaxTax", column = @Column(name = "EMPLR_FICA_MAX_TAX", nullable = false, precision = 9)),
			@AttributeOverride(name = "addlMedRate", column = @Column(name = "ADDL_MED_RATE", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "addlMedSalThreshold", column = @Column(name = "ADDL_MED_SAL_THRESHOLD", nullable = false, precision = 9)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "hsaMaxEmplrContrib", column = @Column(name = "HSA_MAX_EMPLR_CONTRIB", nullable = false, precision = 7)) })
	public BthrFicaTaxRatesBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrFicaTaxRatesBkupPaycalcs5Id id) {
		this.id = id;
	}

}
