package com.esc20.model;
// Generated Jan 4, 2019 3:53:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrPayFreq generated by hbm2java
 */
@Entity
@Table(name = "BTHR_PAY_FREQ", schema = "rsccc", catalog = "rsccc")
public class BthrPayFreq implements java.io.Serializable {

	private char payFreq;
	private String payFreqDescr;
	private String module;

	public BthrPayFreq() {
	}

	public BthrPayFreq(char payFreq, String payFreqDescr, String module) {
		this.payFreq = payFreq;
		this.payFreqDescr = payFreqDescr;
		this.module = module;
	}

	@Id

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "PAY_FREQ_DESCR", nullable = false, length = 20)
	public String getPayFreqDescr() {
		return this.payFreqDescr;
	}

	public void setPayFreqDescr(String payFreqDescr) {
		this.payFreqDescr = payFreqDescr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
