package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrLvSeqBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LV_SEQ_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrLvSeqBkupPaycalcs5 implements java.io.Serializable {

	private BthrLvSeqBkupPaycalcs5Id id;

	public BthrLvSeqBkupPaycalcs5() {
	}

	public BthrLvSeqBkupPaycalcs5(BthrLvSeqBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "lvAltTyp", column = @Column(name = "LV_ALT_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "lvSeqOrder", column = @Column(name = "LV_SEQ_ORDER", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "bwdLvTyp", column = @Column(name = "BWD_LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "balSeq", column = @Column(name = "BAL_SEQ", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrLvSeqBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrLvSeqBkupPaycalcs5Id id) {
		this.id = id;
	}

}
