package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrExtraDutyBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_EXTRA_DUTY_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrExtraDutyBkupPaycalcs5 implements java.io.Serializable {

	private BthrExtraDutyBkupPaycalcs5Id id;

	public BthrExtraDutyBkupPaycalcs5() {
	}

	public BthrExtraDutyBkupPaycalcs5(BthrExtraDutyBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "extraDutyCd", column = @Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "extraDutyDescr", column = @Column(name = "EXTRA_DUTY_DESCR", nullable = false, length = 16)),
			@AttributeOverride(name = "wholeSep", column = @Column(name = "WHOLE_SEP", nullable = false, length = 1)),
			@AttributeOverride(name = "expense373", column = @Column(name = "EXPENSE_373", nullable = false, length = 1)),
			@AttributeOverride(name = "payActy", column = @Column(name = "PAY_ACTY", nullable = false, length = 2)),
			@AttributeOverride(name = "defaultAmt", column = @Column(name = "DEFAULT_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "glFileId", column = @Column(name = "GL_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "fund", column = @Column(name = "FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "func", column = @Column(name = "FUNC", nullable = false, length = 2)),
			@AttributeOverride(name = "obj", column = @Column(name = "OBJ", nullable = false, length = 4)),
			@AttributeOverride(name = "sobj", column = @Column(name = "SOBJ", nullable = false, length = 2)),
			@AttributeOverride(name = "org", column = @Column(name = "ORG", nullable = false, length = 3)),
			@AttributeOverride(name = "fsclYr", column = @Column(name = "FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "pgm", column = @Column(name = "PGM", nullable = false, length = 2)),
			@AttributeOverride(name = "edSpan", column = @Column(name = "ED_SPAN", nullable = false, length = 1)),
			@AttributeOverride(name = "projDtl", column = @Column(name = "PROJ_DTL", nullable = false, length = 2)),
			@AttributeOverride(name = "defaultWrkComp", column = @Column(name = "DEFAULT_WRK_COMP", nullable = false, length = 1)),
			@AttributeOverride(name = "defaultAcctTyp", column = @Column(name = "DEFAULT_ACCT_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "defaultGrantCd", column = @Column(name = "DEFAULT_GRANT_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "inclSupplDockRate", column = @Column(name = "INCL_SUPPL_DOCK_RATE", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "trsPosCd", column = @Column(name = "TRS_POS_CD", nullable = false, length = 2)) })
	public BthrExtraDutyBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrExtraDutyBkupPaycalcs5Id id) {
		this.id = id;
	}

}
