package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrHrlyDlySalary generated by hbm2java
 */
@Entity
@Table(name = "BTHR_HRLY_DLY_SALARY", schema = "rsccc", catalog = "rsccc")
public class BthrHrlyDlySalary implements java.io.Serializable {

	private BthrHrlyDlySalaryId id;
	private BigDecimal payAmt;
	private BigDecimal hrsPerDay;
	private BigDecimal estOvtmHrs;
	private char payTyp;
	private String module;

	public BthrHrlyDlySalary() {
	}

	public BthrHrlyDlySalary(BthrHrlyDlySalaryId id, BigDecimal payAmt, BigDecimal hrsPerDay, BigDecimal estOvtmHrs,
			char payTyp, String module) {
		this.id = id;
		this.payAmt = payAmt;
		this.hrsPerDay = hrsPerDay;
		this.estOvtmHrs = estOvtmHrs;
		this.payTyp = payTyp;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payGrd", column = @Column(name = "PAY_GRD", nullable = false, length = 3)),
			@AttributeOverride(name = "payStep", column = @Column(name = "PAY_STEP", nullable = false, length = 2)),
			@AttributeOverride(name = "sched", column = @Column(name = "SCHED", nullable = false, length = 1)) })
	public BthrHrlyDlySalaryId getId() {
		return this.id;
	}

	public void setId(BthrHrlyDlySalaryId id) {
		this.id = id;
	}

	@Column(name = "PAY_AMT", nullable = false, precision = 6, scale = 3)
	public BigDecimal getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;
	}

	@Column(name = "HRS_PER_DAY", nullable = false, precision = 5)
	public BigDecimal getHrsPerDay() {
		return this.hrsPerDay;
	}

	public void setHrsPerDay(BigDecimal hrsPerDay) {
		this.hrsPerDay = hrsPerDay;
	}

	@Column(name = "EST_OVTM_HRS", nullable = false, precision = 5, scale = 1)
	public BigDecimal getEstOvtmHrs() {
		return this.estOvtmHrs;
	}

	public void setEstOvtmHrs(BigDecimal estOvtmHrs) {
		this.estOvtmHrs = estOvtmHrs;
	}

	@Column(name = "PAY_TYP", nullable = false, length = 1)
	public char getPayTyp() {
		return this.payTyp;
	}

	public void setPayTyp(char payTyp) {
		this.payTyp = payTyp;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
