package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrExtraDuty generated by hbm2java
 */
@Entity
@Table(name = "BTHR_EXTRA_DUTY", schema = "rsccc", catalog = "rsccc")
public class BthrExtraDuty implements java.io.Serializable {

	private BthrExtraDutyId id;
	private String extraDutyDescr;
	private char wholeSep;
	private char expense373;
	private String payActy;
	private BigDecimal defaultAmt;
	private char glFileId;
	private String fund;
	private String func;
	private String obj;
	private String sobj;
	private String org;
	private char fsclYr;
	private String pgm;
	private char edSpan;
	private String projDtl;
	private char defaultWrkComp;
	private char defaultAcctTyp;
	private String defaultGrantCd;
	private char inclSupplDockRate;
	private String module;
	private String trsPosCd;

	public BthrExtraDuty() {
	}

	public BthrExtraDuty(BthrExtraDutyId id, String extraDutyDescr, char wholeSep, char expense373, String payActy,
			BigDecimal defaultAmt, char glFileId, String fund, String func, String obj, String sobj, String org,
			char fsclYr, String pgm, char edSpan, String projDtl, char defaultWrkComp, char defaultAcctTyp,
			String defaultGrantCd, char inclSupplDockRate, String module, String trsPosCd) {
		this.id = id;
		this.extraDutyDescr = extraDutyDescr;
		this.wholeSep = wholeSep;
		this.expense373 = expense373;
		this.payActy = payActy;
		this.defaultAmt = defaultAmt;
		this.glFileId = glFileId;
		this.fund = fund;
		this.func = func;
		this.obj = obj;
		this.sobj = sobj;
		this.org = org;
		this.fsclYr = fsclYr;
		this.pgm = pgm;
		this.edSpan = edSpan;
		this.projDtl = projDtl;
		this.defaultWrkComp = defaultWrkComp;
		this.defaultAcctTyp = defaultAcctTyp;
		this.defaultGrantCd = defaultGrantCd;
		this.inclSupplDockRate = inclSupplDockRate;
		this.module = module;
		this.trsPosCd = trsPosCd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "extraDutyCd", column = @Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)) })
	public BthrExtraDutyId getId() {
		return this.id;
	}

	public void setId(BthrExtraDutyId id) {
		this.id = id;
	}

	@Column(name = "EXTRA_DUTY_DESCR", nullable = false, length = 16)
	public String getExtraDutyDescr() {
		return this.extraDutyDescr;
	}

	public void setExtraDutyDescr(String extraDutyDescr) {
		this.extraDutyDescr = extraDutyDescr;
	}

	@Column(name = "WHOLE_SEP", nullable = false, length = 1)
	public char getWholeSep() {
		return this.wholeSep;
	}

	public void setWholeSep(char wholeSep) {
		this.wholeSep = wholeSep;
	}

	@Column(name = "EXPENSE_373", nullable = false, length = 1)
	public char getExpense373() {
		return this.expense373;
	}

	public void setExpense373(char expense373) {
		this.expense373 = expense373;
	}

	@Column(name = "PAY_ACTY", nullable = false, length = 2)
	public String getPayActy() {
		return this.payActy;
	}

	public void setPayActy(String payActy) {
		this.payActy = payActy;
	}

	@Column(name = "DEFAULT_AMT", nullable = false, precision = 9)
	public BigDecimal getDefaultAmt() {
		return this.defaultAmt;
	}

	public void setDefaultAmt(BigDecimal defaultAmt) {
		this.defaultAmt = defaultAmt;
	}

	@Column(name = "GL_FILE_ID", nullable = false, length = 1)
	public char getGlFileId() {
		return this.glFileId;
	}

	public void setGlFileId(char glFileId) {
		this.glFileId = glFileId;
	}

	@Column(name = "FUND", nullable = false, length = 3)
	public String getFund() {
		return this.fund;
	}

	public void setFund(String fund) {
		this.fund = fund;
	}

	@Column(name = "FUNC", nullable = false, length = 2)
	public String getFunc() {
		return this.func;
	}

	public void setFunc(String func) {
		this.func = func;
	}

	@Column(name = "OBJ", nullable = false, length = 4)
	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	@Column(name = "SOBJ", nullable = false, length = 2)
	public String getSobj() {
		return this.sobj;
	}

	public void setSobj(String sobj) {
		this.sobj = sobj;
	}

	@Column(name = "ORG", nullable = false, length = 3)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "FSCL_YR", nullable = false, length = 1)
	public char getFsclYr() {
		return this.fsclYr;
	}

	public void setFsclYr(char fsclYr) {
		this.fsclYr = fsclYr;
	}

	@Column(name = "PGM", nullable = false, length = 2)
	public String getPgm() {
		return this.pgm;
	}

	public void setPgm(String pgm) {
		this.pgm = pgm;
	}

	@Column(name = "ED_SPAN", nullable = false, length = 1)
	public char getEdSpan() {
		return this.edSpan;
	}

	public void setEdSpan(char edSpan) {
		this.edSpan = edSpan;
	}

	@Column(name = "PROJ_DTL", nullable = false, length = 2)
	public String getProjDtl() {
		return this.projDtl;
	}

	public void setProjDtl(String projDtl) {
		this.projDtl = projDtl;
	}

	@Column(name = "DEFAULT_WRK_COMP", nullable = false, length = 1)
	public char getDefaultWrkComp() {
		return this.defaultWrkComp;
	}

	public void setDefaultWrkComp(char defaultWrkComp) {
		this.defaultWrkComp = defaultWrkComp;
	}

	@Column(name = "DEFAULT_ACCT_TYP", nullable = false, length = 1)
	public char getDefaultAcctTyp() {
		return this.defaultAcctTyp;
	}

	public void setDefaultAcctTyp(char defaultAcctTyp) {
		this.defaultAcctTyp = defaultAcctTyp;
	}

	@Column(name = "DEFAULT_GRANT_CD", nullable = false, length = 2)
	public String getDefaultGrantCd() {
		return this.defaultGrantCd;
	}

	public void setDefaultGrantCd(String defaultGrantCd) {
		this.defaultGrantCd = defaultGrantCd;
	}

	@Column(name = "INCL_SUPPL_DOCK_RATE", nullable = false, length = 1)
	public char getInclSupplDockRate() {
		return this.inclSupplDockRate;
	}

	public void setInclSupplDockRate(char inclSupplDockRate) {
		this.inclSupplDockRate = inclSupplDockRate;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "TRS_POS_CD", nullable = false, length = 2)
	public String getTrsPosCd() {
		return this.trsPosCd;
	}

	public void setTrsPosCd(String trsPosCd) {
		this.trsPosCd = trsPosCd;
	}

}
