package com.esc20.model;
// Generated Jan 4, 2019 3:54:39 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrSimMidpntBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_SIM_MIDPNT_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrSimMidpntBkupPaycalcs5 implements java.io.Serializable {

	private BthrSimMidpntBkupPaycalcs5Id id;

	public BthrSimMidpntBkupPaycalcs5() {
	}

	public BthrSimMidpntBkupPaycalcs5(BthrSimMidpntBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "simName", column = @Column(name = "SIM_NAME", nullable = false, length = 7)),
			@AttributeOverride(name = "payGrd", column = @Column(name = "PAY_GRD", nullable = false, length = 3)),
			@AttributeOverride(name = "payTyp", column = @Column(name = "PAY_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "minAmtChg", column = @Column(name = "MIN_AMT_CHG", nullable = false, precision = 6, scale = 3)),
			@AttributeOverride(name = "minPctChg", column = @Column(name = "MIN_PCT_CHG", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "maxAmtChg", column = @Column(name = "MAX_AMT_CHG", nullable = false, precision = 6, scale = 3)),
			@AttributeOverride(name = "maxPctChg", column = @Column(name = "MAX_PCT_CHG", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "midpntAmtChg", column = @Column(name = "MIDPNT_AMT_CHG", nullable = false, precision = 6, scale = 3)),
			@AttributeOverride(name = "midpntPctChg", column = @Column(name = "MIDPNT_PCT_CHG", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "midpntMaxIncPct", column = @Column(name = "MIDPNT_MAX_INC_PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "midpntMidIncPct", column = @Column(name = "MIDPNT_MID_INC_PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrSimMidpntBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrSimMidpntBkupPaycalcs5Id id) {
		this.id = id;
	}

}
