package com.esc20.model;
// Generated Jan 4, 2019 3:54:39 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrSimOpt generated by hbm2java
 */
@Entity
@Table(name = "BTHR_SIM_OPT", schema = "rsccc", catalog = "rsccc")
public class BthrSimOpt implements java.io.Serializable {

	private BthrSimOptId id;
	private String simDescr;
	private String usrId;
	private char updtFrcstFlg;
	private char updtBudFlg;
	private char inclProposPos;
	private char inclVacSupplPos;
	private char incrPayStp;
	private byte maxAnnlPayStp;
	private byte maxHrlyPayStp;
	private char incrStStp;
	private char actToBudInd;
	private char updtBudAmtFlg;
	private char updtBudRndFlg;
	private char inclTrsOnbehalfCalcs;
	private String trsOnBehalfExpAcct;
	private char midpntSalUpdtFlg;
	private char incrSalToMidpntMin;
	private char inclTeaHlthIns;
	private String module;

	public BthrSimOpt() {
	}

	public BthrSimOpt(BthrSimOptId id, String simDescr, String usrId, char updtFrcstFlg, char updtBudFlg,
			char inclProposPos, char inclVacSupplPos, char incrPayStp, byte maxAnnlPayStp, byte maxHrlyPayStp,
			char incrStStp, char actToBudInd, char updtBudAmtFlg, char updtBudRndFlg, char inclTrsOnbehalfCalcs,
			String trsOnBehalfExpAcct, char midpntSalUpdtFlg, char incrSalToMidpntMin, char inclTeaHlthIns,
			String module) {
		this.id = id;
		this.simDescr = simDescr;
		this.usrId = usrId;
		this.updtFrcstFlg = updtFrcstFlg;
		this.updtBudFlg = updtBudFlg;
		this.inclProposPos = inclProposPos;
		this.inclVacSupplPos = inclVacSupplPos;
		this.incrPayStp = incrPayStp;
		this.maxAnnlPayStp = maxAnnlPayStp;
		this.maxHrlyPayStp = maxHrlyPayStp;
		this.incrStStp = incrStStp;
		this.actToBudInd = actToBudInd;
		this.updtBudAmtFlg = updtBudAmtFlg;
		this.updtBudRndFlg = updtBudRndFlg;
		this.inclTrsOnbehalfCalcs = inclTrsOnbehalfCalcs;
		this.trsOnBehalfExpAcct = trsOnBehalfExpAcct;
		this.midpntSalUpdtFlg = midpntSalUpdtFlg;
		this.incrSalToMidpntMin = incrSalToMidpntMin;
		this.inclTeaHlthIns = inclTeaHlthIns;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "simName", column = @Column(name = "SIM_NAME", nullable = false, length = 7)) })
	public BthrSimOptId getId() {
		return this.id;
	}

	public void setId(BthrSimOptId id) {
		this.id = id;
	}

	@Column(name = "SIM_DESCR", nullable = false, length = 30)
	public String getSimDescr() {
		return this.simDescr;
	}

	public void setSimDescr(String simDescr) {
		this.simDescr = simDescr;
	}

	@Column(name = "USR_ID", nullable = false, length = 12)
	public String getUsrId() {
		return this.usrId;
	}

	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}

	@Column(name = "UPDT_FRCST_FLG", nullable = false, length = 1)
	public char getUpdtFrcstFlg() {
		return this.updtFrcstFlg;
	}

	public void setUpdtFrcstFlg(char updtFrcstFlg) {
		this.updtFrcstFlg = updtFrcstFlg;
	}

	@Column(name = "UPDT_BUD_FLG", nullable = false, length = 1)
	public char getUpdtBudFlg() {
		return this.updtBudFlg;
	}

	public void setUpdtBudFlg(char updtBudFlg) {
		this.updtBudFlg = updtBudFlg;
	}

	@Column(name = "INCL_PROPOS_POS", nullable = false, length = 1)
	public char getInclProposPos() {
		return this.inclProposPos;
	}

	public void setInclProposPos(char inclProposPos) {
		this.inclProposPos = inclProposPos;
	}

	@Column(name = "INCL_VAC_SUPPL_POS", nullable = false, length = 1)
	public char getInclVacSupplPos() {
		return this.inclVacSupplPos;
	}

	public void setInclVacSupplPos(char inclVacSupplPos) {
		this.inclVacSupplPos = inclVacSupplPos;
	}

	@Column(name = "INCR_PAY_STP", nullable = false, length = 1)
	public char getIncrPayStp() {
		return this.incrPayStp;
	}

	public void setIncrPayStp(char incrPayStp) {
		this.incrPayStp = incrPayStp;
	}

	@Column(name = "MAX_ANNL_PAY_STP", nullable = false, precision = 2, scale = 0)
	public byte getMaxAnnlPayStp() {
		return this.maxAnnlPayStp;
	}

	public void setMaxAnnlPayStp(byte maxAnnlPayStp) {
		this.maxAnnlPayStp = maxAnnlPayStp;
	}

	@Column(name = "MAX_HRLY_PAY_STP", nullable = false, precision = 2, scale = 0)
	public byte getMaxHrlyPayStp() {
		return this.maxHrlyPayStp;
	}

	public void setMaxHrlyPayStp(byte maxHrlyPayStp) {
		this.maxHrlyPayStp = maxHrlyPayStp;
	}

	@Column(name = "INCR_ST_STP", nullable = false, length = 1)
	public char getIncrStStp() {
		return this.incrStStp;
	}

	public void setIncrStStp(char incrStStp) {
		this.incrStStp = incrStStp;
	}

	@Column(name = "ACT_TO_BUD_IND", nullable = false, length = 1)
	public char getActToBudInd() {
		return this.actToBudInd;
	}

	public void setActToBudInd(char actToBudInd) {
		this.actToBudInd = actToBudInd;
	}

	@Column(name = "UPDT_BUD_AMT_FLG", nullable = false, length = 1)
	public char getUpdtBudAmtFlg() {
		return this.updtBudAmtFlg;
	}

	public void setUpdtBudAmtFlg(char updtBudAmtFlg) {
		this.updtBudAmtFlg = updtBudAmtFlg;
	}

	@Column(name = "UPDT_BUD_RND_FLG", nullable = false, length = 1)
	public char getUpdtBudRndFlg() {
		return this.updtBudRndFlg;
	}

	public void setUpdtBudRndFlg(char updtBudRndFlg) {
		this.updtBudRndFlg = updtBudRndFlg;
	}

	@Column(name = "INCL_TRS_ONBEHALF_CALCS", nullable = false, length = 1)
	public char getInclTrsOnbehalfCalcs() {
		return this.inclTrsOnbehalfCalcs;
	}

	public void setInclTrsOnbehalfCalcs(char inclTrsOnbehalfCalcs) {
		this.inclTrsOnbehalfCalcs = inclTrsOnbehalfCalcs;
	}

	@Column(name = "TRS_ON_BEHALF_EXP_ACCT", nullable = false, length = 20)
	public String getTrsOnBehalfExpAcct() {
		return this.trsOnBehalfExpAcct;
	}

	public void setTrsOnBehalfExpAcct(String trsOnBehalfExpAcct) {
		this.trsOnBehalfExpAcct = trsOnBehalfExpAcct;
	}

	@Column(name = "MIDPNT_SAL_UPDT_FLG", nullable = false, length = 1)
	public char getMidpntSalUpdtFlg() {
		return this.midpntSalUpdtFlg;
	}

	public void setMidpntSalUpdtFlg(char midpntSalUpdtFlg) {
		this.midpntSalUpdtFlg = midpntSalUpdtFlg;
	}

	@Column(name = "INCR_SAL_TO_MIDPNT_MIN", nullable = false, length = 1)
	public char getIncrSalToMidpntMin() {
		return this.incrSalToMidpntMin;
	}

	public void setIncrSalToMidpntMin(char incrSalToMidpntMin) {
		this.incrSalToMidpntMin = incrSalToMidpntMin;
	}

	@Column(name = "INCL_TEA_HLTH_INS", nullable = false, length = 1)
	public char getInclTeaHlthIns() {
		return this.inclTeaHlthIns;
	}

	public void setInclTeaHlthIns(char inclTeaHlthIns) {
		this.inclTeaHlthIns = inclTeaHlthIns;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
