package com.esc20.model;
// Generated Jan 4, 2019 3:54:39 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrSimPmisOptCodesBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_SIM_PMIS_OPT_CODES_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrSimPmisOptCodesBkupPaycalcs5 implements java.io.Serializable {

	private BthrSimPmisOptCodesBkupPaycalcs5Id id;

	public BthrSimPmisOptCodesBkupPaycalcs5() {
	}

	public BthrSimPmisOptCodesBkupPaycalcs5(BthrSimPmisOptCodesBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "recTyp", column = @Column(name = "REC_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "simName", column = @Column(name = "SIM_NAME", nullable = false, length = 7)),
			@AttributeOverride(name = "recCd", column = @Column(name = "REC_CD", nullable = false, length = 4)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrSimPmisOptCodesBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrSimPmisOptCodesBkupPaycalcs5Id id) {
		this.id = id;
	}

}
