package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BthrLvSeqBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BthrLvSeqBkupPaycalcs5Id implements java.io.Serializable {

	private char payFreq;
	private String lvTyp;
	private String lvAltTyp;
	private short lvSeqOrder;
	private String bwdLvTyp;
	private char balSeq;
	private String module;

	public BthrLvSeqBkupPaycalcs5Id() {
	}

	public BthrLvSeqBkupPaycalcs5Id(char payFreq, String lvTyp, String lvAltTyp, short lvSeqOrder, String bwdLvTyp,
			char balSeq, String module) {
		this.payFreq = payFreq;
		this.lvTyp = lvTyp;
		this.lvAltTyp = lvAltTyp;
		this.lvSeqOrder = lvSeqOrder;
		this.bwdLvTyp = bwdLvTyp;
		this.balSeq = balSeq;
		this.module = module;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "LV_TYP", nullable = false, length = 2)
	public String getLvTyp() {
		return this.lvTyp;
	}

	public void setLvTyp(String lvTyp) {
		this.lvTyp = lvTyp;
	}

	@Column(name = "LV_ALT_TYP", nullable = false, length = 2)
	public String getLvAltTyp() {
		return this.lvAltTyp;
	}

	public void setLvAltTyp(String lvAltTyp) {
		this.lvAltTyp = lvAltTyp;
	}

	@Column(name = "LV_SEQ_ORDER", nullable = false, precision = 3, scale = 0)
	public short getLvSeqOrder() {
		return this.lvSeqOrder;
	}

	public void setLvSeqOrder(short lvSeqOrder) {
		this.lvSeqOrder = lvSeqOrder;
	}

	@Column(name = "BWD_LV_TYP", nullable = false, length = 2)
	public String getBwdLvTyp() {
		return this.bwdLvTyp;
	}

	public void setBwdLvTyp(String bwdLvTyp) {
		this.bwdLvTyp = bwdLvTyp;
	}

	@Column(name = "BAL_SEQ", nullable = false, length = 1)
	public char getBalSeq() {
		return this.balSeq;
	}

	public void setBalSeq(char balSeq) {
		this.balSeq = balSeq;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BthrLvSeqBkupPaycalcs5Id))
			return false;
		BthrLvSeqBkupPaycalcs5Id castOther = (BthrLvSeqBkupPaycalcs5Id) other;

		return (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getLvTyp() == castOther.getLvTyp()) || (this.getLvTyp() != null
						&& castOther.getLvTyp() != null && this.getLvTyp().equals(castOther.getLvTyp())))
				&& ((this.getLvAltTyp() == castOther.getLvAltTyp()) || (this.getLvAltTyp() != null
						&& castOther.getLvAltTyp() != null && this.getLvAltTyp().equals(castOther.getLvAltTyp())))
				&& (this.getLvSeqOrder() == castOther.getLvSeqOrder())
				&& ((this.getBwdLvTyp() == castOther.getBwdLvTyp()) || (this.getBwdLvTyp() != null
						&& castOther.getBwdLvTyp() != null && this.getBwdLvTyp().equals(castOther.getBwdLvTyp())))
				&& (this.getBalSeq() == castOther.getBalSeq())
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getLvTyp() == null ? 0 : this.getLvTyp().hashCode());
		result = 37 * result + (getLvAltTyp() == null ? 0 : this.getLvAltTyp().hashCode());
		result = 37 * result + this.getLvSeqOrder();
		result = 37 * result + (getBwdLvTyp() == null ? 0 : this.getBwdLvTyp().hashCode());
		result = 37 * result + this.getBalSeq();
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		return result;
	}

}
