package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrLocAnnualSalary generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LOC_ANNUAL_SALARY", schema = "rsccc", catalog = "rsccc")
public class BthrLocAnnualSalary implements java.io.Serializable {

	private BthrLocAnnualSalaryId id;
	private BigDecimal annualAmt;
	private String module;

	public BthrLocAnnualSalary() {
	}

	public BthrLocAnnualSalary(BthrLocAnnualSalaryId id, BigDecimal annualAmt, String module) {
		this.id = id;
		this.annualAmt = annualAmt;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payGrd", column = @Column(name = "PAY_GRD", nullable = false, length = 3)),
			@AttributeOverride(name = "payStep", column = @Column(name = "PAY_STEP", nullable = false, length = 2)),
			@AttributeOverride(name = "maxDays", column = @Column(name = "MAX_DAYS", nullable = false, length = 3)),
			@AttributeOverride(name = "sched", column = @Column(name = "SCHED", nullable = false, length = 1)) })
	public BthrLocAnnualSalaryId getId() {
		return this.id;
	}

	public void setId(BthrLocAnnualSalaryId id) {
		this.id = id;
	}

	@Column(name = "ANNUAL_AMT", nullable = false, precision = 9)
	public BigDecimal getAnnualAmt() {
		return this.annualAmt;
	}

	public void setAnnualAmt(BigDecimal annualAmt) {
		this.annualAmt = annualAmt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
