package com.esc20.model;
// Generated Jan 4, 2019 3:54:39 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrSimMidpnt generated by hbm2java
 */
@Entity
@Table(name = "BTHR_SIM_MIDPNT", schema = "rsccc", catalog = "rsccc")
public class BthrSimMidpnt implements java.io.Serializable {

	private BthrSimMidpntId id;
	private BigDecimal minAmtChg;
	private BigDecimal minPctChg;
	private BigDecimal maxAmtChg;
	private BigDecimal maxPctChg;
	private BigDecimal midpntAmtChg;
	private BigDecimal midpntPctChg;
	private BigDecimal midpntMaxIncPct;
	private BigDecimal midpntMidIncPct;
	private String module;

	public BthrSimMidpnt() {
	}

	public BthrSimMidpnt(BthrSimMidpntId id, BigDecimal minAmtChg, BigDecimal minPctChg, BigDecimal maxAmtChg,
			BigDecimal maxPctChg, BigDecimal midpntAmtChg, BigDecimal midpntPctChg, BigDecimal midpntMaxIncPct,
			BigDecimal midpntMidIncPct, String module) {
		this.id = id;
		this.minAmtChg = minAmtChg;
		this.minPctChg = minPctChg;
		this.maxAmtChg = maxAmtChg;
		this.maxPctChg = maxPctChg;
		this.midpntAmtChg = midpntAmtChg;
		this.midpntPctChg = midpntPctChg;
		this.midpntMaxIncPct = midpntMaxIncPct;
		this.midpntMidIncPct = midpntMidIncPct;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "simName", column = @Column(name = "SIM_NAME", nullable = false, length = 7)),
			@AttributeOverride(name = "payGrd", column = @Column(name = "PAY_GRD", nullable = false, length = 3)),
			@AttributeOverride(name = "payTyp", column = @Column(name = "PAY_TYP", nullable = false, length = 1)) })
	public BthrSimMidpntId getId() {
		return this.id;
	}

	public void setId(BthrSimMidpntId id) {
		this.id = id;
	}

	@Column(name = "MIN_AMT_CHG", nullable = false, precision = 6, scale = 3)
	public BigDecimal getMinAmtChg() {
		return this.minAmtChg;
	}

	public void setMinAmtChg(BigDecimal minAmtChg) {
		this.minAmtChg = minAmtChg;
	}

	@Column(name = "MIN_PCT_CHG", nullable = false, precision = 5, scale = 4)
	public BigDecimal getMinPctChg() {
		return this.minPctChg;
	}

	public void setMinPctChg(BigDecimal minPctChg) {
		this.minPctChg = minPctChg;
	}

	@Column(name = "MAX_AMT_CHG", nullable = false, precision = 6, scale = 3)
	public BigDecimal getMaxAmtChg() {
		return this.maxAmtChg;
	}

	public void setMaxAmtChg(BigDecimal maxAmtChg) {
		this.maxAmtChg = maxAmtChg;
	}

	@Column(name = "MAX_PCT_CHG", nullable = false, precision = 5, scale = 4)
	public BigDecimal getMaxPctChg() {
		return this.maxPctChg;
	}

	public void setMaxPctChg(BigDecimal maxPctChg) {
		this.maxPctChg = maxPctChg;
	}

	@Column(name = "MIDPNT_AMT_CHG", nullable = false, precision = 6, scale = 3)
	public BigDecimal getMidpntAmtChg() {
		return this.midpntAmtChg;
	}

	public void setMidpntAmtChg(BigDecimal midpntAmtChg) {
		this.midpntAmtChg = midpntAmtChg;
	}

	@Column(name = "MIDPNT_PCT_CHG", nullable = false, precision = 5, scale = 4)
	public BigDecimal getMidpntPctChg() {
		return this.midpntPctChg;
	}

	public void setMidpntPctChg(BigDecimal midpntPctChg) {
		this.midpntPctChg = midpntPctChg;
	}

	@Column(name = "MIDPNT_MAX_INC_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getMidpntMaxIncPct() {
		return this.midpntMaxIncPct;
	}

	public void setMidpntMaxIncPct(BigDecimal midpntMaxIncPct) {
		this.midpntMaxIncPct = midpntMaxIncPct;
	}

	@Column(name = "MIDPNT_MID_INC_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getMidpntMidIncPct() {
		return this.midpntMidIncPct;
	}

	public void setMidpntMidIncPct(BigDecimal midpntMidIncPct) {
		this.midpntMidIncPct = midpntMidIncPct;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
