package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrFedIncomeTax generated by hbm2java
 */
@Entity
@Table(name = "BTHR_FED_INCOME_TAX", schema = "rsccc", catalog = "rsccc")
public class BthrFedIncomeTax implements java.io.Serializable {

	private BthrFedIncomeTaxId id;
	private int overAmt;
	private int notOver;
	private BigDecimal taxAmt;
	private BigDecimal pct;
	private int inExcess;
	private String module;

	public BthrFedIncomeTax() {
	}

	public BthrFedIncomeTax(BthrFedIncomeTaxId id, int overAmt, int notOver, BigDecimal taxAmt, BigDecimal pct,
			int inExcess, String module) {
		this.id = id;
		this.overAmt = overAmt;
		this.notOver = notOver;
		this.taxAmt = taxAmt;
		this.pct = pct;
		this.inExcess = inExcess;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "marriedSingleFlg", column = @Column(name = "MARRIED_SINGLE_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "taxYr", column = @Column(name = "TAX_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)) })
	public BthrFedIncomeTaxId getId() {
		return this.id;
	}

	public void setId(BthrFedIncomeTaxId id) {
		this.id = id;
	}

	@Column(name = "OVER_AMT", nullable = false, precision = 7, scale = 0)
	public int getOverAmt() {
		return this.overAmt;
	}

	public void setOverAmt(int overAmt) {
		this.overAmt = overAmt;
	}

	@Column(name = "NOT_OVER", nullable = false, precision = 7, scale = 0)
	public int getNotOver() {
		return this.notOver;
	}

	public void setNotOver(int notOver) {
		this.notOver = notOver;
	}

	@Column(name = "TAX_AMT", nullable = false, precision = 9)
	public BigDecimal getTaxAmt() {
		return this.taxAmt;
	}

	public void setTaxAmt(BigDecimal taxAmt) {
		this.taxAmt = taxAmt;
	}

	@Column(name = "PCT", nullable = false, precision = 4, scale = 3)
	public BigDecimal getPct() {
		return this.pct;
	}

	public void setPct(BigDecimal pct) {
		this.pct = pct;
	}

	@Column(name = "IN_EXCESS", nullable = false, precision = 7, scale = 0)
	public int getInExcess() {
		return this.inExcess;
	}

	public void setInExcess(int inExcess) {
		this.inExcess = inExcess;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
