package com.esc20.model;
// Generated Jan 4, 2019 3:50:32 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrCertifTyp generated by hbm2java
 */
@Entity
@Table(name = "BTHR_CERTIF_TYP", schema = "rsccc", catalog = "rsccc")
public class BthrCertifTyp implements java.io.Serializable {

	private char certTyp;
	private String certTypDescr;
	private String module;

	public BthrCertifTyp() {
	}

	public BthrCertifTyp(char certTyp, String certTypDescr, String module) {
		this.certTyp = certTyp;
		this.certTypDescr = certTypDescr;
		this.module = module;
	}

	@Id

	@Column(name = "CERT_TYP", nullable = false, length = 1)
	public char getCertTyp() {
		return this.certTyp;
	}

	public void setCertTyp(char certTyp) {
		this.certTyp = certTyp;
	}

	@Column(name = "CERT_TYP_DESCR", nullable = false, length = 20)
	public String getCertTypDescr() {
		return this.certTypDescr;
	}

	public void setCertTypDescr(String certTypDescr) {
		this.certTypDescr = certTypDescr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
