package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrLvTypBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LV_TYP_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrLvTypBkupPaycalcs5 implements java.io.Serializable {

	private BthrLvTypBkupPaycalcs5Id id;

	public BthrLvTypBkupPaycalcs5() {
	}

	public BthrLvTypBkupPaycalcs5(BthrLvTypBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "chkStubPos", column = @Column(name = "CHK_STUB_POS", nullable = false, length = 1)),
			@AttributeOverride(name = "maxBal", column = @Column(name = "MAX_BAL", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "daysHrs", column = @Column(name = "DAYS_HRS", nullable = false, length = 3)),
			@AttributeOverride(name = "dockWithBal", column = @Column(name = "DOCK_WITH_BAL", nullable = false, length = 1)),
			@AttributeOverride(name = "addSubtractBal", column = @Column(name = "ADD_SUBTRACT_BAL", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "stat", column = @Column(name = "STAT", nullable = false, length = 1)) })
	public BthrLvTypBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrLvTypBkupPaycalcs5Id id) {
		this.id = id;
	}

}
