package com.esc20.model;
// Generated Jan 4, 2019 3:49:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrAbsRsnToLvTypBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ABS_RSN_TO_LV_TYP_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrAbsRsnToLvTypBkupPaycalcs5 implements java.io.Serializable {

	private BthrAbsRsnToLvTypBkupPaycalcs5Id id;

	public BthrAbsRsnToLvTypBkupPaycalcs5() {
	}

	public BthrAbsRsnToLvTypBkupPaycalcs5(BthrAbsRsnToLvTypBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "absRsn", column = @Column(name = "ABS_RSN", nullable = false, length = 2)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrAbsRsnToLvTypBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrAbsRsnToLvTypBkupPaycalcs5Id id) {
		this.id = id;
	}

}
