package com.esc20.model;
// Generated Jan 4, 2019 3:53:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrPayFreqBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_PAY_FREQ_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrPayFreqBkupPaycalcs5 implements java.io.Serializable {

	private BthrPayFreqBkupPaycalcs5Id id;

	public BthrPayFreqBkupPaycalcs5() {
	}

	public BthrPayFreqBkupPaycalcs5(BthrPayFreqBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreqDescr", column = @Column(name = "PAY_FREQ_DESCR", nullable = false, length = 20)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrPayFreqBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrPayFreqBkupPaycalcs5Id id) {
		this.id = id;
	}

}
