package com.esc20.model;
// Generated Jan 4, 2019 3:54:58 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrZeroDaysRsnCd generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ZERO_DAYS_RSN_CD", schema = "rsccc", catalog = "rsccc")
public class BthrZeroDaysRsnCd implements java.io.Serializable {

	private BthrZeroDaysRsnCdId id;
	private String zeroDaysDesc;

	public BthrZeroDaysRsnCd() {
	}

	public BthrZeroDaysRsnCd(BthrZeroDaysRsnCdId id, String zeroDaysDesc) {
		this.id = id;
		this.zeroDaysDesc = zeroDaysDesc;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "zeroDaysRecTyp", column = @Column(name = "ZERO_DAYS_REC_TYP", nullable = false, length = 4)),
			@AttributeOverride(name = "zeroDaysRsnCd", column = @Column(name = "ZERO_DAYS_RSN_CD", nullable = false, length = 1)) })
	public BthrZeroDaysRsnCdId getId() {
		return this.id;
	}

	public void setId(BthrZeroDaysRsnCdId id) {
		this.id = id;
	}

	@Column(name = "ZERO_DAYS_DESC", nullable = false, length = 60)
	public String getZeroDaysDesc() {
		return this.zeroDaysDesc;
	}

	public void setZeroDaysDesc(String zeroDaysDesc) {
		this.zeroDaysDesc = zeroDaysDesc;
	}

}
