package com.esc20.model;
// Generated Jan 4, 2019 3:54:58 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BthrSubTime generated by hbm2java
 */
@Entity
@Table(name = "BTHR_SUB_TIME", schema = "rsccc", catalog = "rsccc")
public class BthrSubTime implements java.io.Serializable {

	private BthrSubTimeId id;
	private BthrSubTyp bthrSubTyp;
	private String tmDescr;
	private BigDecimal unitsPerDay;
	private BigDecimal payAmt;
	private String module;
	private BigDecimal lvUnts;

	public BthrSubTime() {
	}

	public BthrSubTime(BthrSubTimeId id, BthrSubTyp bthrSubTyp, String tmDescr, BigDecimal unitsPerDay,
			BigDecimal payAmt, String module, BigDecimal lvUnts) {
		this.id = id;
		this.bthrSubTyp = bthrSubTyp;
		this.tmDescr = tmDescr;
		this.unitsPerDay = unitsPerDay;
		this.payAmt = payAmt;
		this.module = module;
		this.lvUnts = lvUnts;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tmOfDay", column = @Column(name = "TM_OF_DAY", nullable = false, length = 1)),
			@AttributeOverride(name = "subTyp", column = @Column(name = "SUB_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)) })
	public BthrSubTimeId getId() {
		return this.id;
	}

	public void setId(BthrSubTimeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUB_TYP", nullable = false, insertable = false, updatable = false)
	public BthrSubTyp getBthrSubTyp() {
		return this.bthrSubTyp;
	}

	public void setBthrSubTyp(BthrSubTyp bthrSubTyp) {
		this.bthrSubTyp = bthrSubTyp;
	}

	@Column(name = "TM_DESCR", nullable = false, length = 20)
	public String getTmDescr() {
		return this.tmDescr;
	}

	public void setTmDescr(String tmDescr) {
		this.tmDescr = tmDescr;
	}

	@Column(name = "UNITS_PER_DAY", nullable = false, precision = 3, scale = 1)
	public BigDecimal getUnitsPerDay() {
		return this.unitsPerDay;
	}

	public void setUnitsPerDay(BigDecimal unitsPerDay) {
		this.unitsPerDay = unitsPerDay;
	}

	@Column(name = "PAY_AMT", nullable = false, precision = 5)
	public BigDecimal getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "LV_UNTS", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvUnts() {
		return this.lvUnts;
	}

	public void setLvUnts(BigDecimal lvUnts) {
		this.lvUnts = lvUnts;
	}

}
