package com.esc20.model;
// Generated Jan 4, 2019 3:53:34 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BthrMidPointBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BthrMidPointBkupPaycalcs5Id implements java.io.Serializable {

	private char cyrNyrFlg;
	private String payGrd;
	private char payTyp;
	private BigDecimal min;
	private BigDecimal max;
	private BigDecimal midPoint;
	private BigDecimal hrs;
	private char dockRateTyp;
	private String module;

	public BthrMidPointBkupPaycalcs5Id() {
	}

	public BthrMidPointBkupPaycalcs5Id(char cyrNyrFlg, String payGrd, char payTyp, BigDecimal min, BigDecimal max,
			BigDecimal midPoint, BigDecimal hrs, char dockRateTyp, String module) {
		this.cyrNyrFlg = cyrNyrFlg;
		this.payGrd = payGrd;
		this.payTyp = payTyp;
		this.min = min;
		this.max = max;
		this.midPoint = midPoint;
		this.hrs = hrs;
		this.dockRateTyp = dockRateTyp;
		this.module = module;
	}

	@Column(name = "CYR_NYR_FLG", nullable = false, length = 1)
	public char getCyrNyrFlg() {
		return this.cyrNyrFlg;
	}

	public void setCyrNyrFlg(char cyrNyrFlg) {
		this.cyrNyrFlg = cyrNyrFlg;
	}

	@Column(name = "PAY_GRD", nullable = false, length = 3)
	public String getPayGrd() {
		return this.payGrd;
	}

	public void setPayGrd(String payGrd) {
		this.payGrd = payGrd;
	}

	@Column(name = "PAY_TYP", nullable = false, length = 1)
	public char getPayTyp() {
		return this.payTyp;
	}

	public void setPayTyp(char payTyp) {
		this.payTyp = payTyp;
	}

	@Column(name = "MIN", nullable = false, precision = 6, scale = 3)
	public BigDecimal getMin() {
		return this.min;
	}

	public void setMin(BigDecimal min) {
		this.min = min;
	}

	@Column(name = "MAX", nullable = false, precision = 6, scale = 3)
	public BigDecimal getMax() {
		return this.max;
	}

	public void setMax(BigDecimal max) {
		this.max = max;
	}

	@Column(name = "MID_POINT", nullable = false, precision = 6, scale = 3)
	public BigDecimal getMidPoint() {
		return this.midPoint;
	}

	public void setMidPoint(BigDecimal midPoint) {
		this.midPoint = midPoint;
	}

	@Column(name = "HRS", nullable = false, precision = 4)
	public BigDecimal getHrs() {
		return this.hrs;
	}

	public void setHrs(BigDecimal hrs) {
		this.hrs = hrs;
	}

	@Column(name = "DOCK_RATE_TYP", nullable = false, length = 1)
	public char getDockRateTyp() {
		return this.dockRateTyp;
	}

	public void setDockRateTyp(char dockRateTyp) {
		this.dockRateTyp = dockRateTyp;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BthrMidPointBkupPaycalcs5Id))
			return false;
		BthrMidPointBkupPaycalcs5Id castOther = (BthrMidPointBkupPaycalcs5Id) other;

		return (this.getCyrNyrFlg() == castOther.getCyrNyrFlg())
				&& ((this.getPayGrd() == castOther.getPayGrd()) || (this.getPayGrd() != null
						&& castOther.getPayGrd() != null && this.getPayGrd().equals(castOther.getPayGrd())))
				&& (this.getPayTyp() == castOther.getPayTyp())
				&& ((this.getMin() == castOther.getMin()) || (this.getMin() != null && castOther.getMin() != null
						&& this.getMin().equals(castOther.getMin())))
				&& ((this.getMax() == castOther.getMax()) || (this.getMax() != null && castOther.getMax() != null
						&& this.getMax().equals(castOther.getMax())))
				&& ((this.getMidPoint() == castOther.getMidPoint()) || (this.getMidPoint() != null
						&& castOther.getMidPoint() != null && this.getMidPoint().equals(castOther.getMidPoint())))
				&& ((this.getHrs() == castOther.getHrs()) || (this.getHrs() != null && castOther.getHrs() != null
						&& this.getHrs().equals(castOther.getHrs())))
				&& (this.getDockRateTyp() == castOther.getDockRateTyp())
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCyrNyrFlg();
		result = 37 * result + (getPayGrd() == null ? 0 : this.getPayGrd().hashCode());
		result = 37 * result + this.getPayTyp();
		result = 37 * result + (getMin() == null ? 0 : this.getMin().hashCode());
		result = 37 * result + (getMax() == null ? 0 : this.getMax().hashCode());
		result = 37 * result + (getMidPoint() == null ? 0 : this.getMidPoint().hashCode());
		result = 37 * result + (getHrs() == null ? 0 : this.getHrs().hashCode());
		result = 37 * result + this.getDockRateTyp();
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		return result;
	}

}
