package com.esc20.model;
// Generated Jan 4, 2019 3:53:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrPayDatesBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_PAY_DATES_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrPayDatesBkupPaycalcs5 implements java.io.Serializable {

	private BthrPayDatesBkupPaycalcs5Id id;

	public BthrPayDatesBkupPaycalcs5() {
	}

	public BthrPayDatesBkupPaycalcs5(BthrPayDatesBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "dtPayperBeg", column = @Column(name = "DT_PAYPER_BEG", nullable = false, length = 8)),
			@AttributeOverride(name = "dtPayperEnd", column = @Column(name = "DT_PAYPER_END", nullable = false, length = 8)),
			@AttributeOverride(name = "trsMonth", column = @Column(name = "TRS_MONTH", nullable = false, length = 2)),
			@AttributeOverride(name = "twcQtr", column = @Column(name = "TWC_QTR", nullable = false, length = 1)),
			@AttributeOverride(name = "useAltAddr", column = @Column(name = "USE_ALT_ADDR", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "lvReqCutoffDt", column = @Column(name = "LV_REQ_CUTOFF_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "lvLastAprvDt", column = @Column(name = "LV_LAST_APRV_DT", nullable = false, length = 8)) })
	public BthrPayDatesBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrPayDatesBkupPaycalcs5Id id) {
		this.id = id;
	}

}
