package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrFundToGrantBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_FUND_TO_GRANT_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrFundToGrantBkupPaycalcs5 implements java.io.Serializable {

	private BthrFundToGrantBkupPaycalcs5Id id;

	public BthrFundToGrantBkupPaycalcs5() {
	}

	public BthrFundToGrantBkupPaycalcs5(BthrFundToGrantBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "trsGrantCd", column = @Column(name = "TRS_GRANT_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "glFileId", column = @Column(name = "GL_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "fund", column = @Column(name = "FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "fsclYr", column = @Column(name = "FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrFundToGrantBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrFundToGrantBkupPaycalcs5Id id) {
		this.id = id;
	}

}
