package com.esc20.model;
// Generated Jan 4, 2019 3:54:58 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrTrsRateBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_TRS_RATE_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrTrsRateBkupPaycalcs5 implements java.io.Serializable {

	private BthrTrsRateBkupPaycalcs5Id id;

	public BthrTrsRateBkupPaycalcs5() {
	}

	public BthrTrsRateBkupPaycalcs5(BthrTrsRateBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "trsPct", column = @Column(name = "TRS_PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "trsFee", column = @Column(name = "TRS_FEE", nullable = false, precision = 5)),
			@AttributeOverride(name = "trsIns", column = @Column(name = "TRS_INS", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "districtPct", column = @Column(name = "DISTRICT_PCT", nullable = false, precision = 6, scale = 5)),
			@AttributeOverride(name = "trsCarePct", column = @Column(name = "TRS_CARE_PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "emplrTrsCareContribPct", column = @Column(name = "EMPLR_TRS_CARE_CONTRIB_PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "trs90DaysSocSecFlg", column = @Column(name = "TRS_90_DAYS_SOC_SEC_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "trsIrsSalCap", column = @Column(name = "TRS_IRS_SAL_CAP", nullable = false, precision = 9)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "emplrTrsNonOasdiPct", column = @Column(name = "EMPLR_TRS_NON_OASDI_PCT", nullable = false, precision = 6, scale = 5)) })
	public BthrTrsRateBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrTrsRateBkupPaycalcs5Id id) {
		this.id = id;
	}

}
