package com.esc20.model;
// Generated Jan 4, 2019 3:50:10 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrAccrualExpBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ACCRUAL_EXP_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrAccrualExpBkupPaycalcs5 implements java.io.Serializable {

	private BthrAccrualExpBkupPaycalcs5Id id;

	public BthrAccrualExpBkupPaycalcs5() {
	}

	public BthrAccrualExpBkupPaycalcs5(BthrAccrualExpBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "fund", column = @Column(name = "FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "expFsclYr", column = @Column(name = "EXP_FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "fundDescr", column = @Column(name = "FUND_DESCR", nullable = false, length = 30)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrAccrualExpBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrAccrualExpBkupPaycalcs5Id id) {
		this.id = id;
	}

}
