package com.esc20.model;
// Generated Jan 4, 2019 3:54:39 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrSimPmisOptDed generated by hbm2java
 */
@Entity
@Table(name = "BTHR_SIM_PMIS_OPT_DED", schema = "rsccc", catalog = "rsccc")
public class BthrSimPmisOptDed implements java.io.Serializable {

	private BthrSimPmisOptDedId id;
	private BigDecimal empAmt;
	private BigDecimal emplrAmt;
	private BigDecimal teaHlthInsAmt;
	private char inclVacPos;
	private String module;

	public BthrSimPmisOptDed() {
	}

	public BthrSimPmisOptDed(BthrSimPmisOptDedId id, BigDecimal empAmt, BigDecimal emplrAmt, BigDecimal teaHlthInsAmt,
			char inclVacPos, String module) {
		this.id = id;
		this.empAmt = empAmt;
		this.emplrAmt = emplrAmt;
		this.teaHlthInsAmt = teaHlthInsAmt;
		this.inclVacPos = inclVacPos;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "simName", column = @Column(name = "SIM_NAME", nullable = false, length = 7)),
			@AttributeOverride(name = "dedCd", column = @Column(name = "DED_CD", nullable = false, length = 3)) })
	public BthrSimPmisOptDedId getId() {
		return this.id;
	}

	public void setId(BthrSimPmisOptDedId id) {
		this.id = id;
	}

	@Column(name = "EMP_AMT", nullable = false, precision = 7)
	public BigDecimal getEmpAmt() {
		return this.empAmt;
	}

	public void setEmpAmt(BigDecimal empAmt) {
		this.empAmt = empAmt;
	}

	@Column(name = "EMPLR_AMT", nullable = false, precision = 7)
	public BigDecimal getEmplrAmt() {
		return this.emplrAmt;
	}

	public void setEmplrAmt(BigDecimal emplrAmt) {
		this.emplrAmt = emplrAmt;
	}

	@Column(name = "TEA_HLTH_INS_AMT", nullable = false, precision = 7)
	public BigDecimal getTeaHlthInsAmt() {
		return this.teaHlthInsAmt;
	}

	public void setTeaHlthInsAmt(BigDecimal teaHlthInsAmt) {
		this.teaHlthInsAmt = teaHlthInsAmt;
	}

	@Column(name = "INCL_VAC_POS", nullable = false, length = 1)
	public char getInclVacPos() {
		return this.inclVacPos;
	}

	public void setInclVacPos(char inclVacPos) {
		this.inclVacPos = inclVacPos;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
