package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrLvUntsConv generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LV_UNTS_CONV", schema = "rsccc", catalog = "rsccc")
public class BthrLvUntsConv implements java.io.Serializable {

	private BthrLvUntsConvId id;
	private BigDecimal pctOfHrDay;
	private String module;

	public BthrLvUntsConv() {
	}

	public BthrLvUntsConv(BthrLvUntsConvId id, BigDecimal pctOfHrDay, String module) {
		this.id = id;
		this.pctOfHrDay = pctOfHrDay;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "upToMin", column = @Column(name = "UP_TO_MIN", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "upToHr", column = @Column(name = "UP_TO_HR", nullable = false, precision = 4)) })
	public BthrLvUntsConvId getId() {
		return this.id;
	}

	public void setId(BthrLvUntsConvId id) {
		this.id = id;
	}

	@Column(name = "PCT_OF_HR_DAY", nullable = false, precision = 4, scale = 3)
	public BigDecimal getPctOfHrDay() {
		return this.pctOfHrDay;
	}

	public void setPctOfHrDay(BigDecimal pctOfHrDay) {
		this.pctOfHrDay = pctOfHrDay;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
