package com.esc20.model;
// Generated Jan 4, 2019 3:49:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrAca1095cLineCd generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ACA_1095C_LINE_CD", schema = "rsccc", catalog = "rsccc")
public class BthrAca1095cLineCd implements java.io.Serializable {

	private BthrAca1095cLineCdId id;
	private String lineCdShortDesc;
	private String module;

	public BthrAca1095cLineCd() {
	}

	public BthrAca1095cLineCd(BthrAca1095cLineCdId id, String lineCdShortDesc, String module) {
		this.id = id;
		this.lineCdShortDesc = lineCdShortDesc;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "calYr", column = @Column(name = "CAL_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "lineNbr", column = @Column(name = "LINE_NBR", nullable = false, length = 2)),
			@AttributeOverride(name = "lineCd", column = @Column(name = "LINE_CD", nullable = false, length = 2)) })
	public BthrAca1095cLineCdId getId() {
		return this.id;
	}

	public void setId(BthrAca1095cLineCdId id) {
		this.id = id;
	}

	@Column(name = "LINE_CD_SHORT_DESC", nullable = false, length = 80)
	public String getLineCdShortDesc() {
		return this.lineCdShortDesc;
	}

	public void setLineCdShortDesc(String lineCdShortDesc) {
		this.lineCdShortDesc = lineCdShortDesc;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
