package com.esc20.model;
// Generated Jan 4, 2019 3:54:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrPosFrstPayDt generated by hbm2java
 */
@Entity
@Table(name = "BTHR_POS_FRST_PAY_DT", schema = "rsccc", catalog = "rsccc")
public class BthrPosFrstPayDt implements java.io.Serializable {

	private BthrPosFrstPayDtId id;
	private String frstYrDtOfPay;
	private String module;
	private String frstPayDtDescr;

	public BthrPosFrstPayDt() {
	}

	public BthrPosFrstPayDt(BthrPosFrstPayDtId id, String frstYrDtOfPay, String module, String frstPayDtDescr) {
		this.id = id;
		this.frstYrDtOfPay = frstYrDtOfPay;
		this.module = module;
		this.frstPayDtDescr = frstPayDtDescr;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "frstPayDtCd", column = @Column(name = "FRST_PAY_DT_CD", nullable = false, length = 3)) })
	public BthrPosFrstPayDtId getId() {
		return this.id;
	}

	public void setId(BthrPosFrstPayDtId id) {
		this.id = id;
	}

	@Column(name = "FRST_YR_DT_OF_PAY", nullable = false, length = 8)
	public String getFrstYrDtOfPay() {
		return this.frstYrDtOfPay;
	}

	public void setFrstYrDtOfPay(String frstYrDtOfPay) {
		this.frstYrDtOfPay = frstYrDtOfPay;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "FRST_PAY_DT_DESCR", nullable = false, length = 25)
	public String getFrstPayDtDescr() {
		return this.frstPayDtDescr;
	}

	public void setFrstPayDtDescr(String frstPayDtDescr) {
		this.frstPayDtDescr = frstPayDtDescr;
	}

}
