package com.esc20.model;
// Generated Jan 4, 2019 3:54:39 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrSimOptBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_SIM_OPT_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrSimOptBkupPaycalcs5 implements java.io.Serializable {

	private BthrSimOptBkupPaycalcs5Id id;

	public BthrSimOptBkupPaycalcs5() {
	}

	public BthrSimOptBkupPaycalcs5(BthrSimOptBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "simName", column = @Column(name = "SIM_NAME", nullable = false, length = 7)),
			@AttributeOverride(name = "simDescr", column = @Column(name = "SIM_DESCR", nullable = false, length = 30)),
			@AttributeOverride(name = "usrId", column = @Column(name = "USR_ID", nullable = false, length = 12)),
			@AttributeOverride(name = "updtFrcstFlg", column = @Column(name = "UPDT_FRCST_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "updtBudFlg", column = @Column(name = "UPDT_BUD_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "inclProposPos", column = @Column(name = "INCL_PROPOS_POS", nullable = false, length = 1)),
			@AttributeOverride(name = "inclVacSupplPos", column = @Column(name = "INCL_VAC_SUPPL_POS", nullable = false, length = 1)),
			@AttributeOverride(name = "incrPayStp", column = @Column(name = "INCR_PAY_STP", nullable = false, length = 1)),
			@AttributeOverride(name = "maxAnnlPayStp", column = @Column(name = "MAX_ANNL_PAY_STP", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "maxHrlyPayStp", column = @Column(name = "MAX_HRLY_PAY_STP", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "incrStStp", column = @Column(name = "INCR_ST_STP", nullable = false, length = 1)),
			@AttributeOverride(name = "actToBudInd", column = @Column(name = "ACT_TO_BUD_IND", nullable = false, length = 1)),
			@AttributeOverride(name = "updtBudAmtFlg", column = @Column(name = "UPDT_BUD_AMT_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "updtBudRndFlg", column = @Column(name = "UPDT_BUD_RND_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "inclTrsOnbehalfCalcs", column = @Column(name = "INCL_TRS_ONBEHALF_CALCS", nullable = false, length = 1)),
			@AttributeOverride(name = "trsOnBehalfExpAcct", column = @Column(name = "TRS_ON_BEHALF_EXP_ACCT", nullable = false, length = 20)),
			@AttributeOverride(name = "midpntSalUpdtFlg", column = @Column(name = "MIDPNT_SAL_UPDT_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "incrSalToMidpntMin", column = @Column(name = "INCR_SAL_TO_MIDPNT_MIN", nullable = false, length = 1)),
			@AttributeOverride(name = "inclTeaHlthIns", column = @Column(name = "INCL_TEA_HLTH_INS", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrSimOptBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrSimOptBkupPaycalcs5Id id) {
		this.id = id;
	}

}
