package com.esc20.model;
// Generated Jan 4, 2019 3:51:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrEarnIncomeBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_EARN_INCOME_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrEarnIncomeBkupPaycalcs5 implements java.io.Serializable {

	private BthrEarnIncomeBkupPaycalcs5Id id;

	public BthrEarnIncomeBkupPaycalcs5() {
	}

	public BthrEarnIncomeBkupPaycalcs5(BthrEarnIncomeBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxYr", column = @Column(name = "TAX_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "marriedSingleFlg", column = @Column(name = "MARRIED_SINGLE_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "overAmt", column = @Column(name = "OVER_AMT", nullable = false, precision = 6)),
			@AttributeOverride(name = "notOver", column = @Column(name = "NOT_OVER", nullable = false, precision = 6)),
			@AttributeOverride(name = "pctOfWgs", column = @Column(name = "PCT_OF_WGS", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "adv", column = @Column(name = "ADV", nullable = false, precision = 6)),
			@AttributeOverride(name = "pctOfReductn", column = @Column(name = "PCT_OF_REDUCTN", nullable = false, precision = 6, scale = 5)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrEarnIncomeBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrEarnIncomeBkupPaycalcs5Id id) {
		this.id = id;
	}

}
