package com.esc20.model;
// Generated Jan 4, 2019 3:54:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrPlanTyp generated by hbm2java
 */
@Entity
@Table(name = "BTHR_PLAN_TYP", schema = "rsccc", catalog = "rsccc")
public class BthrPlanTyp implements java.io.Serializable {

	private char planTyp;
	private String planTypDescr;

	public BthrPlanTyp() {
	}

	public BthrPlanTyp(char planTyp, String planTypDescr) {
		this.planTyp = planTyp;
		this.planTypDescr = planTypDescr;
	}

	@Id

	@Column(name = "PLAN_TYP", nullable = false, length = 1)
	public char getPlanTyp() {
		return this.planTyp;
	}

	public void setPlanTyp(char planTyp) {
		this.planTyp = planTyp;
	}

	@Column(name = "PLAN_TYP_DESCR", nullable = false, length = 20)
	public String getPlanTypDescr() {
		return this.planTypDescr;
	}

	public void setPlanTypDescr(String planTypDescr) {
		this.planTypDescr = planTypDescr;
	}

}
