package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BthrInsurPlan generated by hbm2java
 */
@Entity
@Table(name = "BTHR_INSUR_PLAN", schema = "rsccc", catalog = "rsccc")
public class BthrInsurPlan implements java.io.Serializable {

	private BthrInsurPlanId id;
	private BthrInsurCompany bthrInsurCompany;
	private String planDescr;
	private String grpNbr;
	private String module;
	private char selfIns;

	public BthrInsurPlan() {
	}

	public BthrInsurPlan(BthrInsurPlanId id, BthrInsurCompany bthrInsurCompany, String planDescr, String grpNbr,
			String module, char selfIns) {
		this.id = id;
		this.bthrInsurCompany = bthrInsurCompany;
		this.planDescr = planDescr;
		this.grpNbr = grpNbr;
		this.module = module;
		this.selfIns = selfIns;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "companyCd", column = @Column(name = "COMPANY_CD", nullable = false, length = 5)),
			@AttributeOverride(name = "planNbr", column = @Column(name = "PLAN_NBR", nullable = false, length = 20)) })
	public BthrInsurPlanId getId() {
		return this.id;
	}

	public void setId(BthrInsurPlanId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_CD", nullable = false, insertable = false, updatable = false)
	public BthrInsurCompany getBthrInsurCompany() {
		return this.bthrInsurCompany;
	}

	public void setBthrInsurCompany(BthrInsurCompany bthrInsurCompany) {
		this.bthrInsurCompany = bthrInsurCompany;
	}

	@Column(name = "PLAN_DESCR", nullable = false, length = 20)
	public String getPlanDescr() {
		return this.planDescr;
	}

	public void setPlanDescr(String planDescr) {
		this.planDescr = planDescr;
	}

	@Column(name = "GRP_NBR", nullable = false, length = 20)
	public String getGrpNbr() {
		return this.grpNbr;
	}

	public void setGrpNbr(String grpNbr) {
		this.grpNbr = grpNbr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "SELF_INS", nullable = false, length = 1)
	public char getSelfIns() {
		return this.selfIns;
	}

	public void setSelfIns(char selfIns) {
		this.selfIns = selfIns;
	}

}
