package com.esc20.model;
// Generated Jan 4, 2019 3:50:32 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrAreaSpecial generated by hbm2java
 */
@Entity
@Table(name = "BTHR_AREA_SPECIAL", schema = "rsccc", catalog = "rsccc")
public class BthrAreaSpecial implements java.io.Serializable {

	private String areaSpec;
	private String areaSpecDescr;
	private String module;

	public BthrAreaSpecial() {
	}

	public BthrAreaSpecial(String areaSpec, String areaSpecDescr, String module) {
		this.areaSpec = areaSpec;
		this.areaSpecDescr = areaSpecDescr;
		this.module = module;
	}

	@Id

	@Column(name = "AREA_SPEC", nullable = false, length = 2)
	public String getAreaSpec() {
		return this.areaSpec;
	}

	public void setAreaSpec(String areaSpec) {
		this.areaSpec = areaSpec;
	}

	@Column(name = "AREA_SPEC_DESCR", nullable = false, length = 20)
	public String getAreaSpecDescr() {
		return this.areaSpecDescr;
	}

	public void setAreaSpecDescr(String areaSpecDescr) {
		this.areaSpecDescr = areaSpecDescr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
