package com.esc20.model;
// Generated Jan 4, 2019 3:48:53 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bthr457DefBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_457_DEF_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class Bthr457DefBkupPaycalcs5 implements java.io.Serializable {

	private Bthr457DefBkupPaycalcs5Id id;

	public Bthr457DefBkupPaycalcs5() {
	}

	public Bthr457DefBkupPaycalcs5(Bthr457DefBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxYr", column = @Column(name = "TAX_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "emp457Pct", column = @Column(name = "EMP_457_PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "emplr457Pct", column = @Column(name = "EMPLR_457_PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public Bthr457DefBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(Bthr457DefBkupPaycalcs5Id id) {
		this.id = id;
	}

}
