package com.esc20.model;
// Generated Jan 4, 2019 3:50:10 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BthrAccrualCd generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ACCRUAL_CD", schema = "rsccc", catalog = "rsccc")
public class BthrAccrualCd implements java.io.Serializable {

	private BthrAccrualCdId id;
	private BigDecimal totNbrDaysEarned;
	private String module;
	private Set<BthrAccrualDays> bthrAccrualDayses = new HashSet<BthrAccrualDays>(0);

	public BthrAccrualCd() {
	}

	public BthrAccrualCd(BthrAccrualCdId id, BigDecimal totNbrDaysEarned, String module) {
		this.id = id;
		this.totNbrDaysEarned = totNbrDaysEarned;
		this.module = module;
	}

	public BthrAccrualCd(BthrAccrualCdId id, BigDecimal totNbrDaysEarned, String module,
			Set<BthrAccrualDays> bthrAccrualDayses) {
		this.id = id;
		this.totNbrDaysEarned = totNbrDaysEarned;
		this.module = module;
		this.bthrAccrualDayses = bthrAccrualDayses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "accruCd", column = @Column(name = "ACCRU_CD", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)) })
	public BthrAccrualCdId getId() {
		return this.id;
	}

	public void setId(BthrAccrualCdId id) {
		this.id = id;
	}

	@Column(name = "TOT_NBR_DAYS_EARNED", nullable = false, precision = 5)
	public BigDecimal getTotNbrDaysEarned() {
		return this.totNbrDaysEarned;
	}

	public void setTotNbrDaysEarned(BigDecimal totNbrDaysEarned) {
		this.totNbrDaysEarned = totNbrDaysEarned;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bthrAccrualCd")
	public Set<BthrAccrualDays> getBthrAccrualDayses() {
		return this.bthrAccrualDayses;
	}

	public void setBthrAccrualDayses(Set<BthrAccrualDays> bthrAccrualDayses) {
		this.bthrAccrualDayses = bthrAccrualDayses;
	}

}
