package com.esc20.model;
// Generated Jan 4, 2019 3:54:39 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrSimExtraDutyBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_SIM_EXTRA_DUTY_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrSimExtraDutyBkupPaycalcs5 implements java.io.Serializable {

	private BthrSimExtraDutyBkupPaycalcs5Id id;

	public BthrSimExtraDutyBkupPaycalcs5() {
	}

	public BthrSimExtraDutyBkupPaycalcs5(BthrSimExtraDutyBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "simName", column = @Column(name = "SIM_NAME", nullable = false, length = 7)),
			@AttributeOverride(name = "extraDutyCd", column = @Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "amtChg", column = @Column(name = "AMT_CHG", nullable = false, precision = 9)),
			@AttributeOverride(name = "pctChg", column = @Column(name = "PCT_CHG", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "supplExtraDays", column = @Column(name = "SUPPL_EXTRA_DAYS", nullable = false, precision = 3, scale = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrSimExtraDutyBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrSimExtraDutyBkupPaycalcs5Id id) {
		this.id = id;
	}

}
