package com.esc20.model;
// Generated Jan 4, 2019 3:49:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BthrAbsRsnToLvTypBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BthrAbsRsnToLvTypBkupPaycalcs5Id implements java.io.Serializable {

	private String absRsn;
	private String lvTyp;
	private String module;

	public BthrAbsRsnToLvTypBkupPaycalcs5Id() {
	}

	public BthrAbsRsnToLvTypBkupPaycalcs5Id(String absRsn, String lvTyp, String module) {
		this.absRsn = absRsn;
		this.lvTyp = lvTyp;
		this.module = module;
	}

	@Column(name = "ABS_RSN", nullable = false, length = 2)
	public String getAbsRsn() {
		return this.absRsn;
	}

	public void setAbsRsn(String absRsn) {
		this.absRsn = absRsn;
	}

	@Column(name = "LV_TYP", nullable = false, length = 2)
	public String getLvTyp() {
		return this.lvTyp;
	}

	public void setLvTyp(String lvTyp) {
		this.lvTyp = lvTyp;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BthrAbsRsnToLvTypBkupPaycalcs5Id))
			return false;
		BthrAbsRsnToLvTypBkupPaycalcs5Id castOther = (BthrAbsRsnToLvTypBkupPaycalcs5Id) other;

		return ((this.getAbsRsn() == castOther.getAbsRsn()) || (this.getAbsRsn() != null
				&& castOther.getAbsRsn() != null && this.getAbsRsn().equals(castOther.getAbsRsn())))
				&& ((this.getLvTyp() == castOther.getLvTyp()) || (this.getLvTyp() != null
						&& castOther.getLvTyp() != null && this.getLvTyp().equals(castOther.getLvTyp())))
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAbsRsn() == null ? 0 : this.getAbsRsn().hashCode());
		result = 37 * result + (getLvTyp() == null ? 0 : this.getLvTyp().hashCode());
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		return result;
	}

}
