package com.esc20.model;
// Generated Jan 4, 2019 3:49:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BthrAbsRsnToLvTyp generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ABS_RSN_TO_LV_TYP", schema = "rsccc", catalog = "rsccc")
public class BthrAbsRsnToLvTyp implements java.io.Serializable {

	private BthrAbsRsnToLvTypId id;
	private BthrAbsRsn bthrAbsRsn;
	private String module;

	public BthrAbsRsnToLvTyp() {
	}

	public BthrAbsRsnToLvTyp(BthrAbsRsnToLvTypId id, BthrAbsRsn bthrAbsRsn, String module) {
		this.id = id;
		this.bthrAbsRsn = bthrAbsRsn;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "absRsn", column = @Column(name = "ABS_RSN", nullable = false, length = 2)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)) })
	public BthrAbsRsnToLvTypId getId() {
		return this.id;
	}

	public void setId(BthrAbsRsnToLvTypId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ABS_RSN", nullable = false, insertable = false, updatable = false)
	public BthrAbsRsn getBthrAbsRsn() {
		return this.bthrAbsRsn;
	}

	public void setBthrAbsRsn(BthrAbsRsn bthrAbsRsn) {
		this.bthrAbsRsn = bthrAbsRsn;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
