package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrLocAnnualSalaryBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LOC_ANNUAL_SALARY_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrLocAnnualSalaryBkupPaycalcs5 implements java.io.Serializable {

	private BthrLocAnnualSalaryBkupPaycalcs5Id id;

	public BthrLocAnnualSalaryBkupPaycalcs5() {
	}

	public BthrLocAnnualSalaryBkupPaycalcs5(BthrLocAnnualSalaryBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payGrd", column = @Column(name = "PAY_GRD", nullable = false, length = 3)),
			@AttributeOverride(name = "payStep", column = @Column(name = "PAY_STEP", nullable = false, length = 2)),
			@AttributeOverride(name = "maxDays", column = @Column(name = "MAX_DAYS", nullable = false, length = 3)),
			@AttributeOverride(name = "sched", column = @Column(name = "SCHED", nullable = false, length = 1)),
			@AttributeOverride(name = "annualAmt", column = @Column(name = "ANNUAL_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrLocAnnualSalaryBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrLocAnnualSalaryBkupPaycalcs5Id id) {
		this.id = id;
	}

}
