package com.esc20.model;
// Generated Jan 10, 2019 9:13:30 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EtC015Highdeg generated by hbm2java
 */
@Entity
@Table(name = "ET_C015_HIGHDEG", schema = "rsccc", catalog = "rsccc")
public class EtC015Highdeg implements java.io.Serializable {

	private EtC015HighdegId id;
	private String highdegDescr;

	public EtC015Highdeg() {
	}

	public EtC015Highdeg(EtC015HighdegId id, String highdegDescr) {
		this.id = id;
		this.highdegDescr = highdegDescr;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schYr", column = @Column(name = "SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "highdegCd", column = @Column(name = "HIGHDEG_CD", nullable = false, length = 1)) })
	public EtC015HighdegId getId() {
		return this.id;
	}

	public void setId(EtC015HighdegId id) {
		this.id = id;
	}

	@Column(name = "HIGHDEG_DESCR", nullable = false, length = 20)
	public String getHighdegDescr() {
		return this.highdegDescr;
	}

	public void setHighdegDescr(String highdegDescr) {
		this.highdegDescr = highdegDescr;
	}

}
