package com.esc20.model;
// Generated Jan 4, 2019 3:55:15 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImageType generated by hbm2java
 */
@Entity
@Table(name = "IMAGE_TYPE", schema = "rsccc", catalog = "rsccc")
public class ImageType implements java.io.Serializable {

	private int imageTypeId;
	private String imageType;
	private Set<ImageStorage> imageStorages = new HashSet<ImageStorage>(0);

	public ImageType() {
	}

	public ImageType(int imageTypeId, String imageType) {
		this.imageTypeId = imageTypeId;
		this.imageType = imageType;
	}

	public ImageType(int imageTypeId, String imageType, Set<ImageStorage> imageStorages) {
		this.imageTypeId = imageTypeId;
		this.imageType = imageType;
		this.imageStorages = imageStorages;
	}

	@Id

	@Column(name = "IMAGE_TYPE_ID", nullable = false)
	public int getImageTypeId() {
		return this.imageTypeId;
	}

	public void setImageTypeId(int imageTypeId) {
		this.imageTypeId = imageTypeId;
	}

	@Column(name = "IMAGE_TYPE", nullable = false, length = 32)
	public String getImageType() {
		return this.imageType;
	}

	public void setImageType(String imageType) {
		this.imageType = imageType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imageType")
	public Set<ImageStorage> getImageStorages() {
		return this.imageStorages;
	}

	public void setImageStorages(Set<ImageStorage> imageStorages) {
		this.imageStorages = imageStorages;
	}

}
