package com.esc20.model;
// Generated Jan 31, 2019 9:51:40 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SecUsers generated by hbm2java
 */
@Entity
@Table(name = "SEC_USERS", schema = "rsccc", catalog = "rsccc")
public class SecUsers implements java.io.Serializable {

	private int usrId;
	private String usrProfileName;
	private String usrLogName;
	private String usrLogPwd;
	private String usrNameL;
	private String usrNameF;
	private char usrNameM;
	private String dbLogName;
	private String dbLogPwd;
	private String usrPrevPwd;
	private int usrLogTries;
	private Date usrTimeoutDt;
	private Date usrChgPwdDt;
	private int usrDeleted;
	private Date usrLastLogDt;
	private String empNbr;
	private char usrLdap;
	private Date usrDeletedDt;

	public SecUsers() {
	}

	public SecUsers(int usrId, String usrProfileName, String usrLogName, String usrLogPwd, String usrNameL,
			String usrNameF, char usrNameM, String dbLogName, String dbLogPwd, int usrLogTries, int usrDeleted,
			String empNbr, char usrLdap) {
		this.usrId = usrId;
		this.usrProfileName = usrProfileName;
		this.usrLogName = usrLogName;
		this.usrLogPwd = usrLogPwd;
		this.usrNameL = usrNameL;
		this.usrNameF = usrNameF;
		this.usrNameM = usrNameM;
		this.dbLogName = dbLogName;
		this.dbLogPwd = dbLogPwd;
		this.usrLogTries = usrLogTries;
		this.usrDeleted = usrDeleted;
		this.empNbr = empNbr;
		this.usrLdap = usrLdap;
	}

	public SecUsers(int usrId, String usrProfileName, String usrLogName, String usrLogPwd, String usrNameL,
			String usrNameF, char usrNameM, String dbLogName, String dbLogPwd, String usrPrevPwd, int usrLogTries,
			Date usrTimeoutDt, Date usrChgPwdDt, int usrDeleted, Date usrLastLogDt, String empNbr, char usrLdap,
			Date usrDeletedDt) {
		this.usrId = usrId;
		this.usrProfileName = usrProfileName;
		this.usrLogName = usrLogName;
		this.usrLogPwd = usrLogPwd;
		this.usrNameL = usrNameL;
		this.usrNameF = usrNameF;
		this.usrNameM = usrNameM;
		this.dbLogName = dbLogName;
		this.dbLogPwd = dbLogPwd;
		this.usrPrevPwd = usrPrevPwd;
		this.usrLogTries = usrLogTries;
		this.usrTimeoutDt = usrTimeoutDt;
		this.usrChgPwdDt = usrChgPwdDt;
		this.usrDeleted = usrDeleted;
		this.usrLastLogDt = usrLastLogDt;
		this.empNbr = empNbr;
		this.usrLdap = usrLdap;
		this.usrDeletedDt = usrDeletedDt;
	}

	@Id

	@Column(name = "USR_ID", nullable = false)
	public int getUsrId() {
		return this.usrId;
	}

	public void setUsrId(int usrId) {
		this.usrId = usrId;
	}

	@Column(name = "USR_PROFILE_NAME", nullable = false, length = 12)
	public String getUsrProfileName() {
		return this.usrProfileName;
	}

	public void setUsrProfileName(String usrProfileName) {
		this.usrProfileName = usrProfileName;
	}

	@Column(name = "USR_LOG_NAME", nullable = false, length = 30)
	public String getUsrLogName() {
		return this.usrLogName;
	}

	public void setUsrLogName(String usrLogName) {
		this.usrLogName = usrLogName;
	}

	@Column(name = "USR_LOG_PWD", nullable = false, length = 256)
	public String getUsrLogPwd() {
		return this.usrLogPwd;
	}

	public void setUsrLogPwd(String usrLogPwd) {
		this.usrLogPwd = usrLogPwd;
	}

	@Column(name = "USR_NAME_L", nullable = false, length = 30)
	public String getUsrNameL() {
		return this.usrNameL;
	}

	public void setUsrNameL(String usrNameL) {
		this.usrNameL = usrNameL;
	}

	@Column(name = "USR_NAME_F", nullable = false, length = 30)
	public String getUsrNameF() {
		return this.usrNameF;
	}

	public void setUsrNameF(String usrNameF) {
		this.usrNameF = usrNameF;
	}

	@Column(name = "USR_NAME_M", nullable = false, length = 1)
	public char getUsrNameM() {
		return this.usrNameM;
	}

	public void setUsrNameM(char usrNameM) {
		this.usrNameM = usrNameM;
	}

	@Column(name = "DB_LOG_NAME", nullable = false, length = 100)
	public String getDbLogName() {
		return this.dbLogName;
	}

	public void setDbLogName(String dbLogName) {
		this.dbLogName = dbLogName;
	}

	@Column(name = "DB_LOG_PWD", nullable = false, length = 256)
	public String getDbLogPwd() {
		return this.dbLogPwd;
	}

	public void setDbLogPwd(String dbLogPwd) {
		this.dbLogPwd = dbLogPwd;
	}

	@Column(name = "USR_PREV_PWD", length = 256)
	public String getUsrPrevPwd() {
		return this.usrPrevPwd;
	}

	public void setUsrPrevPwd(String usrPrevPwd) {
		this.usrPrevPwd = usrPrevPwd;
	}

	@Column(name = "USR_LOG_TRIES", nullable = false)
	public int getUsrLogTries() {
		return this.usrLogTries;
	}

	public void setUsrLogTries(int usrLogTries) {
		this.usrLogTries = usrLogTries;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USR_TIMEOUT_DT", length = 23)
	public Date getUsrTimeoutDt() {
		return this.usrTimeoutDt;
	}

	public void setUsrTimeoutDt(Date usrTimeoutDt) {
		this.usrTimeoutDt = usrTimeoutDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USR_CHG_PWD_DT", length = 23)
	public Date getUsrChgPwdDt() {
		return this.usrChgPwdDt;
	}

	public void setUsrChgPwdDt(Date usrChgPwdDt) {
		this.usrChgPwdDt = usrChgPwdDt;
	}

	@Column(name = "USR_DELETED", nullable = false)
	public int getUsrDeleted() {
		return this.usrDeleted;
	}

	public void setUsrDeleted(int usrDeleted) {
		this.usrDeleted = usrDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USR_LAST_LOG_DT", length = 23)
	public Date getUsrLastLogDt() {
		return this.usrLastLogDt;
	}

	public void setUsrLastLogDt(Date usrLastLogDt) {
		this.usrLastLogDt = usrLastLogDt;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "USR_LDAP", nullable = false, length = 1)
	public char getUsrLdap() {
		return this.usrLdap;
	}

	public void setUsrLdap(char usrLdap) {
		this.usrLdap = usrLdap;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USR_DELETED_DT", length = 23)
	public Date getUsrDeletedDt() {
		return this.usrDeletedDt;
	}

	public void setUsrDeletedDt(Date usrDeletedDt) {
		this.usrDeletedDt = usrDeletedDt;
	}

}
