package com.esc20.model;
// Generated Jan 4, 2019 3:30:30 PM by Hibernate Tools 4.3.5.Final

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BeaAltMailAddr generated by hbm2java
 */
@Entity
@Table(name = "BEA_ALT_MAIL_ADDR", schema = "rsccc", catalog = "rsccc")
public class BeaAltMailAddr implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BeaAltMailAddrId id;
	private String smrAddrNbr;
	private String smrAddrStr;
	private String smrAddrApt;
	private String smrAddrCity;
	private String smrAddrSt;
	private String smrAddrZip;
	private String smrAddrZip4;
	private String smrAddrNbrNew;
	private String smrAddrStrNew;
	private String smrAddrAptNew;
	private String smrAddrCityNew;
	private String smrAddrStNew;
	private String smrAddrZipNew;
	private String smrAddrZip4New;
	private String apprvdDts;
	private int apprvrUsrId;
	private char statCd;

	public BeaAltMailAddr() {
	}

	public BeaAltMailAddr(BeaAltMailAddrId id, String smrAddrNbr, String smrAddrStr, String smrAddrApt,
			String smrAddrCity, String smrAddrSt, String smrAddrZip, String smrAddrZip4, String smrAddrNbrNew,
			String smrAddrStrNew, String smrAddrAptNew, String smrAddrCityNew, String smrAddrStNew,
			String smrAddrZipNew, String smrAddrZip4New, String apprvdDts, int apprvrUsrId, char statCd) {
		this.id = id;
		this.smrAddrNbr = smrAddrNbr;
		this.smrAddrStr = smrAddrStr;
		this.smrAddrApt = smrAddrApt;
		this.smrAddrCity = smrAddrCity;
		this.smrAddrSt = smrAddrSt;
		this.smrAddrZip = smrAddrZip;
		this.smrAddrZip4 = smrAddrZip4;
		this.smrAddrNbrNew = smrAddrNbrNew;
		this.smrAddrStrNew = smrAddrStrNew;
		this.smrAddrAptNew = smrAddrAptNew;
		this.smrAddrCityNew = smrAddrCityNew;
		this.smrAddrStNew = smrAddrStNew;
		this.smrAddrZipNew = smrAddrZipNew;
		this.smrAddrZip4New = smrAddrZip4New;
		this.apprvdDts = apprvdDts;
		this.apprvrUsrId = apprvrUsrId;
		this.statCd = statCd;
	}

	public BeaAltMailAddr(BhrEmpDemo demo) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
		BeaAltMailAddrId id = new BeaAltMailAddrId();
		id.setEmpNbr(demo.getEmpNbr());
		id.setReqDts(sdf.format(new Date()).substring(0, 16));
		this.id = id;
		this.smrAddrNbr = demo.getSmrAddrNbr()==null?demo.getSmrAddrNbr():demo.getSmrAddrNbr().trim();
		this.smrAddrStr = demo.getSmrAddrStr()==null?demo.getSmrAddrStr():demo.getSmrAddrStr().trim();
		this.smrAddrApt = demo.getSmrAddrApt();
		this.smrAddrCity = demo.getSmrAddrCity();
		this.smrAddrSt = demo.getSmrAddrSt();
		this.smrAddrZip = demo.getSmrAddrZip();
		this.smrAddrZip4 = demo.getSmrAddrZip4();
		this.smrAddrNbrNew = demo.getSmrAddrNbr();
		this.smrAddrStrNew = demo.getSmrAddrStr();
		this.smrAddrAptNew = demo.getSmrAddrApt();
		this.smrAddrCityNew = demo.getSmrAddrCity();
		this.smrAddrStNew = demo.getSmrAddrSt();
		this.smrAddrZipNew = demo.getSmrAddrZip();
		this.smrAddrZip4New = demo.getSmrAddrZip4();
		this.apprvdDts = "";
		this.apprvrUsrId = -1;
		this.statCd = 'P';
	}
	public BeaAltMailAddr(BhrEmpDemo demo, String empNbr, String reqDts, String smrAddrNbrNew, String smrAddrStrNew,String smrAddrAptNew,
			String smrAddrCityNew, String smrAddrStNew, String smrAddrZipNew,String smrAddrZip4New, Character statCd) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
		BeaAltMailAddrId id = new BeaAltMailAddrId();
		id.setEmpNbr(empNbr);
		id.setReqDts(reqDts);
		this.id = id;
		this.smrAddrNbr = demo.getSmrAddrNbr()==null?"":demo.getSmrAddrNbr();
		this.smrAddrNbrNew = smrAddrNbrNew;
		this.smrAddrStr = demo.getSmrAddrStr()==null?"":demo.getSmrAddrStr();
		this.smrAddrStrNew = smrAddrStrNew;
		this.smrAddrApt = demo.getSmrAddrApt()==null?"":demo.getSmrAddrApt();
		this.smrAddrAptNew = smrAddrAptNew;
		this.smrAddrCity = demo.getSmrAddrCity()==null?"":demo.getSmrAddrCity();
		this.smrAddrCityNew = smrAddrCityNew;
		this.smrAddrSt = demo.getSmrAddrSt()==null?"":demo.getSmrAddrSt();
		this.smrAddrStNew = smrAddrStNew;
		this.smrAddrZip = demo.getSmrAddrZip()==null?"":demo.getSmrAddrZip();
		this.smrAddrZipNew = smrAddrZipNew;
		this.smrAddrZip4 = demo.getSmrAddrZip4()==null?"":demo.getSmrAddrZip4();
		this.smrAddrZip4New = smrAddrZip4New;
		
		if("A".equals(statCd.toString())) {
			this.apprvdDts = sdf.format(new Date()).substring(0, 16);
			this.apprvrUsrId = 0;
		}else {
			this.apprvdDts = "";
			this.apprvrUsrId = -1;
		}
		this.statCd = statCd;
	}
	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "reqDts", column = @Column(name = "REQ_DTS", nullable = false, length = 16)) })
	public BeaAltMailAddrId getId() {
		return this.id;
	}

	public void setId(BeaAltMailAddrId id) {
		this.id = id;
	}

	@Column(name = "SMR_ADDR_NBR", nullable = false, length = 8)
	public String getSmrAddrNbr() {
		return this.smrAddrNbr;
	}

	public void setSmrAddrNbr(String smrAddrNbr) {
		this.smrAddrNbr = smrAddrNbr;
	}

	@Column(name = "SMR_ADDR_STR", nullable = false, length = 20)
	public String getSmrAddrStr() {
		return this.smrAddrStr;
	}

	public void setSmrAddrStr(String smrAddrStr) {
		this.smrAddrStr = smrAddrStr;
	}

	@Column(name = "SMR_ADDR_APT", nullable = false, length = 7)
	public String getSmrAddrApt() {
		return this.smrAddrApt;
	}

	public void setSmrAddrApt(String smrAddrApt) {
		this.smrAddrApt = smrAddrApt;
	}

	@Column(name = "SMR_ADDR_CITY", nullable = false, length = 17)
	public String getSmrAddrCity() {
		return this.smrAddrCity;
	}

	public void setSmrAddrCity(String smrAddrCity) {
		this.smrAddrCity = smrAddrCity;
	}

	@Column(name = "SMR_ADDR_ST", nullable = false, length = 2)
	public String getSmrAddrSt() {
		return this.smrAddrSt;
	}

	public void setSmrAddrSt(String smrAddrSt) {
		this.smrAddrSt = smrAddrSt;
	}

	@Column(name = "SMR_ADDR_ZIP", nullable = false, length = 5)
	public String getSmrAddrZip() {
		return this.smrAddrZip;
	}

	public void setSmrAddrZip(String smrAddrZip) {
		this.smrAddrZip = smrAddrZip;
	}

	@Column(name = "SMR_ADDR_ZIP4", nullable = false, length = 4)
	public String getSmrAddrZip4() {
		return this.smrAddrZip4;
	}

	public void setSmrAddrZip4(String smrAddrZip4) {
		this.smrAddrZip4 = smrAddrZip4;
	}

	@Column(name = "SMR_ADDR_NBR_NEW", nullable = false, length = 8)
	public String getSmrAddrNbrNew() {
		return this.smrAddrNbrNew;
	}

	public void setSmrAddrNbrNew(String smrAddrNbrNew) {
		this.smrAddrNbrNew = smrAddrNbrNew;
	}

	@Column(name = "SMR_ADDR_STR_NEW", nullable = false, length = 20)
	public String getSmrAddrStrNew() {
		return this.smrAddrStrNew;
	}

	public void setSmrAddrStrNew(String smrAddrStrNew) {
		this.smrAddrStrNew = smrAddrStrNew;
	}

	@Column(name = "SMR_ADDR_APT_NEW", nullable = false, length = 7)
	public String getSmrAddrAptNew() {
		return this.smrAddrAptNew;
	}

	public void setSmrAddrAptNew(String smrAddrAptNew) {
		this.smrAddrAptNew = smrAddrAptNew;
	}

	@Column(name = "SMR_ADDR_CITY_NEW", nullable = false, length = 25)
	public String getSmrAddrCityNew() {
		return this.smrAddrCityNew;
	}

	public void setSmrAddrCityNew(String smrAddrCityNew) {
		this.smrAddrCityNew = smrAddrCityNew;
	}

	@Column(name = "SMR_ADDR_ST_NEW", nullable = false, length = 2)
	public String getSmrAddrStNew() {
		return this.smrAddrStNew;
	}

	public void setSmrAddrStNew(String smrAddrStNew) {
		this.smrAddrStNew = smrAddrStNew;
	}

	@Column(name = "SMR_ADDR_ZIP_NEW", nullable = false, length = 5)
	public String getSmrAddrZipNew() {
		return this.smrAddrZipNew;
	}

	public void setSmrAddrZipNew(String smrAddrZipNew) {
		this.smrAddrZipNew = smrAddrZipNew;
	}

	@Column(name = "SMR_ADDR_ZIP4_NEW", nullable = false, length = 4)
	public String getSmrAddrZip4New() {
		return this.smrAddrZip4New;
	}

	public void setSmrAddrZip4New(String smrAddrZip4New) {
		this.smrAddrZip4New = smrAddrZip4New;
	}

	@Column(name = "APPRVD_DTS", nullable = false, length = 16)
	public String getApprvdDts() {
		return this.apprvdDts;
	}

	public void setApprvdDts(String apprvdDts) {
		this.apprvdDts = apprvdDts;
	}

	@Column(name = "APPRVR_USR_ID", nullable = false)
	public int getApprvrUsrId() {
		return this.apprvrUsrId;
	}

	public void setApprvrUsrId(int apprvrUsrId) {
		this.apprvrUsrId = apprvrUsrId;
	}

	@Column(name = "STAT_CD", nullable = false, length = 1)
	public char getStatCd() {
		return this.statCd;
	}

	public void setStatCd(char statCd) {
		this.statCd = statCd;
	}

}
