package com.esc20.model;
// Generated Jan 4, 2019 3:30:30 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BeaDrctDpstBnkAcct generated by hbm2java
 */
@Entity
@Table(name = "BEA_DRCT_DPST_BNK_ACCT", schema = "rsccc", catalog = "rsccc")
public class BeaDrctDpstBnkAcct implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BeaDrctDpstBnkAcctId id;
	private char bnkAcctTyp;
	private BigDecimal bnkAcctAmt;
	private char bnkAcctTypNew;
	private BigDecimal bnkAcctAmtNew;
	private String apprvdDts;
	private int apprvrUsrId;
	private char statCd;

	public BeaDrctDpstBnkAcct() {
	}

	public BeaDrctDpstBnkAcct(BeaDrctDpstBnkAcctId id, char bnkAcctTyp, BigDecimal bnkAcctAmt, char bnkAcctTypNew,
			BigDecimal bnkAcctAmtNew, String apprvdDts, int apprvrUsrId, char statCd) {
		this.id = id;
		this.bnkAcctTyp = bnkAcctTyp;
		this.bnkAcctAmt = bnkAcctAmt;
		this.bnkAcctTypNew = bnkAcctTypNew;
		this.bnkAcctAmtNew = bnkAcctAmtNew;
		this.apprvdDts = apprvdDts;
		this.apprvrUsrId = apprvrUsrId;
		this.statCd = statCd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "reqDts", column = @Column(name = "REQ_DTS", nullable = false, length = 16)),
			@AttributeOverride(name = "bnkCd", column = @Column(name = "BNK_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "bnkAcctNbr", column = @Column(name = "BNK_ACCT_NBR", nullable = false, length = 17)),
			@AttributeOverride(name = "bnkCdNew", column = @Column(name = "BNK_CD_NEW", nullable = false, length = 3)),
			@AttributeOverride(name = "bnkAcctNbrNew", column = @Column(name = "BNK_ACCT_NBR_NEW", nullable = false, length = 17)) })
	public BeaDrctDpstBnkAcctId getId() {
		return this.id;
	}

	public void setId(BeaDrctDpstBnkAcctId id) {
		this.id = id;
	}

	@Column(name = "BNK_ACCT_TYP", nullable = false, length = 1)
	public char getBnkAcctTyp() {
		return this.bnkAcctTyp;
	}

	public void setBnkAcctTyp(char bnkAcctTyp) {
		this.bnkAcctTyp = bnkAcctTyp;
	}

	@Column(name = "BNK_ACCT_AMT", nullable = false, precision = 11)
	public BigDecimal getBnkAcctAmt() {
		return this.bnkAcctAmt;
	}

	public void setBnkAcctAmt(BigDecimal bnkAcctAmt) {
		this.bnkAcctAmt = bnkAcctAmt;
	}

	@Column(name = "BNK_ACCT_TYP_NEW", nullable = false, length = 1)
	public char getBnkAcctTypNew() {
		return this.bnkAcctTypNew;
	}

	public void setBnkAcctTypNew(char bnkAcctTypNew) {
		this.bnkAcctTypNew = bnkAcctTypNew;
	}

	@Column(name = "BNK_ACCT_AMT_NEW", nullable = false, precision = 11)
	public BigDecimal getBnkAcctAmtNew() {
		return this.bnkAcctAmtNew;
	}

	public void setBnkAcctAmtNew(BigDecimal bnkAcctAmtNew) {
		this.bnkAcctAmtNew = bnkAcctAmtNew;
	}

	@Column(name = "APPRVD_DTS", nullable = false, length = 16)
	public String getApprvdDts() {
		return this.apprvdDts;
	}

	public void setApprvdDts(String apprvdDts) {
		this.apprvdDts = apprvdDts;
	}

	@Column(name = "APPRVR_USR_ID", nullable = false)
	public int getApprvrUsrId() {
		return this.apprvrUsrId;
	}

	public void setApprvrUsrId(int apprvrUsrId) {
		this.apprvrUsrId = apprvrUsrId;
	}

	@Column(name = "STAT_CD", nullable = false, length = 1)
	public char getStatCd() {
		return this.statCd;
	}

	public void setStatCd(char statCd) {
		this.statCd = statCd;
	}

}
