package com.esc20.model;
// Generated Jan 4, 2019 3:30:30 PM by Hibernate Tools 4.3.5.Final

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BeaEmerContact generated by hbm2java
 */
@Entity
@Table(name = "BEA_EMER_CONTACT", schema = "rsccc", catalog = "rsccc")
public class BeaEmerContact implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BeaEmerContactId id;
	private String emerContact;
	private String emerPhoneAc;
	private String emerPhoneNbr;
	private String emerPhoneExt;
	private String emerRel;
	private String emerNote;
	private String emerContactNew;
	private String emerPhoneAcNew;
	private String emerPhoneNbrNew;
	private String emerPhoneExtNew;
	private String emerRelNew;
	private String emerNoteNew;
	private String apprvdDts;
	private Integer apprvrUsrId;
	private Character statCd;

	public BeaEmerContact() {
	}

	public BeaEmerContact(BeaEmerContactId id, String emerContact, String emerPhoneAc, String emerPhoneNbr,
			String emerPhoneExt, String emerRel, String emerNote, String emerContactNew, String emerPhoneAcNew,
			String emerPhoneNbrNew, String emerPhoneExtNew, String emerRelNew, String emerNoteNew, String apprvdDts,
			Integer apprvrUsrId, Character statCd) {
		this.id = id;
		this.emerContact = emerContact;
		this.emerPhoneAc = emerPhoneAc;
		this.emerPhoneNbr = emerPhoneNbr;
		this.emerPhoneExt = emerPhoneExt;
		this.emerRel = emerRel;
		this.emerNote = emerNote;
		this.emerContactNew = emerContactNew;
		this.emerPhoneAcNew = emerPhoneAcNew;
		this.emerPhoneNbrNew = emerPhoneNbrNew;
		this.emerPhoneExtNew = emerPhoneExtNew;
		this.emerRelNew = emerRelNew;
		this.emerNoteNew = emerNoteNew;
		this.apprvdDts = apprvdDts;
		this.apprvrUsrId = apprvrUsrId;
		this.statCd = statCd;
	}

	public BeaEmerContact(BhrEmpDemo demo) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
		BeaEmerContactId id = new BeaEmerContactId();
		id.setEmpNbr(demo.getEmpNbr());
		id.setReqDts(sdf.format(new Date()).substring(0, 16));
		this.id = id;
		this.emerContact = demo.getEmerContact();
		this.emerPhoneAc = demo.getEmerPhoneAc();
		this.emerPhoneNbr = demo.getEmerPhoneNbr();
		this.emerPhoneExt = demo.getEmerPhoneExt();
		this.emerRel = demo.getEmerRel();
		this.emerNote = demo.getEmerNote();
		this.emerContactNew = demo.getEmerContact();
		this.emerPhoneAcNew = demo.getEmerPhoneAc();
		this.emerPhoneNbrNew = demo.getEmerPhoneNbr();
		this.emerPhoneExtNew = demo.getEmerPhoneExt()==null?demo.getEmerPhoneExt():demo.getEmerPhoneExt().trim();
		this.emerRelNew = demo.getEmerRel();
		this.emerNoteNew = demo.getEmerNote();
		this.apprvdDts = "";
		this.apprvrUsrId = -1;
		this.statCd = 'P';
	}
	public BeaEmerContact(BhrEmpDemo demo, String empNbr, String reqDts, String emerContactNew, String emerPhoneAcNew,String emerPhoneNbrNew,
			String emerPhoneExtNew, String emerRelNew, String emerNoteNew,Character statCd) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
		BeaEmerContactId id = new BeaEmerContactId();
		id.setEmpNbr(empNbr);
		id.setReqDts(reqDts);
		this.id = id;
		this.emerContact = demo.getEmerContact()==null?"":demo.getEmerContact();
		this.emerContactNew = emerContactNew;
		this.emerPhoneAc = demo.getEmerPhoneAc()==null?"":demo.getEmerPhoneAc();
		this.emerPhoneAcNew = emerPhoneAcNew;
		this.emerPhoneNbr = demo.getEmerPhoneNbr()==null?"":demo.getEmerPhoneNbr();
		this.emerPhoneNbrNew = emerPhoneNbrNew;
		this.emerPhoneExt = demo.getEmerPhoneExt()==null?"":demo.getEmerPhoneExt();
		this.emerPhoneExtNew = emerPhoneExtNew;
		this.emerRel = demo.getEmerRel()==null?"":demo.getEmerRel();
		this.emerRelNew = emerRelNew;
		this.emerNote = demo.getEmerNote()==null?"":demo.getEmerNote();
		this.emerNoteNew = emerNoteNew;
		
		if("A".equals(statCd.toString())) {
			this.apprvdDts = sdf.format(new Date()).substring(0, 16);
			this.apprvrUsrId = 0;
		}else {
			this.apprvdDts = "";
			this.apprvrUsrId = -1;
		}
		this.statCd = statCd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "reqDts", column = @Column(name = "REQ_DTS", nullable = false, length = 16)) })
	public BeaEmerContactId getId() {
		return this.id;
	}

	public void setId(BeaEmerContactId id) {
		this.id = id;
	}

	@Column(name = "EMER_CONTACT", nullable = false, length = 26)
	public String getEmerContact() {
		return this.emerContact;
	}

	public void setEmerContact(String emerContact) {
		this.emerContact = emerContact;
	}

	@Column(name = "EMER_PHONE_AC", nullable = false, length = 3)
	public String getEmerPhoneAc() {
		return this.emerPhoneAc;
	}

	public void setEmerPhoneAc(String emerPhoneAc) {
		this.emerPhoneAc = emerPhoneAc;
	}

	@Column(name = "EMER_PHONE_NBR", nullable = false, length = 7)
	public String getEmerPhoneNbr() {
		return this.emerPhoneNbr;
	}

	public void setEmerPhoneNbr(String emerPhoneNbr) {
		this.emerPhoneNbr = emerPhoneNbr;
	}

	@Column(name = "EMER_PHONE_EXT", nullable = false, length = 6)
	public String getEmerPhoneExt() {
		return this.emerPhoneExt;
	}

	public void setEmerPhoneExt(String emerPhoneExt) {
		this.emerPhoneExt = emerPhoneExt;
	}

	@Column(name = "EMER_REL", nullable = false, length = 25)
	public String getEmerRel() {
		return this.emerRel;
	}

	public void setEmerRel(String emerRel) {
		this.emerRel = emerRel;
	}

	@Column(name = "EMER_NOTE", nullable = false, length = 25)
	public String getEmerNote() {
		return this.emerNote;
	}

	public void setEmerNote(String emerNote) {
		this.emerNote = emerNote;
	}

	@Column(name = "EMER_CONTACT_NEW", nullable = false, length = 26)
	public String getEmerContactNew() {
		return this.emerContactNew;
	}

	public void setEmerContactNew(String emerContactNew) {
		this.emerContactNew = emerContactNew;
	}

	@Column(name = "EMER_PHONE_AC_NEW", nullable = false, length = 3)
	public String getEmerPhoneAcNew() {
		return this.emerPhoneAcNew;
	}

	public void setEmerPhoneAcNew(String emerPhoneAcNew) {
		this.emerPhoneAcNew = emerPhoneAcNew;
	}

	@Column(name = "EMER_PHONE_NBR_NEW", nullable = false, length = 7)
	public String getEmerPhoneNbrNew() {
		return this.emerPhoneNbrNew;
	}

	public void setEmerPhoneNbrNew(String emerPhoneNbrNew) {
		this.emerPhoneNbrNew = emerPhoneNbrNew;
	}

	@Column(name = "EMER_PHONE_EXT_NEW", nullable = false, length = 6)
	public String getEmerPhoneExtNew() {
		return this.emerPhoneExtNew;
	}

	public void setEmerPhoneExtNew(String emerPhoneExtNew) {
		this.emerPhoneExtNew = emerPhoneExtNew;
	}

	@Column(name = "EMER_REL_NEW", nullable = false, length = 25)
	public String getEmerRelNew() {
		return this.emerRelNew;
	}

	public void setEmerRelNew(String emerRelNew) {
		this.emerRelNew = emerRelNew;
	}

	@Column(name = "EMER_NOTE_NEW", nullable = false, length = 25)
	public String getEmerNoteNew() {
		return this.emerNoteNew;
	}

	public void setEmerNoteNew(String emerNoteNew) {
		this.emerNoteNew = emerNoteNew;
	}

	@Column(name = "APPRVD_DTS", nullable = false, length = 16)
	public String getApprvdDts() {
		return this.apprvdDts;
	}

	public void setApprvdDts(String apprvdDts) {
		this.apprvdDts = apprvdDts;
	}

	@Column(name = "APPRVR_USR_ID", nullable = false)
	public Integer getApprvrUsrId() {
		return this.apprvrUsrId;
	}

	public void setApprvrUsrId(Integer apprvrUsrId) {
		this.apprvrUsrId = apprvrUsrId;
	}

	@Column(name = "STAT_CD", nullable = false, length = 1)
	public Character getStatCd() {
		return this.statCd;
	}

	public void setStatCd(Character statCd) {
		this.statCd = statCd;
	}

}
