package com.esc20.model;
// Generated Jan 4, 2019 3:36:55 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BhrAcaAirFileRun generated by hbm2java
 */
@Entity
@Table(name = "BHR_ACA_AIR_FILE_RUN", schema = "rsccc", catalog = "rsccc")
public class BhrAcaAirFileRun implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private int runId;
	private Date runTime;
	private String runUserId;
	private char runType;
	private String fileName;
	private char fileType;
	private String fileUtid;
	private String paymentYr;
	private int tot1095Cnt;
	private Set<BhrAcaAirEmpRecord> bhrAcaAirEmpRecords = new HashSet<BhrAcaAirEmpRecord>(0);

	public BhrAcaAirFileRun() {
	}

	public BhrAcaAirFileRun(int runId, Date runTime, String runUserId, char runType, String fileName, char fileType,
			String fileUtid, String paymentYr, int tot1095Cnt) {
		this.runId = runId;
		this.runTime = runTime;
		this.runUserId = runUserId;
		this.runType = runType;
		this.fileName = fileName;
		this.fileType = fileType;
		this.fileUtid = fileUtid;
		this.paymentYr = paymentYr;
		this.tot1095Cnt = tot1095Cnt;
	}

	public BhrAcaAirFileRun(int runId, Date runTime, String runUserId, char runType, String fileName, char fileType,
			String fileUtid, String paymentYr, int tot1095Cnt, Set<BhrAcaAirEmpRecord> bhrAcaAirEmpRecords) {
		this.runId = runId;
		this.runTime = runTime;
		this.runUserId = runUserId;
		this.runType = runType;
		this.fileName = fileName;
		this.fileType = fileType;
		this.fileUtid = fileUtid;
		this.paymentYr = paymentYr;
		this.tot1095Cnt = tot1095Cnt;
		this.bhrAcaAirEmpRecords = bhrAcaAirEmpRecords;
	}

	@Id

	@Column(name = "RUN_ID", nullable = false)
	public int getRunId() {
		return this.runId;
	}

	public void setRunId(int runId) {
		this.runId = runId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RUN_TIME", nullable = false, length = 23)
	public Date getRunTime() {
		return this.runTime;
	}

	public void setRunTime(Date runTime) {
		this.runTime = runTime;
	}

	@Column(name = "RUN_USER_ID", nullable = false, length = 12)
	public String getRunUserId() {
		return this.runUserId;
	}

	public void setRunUserId(String runUserId) {
		this.runUserId = runUserId;
	}

	@Column(name = "RUN_TYPE", nullable = false, length = 1)
	public char getRunType() {
		return this.runType;
	}

	public void setRunType(char runType) {
		this.runType = runType;
	}

	@Column(name = "FILE_NAME", nullable = false, length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FILE_TYPE", nullable = false, length = 1)
	public char getFileType() {
		return this.fileType;
	}

	public void setFileType(char fileType) {
		this.fileType = fileType;
	}

	@Column(name = "FILE_UTID", nullable = false, length = 100)
	public String getFileUtid() {
		return this.fileUtid;
	}

	public void setFileUtid(String fileUtid) {
		this.fileUtid = fileUtid;
	}

	@Column(name = "PAYMENT_YR", nullable = false, length = 4)
	public String getPaymentYr() {
		return this.paymentYr;
	}

	public void setPaymentYr(String paymentYr) {
		this.paymentYr = paymentYr;
	}

	@Column(name = "TOT_1095_CNT", nullable = false, precision = 6, scale = 0)
	public int getTot1095Cnt() {
		return this.tot1095Cnt;
	}

	public void setTot1095Cnt(int tot1095Cnt) {
		this.tot1095Cnt = tot1095Cnt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bhrAcaAirFileRun")
	public Set<BhrAcaAirEmpRecord> getBhrAcaAirEmpRecords() {
		return this.bhrAcaAirEmpRecords;
	}

	public void setBhrAcaAirEmpRecords(Set<BhrAcaAirEmpRecord> bhrAcaAirEmpRecords) {
		this.bhrAcaAirEmpRecords = bhrAcaAirEmpRecords;
	}

}
