package com.esc20.model;
// Generated Jan 4, 2019 3:31:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrAca1094cAleMbrMonHist generated by hbm2java
 */
@Entity
@Table(name = "BHR_ACA_1094C_ALE_MBR_MON_HIST", schema = "rsccc", catalog = "rsccc")
public class BhrAca1094cAleMbrMonHist implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrAca1094cAleMbrMonHistId id;
	private char minEssentCovrgOffrIndY;
	private char minEssentCovrgOffrIndN;
	private int ftEmpCnt;
	private int totEmpCnt;
	private char aggGrpInd;
	private char sec4980hTranstnReliefInd;
	private String module;

	public BhrAca1094cAleMbrMonHist() {
	}

	public BhrAca1094cAleMbrMonHist(BhrAca1094cAleMbrMonHistId id, char minEssentCovrgOffrIndY,
			char minEssentCovrgOffrIndN, int ftEmpCnt, int totEmpCnt, char aggGrpInd, char sec4980hTranstnReliefInd,
			String module) {
		this.id = id;
		this.minEssentCovrgOffrIndY = minEssentCovrgOffrIndY;
		this.minEssentCovrgOffrIndN = minEssentCovrgOffrIndN;
		this.ftEmpCnt = ftEmpCnt;
		this.totEmpCnt = totEmpCnt;
		this.aggGrpInd = aggGrpInd;
		this.sec4980hTranstnReliefInd = sec4980hTranstnReliefInd;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "calYr", column = @Column(name = "CAL_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "mon", column = @Column(name = "MON", nullable = false, length = 3)) })
	public BhrAca1094cAleMbrMonHistId getId() {
		return this.id;
	}

	public void setId(BhrAca1094cAleMbrMonHistId id) {
		this.id = id;
	}

	@Column(name = "MIN_ESSENT_COVRG_OFFR_IND_Y", nullable = false, length = 1)
	public char getMinEssentCovrgOffrIndY() {
		return this.minEssentCovrgOffrIndY;
	}

	public void setMinEssentCovrgOffrIndY(char minEssentCovrgOffrIndY) {
		this.minEssentCovrgOffrIndY = minEssentCovrgOffrIndY;
	}

	@Column(name = "MIN_ESSENT_COVRG_OFFR_IND_N", nullable = false, length = 1)
	public char getMinEssentCovrgOffrIndN() {
		return this.minEssentCovrgOffrIndN;
	}

	public void setMinEssentCovrgOffrIndN(char minEssentCovrgOffrIndN) {
		this.minEssentCovrgOffrIndN = minEssentCovrgOffrIndN;
	}

	@Column(name = "FT_EMP_CNT", nullable = false, precision = 6, scale = 0)
	public int getFtEmpCnt() {
		return this.ftEmpCnt;
	}

	public void setFtEmpCnt(int ftEmpCnt) {
		this.ftEmpCnt = ftEmpCnt;
	}

	@Column(name = "TOT_EMP_CNT", nullable = false, precision = 6, scale = 0)
	public int getTotEmpCnt() {
		return this.totEmpCnt;
	}

	public void setTotEmpCnt(int totEmpCnt) {
		this.totEmpCnt = totEmpCnt;
	}

	@Column(name = "AGG_GRP_IND", nullable = false, length = 1)
	public char getAggGrpInd() {
		return this.aggGrpInd;
	}

	public void setAggGrpInd(char aggGrpInd) {
		this.aggGrpInd = aggGrpInd;
	}

	@Column(name = "SEC_4980H_TRANSTN_RELIEF_IND", nullable = false, length = 1)
	public char getSec4980hTranstnReliefInd() {
		return this.sec4980hTranstnReliefInd;
	}

	public void setSec4980hTranstnReliefInd(char sec4980hTranstnReliefInd) {
		this.sec4980hTranstnReliefInd = sec4980hTranstnReliefInd;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
