package com.esc20.model;
// Generated Jan 4, 2019 3:38:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BhrCalSch generated by hbm2java
 */
@Entity
@Table(name = "BHR_CAL_SCH", schema = "rsccc", catalog = "rsccc")
public class BhrCalSch implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrCalSchId id;
	private String calDescr;
	private String module;
	private Set<BhrCalSchDays> bhrCalSchDayses = new HashSet<BhrCalSchDays>(0);

	public BhrCalSch() {
	}

	public BhrCalSch(BhrCalSchId id, String calDescr, String module) {
		this.id = id;
		this.calDescr = calDescr;
		this.module = module;
	}

	public BhrCalSch(BhrCalSchId id, String calDescr, String module, Set<BhrCalSchDays> bhrCalSchDayses) {
		this.id = id;
		this.calDescr = calDescr;
		this.module = module;
		this.bhrCalSchDayses = bhrCalSchDayses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "calCd", column = @Column(name = "CAL_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)) })
	public BhrCalSchId getId() {
		return this.id;
	}

	public void setId(BhrCalSchId id) {
		this.id = id;
	}

	@Column(name = "CAL_DESCR", nullable = false, length = 20)
	public String getCalDescr() {
		return this.calDescr;
	}

	public void setCalDescr(String calDescr) {
		this.calDescr = calDescr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bhrCalSch")
	public Set<BhrCalSchDays> getBhrCalSchDayses() {
		return this.bhrCalSchDayses;
	}

	public void setBhrCalSchDayses(Set<BhrCalSchDays> bhrCalSchDayses) {
		this.bhrCalSchDayses = bhrCalSchDayses;
	}

}
