package com.esc20.model;
// Generated Jan 4, 2019 3:39:11 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrDeductXmital generated by hbm2java
 */
@Entity
@Table(name = "BHR_DEDUCT_XMITAL", schema = "rsccc", catalog = "rsccc")
public class BhrDeductXmital implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrDeductXmitalId id;
	private String dedCd;
	private BigDecimal dedAmt;
	private char dedRefund;
	private char cafeFlg;
	private String processDt;
	private String userId;
	private String rsn;
	private char w2EmplrHlthcare;
	private BigDecimal grossAmt;
	private String module;

	public BhrDeductXmital() {
	}

	public BhrDeductXmital(BhrDeductXmitalId id, String dedCd, BigDecimal dedAmt, char dedRefund, char cafeFlg,
			String processDt, String userId, String rsn, char w2EmplrHlthcare, BigDecimal grossAmt, String module) {
		this.id = id;
		this.dedCd = dedCd;
		this.dedAmt = dedAmt;
		this.dedRefund = dedRefund;
		this.cafeFlg = cafeFlg;
		this.processDt = processDt;
		this.userId = userId;
		this.rsn = rsn;
		this.w2EmplrHlthcare = w2EmplrHlthcare;
		this.grossAmt = grossAmt;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "dts", column = @Column(name = "DTS", nullable = false, length = 16)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, length = 5)) })
	public BhrDeductXmitalId getId() {
		return this.id;
	}

	public void setId(BhrDeductXmitalId id) {
		this.id = id;
	}

	@Column(name = "DED_CD", nullable = false, length = 3)
	public String getDedCd() {
		return this.dedCd;
	}

	public void setDedCd(String dedCd) {
		this.dedCd = dedCd;
	}

	@Column(name = "DED_AMT", nullable = false, precision = 9)
	public BigDecimal getDedAmt() {
		return this.dedAmt;
	}

	public void setDedAmt(BigDecimal dedAmt) {
		this.dedAmt = dedAmt;
	}

	@Column(name = "DED_REFUND", nullable = false, length = 1)
	public char getDedRefund() {
		return this.dedRefund;
	}

	public void setDedRefund(char dedRefund) {
		this.dedRefund = dedRefund;
	}

	@Column(name = "CAFE_FLG", nullable = false, length = 1)
	public char getCafeFlg() {
		return this.cafeFlg;
	}

	public void setCafeFlg(char cafeFlg) {
		this.cafeFlg = cafeFlg;
	}

	@Column(name = "PROCESS_DT", nullable = false, length = 8)
	public String getProcessDt() {
		return this.processDt;
	}

	public void setProcessDt(String processDt) {
		this.processDt = processDt;
	}

	@Column(name = "USER_ID", nullable = false, length = 12)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "RSN", nullable = false, length = 30)
	public String getRsn() {
		return this.rsn;
	}

	public void setRsn(String rsn) {
		this.rsn = rsn;
	}

	@Column(name = "W2_EMPLR_HLTHCARE", nullable = false, length = 1)
	public char getW2EmplrHlthcare() {
		return this.w2EmplrHlthcare;
	}

	public void setW2EmplrHlthcare(char w2EmplrHlthcare) {
		this.w2EmplrHlthcare = w2EmplrHlthcare;
	}

	@Column(name = "GROSS_AMT", nullable = false, precision = 9)
	public BigDecimal getGrossAmt() {
		return this.grossAmt;
	}

	public void setGrossAmt(BigDecimal grossAmt) {
		this.grossAmt = grossAmt;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
