package com.esc20.model;
// Generated Jan 4, 2019 3:40:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpLvBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_LV_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrEmpLvBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpLvBkupPaycalcs5Id id;

	public BhrEmpLvBkupPaycalcs5() {
	}

	public BhrEmpLvBkupPaycalcs5(BhrEmpLvBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "lvBeginBal", column = @Column(name = "LV_BEGIN_BAL", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "lvEarned", column = @Column(name = "LV_EARNED", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "lvUsed", column = @Column(name = "LV_USED", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "lvEndBal", column = @Column(name = "LV_END_BAL", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BhrEmpLvBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrEmpLvBkupPaycalcs5Id id) {
		this.id = id;
	}

}
