package com.esc20.model;
// Generated Jan 4, 2019 3:40:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrEmpLvDockHistId generated by hbm2java
 */
@Embeddable
public class BhrEmpLvDockHistId implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private String empNbr;
	private char voidOrIss;
	private String chkNbr;
	private short adjNbr;
	private String dtOfPay;
	private char payFreq;
	private char cyrNyrFlg;
	private String lvTyp;
	private String lvAltTyp;

	public BhrEmpLvDockHistId() {
	}

	public BhrEmpLvDockHistId(String empNbr, char voidOrIss, String chkNbr, short adjNbr, String dtOfPay, char payFreq,
			char cyrNyrFlg, String lvTyp, String lvAltTyp) {
		this.empNbr = empNbr;
		this.voidOrIss = voidOrIss;
		this.chkNbr = chkNbr;
		this.adjNbr = adjNbr;
		this.dtOfPay = dtOfPay;
		this.payFreq = payFreq;
		this.cyrNyrFlg = cyrNyrFlg;
		this.lvTyp = lvTyp;
		this.lvAltTyp = lvAltTyp;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "VOID_OR_ISS", nullable = false, length = 1)
	public char getVoidOrIss() {
		return this.voidOrIss;
	}

	public void setVoidOrIss(char voidOrIss) {
		this.voidOrIss = voidOrIss;
	}

	@Column(name = "CHK_NBR", nullable = false, length = 6)
	public String getChkNbr() {
		return this.chkNbr;
	}

	public void setChkNbr(String chkNbr) {
		this.chkNbr = chkNbr;
	}

	@Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)
	public short getAdjNbr() {
		return this.adjNbr;
	}

	public void setAdjNbr(short adjNbr) {
		this.adjNbr = adjNbr;
	}

	@Column(name = "DT_OF_PAY", nullable = false, length = 8)
	public String getDtOfPay() {
		return this.dtOfPay;
	}

	public void setDtOfPay(String dtOfPay) {
		this.dtOfPay = dtOfPay;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "CYR_NYR_FLG", nullable = false, length = 1)
	public char getCyrNyrFlg() {
		return this.cyrNyrFlg;
	}

	public void setCyrNyrFlg(char cyrNyrFlg) {
		this.cyrNyrFlg = cyrNyrFlg;
	}

	@Column(name = "LV_TYP", nullable = false, length = 2)
	public String getLvTyp() {
		return this.lvTyp;
	}

	public void setLvTyp(String lvTyp) {
		this.lvTyp = lvTyp;
	}

	@Column(name = "LV_ALT_TYP", nullable = false, length = 2)
	public String getLvAltTyp() {
		return this.lvAltTyp;
	}

	public void setLvAltTyp(String lvAltTyp) {
		this.lvAltTyp = lvAltTyp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrEmpLvDockHistId))
			return false;
		BhrEmpLvDockHistId castOther = (BhrEmpLvDockHistId) other;

		return ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
				&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& (this.getVoidOrIss() == castOther.getVoidOrIss())
				&& ((this.getChkNbr() == castOther.getChkNbr()) || (this.getChkNbr() != null
						&& castOther.getChkNbr() != null && this.getChkNbr().equals(castOther.getChkNbr())))
				&& (this.getAdjNbr() == castOther.getAdjNbr())
				&& ((this.getDtOfPay() == castOther.getDtOfPay()) || (this.getDtOfPay() != null
						&& castOther.getDtOfPay() != null && this.getDtOfPay().equals(castOther.getDtOfPay())))
				&& (this.getPayFreq() == castOther.getPayFreq()) && (this.getCyrNyrFlg() == castOther.getCyrNyrFlg())
				&& ((this.getLvTyp() == castOther.getLvTyp()) || (this.getLvTyp() != null
						&& castOther.getLvTyp() != null && this.getLvTyp().equals(castOther.getLvTyp())))
				&& ((this.getLvAltTyp() == castOther.getLvAltTyp()) || (this.getLvAltTyp() != null
						&& castOther.getLvAltTyp() != null && this.getLvAltTyp().equals(castOther.getLvAltTyp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + this.getVoidOrIss();
		result = 37 * result + (getChkNbr() == null ? 0 : this.getChkNbr().hashCode());
		result = 37 * result + this.getAdjNbr();
		result = 37 * result + (getDtOfPay() == null ? 0 : this.getDtOfPay().hashCode());
		result = 37 * result + this.getPayFreq();
		result = 37 * result + this.getCyrNyrFlg();
		result = 37 * result + (getLvTyp() == null ? 0 : this.getLvTyp().hashCode());
		result = 37 * result + (getLvAltTyp() == null ? 0 : this.getLvAltTyp().hashCode());
		return result;
	}

}
