package com.esc20.model;
// Generated Jan 4, 2019 3:40:36 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpLvHist generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_LV_HIST", schema = "rsccc", catalog = "rsccc")
public class BhrEmpLvHist implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpLvHistId id;
	private BigDecimal lvTaken;
	private BigDecimal lvEarned;
	private String rsn;
	private String userId;
	private String dtOfAbs;
	private char tmOfDay;
	private String subTyp;
	private String absRsn;
	private BigDecimal servRecDaysDeduct;
	private String module;
	private int lvId;

	public BhrEmpLvHist() {
	}

	public BhrEmpLvHist(BhrEmpLvHistId id, BigDecimal lvTaken, BigDecimal lvEarned, String rsn, String userId,
			String dtOfAbs, char tmOfDay, String subTyp, String absRsn, BigDecimal servRecDaysDeduct, String module,
			int lvId) {
		this.id = id;
		this.lvTaken = lvTaken;
		this.lvEarned = lvEarned;
		this.rsn = rsn;
		this.userId = userId;
		this.dtOfAbs = dtOfAbs;
		this.tmOfDay = tmOfDay;
		this.subTyp = subTyp;
		this.absRsn = absRsn;
		this.servRecDaysDeduct = servRecDaysDeduct;
		this.module = module;
		this.lvId = lvId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "voidOrIss", column = @Column(name = "VOID_OR_ISS", nullable = false, length = 1)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, precision = 3, scale = 0)) })
	public BhrEmpLvHistId getId() {
		return this.id;
	}

	public void setId(BhrEmpLvHistId id) {
		this.id = id;
	}

	@Column(name = "LV_TAKEN", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvTaken() {
		return this.lvTaken;
	}

	public void setLvTaken(BigDecimal lvTaken) {
		this.lvTaken = lvTaken;
	}

	@Column(name = "LV_EARNED", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvEarned() {
		return this.lvEarned;
	}

	public void setLvEarned(BigDecimal lvEarned) {
		this.lvEarned = lvEarned;
	}

	@Column(name = "RSN", nullable = false, length = 20)
	public String getRsn() {
		return this.rsn;
	}

	public void setRsn(String rsn) {
		this.rsn = rsn;
	}

	@Column(name = "USER_ID", nullable = false, length = 12)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "DT_OF_ABS", nullable = false, length = 8)
	public String getDtOfAbs() {
		return this.dtOfAbs;
	}

	public void setDtOfAbs(String dtOfAbs) {
		this.dtOfAbs = dtOfAbs;
	}

	@Column(name = "TM_OF_DAY", nullable = false, length = 1)
	public char getTmOfDay() {
		return this.tmOfDay;
	}

	public void setTmOfDay(char tmOfDay) {
		this.tmOfDay = tmOfDay;
	}

	@Column(name = "SUB_TYP", nullable = false, length = 2)
	public String getSubTyp() {
		return this.subTyp;
	}

	public void setSubTyp(String subTyp) {
		this.subTyp = subTyp;
	}

	@Column(name = "ABS_RSN", nullable = false, length = 2)
	public String getAbsRsn() {
		return this.absRsn;
	}

	public void setAbsRsn(String absRsn) {
		this.absRsn = absRsn;
	}

	@Column(name = "SERV_REC_DAYS_DEDUCT", nullable = false, precision = 5)
	public BigDecimal getServRecDaysDeduct() {
		return this.servRecDaysDeduct;
	}

	public void setServRecDaysDeduct(BigDecimal servRecDaysDeduct) {
		this.servRecDaysDeduct = servRecDaysDeduct;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "LV_ID", nullable = false)
	public int getLvId() {
		return this.lvId;
	}

	public void setLvId(int lvId) {
		this.lvId = lvId;
	}

}
