package com.esc20.model;
// Generated Jan 4, 2019 3:44:27 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayAdj generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAY_ADJ", schema = "rsccc", catalog = "rsccc")
public class BhrPayAdj implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayAdjId id;
	private char adjTyp;
	private String fromDtOfPay;
	private String toDtOfPay;
	private String fromSchYr;
	private String toSchYr;
	private String jvNbr;
	private String finTransDt;
	private BigDecimal pct;
	private String fromAcctPer;
	private String toAcctPer;
	private char fromFileId;
	private char toFileId;

	public BhrPayAdj() {
	}

	public BhrPayAdj(BhrPayAdjId id, char adjTyp, String fromDtOfPay, String toDtOfPay, String fromSchYr,
			String toSchYr, String jvNbr, String finTransDt, BigDecimal pct, String fromAcctPer, String toAcctPer,
			char fromFileId, char toFileId) {
		this.id = id;
		this.adjTyp = adjTyp;
		this.fromDtOfPay = fromDtOfPay;
		this.toDtOfPay = toDtOfPay;
		this.fromSchYr = fromSchYr;
		this.toSchYr = toSchYr;
		this.jvNbr = jvNbr;
		this.finTransDt = finTransDt;
		this.pct = pct;
		this.fromAcctPer = fromAcctPer;
		this.toAcctPer = toAcctPer;
		this.fromFileId = fromFileId;
		this.toFileId = toFileId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)) })
	public BhrPayAdjId getId() {
		return this.id;
	}

	public void setId(BhrPayAdjId id) {
		this.id = id;
	}

	@Column(name = "ADJ_TYP", nullable = false, length = 1)
	public char getAdjTyp() {
		return this.adjTyp;
	}

	public void setAdjTyp(char adjTyp) {
		this.adjTyp = adjTyp;
	}

	@Column(name = "FROM_DT_OF_PAY", nullable = false, length = 8)
	public String getFromDtOfPay() {
		return this.fromDtOfPay;
	}

	public void setFromDtOfPay(String fromDtOfPay) {
		this.fromDtOfPay = fromDtOfPay;
	}

	@Column(name = "TO_DT_OF_PAY", nullable = false, length = 8)
	public String getToDtOfPay() {
		return this.toDtOfPay;
	}

	public void setToDtOfPay(String toDtOfPay) {
		this.toDtOfPay = toDtOfPay;
	}

	@Column(name = "FROM_SCH_YR", nullable = false, length = 4)
	public String getFromSchYr() {
		return this.fromSchYr;
	}

	public void setFromSchYr(String fromSchYr) {
		this.fromSchYr = fromSchYr;
	}

	@Column(name = "TO_SCH_YR", nullable = false, length = 4)
	public String getToSchYr() {
		return this.toSchYr;
	}

	public void setToSchYr(String toSchYr) {
		this.toSchYr = toSchYr;
	}

	@Column(name = "JV_NBR", nullable = false, length = 6)
	public String getJvNbr() {
		return this.jvNbr;
	}

	public void setJvNbr(String jvNbr) {
		this.jvNbr = jvNbr;
	}

	@Column(name = "FIN_TRANS_DT", nullable = false, length = 8)
	public String getFinTransDt() {
		return this.finTransDt;
	}

	public void setFinTransDt(String finTransDt) {
		this.finTransDt = finTransDt;
	}

	@Column(name = "PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getPct() {
		return this.pct;
	}

	public void setPct(BigDecimal pct) {
		this.pct = pct;
	}

	@Column(name = "FROM_ACCT_PER", nullable = false, length = 2)
	public String getFromAcctPer() {
		return this.fromAcctPer;
	}

	public void setFromAcctPer(String fromAcctPer) {
		this.fromAcctPer = fromAcctPer;
	}

	@Column(name = "TO_ACCT_PER", nullable = false, length = 2)
	public String getToAcctPer() {
		return this.toAcctPer;
	}

	public void setToAcctPer(String toAcctPer) {
		this.toAcctPer = toAcctPer;
	}

	@Column(name = "FROM_FILE_ID", nullable = false, length = 1)
	public char getFromFileId() {
		return this.fromFileId;
	}

	public void setFromFileId(char fromFileId) {
		this.fromFileId = fromFileId;
	}

	@Column(name = "TO_FILE_ID", nullable = false, length = 1)
	public char getToFileId() {
		return this.toFileId;
	}

	public void setToFileId(char toFileId) {
		this.toFileId = toFileId;
	}

}
