package com.esc20.model;
// Generated Jan 4, 2019 3:44:13 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayrunOptTeamExtraDuty generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAYRUN_OPT_TEAM_EXTRA_DUTY", schema = "rsccc", catalog = "rsccc")
public class BhrPayrunOptTeamExtraDuty implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayrunOptTeamExtraDutyId id;
	private char wholeSep;
	private char expense373;
	private String trsPosCd;
	private String module;

	public BhrPayrunOptTeamExtraDuty() {
	}

	public BhrPayrunOptTeamExtraDuty(BhrPayrunOptTeamExtraDutyId id, char wholeSep, char expense373, String trsPosCd,
			String module) {
		this.id = id;
		this.wholeSep = wholeSep;
		this.expense373 = expense373;
		this.trsPosCd = trsPosCd;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "extraDutyCd", column = @Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)) })
	public BhrPayrunOptTeamExtraDutyId getId() {
		return this.id;
	}

	public void setId(BhrPayrunOptTeamExtraDutyId id) {
		this.id = id;
	}

	@Column(name = "WHOLE_SEP", nullable = false, length = 1)
	public char getWholeSep() {
		return this.wholeSep;
	}

	public void setWholeSep(char wholeSep) {
		this.wholeSep = wholeSep;
	}

	@Column(name = "EXPENSE_373", nullable = false, length = 1)
	public char getExpense373() {
		return this.expense373;
	}

	public void setExpense373(char expense373) {
		this.expense373 = expense373;
	}

	@Column(name = "TRS_POS_CD", nullable = false, length = 2)
	public String getTrsPosCd() {
		return this.trsPosCd;
	}

	public void setTrsPosCd(String trsPosCd) {
		this.trsPosCd = trsPosCd;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
