package com.esc20.model;
// Generated Jan 4, 2019 3:44:27 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayAdjBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAY_ADJ_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrPayAdjBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayAdjBkupPaycalcs5Id id;

	public BhrPayAdjBkupPaycalcs5() {
	}

	public BhrPayAdjBkupPaycalcs5(BhrPayAdjBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "adjTyp", column = @Column(name = "ADJ_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "fromDtOfPay", column = @Column(name = "FROM_DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "toDtOfPay", column = @Column(name = "TO_DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "fromSchYr", column = @Column(name = "FROM_SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "toSchYr", column = @Column(name = "TO_SCH_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "jvNbr", column = @Column(name = "JV_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "finTransDt", column = @Column(name = "FIN_TRANS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "pct", column = @Column(name = "PCT", nullable = false, precision = 5, scale = 4)),
			@AttributeOverride(name = "fromAcctPer", column = @Column(name = "FROM_ACCT_PER", nullable = false, length = 2)),
			@AttributeOverride(name = "toAcctPer", column = @Column(name = "TO_ACCT_PER", nullable = false, length = 2)),
			@AttributeOverride(name = "fromFileId", column = @Column(name = "FROM_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "toFileId", column = @Column(name = "TO_FILE_ID", nullable = false, length = 1)) })
	public BhrPayAdjBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrPayAdjBkupPaycalcs5Id id) {
		this.id = id;
	}

}
