package com.esc20.model;
// Generated Jan 4, 2019 3:44:27 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BhrPayDeductHist generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAY_DEDUCT_HIST", schema = "rsccc", catalog = "rsccc")
public class BhrPayDeductHist implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayDeductHistId id;
	private BigDecimal dedAmt;
	private short dedRemain;
	private short dedTaken;
	private char cafeFlg;
	private BigDecimal emplrAmt;
	private boolean emplrContribFactor;
	private char refundFlg;
	private String caseNbr;
	private String causeNbr;
	private BigDecimal teaHealthInsContrib;
	private boolean teaHealthInsContribFactor;
	private char w2EmplrHlthcare;

	public BhrPayDeductHist() {
	}

	public BhrPayDeductHist(BhrPayDeductHistId id, BigDecimal dedAmt, short dedRemain,
			short dedTaken, char cafeFlg, BigDecimal emplrAmt, boolean emplrContribFactor, char refundFlg,
			String caseNbr, String causeNbr, BigDecimal teaHealthInsContrib, boolean teaHealthInsContribFactor,
			char w2EmplrHlthcare) {
		this.id = id;
		this.dedAmt = dedAmt;
		this.dedRemain = dedRemain;
		this.dedTaken = dedTaken;
		this.cafeFlg = cafeFlg;
		this.emplrAmt = emplrAmt;
		this.emplrContribFactor = emplrContribFactor;
		this.refundFlg = refundFlg;
		this.caseNbr = caseNbr;
		this.causeNbr = causeNbr;
		this.teaHealthInsContrib = teaHealthInsContrib;
		this.teaHealthInsContribFactor = teaHealthInsContribFactor;
		this.w2EmplrHlthcare = w2EmplrHlthcare;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "voidOrIss", column = @Column(name = "VOID_OR_ISS", nullable = false, length = 1)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "dedCd", column = @Column(name = "DED_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "dedSeq", column = @Column(name = "DED_SEQ", nullable = false, length = 1)) })
	public BhrPayDeductHistId getId() {
		return this.id;
	}

	public void setId(BhrPayDeductHistId id) {
		this.id = id;
	}

	@Column(name = "DED_AMT", nullable = false, precision = 9)
	public BigDecimal getDedAmt() {
		return this.dedAmt;
	}

	public void setDedAmt(BigDecimal dedAmt) {
		this.dedAmt = dedAmt;
	}

	@Column(name = "DED_REMAIN", nullable = false, precision = 3, scale = 0)
	public short getDedRemain() {
		return this.dedRemain;
	}

	public void setDedRemain(short dedRemain) {
		this.dedRemain = dedRemain;
	}

	@Column(name = "DED_TAKEN", nullable = false, precision = 3, scale = 0)
	public short getDedTaken() {
		return this.dedTaken;
	}

	public void setDedTaken(short dedTaken) {
		this.dedTaken = dedTaken;
	}

	@Column(name = "CAFE_FLG", nullable = false, length = 1)
	public char getCafeFlg() {
		return this.cafeFlg;
	}

	public void setCafeFlg(char cafeFlg) {
		this.cafeFlg = cafeFlg;
	}

	@Column(name = "EMPLR_AMT", nullable = false, precision = 7)
	public BigDecimal getEmplrAmt() {
		return this.emplrAmt;
	}

	public void setEmplrAmt(BigDecimal emplrAmt) {
		this.emplrAmt = emplrAmt;
	}

	@Column(name = "EMPLR_CONTRIB_FACTOR", nullable = false, precision = 1, scale = 0)
	public boolean isEmplrContribFactor() {
		return this.emplrContribFactor;
	}

	public void setEmplrContribFactor(boolean emplrContribFactor) {
		this.emplrContribFactor = emplrContribFactor;
	}

	@Column(name = "REFUND_FLG", nullable = false, length = 1)
	public char getRefundFlg() {
		return this.refundFlg;
	}

	public void setRefundFlg(char refundFlg) {
		this.refundFlg = refundFlg;
	}

	@Column(name = "CASE_NBR", nullable = false, length = 20)
	public String getCaseNbr() {
		return this.caseNbr;
	}

	public void setCaseNbr(String caseNbr) {
		this.caseNbr = caseNbr;
	}

	@Column(name = "CAUSE_NBR", nullable = false, length = 12)
	public String getCauseNbr() {
		return this.causeNbr;
	}

	public void setCauseNbr(String causeNbr) {
		this.causeNbr = causeNbr;
	}

	@Column(name = "TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getTeaHealthInsContrib() {
		return this.teaHealthInsContrib;
	}

	public void setTeaHealthInsContrib(BigDecimal teaHealthInsContrib) {
		this.teaHealthInsContrib = teaHealthInsContrib;
	}

	@Column(name = "TEA_HEALTH_INS_CONTRIB_FACTOR", nullable = false, precision = 1, scale = 0)
	public boolean isTeaHealthInsContribFactor() {
		return this.teaHealthInsContribFactor;
	}

	public void setTeaHealthInsContribFactor(boolean teaHealthInsContribFactor) {
		this.teaHealthInsContribFactor = teaHealthInsContribFactor;
	}

	@Column(name = "W2_EMPLR_HLTHCARE", nullable = false, length = 1)
	public char getW2EmplrHlthcare() {
		return this.w2EmplrHlthcare;
	}

	public void setW2EmplrHlthcare(char w2EmplrHlthcare) {
		this.w2EmplrHlthcare = w2EmplrHlthcare;
	}

}
