package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BhrPermit generated by hbm2java
 */
@Entity
@Table(name = "BHR_PERMIT", schema = "rsccc", catalog = "rsccc")
public class BhrPermit implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPermitId id;
	private char prmtRenewNbr;
	private String prmtRenewDt;
	private String prmtRenewStat;
	private String module;

	public BhrPermit() {
	}

	public BhrPermit(BhrPermitId id, char prmtRenewNbr, String prmtRenewDt, String prmtRenewStat, String module) {
		this.id = id;
		this.prmtRenewNbr = prmtRenewNbr;
		this.prmtRenewDt = prmtRenewDt;
		this.prmtRenewStat = prmtRenewStat;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "prmtTyp", column = @Column(name = "PRMT_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "prmtIssueDt", column = @Column(name = "PRMT_ISSUE_DT", nullable = false, length = 6)),
			@AttributeOverride(name = "prmtIssueStat", column = @Column(name = "PRMT_ISSUE_STAT", nullable = false, length = 2)) })
	public BhrPermitId getId() {
		return this.id;
	}

	public void setId(BhrPermitId id) {
		this.id = id;
	}

	@Column(name = "PRMT_RENEW_NBR", nullable = false, length = 1)
	public char getPrmtRenewNbr() {
		return this.prmtRenewNbr;
	}

	public void setPrmtRenewNbr(char prmtRenewNbr) {
		this.prmtRenewNbr = prmtRenewNbr;
	}

	@Column(name = "PRMT_RENEW_DT", nullable = false, length = 6)
	public String getPrmtRenewDt() {
		return this.prmtRenewDt;
	}

	public void setPrmtRenewDt(String prmtRenewDt) {
		this.prmtRenewDt = prmtRenewDt;
	}

	@Column(name = "PRMT_RENEW_STAT", nullable = false, length = 2)
	public String getPrmtRenewStat() {
		return this.prmtRenewStat;
	}

	public void setPrmtRenewStat(String prmtRenewStat) {
		this.prmtRenewStat = prmtRenewStat;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
