package com.esc20.model;
// Generated Jan 4, 2019 3:46:21 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrSupplXmital generated by hbm2java
 */
@Entity
@Table(name = "BHR_SUPPL_XMITAL", schema = "rsccc", catalog = "rsccc")
public class BhrSupplXmital implements java.io.Serializable {

	private BhrSupplXmitalId id;
	private String jobCd;
	private String campusId;
	private char dept;
	private String trsGrantCd;
	private char glFileId;
	private String fund;
	private String func;
	private String obj;
	private String sobj;
	private char wrkComp;
	private String org;
	private char fsclYr;
	private String pgm;
	private char edSpan;
	private String projDtl;
	private BigDecimal supplAmt;
	private char addStdGrossCd;
	private char adjSalaryCd;
	private char ovtmCd;
	private BigDecimal ovtmHrsWrk;
	private BigDecimal regHrsWrk;
	private char taxedBenefitFlg;
	private char nonTrsPymtTyp;
	private char nonTrsPymtCd;
	private BigDecimal nonTrsNonTaxAmt;
	private BigDecimal nonTrsTaxAmt;
	private char expense373;
	private char blkIns;
	private BigDecimal servRecDaysDeduct;
	private String subTyp;
	private char transmittalType;
	private String extraDutyCd;
	private String processDt;
	private String userId;
	private char taxedFringeBenefit;
	private char perforPay;
	private String rsn;
	private char apply457;
	private char createdCip;
	private String module;
	private BigDecimal actHrs;
	private String actDt;

	public BhrSupplXmital() {
	}

	public BhrSupplXmital(BhrSupplXmitalId id, String jobCd, String campusId, char dept, String trsGrantCd,
			char glFileId, String fund, String func, String obj, String sobj, char wrkComp, String org, char fsclYr,
			String pgm, char edSpan, String projDtl, BigDecimal supplAmt, char addStdGrossCd, char adjSalaryCd,
			char ovtmCd, BigDecimal ovtmHrsWrk, BigDecimal regHrsWrk, char taxedBenefitFlg, char nonTrsPymtTyp,
			char nonTrsPymtCd, BigDecimal nonTrsNonTaxAmt, BigDecimal nonTrsTaxAmt, char expense373, char blkIns,
			BigDecimal servRecDaysDeduct, String subTyp, char transmittalType, String extraDutyCd, String processDt,
			String userId, char taxedFringeBenefit, char perforPay, String rsn, char apply457, char createdCip,
			String module, BigDecimal actHrs, String actDt) {
		this.id = id;
		this.jobCd = jobCd;
		this.campusId = campusId;
		this.dept = dept;
		this.trsGrantCd = trsGrantCd;
		this.glFileId = glFileId;
		this.fund = fund;
		this.func = func;
		this.obj = obj;
		this.sobj = sobj;
		this.wrkComp = wrkComp;
		this.org = org;
		this.fsclYr = fsclYr;
		this.pgm = pgm;
		this.edSpan = edSpan;
		this.projDtl = projDtl;
		this.supplAmt = supplAmt;
		this.addStdGrossCd = addStdGrossCd;
		this.adjSalaryCd = adjSalaryCd;
		this.ovtmCd = ovtmCd;
		this.ovtmHrsWrk = ovtmHrsWrk;
		this.regHrsWrk = regHrsWrk;
		this.taxedBenefitFlg = taxedBenefitFlg;
		this.nonTrsPymtTyp = nonTrsPymtTyp;
		this.nonTrsPymtCd = nonTrsPymtCd;
		this.nonTrsNonTaxAmt = nonTrsNonTaxAmt;
		this.nonTrsTaxAmt = nonTrsTaxAmt;
		this.expense373 = expense373;
		this.blkIns = blkIns;
		this.servRecDaysDeduct = servRecDaysDeduct;
		this.subTyp = subTyp;
		this.transmittalType = transmittalType;
		this.extraDutyCd = extraDutyCd;
		this.processDt = processDt;
		this.userId = userId;
		this.taxedFringeBenefit = taxedFringeBenefit;
		this.perforPay = perforPay;
		this.rsn = rsn;
		this.apply457 = apply457;
		this.createdCip = createdCip;
		this.module = module;
		this.actHrs = actHrs;
		this.actDt = actDt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "dts", column = @Column(name = "DTS", nullable = false, length = 16)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, length = 5)) })
	public BhrSupplXmitalId getId() {
		return this.id;
	}

	public void setId(BhrSupplXmitalId id) {
		this.id = id;
	}

	@Column(name = "JOB_CD", nullable = false, length = 4)
	public String getJobCd() {
		return this.jobCd;
	}

	public void setJobCd(String jobCd) {
		this.jobCd = jobCd;
	}

	@Column(name = "CAMPUS_ID", nullable = false, length = 3)
	public String getCampusId() {
		return this.campusId;
	}

	public void setCampusId(String campusId) {
		this.campusId = campusId;
	}

	@Column(name = "DEPT", nullable = false, length = 1)
	public char getDept() {
		return this.dept;
	}

	public void setDept(char dept) {
		this.dept = dept;
	}

	@Column(name = "TRS_GRANT_CD", nullable = false, length = 2)
	public String getTrsGrantCd() {
		return this.trsGrantCd;
	}

	public void setTrsGrantCd(String trsGrantCd) {
		this.trsGrantCd = trsGrantCd;
	}

	@Column(name = "GL_FILE_ID", nullable = false, length = 1)
	public char getGlFileId() {
		return this.glFileId;
	}

	public void setGlFileId(char glFileId) {
		this.glFileId = glFileId;
	}

	@Column(name = "FUND", nullable = false, length = 3)
	public String getFund() {
		return this.fund;
	}

	public void setFund(String fund) {
		this.fund = fund;
	}

	@Column(name = "FUNC", nullable = false, length = 2)
	public String getFunc() {
		return this.func;
	}

	public void setFunc(String func) {
		this.func = func;
	}

	@Column(name = "OBJ", nullable = false, length = 4)
	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	@Column(name = "SOBJ", nullable = false, length = 2)
	public String getSobj() {
		return this.sobj;
	}

	public void setSobj(String sobj) {
		this.sobj = sobj;
	}

	@Column(name = "WRK_COMP", nullable = false, length = 1)
	public char getWrkComp() {
		return this.wrkComp;
	}

	public void setWrkComp(char wrkComp) {
		this.wrkComp = wrkComp;
	}

	@Column(name = "ORG", nullable = false, length = 3)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "FSCL_YR", nullable = false, length = 1)
	public char getFsclYr() {
		return this.fsclYr;
	}

	public void setFsclYr(char fsclYr) {
		this.fsclYr = fsclYr;
	}

	@Column(name = "PGM", nullable = false, length = 2)
	public String getPgm() {
		return this.pgm;
	}

	public void setPgm(String pgm) {
		this.pgm = pgm;
	}

	@Column(name = "ED_SPAN", nullable = false, length = 1)
	public char getEdSpan() {
		return this.edSpan;
	}

	public void setEdSpan(char edSpan) {
		this.edSpan = edSpan;
	}

	@Column(name = "PROJ_DTL", nullable = false, length = 2)
	public String getProjDtl() {
		return this.projDtl;
	}

	public void setProjDtl(String projDtl) {
		this.projDtl = projDtl;
	}

	@Column(name = "SUPPL_AMT", nullable = false, precision = 9)
	public BigDecimal getSupplAmt() {
		return this.supplAmt;
	}

	public void setSupplAmt(BigDecimal supplAmt) {
		this.supplAmt = supplAmt;
	}

	@Column(name = "ADD_STD_GROSS_CD", nullable = false, length = 1)
	public char getAddStdGrossCd() {
		return this.addStdGrossCd;
	}

	public void setAddStdGrossCd(char addStdGrossCd) {
		this.addStdGrossCd = addStdGrossCd;
	}

	@Column(name = "ADJ_SALARY_CD", nullable = false, length = 1)
	public char getAdjSalaryCd() {
		return this.adjSalaryCd;
	}

	public void setAdjSalaryCd(char adjSalaryCd) {
		this.adjSalaryCd = adjSalaryCd;
	}

	@Column(name = "OVTM_CD", nullable = false, length = 1)
	public char getOvtmCd() {
		return this.ovtmCd;
	}

	public void setOvtmCd(char ovtmCd) {
		this.ovtmCd = ovtmCd;
	}

	@Column(name = "OVTM_HRS_WRK", nullable = false, precision = 5)
	public BigDecimal getOvtmHrsWrk() {
		return this.ovtmHrsWrk;
	}

	public void setOvtmHrsWrk(BigDecimal ovtmHrsWrk) {
		this.ovtmHrsWrk = ovtmHrsWrk;
	}

	@Column(name = "REG_HRS_WRK", nullable = false, precision = 5)
	public BigDecimal getRegHrsWrk() {
		return this.regHrsWrk;
	}

	public void setRegHrsWrk(BigDecimal regHrsWrk) {
		this.regHrsWrk = regHrsWrk;
	}

	@Column(name = "TAXED_BENEFIT_FLG", nullable = false, length = 1)
	public char getTaxedBenefitFlg() {
		return this.taxedBenefitFlg;
	}

	public void setTaxedBenefitFlg(char taxedBenefitFlg) {
		this.taxedBenefitFlg = taxedBenefitFlg;
	}

	@Column(name = "NON_TRS_PYMT_TYP", nullable = false, length = 1)
	public char getNonTrsPymtTyp() {
		return this.nonTrsPymtTyp;
	}

	public void setNonTrsPymtTyp(char nonTrsPymtTyp) {
		this.nonTrsPymtTyp = nonTrsPymtTyp;
	}

	@Column(name = "NON_TRS_PYMT_CD", nullable = false, length = 1)
	public char getNonTrsPymtCd() {
		return this.nonTrsPymtCd;
	}

	public void setNonTrsPymtCd(char nonTrsPymtCd) {
		this.nonTrsPymtCd = nonTrsPymtCd;
	}

	@Column(name = "NON_TRS_NON_TAX_AMT", nullable = false, precision = 9)
	public BigDecimal getNonTrsNonTaxAmt() {
		return this.nonTrsNonTaxAmt;
	}

	public void setNonTrsNonTaxAmt(BigDecimal nonTrsNonTaxAmt) {
		this.nonTrsNonTaxAmt = nonTrsNonTaxAmt;
	}

	@Column(name = "NON_TRS_TAX_AMT", nullable = false, precision = 9)
	public BigDecimal getNonTrsTaxAmt() {
		return this.nonTrsTaxAmt;
	}

	public void setNonTrsTaxAmt(BigDecimal nonTrsTaxAmt) {
		this.nonTrsTaxAmt = nonTrsTaxAmt;
	}

	@Column(name = "EXPENSE_373", nullable = false, length = 1)
	public char getExpense373() {
		return this.expense373;
	}

	public void setExpense373(char expense373) {
		this.expense373 = expense373;
	}

	@Column(name = "BLK_INS", nullable = false, length = 1)
	public char getBlkIns() {
		return this.blkIns;
	}

	public void setBlkIns(char blkIns) {
		this.blkIns = blkIns;
	}

	@Column(name = "SERV_REC_DAYS_DEDUCT", nullable = false, precision = 5)
	public BigDecimal getServRecDaysDeduct() {
		return this.servRecDaysDeduct;
	}

	public void setServRecDaysDeduct(BigDecimal servRecDaysDeduct) {
		this.servRecDaysDeduct = servRecDaysDeduct;
	}

	@Column(name = "SUB_TYP", nullable = false, length = 2)
	public String getSubTyp() {
		return this.subTyp;
	}

	public void setSubTyp(String subTyp) {
		this.subTyp = subTyp;
	}

	@Column(name = "TRANSMITTAL_TYPE", nullable = false, length = 1)
	public char getTransmittalType() {
		return this.transmittalType;
	}

	public void setTransmittalType(char transmittalType) {
		this.transmittalType = transmittalType;
	}

	@Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)
	public String getExtraDutyCd() {
		return this.extraDutyCd;
	}

	public void setExtraDutyCd(String extraDutyCd) {
		this.extraDutyCd = extraDutyCd;
	}

	@Column(name = "PROCESS_DT", nullable = false, length = 8)
	public String getProcessDt() {
		return this.processDt;
	}

	public void setProcessDt(String processDt) {
		this.processDt = processDt;
	}

	@Column(name = "USER_ID", nullable = false, length = 12)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "TAXED_FRINGE_BENEFIT", nullable = false, length = 1)
	public char getTaxedFringeBenefit() {
		return this.taxedFringeBenefit;
	}

	public void setTaxedFringeBenefit(char taxedFringeBenefit) {
		this.taxedFringeBenefit = taxedFringeBenefit;
	}

	@Column(name = "PERFOR_PAY", nullable = false, length = 1)
	public char getPerforPay() {
		return this.perforPay;
	}

	public void setPerforPay(char perforPay) {
		this.perforPay = perforPay;
	}

	@Column(name = "RSN", nullable = false, length = 30)
	public String getRsn() {
		return this.rsn;
	}

	public void setRsn(String rsn) {
		this.rsn = rsn;
	}

	@Column(name = "APPLY_457", nullable = false, length = 1)
	public char getApply457() {
		return this.apply457;
	}

	public void setApply457(char apply457) {
		this.apply457 = apply457;
	}

	@Column(name = "CREATED_CIP", nullable = false, length = 1)
	public char getCreatedCip() {
		return this.createdCip;
	}

	public void setCreatedCip(char createdCip) {
		this.createdCip = createdCip;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "ACT_HRS", nullable = false, precision = 5)
	public BigDecimal getActHrs() {
		return this.actHrs;
	}

	public void setActHrs(BigDecimal actHrs) {
		this.actHrs = actHrs;
	}

	@Column(name = "ACT_DT", nullable = false, length = 8)
	public String getActDt() {
		return this.actDt;
	}

	public void setActDt(String actDt) {
		this.actDt = actDt;
	}

}
