package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTrsMd90 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TRS_MD90", schema = "rsccc", catalog = "rsccc")
public class BhrTrsMd90 implements java.io.Serializable {

	private BhrTrsMd90Id id;
	private String dtTerm;
	private char noFurtherCon;
	private String finalPayMo;
	private String finalPayYr;
	private String nbrDaysPaid;
	private BigDecimal annualSalary;
	private char termRsnCd;
	private String module;

	public BhrTrsMd90() {
	}

	public BhrTrsMd90(BhrTrsMd90Id id, String dtTerm, char noFurtherCon, String finalPayMo, String finalPayYr,
			String nbrDaysPaid, BigDecimal annualSalary, char termRsnCd, String module) {
		this.id = id;
		this.dtTerm = dtTerm;
		this.noFurtherCon = noFurtherCon;
		this.finalPayMo = finalPayMo;
		this.finalPayYr = finalPayYr;
		this.nbrDaysPaid = nbrDaysPaid;
		this.annualSalary = annualSalary;
		this.termRsnCd = termRsnCd;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "staffId", column = @Column(name = "STAFF_ID", nullable = false, length = 9)) })
	public BhrTrsMd90Id getId() {
		return this.id;
	}

	public void setId(BhrTrsMd90Id id) {
		this.id = id;
	}

	@Column(name = "DT_TERM", nullable = false, length = 8)
	public String getDtTerm() {
		return this.dtTerm;
	}

	public void setDtTerm(String dtTerm) {
		this.dtTerm = dtTerm;
	}

	@Column(name = "NO_FURTHER_CON", nullable = false, length = 1)
	public char getNoFurtherCon() {
		return this.noFurtherCon;
	}

	public void setNoFurtherCon(char noFurtherCon) {
		this.noFurtherCon = noFurtherCon;
	}

	@Column(name = "FINAL_PAY_MO", nullable = false, length = 2)
	public String getFinalPayMo() {
		return this.finalPayMo;
	}

	public void setFinalPayMo(String finalPayMo) {
		this.finalPayMo = finalPayMo;
	}

	@Column(name = "FINAL_PAY_YR", nullable = false, length = 4)
	public String getFinalPayYr() {
		return this.finalPayYr;
	}

	public void setFinalPayYr(String finalPayYr) {
		this.finalPayYr = finalPayYr;
	}

	@Column(name = "NBR_DAYS_PAID", nullable = false, length = 3)
	public String getNbrDaysPaid() {
		return this.nbrDaysPaid;
	}

	public void setNbrDaysPaid(String nbrDaysPaid) {
		this.nbrDaysPaid = nbrDaysPaid;
	}

	@Column(name = "ANNUAL_SALARY", nullable = false, precision = 9)
	public BigDecimal getAnnualSalary() {
		return this.annualSalary;
	}

	public void setAnnualSalary(BigDecimal annualSalary) {
		this.annualSalary = annualSalary;
	}

	@Column(name = "TERM_RSN_CD", nullable = false, length = 1)
	public char getTermRsnCd() {
		return this.termRsnCd;
	}

	public void setTermRsnCd(char termRsnCd) {
		this.termRsnCd = termRsnCd;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
