package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrTrsAdjustmentDaysId generated by hbm2java
 */
@Embeddable
public class BhrTrsAdjustmentDaysId implements java.io.Serializable {

	private String staffId;
	private String dtBegAdj;
	private String dtEndAdj;

	public BhrTrsAdjustmentDaysId() {
	}

	public BhrTrsAdjustmentDaysId(String staffId, String dtBegAdj, String dtEndAdj) {
		this.staffId = staffId;
		this.dtBegAdj = dtBegAdj;
		this.dtEndAdj = dtEndAdj;
	}

	@Column(name = "STAFF_ID", nullable = false, length = 9)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "DT_BEG_ADJ", nullable = false, length = 8)
	public String getDtBegAdj() {
		return this.dtBegAdj;
	}

	public void setDtBegAdj(String dtBegAdj) {
		this.dtBegAdj = dtBegAdj;
	}

	@Column(name = "DT_END_ADJ", nullable = false, length = 8)
	public String getDtEndAdj() {
		return this.dtEndAdj;
	}

	public void setDtEndAdj(String dtEndAdj) {
		this.dtEndAdj = dtEndAdj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrTrsAdjustmentDaysId))
			return false;
		BhrTrsAdjustmentDaysId castOther = (BhrTrsAdjustmentDaysId) other;

		return ((this.getStaffId() == castOther.getStaffId()) || (this.getStaffId() != null
				&& castOther.getStaffId() != null && this.getStaffId().equals(castOther.getStaffId())))
				&& ((this.getDtBegAdj() == castOther.getDtBegAdj()) || (this.getDtBegAdj() != null
						&& castOther.getDtBegAdj() != null && this.getDtBegAdj().equals(castOther.getDtBegAdj())))
				&& ((this.getDtEndAdj() == castOther.getDtEndAdj()) || (this.getDtEndAdj() != null
						&& castOther.getDtEndAdj() != null && this.getDtEndAdj().equals(castOther.getDtEndAdj())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStaffId() == null ? 0 : this.getStaffId().hashCode());
		result = 37 * result + (getDtBegAdj() == null ? 0 : this.getDtBegAdj().hashCode());
		result = 37 * result + (getDtEndAdj() == null ? 0 : this.getDtEndAdj().hashCode());
		return result;
	}

}
