package com.esc20.model;
// Generated Jan 4, 2019 3:48:53 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Bthr457DefBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class Bthr457DefBkupPaycalcs5Id implements java.io.Serializable {

	private String taxYr;
	private BigDecimal emp457Pct;
	private BigDecimal emplr457Pct;
	private String module;

	public Bthr457DefBkupPaycalcs5Id() {
	}

	public Bthr457DefBkupPaycalcs5Id(String taxYr, BigDecimal emp457Pct, BigDecimal emplr457Pct, String module) {
		this.taxYr = taxYr;
		this.emp457Pct = emp457Pct;
		this.emplr457Pct = emplr457Pct;
		this.module = module;
	}

	@Column(name = "TAX_YR", nullable = false, length = 4)
	public String getTaxYr() {
		return this.taxYr;
	}

	public void setTaxYr(String taxYr) {
		this.taxYr = taxYr;
	}

	@Column(name = "EMP_457_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getEmp457Pct() {
		return this.emp457Pct;
	}

	public void setEmp457Pct(BigDecimal emp457Pct) {
		this.emp457Pct = emp457Pct;
	}

	@Column(name = "EMPLR_457_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getEmplr457Pct() {
		return this.emplr457Pct;
	}

	public void setEmplr457Pct(BigDecimal emplr457Pct) {
		this.emplr457Pct = emplr457Pct;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Bthr457DefBkupPaycalcs5Id))
			return false;
		Bthr457DefBkupPaycalcs5Id castOther = (Bthr457DefBkupPaycalcs5Id) other;

		return ((this.getTaxYr() == castOther.getTaxYr()) || (this.getTaxYr() != null && castOther.getTaxYr() != null
				&& this.getTaxYr().equals(castOther.getTaxYr())))
				&& ((this.getEmp457Pct() == castOther.getEmp457Pct()) || (this.getEmp457Pct() != null
						&& castOther.getEmp457Pct() != null && this.getEmp457Pct().equals(castOther.getEmp457Pct())))
				&& ((this.getEmplr457Pct() == castOther.getEmplr457Pct())
						|| (this.getEmplr457Pct() != null && castOther.getEmplr457Pct() != null
								&& this.getEmplr457Pct().equals(castOther.getEmplr457Pct())))
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTaxYr() == null ? 0 : this.getTaxYr().hashCode());
		result = 37 * result + (getEmp457Pct() == null ? 0 : this.getEmp457Pct().hashCode());
		result = 37 * result + (getEmplr457Pct() == null ? 0 : this.getEmplr457Pct().hashCode());
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		return result;
	}

}
