package com.esc20.model;
// Generated Jan 4, 2019 3:54:04 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrPosFrcstConv generated by hbm2java
 */
@Entity
@Table(name = "BTHR_POS_FRCST_CONV", schema = "rsccc", catalog = "rsccc")
public class BthrPosFrcstConv implements java.io.Serializable {

	private BthrPosFrcstConvId id;
	private String startDt;
	private String endDt;
	private String dtPayoff;
	private short maxDays;
	private short actDays;
	private BigDecimal nbrDaysOff;
	private short nbrPymts;
	private String module;

	public BthrPosFrcstConv() {
	}

	public BthrPosFrcstConv(BthrPosFrcstConvId id, String startDt, String endDt, String dtPayoff, short maxDays,
			short actDays, BigDecimal nbrDaysOff, short nbrPymts, String module) {
		this.id = id;
		this.startDt = startDt;
		this.endDt = endDt;
		this.dtPayoff = dtPayoff;
		this.maxDays = maxDays;
		this.actDays = actDays;
		this.nbrDaysOff = nbrDaysOff;
		this.nbrPymts = nbrPymts;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "frstPayDtCd", column = @Column(name = "FRST_PAY_DT_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "calCd", column = @Column(name = "CAL_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "extraDutyCd", column = @Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)) })
	public BthrPosFrcstConvId getId() {
		return this.id;
	}

	public void setId(BthrPosFrcstConvId id) {
		this.id = id;
	}

	@Column(name = "START_DT", nullable = false, length = 8)
	public String getStartDt() {
		return this.startDt;
	}

	public void setStartDt(String startDt) {
		this.startDt = startDt;
	}

	@Column(name = "END_DT", nullable = false, length = 8)
	public String getEndDt() {
		return this.endDt;
	}

	public void setEndDt(String endDt) {
		this.endDt = endDt;
	}

	@Column(name = "DT_PAYOFF", nullable = false, length = 8)
	public String getDtPayoff() {
		return this.dtPayoff;
	}

	public void setDtPayoff(String dtPayoff) {
		this.dtPayoff = dtPayoff;
	}

	@Column(name = "MAX_DAYS", nullable = false, precision = 3, scale = 0)
	public short getMaxDays() {
		return this.maxDays;
	}

	public void setMaxDays(short maxDays) {
		this.maxDays = maxDays;
	}

	@Column(name = "ACT_DAYS", nullable = false, precision = 3, scale = 0)
	public short getActDays() {
		return this.actDays;
	}

	public void setActDays(short actDays) {
		this.actDays = actDays;
	}

	@Column(name = "NBR_DAYS_OFF", nullable = false, precision = 3, scale = 1)
	public BigDecimal getNbrDaysOff() {
		return this.nbrDaysOff;
	}

	public void setNbrDaysOff(BigDecimal nbrDaysOff) {
		this.nbrDaysOff = nbrDaysOff;
	}

	@Column(name = "NBR_PYMTS", nullable = false, precision = 3, scale = 0)
	public short getNbrPymts() {
		return this.nbrPymts;
	}

	public void setNbrPymts(short nbrPymts) {
		this.nbrPymts = nbrPymts;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
