package com.esc20.model;
// Generated Jan 4, 2019 3:51:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrDockTyp generated by hbm2java
 */
@Entity
@Table(name = "BTHR_DOCK_TYP", schema = "rsccc", catalog = "rsccc")
public class BthrDockTyp implements java.io.Serializable {

	private char dockTyp;
	private String dockDescr;

	public BthrDockTyp() {
	}

	public BthrDockTyp(char dockTyp, String dockDescr) {
		this.dockTyp = dockTyp;
		this.dockDescr = dockDescr;
	}

	@Id

	@Column(name = "DOCK_TYP", nullable = false, length = 1)
	public char getDockTyp() {
		return this.dockTyp;
	}

	public void setDockTyp(char dockTyp) {
		this.dockTyp = dockTyp;
	}

	@Column(name = "DOCK_DESCR", nullable = false, length = 30)
	public String getDockDescr() {
		return this.dockDescr;
	}

	public void setDockDescr(String dockDescr) {
		this.dockDescr = dockDescr;
	}

}
