package com.esc20.model;
// Generated Jan 4, 2019 3:51:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrEmplrTyp generated by hbm2java
 */
@Entity
@Table(name = "BTHR_EMPLR_TYP", schema = "rsccc", catalog = "rsccc")
public class BthrEmplrTyp implements java.io.Serializable {

	private char emplrTyp;
	private String emplrDescr;

	public BthrEmplrTyp() {
	}

	public BthrEmplrTyp(char emplrTyp, String emplrDescr) {
		this.emplrTyp = emplrTyp;
		this.emplrDescr = emplrDescr;
	}

	@Id

	@Column(name = "EMPLR_TYP", nullable = false, length = 1)
	public char getEmplrTyp() {
		return this.emplrTyp;
	}

	public void setEmplrTyp(char emplrTyp) {
		this.emplrTyp = emplrTyp;
	}

	@Column(name = "EMPLR_DESCR", nullable = false, length = 20)
	public String getEmplrDescr() {
		return this.emplrDescr;
	}

	public void setEmplrDescr(String emplrDescr) {
		this.emplrDescr = emplrDescr;
	}

}
