package com.esc20.model;
// Generated Jan 4, 2019 3:53:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BthrPayDatesStatus generated by hbm2java
 */
@Entity
@Table(name = "BTHR_PAY_DATES_STATUS", schema = "rsccc", catalog = "rsccc")
public class BthrPayDatesStatus implements java.io.Serializable {

	private BthrPayDatesStatusId id;
	private String dtPayRun;
	private char interfaceFlg;
	private String usrId;
	private String module;

	public BthrPayDatesStatus() {
	}

	public BthrPayDatesStatus(BthrPayDatesStatusId id, String dtPayRun, char interfaceFlg,
			String usrId, String module) {
		this.id = id;
		this.dtPayRun = dtPayRun;
		this.interfaceFlg = interfaceFlg;
		this.usrId = usrId;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)) })
	public BthrPayDatesStatusId getId() {
		return this.id;
	}

	public void setId(BthrPayDatesStatusId id) {
		this.id = id;
	}

	@Column(name = "DT_PAY_RUN", nullable = false, length = 8)
	public String getDtPayRun() {
		return this.dtPayRun;
	}

	public void setDtPayRun(String dtPayRun) {
		this.dtPayRun = dtPayRun;
	}

	@Column(name = "INTERFACE_FLG", nullable = false, length = 1)
	public char getInterfaceFlg() {
		return this.interfaceFlg;
	}

	public void setInterfaceFlg(char interfaceFlg) {
		this.interfaceFlg = interfaceFlg;
	}

	@Column(name = "USR_ID", nullable = false, length = 12)
	public String getUsrId() {
		return this.usrId;
	}

	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
