package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * BthrLvTypDescr generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LV_TYP_DESCR", schema = "rsccc", catalog = "rsccc")
public class BthrLvTypDescr implements java.io.Serializable {

	private String lvTyp;
	private String shortDescr;
	private String longDescr;
	private char useForDockTrsDays;
	private String module;
	private char textReq;
	private char postAgnstZeroBal;
	private String eoyCutoffDt;
	private String eoyEntryCutoffDt;
	private char stat;
	private Set<BthrLvTyp> bthrLvTyps = new HashSet<BthrLvTyp>(0);
	private BthrLvTypNotes bthrLvTypNotes;

	public BthrLvTypDescr() {
	}

	public BthrLvTypDescr(String lvTyp, String shortDescr, String longDescr, char useForDockTrsDays, String module,
			char textReq, char postAgnstZeroBal, String eoyCutoffDt, String eoyEntryCutoffDt, char stat) {
		this.lvTyp = lvTyp;
		this.shortDescr = shortDescr;
		this.longDescr = longDescr;
		this.useForDockTrsDays = useForDockTrsDays;
		this.module = module;
		this.textReq = textReq;
		this.postAgnstZeroBal = postAgnstZeroBal;
		this.eoyCutoffDt = eoyCutoffDt;
		this.eoyEntryCutoffDt = eoyEntryCutoffDt;
		this.stat = stat;
	}

	public BthrLvTypDescr(String lvTyp, String shortDescr, String longDescr, char useForDockTrsDays, String module,
			char textReq, char postAgnstZeroBal, String eoyCutoffDt, String eoyEntryCutoffDt, char stat,
			Set<BthrLvTyp> bthrLvTyps, BthrLvTypNotes bthrLvTypNotes) {
		this.lvTyp = lvTyp;
		this.shortDescr = shortDescr;
		this.longDescr = longDescr;
		this.useForDockTrsDays = useForDockTrsDays;
		this.module = module;
		this.textReq = textReq;
		this.postAgnstZeroBal = postAgnstZeroBal;
		this.eoyCutoffDt = eoyCutoffDt;
		this.eoyEntryCutoffDt = eoyEntryCutoffDt;
		this.stat = stat;
		this.bthrLvTyps = bthrLvTyps;
		this.bthrLvTypNotes = bthrLvTypNotes;
	}

	@Id

	@Column(name = "LV_TYP", nullable = false, length = 2)
	public String getLvTyp() {
		return this.lvTyp;
	}

	public void setLvTyp(String lvTyp) {
		this.lvTyp = lvTyp;
	}

	@Column(name = "SHORT_DESCR", nullable = false, length = 10)
	public String getShortDescr() {
		return this.shortDescr;
	}

	public void setShortDescr(String shortDescr) {
		this.shortDescr = shortDescr;
	}

	@Column(name = "LONG_DESCR", nullable = false, length = 20)
	public String getLongDescr() {
		return this.longDescr;
	}

	public void setLongDescr(String longDescr) {
		this.longDescr = longDescr;
	}

	@Column(name = "USE_FOR_DOCK_TRS_DAYS", nullable = false, length = 1)
	public char getUseForDockTrsDays() {
		return this.useForDockTrsDays;
	}

	public void setUseForDockTrsDays(char useForDockTrsDays) {
		this.useForDockTrsDays = useForDockTrsDays;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "TEXT_REQ", nullable = false, length = 1)
	public char getTextReq() {
		return this.textReq;
	}

	public void setTextReq(char textReq) {
		this.textReq = textReq;
	}

	@Column(name = "POST_AGNST_ZERO_BAL", nullable = false, length = 1)
	public char getPostAgnstZeroBal() {
		return this.postAgnstZeroBal;
	}

	public void setPostAgnstZeroBal(char postAgnstZeroBal) {
		this.postAgnstZeroBal = postAgnstZeroBal;
	}

	@Column(name = "EOY_CUTOFF_DT", nullable = false, length = 8)
	public String getEoyCutoffDt() {
		return this.eoyCutoffDt;
	}

	public void setEoyCutoffDt(String eoyCutoffDt) {
		this.eoyCutoffDt = eoyCutoffDt;
	}

	@Column(name = "EOY_ENTRY_CUTOFF_DT", nullable = false, length = 8)
	public String getEoyEntryCutoffDt() {
		return this.eoyEntryCutoffDt;
	}

	public void setEoyEntryCutoffDt(String eoyEntryCutoffDt) {
		this.eoyEntryCutoffDt = eoyEntryCutoffDt;
	}

	@Column(name = "STAT", nullable = false, length = 1)
	public char getStat() {
		return this.stat;
	}

	public void setStat(char stat) {
		this.stat = stat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bthrLvTypDescr")
	public Set<BthrLvTyp> getBthrLvTyps() {
		return this.bthrLvTyps;
	}

	public void setBthrLvTyps(Set<BthrLvTyp> bthrLvTyps) {
		this.bthrLvTyps = bthrLvTyps;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "bthrLvTypDescr")
	public BthrLvTypNotes getBthrLvTypNotes() {
		return this.bthrLvTypNotes;
	}

	public void setBthrLvTypNotes(BthrLvTypNotes bthrLvTypNotes) {
		this.bthrLvTypNotes = bthrLvTypNotes;
	}

}
