package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BthrLvRates generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LV_RATES", schema = "rsccc", catalog = "rsccc")
public class BthrLvRates implements java.io.Serializable {

	private BthrLvRatesId id;
	private BthrLvTyp bthrLvTyp;
	private char seqOrder;
	private String duration;
	private BigDecimal dockAmt;
	private char dockTyp;
	private String module;

	public BthrLvRates() {
	}

	public BthrLvRates(BthrLvRatesId id, BthrLvTyp bthrLvTyp, char seqOrder, String duration, BigDecimal dockAmt,
			char dockTyp, String module) {
		this.id = id;
		this.bthrLvTyp = bthrLvTyp;
		this.seqOrder = seqOrder;
		this.duration = duration;
		this.dockAmt = dockAmt;
		this.dockTyp = dockTyp;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "lvSeq", column = @Column(name = "LV_SEQ", nullable = false, precision = 2, scale = 0)) })
	public BthrLvRatesId getId() {
		return this.id;
	}

	public void setId(BthrLvRatesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PAY_FREQ", referencedColumnName = "PAY_FREQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "LV_TYP", referencedColumnName = "LV_TYP", nullable = false, insertable = false, updatable = false) })
	public BthrLvTyp getBthrLvTyp() {
		return this.bthrLvTyp;
	}

	public void setBthrLvTyp(BthrLvTyp bthrLvTyp) {
		this.bthrLvTyp = bthrLvTyp;
	}

	@Column(name = "SEQ_ORDER", nullable = false, length = 1)
	public char getSeqOrder() {
		return this.seqOrder;
	}

	public void setSeqOrder(char seqOrder) {
		this.seqOrder = seqOrder;
	}

	@Column(name = "DURATION", nullable = false, length = 3)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "DOCK_AMT", nullable = false, precision = 7)
	public BigDecimal getDockAmt() {
		return this.dockAmt;
	}

	public void setDockAmt(BigDecimal dockAmt) {
		this.dockAmt = dockAmt;
	}

	@Column(name = "DOCK_TYP", nullable = false, length = 1)
	public char getDockTyp() {
		return this.dockTyp;
	}

	public void setDockTyp(char dockTyp) {
		this.dockTyp = dockTyp;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
