package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BthrLvTypBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BthrLvTypBkupPaycalcs5Id implements java.io.Serializable {

	private char payFreq;
	private String lvTyp;
	private char chkStubPos;
	private int maxBal;
	private String daysHrs;
	private char dockWithBal;
	private char addSubtractBal;
	private String module;
	private char stat;

	public BthrLvTypBkupPaycalcs5Id() {
	}

	public BthrLvTypBkupPaycalcs5Id(char payFreq, String lvTyp, char chkStubPos, int maxBal, String daysHrs,
			char dockWithBal, char addSubtractBal, String module, char stat) {
		this.payFreq = payFreq;
		this.lvTyp = lvTyp;
		this.chkStubPos = chkStubPos;
		this.maxBal = maxBal;
		this.daysHrs = daysHrs;
		this.dockWithBal = dockWithBal;
		this.addSubtractBal = addSubtractBal;
		this.module = module;
		this.stat = stat;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "LV_TYP", nullable = false, length = 2)
	public String getLvTyp() {
		return this.lvTyp;
	}

	public void setLvTyp(String lvTyp) {
		this.lvTyp = lvTyp;
	}

	@Column(name = "CHK_STUB_POS", nullable = false, length = 1)
	public char getChkStubPos() {
		return this.chkStubPos;
	}

	public void setChkStubPos(char chkStubPos) {
		this.chkStubPos = chkStubPos;
	}

	@Column(name = "MAX_BAL", nullable = false, precision = 5, scale = 0)
	public int getMaxBal() {
		return this.maxBal;
	}

	public void setMaxBal(int maxBal) {
		this.maxBal = maxBal;
	}

	@Column(name = "DAYS_HRS", nullable = false, length = 3)
	public String getDaysHrs() {
		return this.daysHrs;
	}

	public void setDaysHrs(String daysHrs) {
		this.daysHrs = daysHrs;
	}

	@Column(name = "DOCK_WITH_BAL", nullable = false, length = 1)
	public char getDockWithBal() {
		return this.dockWithBal;
	}

	public void setDockWithBal(char dockWithBal) {
		this.dockWithBal = dockWithBal;
	}

	@Column(name = "ADD_SUBTRACT_BAL", nullable = false, length = 1)
	public char getAddSubtractBal() {
		return this.addSubtractBal;
	}

	public void setAddSubtractBal(char addSubtractBal) {
		this.addSubtractBal = addSubtractBal;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "STAT", nullable = false, length = 1)
	public char getStat() {
		return this.stat;
	}

	public void setStat(char stat) {
		this.stat = stat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BthrLvTypBkupPaycalcs5Id))
			return false;
		BthrLvTypBkupPaycalcs5Id castOther = (BthrLvTypBkupPaycalcs5Id) other;

		return (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getLvTyp() == castOther.getLvTyp()) || (this.getLvTyp() != null
						&& castOther.getLvTyp() != null && this.getLvTyp().equals(castOther.getLvTyp())))
				&& (this.getChkStubPos() == castOther.getChkStubPos()) && (this.getMaxBal() == castOther.getMaxBal())
				&& ((this.getDaysHrs() == castOther.getDaysHrs()) || (this.getDaysHrs() != null
						&& castOther.getDaysHrs() != null && this.getDaysHrs().equals(castOther.getDaysHrs())))
				&& (this.getDockWithBal() == castOther.getDockWithBal())
				&& (this.getAddSubtractBal() == castOther.getAddSubtractBal())
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())))
				&& (this.getStat() == castOther.getStat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getLvTyp() == null ? 0 : this.getLvTyp().hashCode());
		result = 37 * result + this.getChkStubPos();
		result = 37 * result + this.getMaxBal();
		result = 37 * result + (getDaysHrs() == null ? 0 : this.getDaysHrs().hashCode());
		result = 37 * result + this.getDockWithBal();
		result = 37 * result + this.getAddSubtractBal();
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		result = 37 * result + this.getStat();
		return result;
	}

}
