package com.esc20.model;
// Generated Jan 4, 2019 3:54:58 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrTeachField generated by hbm2java
 */
@Entity
@Table(name = "BTHR_TEACH_FIELD", schema = "rsccc", catalog = "rsccc")
public class BthrTeachField implements java.io.Serializable {

	private String teachField;
	private String teachFieldDescr;
	private String module;
	private String pkTeachReqmnt;

	public BthrTeachField() {
	}

	public BthrTeachField(String teachField, String teachFieldDescr, String module, String pkTeachReqmnt) {
		this.teachField = teachField;
		this.teachFieldDescr = teachFieldDescr;
		this.module = module;
		this.pkTeachReqmnt = pkTeachReqmnt;
	}

	@Id

	@Column(name = "TEACH_FIELD", nullable = false, length = 3)
	public String getTeachField() {
		return this.teachField;
	}

	public void setTeachField(String teachField) {
		this.teachField = teachField;
	}

	@Column(name = "TEACH_FIELD_DESCR", nullable = false, length = 20)
	public String getTeachFieldDescr() {
		return this.teachFieldDescr;
	}

	public void setTeachFieldDescr(String teachFieldDescr) {
		this.teachFieldDescr = teachFieldDescr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "PK_TEACH_REQMNT", nullable = false, length = 2)
	public String getPkTeachReqmnt() {
		return this.pkTeachReqmnt;
	}

	public void setPkTeachReqmnt(String pkTeachReqmnt) {
		this.pkTeachReqmnt = pkTeachReqmnt;
	}

}
