package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrFedIncomeExmptBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_FED_INCOME_EXMPT_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrFedIncomeExmptBkupPaycalcs5 implements java.io.Serializable {

	private BthrFedIncomeExmptBkupPaycalcs5Id id;

	public BthrFedIncomeExmptBkupPaycalcs5() {
	}

	public BthrFedIncomeExmptBkupPaycalcs5(BthrFedIncomeExmptBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxYr", column = @Column(name = "TAX_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "biWklyAmt", column = @Column(name = "BI_WKLY_AMT", nullable = false, precision = 7)),
			@AttributeOverride(name = "semiMnthlyAmt", column = @Column(name = "SEMI_MNTHLY_AMT", nullable = false, precision = 7)),
			@AttributeOverride(name = "mnthlyAmt", column = @Column(name = "MNTHLY_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrFedIncomeExmptBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrFedIncomeExmptBkupPaycalcs5Id id) {
		this.id = id;
	}

}
