package com.esc20.model;
// Generated Jan 4, 2019 3:54:58 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrTrsRate generated by hbm2java
 */
@Entity
@Table(name = "BTHR_TRS_RATE", schema = "rsccc", catalog = "rsccc")
public class BthrTrsRate implements java.io.Serializable {

	private String schYr;
	private BigDecimal trsPct;
	private BigDecimal trsFee;
	private BigDecimal trsIns;
	private BigDecimal districtPct;
	private BigDecimal trsCarePct;
	private BigDecimal emplrTrsCareContribPct;
	private char trs90DaysSocSecFlg;
	private BigDecimal trsIrsSalCap;
	private String module;
	private BigDecimal emplrTrsNonOasdiPct;

	public BthrTrsRate() {
	}

	public BthrTrsRate(String schYr, BigDecimal trsPct, BigDecimal trsFee, BigDecimal trsIns, BigDecimal districtPct,
			BigDecimal trsCarePct, BigDecimal emplrTrsCareContribPct, char trs90DaysSocSecFlg, BigDecimal trsIrsSalCap,
			String module, BigDecimal emplrTrsNonOasdiPct) {
		this.schYr = schYr;
		this.trsPct = trsPct;
		this.trsFee = trsFee;
		this.trsIns = trsIns;
		this.districtPct = districtPct;
		this.trsCarePct = trsCarePct;
		this.emplrTrsCareContribPct = emplrTrsCareContribPct;
		this.trs90DaysSocSecFlg = trs90DaysSocSecFlg;
		this.trsIrsSalCap = trsIrsSalCap;
		this.module = module;
		this.emplrTrsNonOasdiPct = emplrTrsNonOasdiPct;
	}

	@Id

	@Column(name = "SCH_YR", nullable = false, length = 4)
	public String getSchYr() {
		return this.schYr;
	}

	public void setSchYr(String schYr) {
		this.schYr = schYr;
	}

	@Column(name = "TRS_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getTrsPct() {
		return this.trsPct;
	}

	public void setTrsPct(BigDecimal trsPct) {
		this.trsPct = trsPct;
	}

	@Column(name = "TRS_FEE", nullable = false, precision = 5)
	public BigDecimal getTrsFee() {
		return this.trsFee;
	}

	public void setTrsFee(BigDecimal trsFee) {
		this.trsFee = trsFee;
	}

	@Column(name = "TRS_INS", nullable = false, precision = 5, scale = 4)
	public BigDecimal getTrsIns() {
		return this.trsIns;
	}

	public void setTrsIns(BigDecimal trsIns) {
		this.trsIns = trsIns;
	}

	@Column(name = "DISTRICT_PCT", nullable = false, precision = 6, scale = 5)
	public BigDecimal getDistrictPct() {
		return this.districtPct;
	}

	public void setDistrictPct(BigDecimal districtPct) {
		this.districtPct = districtPct;
	}

	@Column(name = "TRS_CARE_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getTrsCarePct() {
		return this.trsCarePct;
	}

	public void setTrsCarePct(BigDecimal trsCarePct) {
		this.trsCarePct = trsCarePct;
	}

	@Column(name = "EMPLR_TRS_CARE_CONTRIB_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getEmplrTrsCareContribPct() {
		return this.emplrTrsCareContribPct;
	}

	public void setEmplrTrsCareContribPct(BigDecimal emplrTrsCareContribPct) {
		this.emplrTrsCareContribPct = emplrTrsCareContribPct;
	}

	@Column(name = "TRS_90_DAYS_SOC_SEC_FLG", nullable = false, length = 1)
	public char getTrs90DaysSocSecFlg() {
		return this.trs90DaysSocSecFlg;
	}

	public void setTrs90DaysSocSecFlg(char trs90DaysSocSecFlg) {
		this.trs90DaysSocSecFlg = trs90DaysSocSecFlg;
	}

	@Column(name = "TRS_IRS_SAL_CAP", nullable = false, precision = 9)
	public BigDecimal getTrsIrsSalCap() {
		return this.trsIrsSalCap;
	}

	public void setTrsIrsSalCap(BigDecimal trsIrsSalCap) {
		this.trsIrsSalCap = trsIrsSalCap;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "EMPLR_TRS_NON_OASDI_PCT", nullable = false, precision = 6, scale = 5)
	public BigDecimal getEmplrTrsNonOasdiPct() {
		return this.emplrTrsNonOasdiPct;
	}

	public void setEmplrTrsNonOasdiPct(BigDecimal emplrTrsNonOasdiPct) {
		this.emplrTrsNonOasdiPct = emplrTrsNonOasdiPct;
	}

}
