package com.esc20.model;
// Generated Jan 4, 2019 3:49:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrAbsRsnBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ABS_RSN_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrAbsRsnBkupPaycalcs5 implements java.io.Serializable {

	private BthrAbsRsnBkupPaycalcs5Id id;

	public BthrAbsRsnBkupPaycalcs5() {
	}

	public BthrAbsRsnBkupPaycalcs5(BthrAbsRsnBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "absRsn", column = @Column(name = "ABS_RSN", nullable = false, length = 2)),
			@AttributeOverride(name = "absDescr", column = @Column(name = "ABS_DESCR", nullable = false, length = 30)),
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "glFileId", column = @Column(name = "GL_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "fund", column = @Column(name = "FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "func", column = @Column(name = "FUNC", nullable = false, length = 2)),
			@AttributeOverride(name = "obj", column = @Column(name = "OBJ", nullable = false, length = 4)),
			@AttributeOverride(name = "sobj", column = @Column(name = "SOBJ", nullable = false, length = 2)),
			@AttributeOverride(name = "org", column = @Column(name = "ORG", nullable = false, length = 3)),
			@AttributeOverride(name = "fsclYr", column = @Column(name = "FSCL_YR", nullable = false, length = 1)),
			@AttributeOverride(name = "pgm", column = @Column(name = "PGM", nullable = false, length = 2)),
			@AttributeOverride(name = "edSpan", column = @Column(name = "ED_SPAN", nullable = false, length = 1)),
			@AttributeOverride(name = "projDtl", column = @Column(name = "PROJ_DTL", nullable = false, length = 2)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "consecUntsReqrDoc", column = @Column(name = "CONSEC_UNTS_REQR_DOC", nullable = false, precision = 7)),
			@AttributeOverride(name = "consecUntsNxtApprvr", column = @Column(name = "CONSEC_UNTS_NXT_APPRVR", nullable = false, precision = 7)),
			@AttributeOverride(name = "consecUntsApprv3", column = @Column(name = "CONSEC_UNTS_APPRV3", nullable = false, precision = 7)),
			@AttributeOverride(name = "consecUntsApprv4", column = @Column(name = "CONSEC_UNTS_APPRV4", nullable = false, precision = 7)),
			@AttributeOverride(name = "consecUntsApprv5", column = @Column(name = "CONSEC_UNTS_APPRV5", nullable = false, precision = 7)),
			@AttributeOverride(name = "apprv3EmpNbr", column = @Column(name = "APPRV3_EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "apprv4EmpNbr", column = @Column(name = "APPRV4_EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "apprv5EmpNbr", column = @Column(name = "APPRV5_EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "stat", column = @Column(name = "STAT", nullable = false, length = 1)) })
	public BthrAbsRsnBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrAbsRsnBkupPaycalcs5Id id) {
		this.id = id;
	}

}
