package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrFundToGrant generated by hbm2java
 */
@Entity
@Table(name = "BTHR_FUND_TO_GRANT", schema = "rsccc", catalog = "rsccc")
public class BthrFundToGrant implements java.io.Serializable {

	private BthrFundToGrantId id;
	private String module;

	public BthrFundToGrant() {
	}

	public BthrFundToGrant(BthrFundToGrantId id, String module) {
		this.id = id;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "trsGrantCd", column = @Column(name = "TRS_GRANT_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "fund", column = @Column(name = "FUND", nullable = false, length = 3)),
			@AttributeOverride(name = "glFileId", column = @Column(name = "GL_FILE_ID", nullable = false, length = 1)),
			@AttributeOverride(name = "fsclYr", column = @Column(name = "FSCL_YR", nullable = false, length = 1)) })
	public BthrFundToGrantId getId() {
		return this.id;
	}

	public void setId(BthrFundToGrantId id) {
		this.id = id;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
