package com.esc20.model;
// Generated Jan 4, 2019 3:54:58 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BthrTrsRateBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BthrTrsRateBkupPaycalcs5Id implements java.io.Serializable {

	private String schYr;
	private BigDecimal trsPct;
	private BigDecimal trsFee;
	private BigDecimal trsIns;
	private BigDecimal districtPct;
	private BigDecimal trsCarePct;
	private BigDecimal emplrTrsCareContribPct;
	private char trs90DaysSocSecFlg;
	private BigDecimal trsIrsSalCap;
	private String module;
	private BigDecimal emplrTrsNonOasdiPct;

	public BthrTrsRateBkupPaycalcs5Id() {
	}

	public BthrTrsRateBkupPaycalcs5Id(String schYr, BigDecimal trsPct, BigDecimal trsFee, BigDecimal trsIns,
			BigDecimal districtPct, BigDecimal trsCarePct, BigDecimal emplrTrsCareContribPct, char trs90DaysSocSecFlg,
			BigDecimal trsIrsSalCap, String module, BigDecimal emplrTrsNonOasdiPct) {
		this.schYr = schYr;
		this.trsPct = trsPct;
		this.trsFee = trsFee;
		this.trsIns = trsIns;
		this.districtPct = districtPct;
		this.trsCarePct = trsCarePct;
		this.emplrTrsCareContribPct = emplrTrsCareContribPct;
		this.trs90DaysSocSecFlg = trs90DaysSocSecFlg;
		this.trsIrsSalCap = trsIrsSalCap;
		this.module = module;
		this.emplrTrsNonOasdiPct = emplrTrsNonOasdiPct;
	}

	@Column(name = "SCH_YR", nullable = false, length = 4)
	public String getSchYr() {
		return this.schYr;
	}

	public void setSchYr(String schYr) {
		this.schYr = schYr;
	}

	@Column(name = "TRS_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getTrsPct() {
		return this.trsPct;
	}

	public void setTrsPct(BigDecimal trsPct) {
		this.trsPct = trsPct;
	}

	@Column(name = "TRS_FEE", nullable = false, precision = 5)
	public BigDecimal getTrsFee() {
		return this.trsFee;
	}

	public void setTrsFee(BigDecimal trsFee) {
		this.trsFee = trsFee;
	}

	@Column(name = "TRS_INS", nullable = false, precision = 5, scale = 4)
	public BigDecimal getTrsIns() {
		return this.trsIns;
	}

	public void setTrsIns(BigDecimal trsIns) {
		this.trsIns = trsIns;
	}

	@Column(name = "DISTRICT_PCT", nullable = false, precision = 6, scale = 5)
	public BigDecimal getDistrictPct() {
		return this.districtPct;
	}

	public void setDistrictPct(BigDecimal districtPct) {
		this.districtPct = districtPct;
	}

	@Column(name = "TRS_CARE_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getTrsCarePct() {
		return this.trsCarePct;
	}

	public void setTrsCarePct(BigDecimal trsCarePct) {
		this.trsCarePct = trsCarePct;
	}

	@Column(name = "EMPLR_TRS_CARE_CONTRIB_PCT", nullable = false, precision = 5, scale = 4)
	public BigDecimal getEmplrTrsCareContribPct() {
		return this.emplrTrsCareContribPct;
	}

	public void setEmplrTrsCareContribPct(BigDecimal emplrTrsCareContribPct) {
		this.emplrTrsCareContribPct = emplrTrsCareContribPct;
	}

	@Column(name = "TRS_90_DAYS_SOC_SEC_FLG", nullable = false, length = 1)
	public char getTrs90DaysSocSecFlg() {
		return this.trs90DaysSocSecFlg;
	}

	public void setTrs90DaysSocSecFlg(char trs90DaysSocSecFlg) {
		this.trs90DaysSocSecFlg = trs90DaysSocSecFlg;
	}

	@Column(name = "TRS_IRS_SAL_CAP", nullable = false, precision = 9)
	public BigDecimal getTrsIrsSalCap() {
		return this.trsIrsSalCap;
	}

	public void setTrsIrsSalCap(BigDecimal trsIrsSalCap) {
		this.trsIrsSalCap = trsIrsSalCap;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "EMPLR_TRS_NON_OASDI_PCT", nullable = false, precision = 6, scale = 5)
	public BigDecimal getEmplrTrsNonOasdiPct() {
		return this.emplrTrsNonOasdiPct;
	}

	public void setEmplrTrsNonOasdiPct(BigDecimal emplrTrsNonOasdiPct) {
		this.emplrTrsNonOasdiPct = emplrTrsNonOasdiPct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BthrTrsRateBkupPaycalcs5Id))
			return false;
		BthrTrsRateBkupPaycalcs5Id castOther = (BthrTrsRateBkupPaycalcs5Id) other;

		return ((this.getSchYr() == castOther.getSchYr()) || (this.getSchYr() != null && castOther.getSchYr() != null
				&& this.getSchYr().equals(castOther.getSchYr())))
				&& ((this.getTrsPct() == castOther.getTrsPct()) || (this.getTrsPct() != null
						&& castOther.getTrsPct() != null && this.getTrsPct().equals(castOther.getTrsPct())))
				&& ((this.getTrsFee() == castOther.getTrsFee()) || (this.getTrsFee() != null
						&& castOther.getTrsFee() != null && this.getTrsFee().equals(castOther.getTrsFee())))
				&& ((this.getTrsIns() == castOther.getTrsIns()) || (this.getTrsIns() != null
						&& castOther.getTrsIns() != null && this.getTrsIns().equals(castOther.getTrsIns())))
				&& ((this.getDistrictPct() == castOther.getDistrictPct())
						|| (this.getDistrictPct() != null && castOther.getDistrictPct() != null
								&& this.getDistrictPct().equals(castOther.getDistrictPct())))
				&& ((this.getTrsCarePct() == castOther.getTrsCarePct()) || (this.getTrsCarePct() != null
						&& castOther.getTrsCarePct() != null && this.getTrsCarePct().equals(castOther.getTrsCarePct())))
				&& ((this.getEmplrTrsCareContribPct() == castOther.getEmplrTrsCareContribPct())
						|| (this.getEmplrTrsCareContribPct() != null && castOther.getEmplrTrsCareContribPct() != null
								&& this.getEmplrTrsCareContribPct().equals(castOther.getEmplrTrsCareContribPct())))
				&& (this.getTrs90DaysSocSecFlg() == castOther.getTrs90DaysSocSecFlg())
				&& ((this.getTrsIrsSalCap() == castOther.getTrsIrsSalCap())
						|| (this.getTrsIrsSalCap() != null && castOther.getTrsIrsSalCap() != null
								&& this.getTrsIrsSalCap().equals(castOther.getTrsIrsSalCap())))
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())))
				&& ((this.getEmplrTrsNonOasdiPct() == castOther.getEmplrTrsNonOasdiPct())
						|| (this.getEmplrTrsNonOasdiPct() != null && castOther.getEmplrTrsNonOasdiPct() != null
								&& this.getEmplrTrsNonOasdiPct().equals(castOther.getEmplrTrsNonOasdiPct())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSchYr() == null ? 0 : this.getSchYr().hashCode());
		result = 37 * result + (getTrsPct() == null ? 0 : this.getTrsPct().hashCode());
		result = 37 * result + (getTrsFee() == null ? 0 : this.getTrsFee().hashCode());
		result = 37 * result + (getTrsIns() == null ? 0 : this.getTrsIns().hashCode());
		result = 37 * result + (getDistrictPct() == null ? 0 : this.getDistrictPct().hashCode());
		result = 37 * result + (getTrsCarePct() == null ? 0 : this.getTrsCarePct().hashCode());
		result = 37 * result + (getEmplrTrsCareContribPct() == null ? 0 : this.getEmplrTrsCareContribPct().hashCode());
		result = 37 * result + this.getTrs90DaysSocSecFlg();
		result = 37 * result + (getTrsIrsSalCap() == null ? 0 : this.getTrsIrsSalCap().hashCode());
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		result = 37 * result + (getEmplrTrsNonOasdiPct() == null ? 0 : this.getEmplrTrsNonOasdiPct().hashCode());
		return result;
	}

}
