package com.esc20.model;
// Generated Jan 4, 2019 3:49:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrAcaAirSoftwareId generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ACA_AIR_SOFTWARE_ID", schema = "rsccc", catalog = "rsccc")
public class BthrAcaAirSoftwareId implements java.io.Serializable {

	private BthrAcaAirSoftwareIdId id;
	private String softwareId;

	public BthrAcaAirSoftwareId() {
	}

	public BthrAcaAirSoftwareId(BthrAcaAirSoftwareIdId id, String softwareId) {
		this.id = id;
		this.softwareId = softwareId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxYr", column = @Column(name = "TAX_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "formCd", column = @Column(name = "FORM_CD", nullable = false, length = 1)) })
	public BthrAcaAirSoftwareIdId getId() {
		return this.id;
	}

	public void setId(BthrAcaAirSoftwareIdId id) {
		this.id = id;
	}

	@Column(name = "SOFTWARE_ID", nullable = false, length = 25)
	public String getSoftwareId() {
		return this.softwareId;
	}

	public void setSoftwareId(String softwareId) {
		this.softwareId = softwareId;
	}

}
