package com.esc20.model;
// Generated Jan 4, 2019 3:53:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrPayStat generated by hbm2java
 */
@Entity
@Table(name = "BTHR_PAY_STAT", schema = "rsccc", catalog = "rsccc")
public class BthrPayStat implements java.io.Serializable {

	private char stat;
	private String descr;

	public BthrPayStat() {
	}

	public BthrPayStat(char stat, String descr) {
		this.stat = stat;
		this.descr = descr;
	}

	@Id

	@Column(name = "STAT", nullable = false, length = 1)
	public char getStat() {
		return this.stat;
	}

	public void setStat(char stat) {
		this.stat = stat;
	}

	@Column(name = "DESCR", nullable = false, length = 30)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

}
