package com.esc20.model;
// Generated Jan 4, 2019 3:55:15 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TxeisPreferences generated by hbm2java
 */
@Entity
@Table(name = "TXEIS_PREFERENCES", schema = "rsccc", catalog = "rsccc")
public class TxeisPreferences implements java.io.Serializable {

	private TxeisPreferencesId id;

	public TxeisPreferences() {
	}

	public TxeisPreferences(TxeisPreferencesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prefName", column = @Column(name = "PREF_NAME", nullable = false, length = 100)),
			@AttributeOverride(name = "prefValue", column = @Column(name = "PREF_VALUE", nullable = false, length = 250)) })
	public TxeisPreferencesId getId() {
		return this.id;
	}

	public void setId(TxeisPreferencesId id) {
		this.id = id;
	}

}
