package com.esc20.model;
// Generated Jan 4, 2019 3:30:30 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.esc20.nonDBModels.LeaveRequest;

/**
 * BeaEmpLvRqst generated by hbm2java
 */
@Entity
@Table(name = "BEA_EMP_LV_RQST", schema = "rsccc", catalog = "rsccc")
public class BeaEmpLvRqst implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private Integer id;
	private Character payFreq;
	private String empNbr;
	private Date datetimeSubmitted;
	private Date datetimeFrom;
	private Date datetimeTo;
	private BigDecimal lvUnitsDaily;
	private BigDecimal lvUnitsUsed;
	private String lvTyp;
	private String absRsn;
	private Character statusCd;
	private String dtOfPay;

	public BeaEmpLvRqst() {
	}

	public BeaEmpLvRqst(Integer id, Character payFreq, String empNbr, Date datetimeSubmitted, Date datetimeFrom, Date datetimeTo,
			BigDecimal lvUnitsDaily, BigDecimal lvUnitsUsed, String lvTyp, String absRsn, Character statusCd,
			String dtOfPay) {
		this.id = id;
		this.payFreq = payFreq;
		this.empNbr = empNbr;
		this.datetimeSubmitted = datetimeSubmitted;
		this.datetimeFrom = datetimeFrom;
		this.datetimeTo = datetimeTo;
		this.lvUnitsDaily = lvUnitsDaily;
		this.lvUnitsUsed = lvUnitsUsed;
		this.lvTyp = lvTyp;
		this.absRsn = absRsn;
		this.statusCd = statusCd;
		this.dtOfPay = dtOfPay;
	}
	
	public BeaEmpLvRqst (LeaveRequest rqst) {
		this.id = rqst.getId();
		this.payFreq = rqst.getPayFreq();
		this.empNbr = rqst.getEmpNbr();
		this.datetimeSubmitted = rqst.getDatetimeSubmitted();
		this.datetimeFrom = rqst.getDatetimeFrom();
		this.datetimeTo = rqst.getDatetimeTo();
		this.lvUnitsDaily = rqst.getLvUnitsDaily();
		this.lvUnitsUsed = rqst.getLvUnitsUsed();
		this.lvTyp = rqst.getLvTyp();
		this.absRsn = rqst.getAbsRsn();
		this.statusCd = rqst.getStatusCd();
		this.dtOfPay = rqst.getDtOfPay();
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public Character getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(Character payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATETIME_SUBMITTED", nullable = false, length = 23)
	public Date getDatetimeSubmitted() {
		return this.datetimeSubmitted;
	}

	public void setDatetimeSubmitted(Date datetimeSubmitted) {
		this.datetimeSubmitted = datetimeSubmitted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATETIME_FROM", nullable = false, length = 23)
	public Date getDatetimeFrom() {
		return this.datetimeFrom;
	}

	public void setDatetimeFrom(Date datetimeFrom) {
		this.datetimeFrom = datetimeFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATETIME_TO", nullable = false, length = 23)
	public Date getDatetimeTo() {
		return this.datetimeTo;
	}

	public void setDatetimeTo(Date datetimeTo) {
		this.datetimeTo = datetimeTo;
	}

	@Column(name = "LV_UNITS_DAILY", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvUnitsDaily() {
		return this.lvUnitsDaily;
	}

	public void setLvUnitsDaily(BigDecimal lvUnitsDaily) {
		this.lvUnitsDaily = lvUnitsDaily;
	}

	@Column(name = "LV_UNITS_USED", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvUnitsUsed() {
		return this.lvUnitsUsed;
	}

	public void setLvUnitsUsed(BigDecimal lvUnitsUsed) {
		this.lvUnitsUsed = lvUnitsUsed;
	}

	@Column(name = "LV_TYP", nullable = false, length = 2)
	public String getLvTyp() {
		return this.lvTyp;
	}

	public void setLvTyp(String lvTyp) {
		this.lvTyp = lvTyp;
	}

	@Column(name = "ABS_RSN", nullable = false, length = 2)
	public String getAbsRsn() {
		return this.absRsn;
	}

	public void setAbsRsn(String absRsn) {
		this.absRsn = absRsn;
	}

	@Column(name = "STATUS_CD", nullable = false, length = 1)
	public Character getStatusCd() {
		return this.statusCd;
	}

	public void setStatusCd(Character statusCd) {
		this.statusCd = statusCd;
	}

	@Column(name = "DT_OF_PAY", nullable = false, length = 8)
	public String getDtOfPay() {
		return this.dtOfPay;
	}

	public void setDtOfPay(String dtOfPay) {
		this.dtOfPay = dtOfPay;
	}

}
