package com.esc20.model;
// Generated Jan 4, 2019 3:30:30 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BeaEmpLvWorkflow generated by hbm2java
 */
@Entity
@Table(name = "BEA_EMP_LV_WORKFLOW", schema = "rsccc", catalog = "rsccc")
public class BeaEmpLvWorkflow implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private int id;
	private int lvId;
	private int seqNum;
	private Date insertDatetime;
	private Date tmpApprvrExpDatetime;
	private String apprvrEmpNbr;

	public BeaEmpLvWorkflow() {
	}

	public BeaEmpLvWorkflow(int id, int lvId, int seqNum, Date insertDatetime, String apprvrEmpNbr) {
		this.id = id;
		this.lvId = lvId;
		this.seqNum = seqNum;
		this.insertDatetime = insertDatetime;
		this.apprvrEmpNbr = apprvrEmpNbr;
	}

	public BeaEmpLvWorkflow(int id, int lvId, int seqNum, Date insertDatetime,
			Date tmpApprvrExpDatetime, String apprvrEmpNbr) {
		this.id = id;
		this.lvId = lvId;
		this.seqNum = seqNum;
		this.insertDatetime = insertDatetime;
		this.tmpApprvrExpDatetime = tmpApprvrExpDatetime;
		this.apprvrEmpNbr = apprvrEmpNbr;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LV_ID", nullable = false)
	public Integer getLvId() {
		return this.lvId;
	}

	public void setLvId(Integer lvId) {
		this.lvId = lvId;
	}

	@Column(name = "SEQ_NUM", nullable = false)
	public int getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(int seqNum) {
		this.seqNum = seqNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATETIME", nullable = false, length = 23)
	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TMP_APPRVR_EXP_DATETIME", length = 23)
	public Date getTmpApprvrExpDatetime() {
		return this.tmpApprvrExpDatetime;
	}

	public void setTmpApprvrExpDatetime(Date tmpApprvrExpDatetime) {
		this.tmpApprvrExpDatetime = tmpApprvrExpDatetime;
	}

	@Column(name = "APPRVR_EMP_NBR", nullable = false, length = 6)
	public String getApprvrEmpNbr() {
		return this.apprvrEmpNbr;
	}

	public void setApprvrEmpNbr(String apprvrEmpNbr) {
		this.apprvrEmpNbr = apprvrEmpNbr;
	}

}
