package com.esc20.model;
// Generated Jan 4, 2019 3:40:12 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpDeductBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_DEDUCT_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrEmpDeductBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpDeductBkupPaycalcs5Id id;

	public BhrEmpDeductBkupPaycalcs5() {
	}

	public BhrEmpDeductBkupPaycalcs5(BhrEmpDeductBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dedCd", column = @Column(name = "DED_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "dedSeq", column = @Column(name = "DED_SEQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empAmt", column = @Column(name = "EMP_AMT", nullable = false, precision = 7)),
			@AttributeOverride(name = "emplrAmt", column = @Column(name = "EMPLR_AMT", nullable = false, precision = 7)),
			@AttributeOverride(name = "emplrContribFactor", column = @Column(name = "EMPLR_CONTRIB_FACTOR", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "dedRemain", column = @Column(name = "DED_REMAIN", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "cafeFlg", column = @Column(name = "CAFE_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "refundElig", column = @Column(name = "REFUND_ELIG", nullable = false, length = 1)),
			@AttributeOverride(name = "caseNbr", column = @Column(name = "CASE_NBR", nullable = false, length = 20)),
			@AttributeOverride(name = "causeNbr", column = @Column(name = "CAUSE_NBR", nullable = false, length = 12)),
			@AttributeOverride(name = "bankCd", column = @Column(name = "BANK_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "bankAcctNbr", column = @Column(name = "BANK_ACCT_NBR", nullable = false, length = 17)),
			@AttributeOverride(name = "bankAcctTyp", column = @Column(name = "BANK_ACCT_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "bankPrenote", column = @Column(name = "BANK_PRENOTE", nullable = false, length = 1)),
			@AttributeOverride(name = "teaHealthInsContribFactor", column = @Column(name = "TEA_HEALTH_INS_CONTRIB_FACTOR", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BhrEmpDeductBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrEmpDeductBkupPaycalcs5Id id) {
		this.id = id;
	}

}
