package com.esc20.model;
// Generated Jan 4, 2019 3:40:12 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpJobBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_JOB_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrEmpJobBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpJobBkupPaycalcs5Id id;

	public BhrEmpJobBkupPaycalcs5() {
	}

	public BhrEmpJobBkupPaycalcs5(BhrEmpJobBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)),
			@AttributeOverride(name = "primJob", column = @Column(name = "PRIM_JOB", nullable = false, length = 1)),
			@AttributeOverride(name = "pctAssgnd", column = @Column(name = "PCT_ASSGND", nullable = false, precision = 3)),
			@AttributeOverride(name = "campusId", column = @Column(name = "CAMPUS_ID", nullable = false, length = 3)),
			@AttributeOverride(name = "dept", column = @Column(name = "DEPT", nullable = false, length = 1)),
			@AttributeOverride(name = "eeoc", column = @Column(name = "EEOC", nullable = false, length = 2)),
			@AttributeOverride(name = "contrAmt", column = @Column(name = "CONTR_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "contrRemainAmt", column = @Column(name = "CONTR_REMAIN_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "calCd", column = @Column(name = "CAL_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "contrDtBegin", column = @Column(name = "CONTR_DT_BEGIN", nullable = false, length = 8)),
			@AttributeOverride(name = "contrDtEnd", column = @Column(name = "CONTR_DT_END", nullable = false, length = 8)),
			@AttributeOverride(name = "contrNonStdFlg", column = @Column(name = "CONTR_NON_STD_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "contrDays", column = @Column(name = "CONTR_DAYS", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "stStep", column = @Column(name = "ST_STEP", nullable = false, length = 2)),
			@AttributeOverride(name = "stMinSalary", column = @Column(name = "ST_MIN_SALARY", nullable = false, precision = 9)),
			@AttributeOverride(name = "yrsCarLad", column = @Column(name = "YRS_CAR_LAD", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "payType", column = @Column(name = "PAY_TYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "payRate", column = @Column(name = "PAY_RATE", nullable = false, precision = 9)),
			@AttributeOverride(name = "payGrd", column = @Column(name = "PAY_GRD", nullable = false, length = 3)),
			@AttributeOverride(name = "paySched", column = @Column(name = "PAY_SCHED", nullable = false, length = 1)),
			@AttributeOverride(name = "payStep", column = @Column(name = "PAY_STEP", nullable = false, length = 2)),
			@AttributeOverride(name = "maxDays", column = @Column(name = "MAX_DAYS", nullable = false, length = 3)),
			@AttributeOverride(name = "exemptStat", column = @Column(name = "EXEMPT_STAT", nullable = false, length = 1)),
			@AttributeOverride(name = "dlyRateOfPay", column = @Column(name = "DLY_RATE_OF_PAY", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "regHrsWrk", column = @Column(name = "REG_HRS_WRK", nullable = false, precision = 5)),
			@AttributeOverride(name = "hrsPerDay", column = @Column(name = "HRS_PER_DAY", nullable = false, precision = 5, scale = 3)),
			@AttributeOverride(name = "nbrDaysEmpld", column = @Column(name = "NBR_DAYS_EMPLD", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "nbrDaysOff", column = @Column(name = "NBR_DAYS_OFF", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "nbrAnnualPymts", column = @Column(name = "NBR_ANNUAL_PYMTS", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "nbrRemainPymts", column = @Column(name = "NBR_REMAIN_PYMTS", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "nbrMonContr", column = @Column(name = "NBR_MON_CONTR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "ovtmEligFlg", column = @Column(name = "OVTM_ELIG_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "ovtmRate", column = @Column(name = "OVTM_RATE", nullable = false, precision = 5)),
			@AttributeOverride(name = "wrkComp", column = @Column(name = "WRK_COMP", nullable = false, length = 1)),
			@AttributeOverride(name = "wrkCompRemain", column = @Column(name = "WRK_COMP_REMAIN", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "trsPosCd", column = @Column(name = "TRS_POS_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "stMinSalaryPct", column = @Column(name = "ST_MIN_SALARY_PCT", nullable = false, precision = 3)),
			@AttributeOverride(name = "accruJob", column = @Column(name = "ACCRU_JOB", nullable = false, length = 1)),
			@AttributeOverride(name = "accruRate", column = @Column(name = "ACCRU_RATE", nullable = false, precision = 7, scale = 3)),
			@AttributeOverride(name = "contrDaysLoc", column = @Column(name = "CONTR_DAYS_LOC", nullable = false, length = 3)),
			@AttributeOverride(name = "dtPayoff", column = @Column(name = "DT_PAYOFF", nullable = false, length = 8)),
			@AttributeOverride(name = "yrsExpJob", column = @Column(name = "YRS_EXP_JOB", nullable = false, length = 2)),
			@AttributeOverride(name = "accruCd", column = @Column(name = "ACCRU_CD", nullable = false, length = 1)),
			@AttributeOverride(name = "wrkCompAnnlPymts", column = @Column(name = "WRK_COMP_ANNL_PYMTS", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "hrlyRate", column = @Column(name = "HRLY_RATE", nullable = false, precision = 5)),
			@AttributeOverride(name = "incrPayStp", column = @Column(name = "INCR_PAY_STP", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "vacantPos", column = @Column(name = "VACANT_POS", nullable = false, length = 1)),
			@AttributeOverride(name = "wklyHrsSched", column = @Column(name = "WKLY_HRS_SCHED", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "whollySepAmt", column = @Column(name = "WHOLLY_SEP_AMT", nullable = false, precision = 7)) })
	public BhrEmpJobBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrEmpJobBkupPaycalcs5Id id) {
		this.id = id;
	}

}
