package com.esc20.model;
// Generated Jan 4, 2019 3:40:12 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * BhrEmpDemo generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_DEMO", schema = "rsccc", catalog = "rsccc")
public class BhrEmpDemo implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private String empNbr;
	private String staffId;
	private String priorStaffId;
	private String namePre;
	private String nameF;
	private String nameM;
	private String nameL;
	private Character nameGen;
	private String nameMaiden;
	private String prvNamePre;
	private String prvNameF;
	private String prvNameM;
	private String prvNameL;
	private Character prvNameGen;
	private Character bilInd;
	private Character citzFlg;
	private Character deceased;
	private Character demoRevCd;
	private String dob;
	private String driversLicNbr;
	private String driversLicSt;
	private Character ethn;
	private Character maritalStat;
	private Character sex;
	private String addrNbr;
	private String addrStr;
	private transient String addrApt;
	private String addrCity;
	private String addrSt;
	private String addrZip;
	private String addrZip4;
	private String smrAddrNbr;
	private String smrAddrStr;
	private String smrAddrApt;
	private String smrAddrCity;
	private String smrAddrSt;
	private String smrAddrZip;
	private String smrAddrZip4;
	private Character restrictCd;
	private Character restrictCdPublic;
	private String phoneArea;
	private String phoneNbr;
	private String phoneAreaBus;
	private String phoneNbrBus;
	private String busPhoneExt;
	private String email;
	private String locUse1;
	private String locUse2;
	private String emerContact;
	private String emerPhoneAc;
	private String emerPhoneNbr;
	private String emerPhoneExt;
	private String emerRel;
	private String emerNote;
	private String chkNamePre;
	private String chkNameF;
	private Character chkNameM;
	private String chkNameL;
	private Character chkNameGen;
	private String trsNamePre;
	private String trsNameF;
	private String trsNameM;
	private String trsNameL;
	private Character trsNameGen;
	private String dtLastChanged;
	private String supplAddr;
	private String supplCntry;
	private String supplDelivName;
	private String phoneAreaCell;
	private String phoneNbrCell;
	private String dtDlExpr;
	private Character ethnHispanic;
	private Character raceAmerIndian;
	private Character raceAsian;
	private Character raceBlack;
	private Character racePacificIsl;
	private Character raceWhite;
	private String hmEmail;
	private String addrCtry;
	private String module;
	private String txUniqueStfId;
	private Character nonEmp;
	private BhrEmpEmply bhrEmpEmply;

	private transient String genDescription;
	
	public BhrEmpDemo() {
	}

	public BhrEmpDemo(String empNbr, String staffId, String priorStaffId, String namePre, String nameF, String nameM,
			String nameL, Character nameGen, String nameMaiden, String prvNamePre, String prvNameF, String prvNameM,
			String prvNameL, Character prvNameGen, Character bilInd, Character citzFlg, Character deceased, Character demoRevCd, String dob,
			String driversLicNbr, String driversLicSt, Character ethn, Character maritalStat, Character sex, String addrNbr,
			String addrStr, String addrApt, String addrCity, String addrSt, String addrZip, String addrZip4,
			String smrAddrNbr, String smrAddrStr, String smrAddrApt, String smrAddrCity, String smrAddrSt,
			String smrAddrZip, String smrAddrZip4, Character restrictCd, Character restrictCdPublic, String phoneArea,
			String phoneNbr, String phoneAreaBus, String phoneNbrBus, String busPhoneExt, String email, String locUse1,
			String locUse2, String emerContact, String emerPhoneAc, String emerPhoneNbr, String emerPhoneExt,
			String emerRel, String emerNote, String chkNamePre, String chkNameF, Character chkNameM, String chkNameL,
			Character chkNameGen, String trsNamePre, String trsNameF, String trsNameM, String trsNameL, Character trsNameGen,
			String dtLastChanged, String supplAddr, String supplCntry, String supplDelivName, String phoneAreaCell,
			String phoneNbrCell, String dtDlExpr, Character ethnHispanic, Character raceAmerIndian, Character raceAsian,
			Character raceBlack, Character racePacificIsl, Character raceWhite, String hmEmail, String addrCtry, String module,
			String txUniqueStfId, Character nonEmp) {
		this.empNbr = empNbr;
		this.staffId = staffId;
		this.priorStaffId = priorStaffId;
		this.namePre = namePre;
		this.nameF = nameF;
		this.nameM = nameM;
		this.nameL = nameL;
		this.nameGen = nameGen;
		this.nameMaiden = nameMaiden;
		this.prvNamePre = prvNamePre;
		this.prvNameF = prvNameF;
		this.prvNameM = prvNameM;
		this.prvNameL = prvNameL;
		this.prvNameGen = prvNameGen;
		this.bilInd = bilInd;
		this.citzFlg = citzFlg;
		this.deceased = deceased;
		this.demoRevCd = demoRevCd;
		this.dob = dob;
		this.driversLicNbr = driversLicNbr;
		this.driversLicSt = driversLicSt;
		this.ethn = ethn;
		this.maritalStat = maritalStat;
		this.sex = sex;
		this.addrNbr = addrNbr;
		this.addrStr = addrStr;
		this.addrApt = addrApt;
		this.addrCity = addrCity;
		this.addrSt = addrSt;
		this.addrZip = addrZip;
		this.addrZip4 = addrZip4;
		this.smrAddrNbr = smrAddrNbr;
		this.smrAddrStr = smrAddrStr;
		this.smrAddrApt = smrAddrApt;
		this.smrAddrCity = smrAddrCity;
		this.smrAddrSt = smrAddrSt;
		this.smrAddrZip = smrAddrZip;
		this.smrAddrZip4 = smrAddrZip4;
		this.restrictCd = restrictCd;
		this.restrictCdPublic = restrictCdPublic;
		this.phoneArea = phoneArea;
		this.phoneNbr = phoneNbr;
		this.phoneAreaBus = phoneAreaBus;
		this.phoneNbrBus = phoneNbrBus;
		this.busPhoneExt = busPhoneExt;
		this.email = email;
		this.locUse1 = locUse1;
		this.locUse2 = locUse2;
		this.emerContact = emerContact;
		this.emerPhoneAc = emerPhoneAc;
		this.emerPhoneNbr = emerPhoneNbr;
		this.emerPhoneExt = emerPhoneExt;
		this.emerRel = emerRel;
		this.emerNote = emerNote;
		this.chkNamePre = chkNamePre;
		this.chkNameF = chkNameF;
		this.chkNameM = chkNameM;
		this.chkNameL = chkNameL;
		this.chkNameGen = chkNameGen;
		this.trsNamePre = trsNamePre;
		this.trsNameF = trsNameF;
		this.trsNameM = trsNameM;
		this.trsNameL = trsNameL;
		this.trsNameGen = trsNameGen;
		this.dtLastChanged = dtLastChanged;
		this.supplAddr = supplAddr;
		this.supplCntry = supplCntry;
		this.supplDelivName = supplDelivName;
		this.phoneAreaCell = phoneAreaCell;
		this.phoneNbrCell = phoneNbrCell;
		this.dtDlExpr = dtDlExpr;
		this.ethnHispanic = ethnHispanic;
		this.raceAmerIndian = raceAmerIndian;
		this.raceAsian = raceAsian;
		this.raceBlack = raceBlack;
		this.racePacificIsl = racePacificIsl;
		this.raceWhite = raceWhite;
		this.hmEmail = hmEmail;
		this.addrCtry = addrCtry;
		this.module = module;
		this.txUniqueStfId = txUniqueStfId;
		this.nonEmp = nonEmp;
	}

	public BhrEmpDemo(String empNbr, String staffId, String priorStaffId, String namePre, String nameF, String nameM,
			String nameL, Character nameGen, String nameMaiden, String prvNamePre, String prvNameF, String prvNameM,
			String prvNameL, Character prvNameGen, Character bilInd, Character citzFlg, Character deceased, Character demoRevCd, String dob,
			String driversLicNbr, String driversLicSt, Character ethn, Character maritalStat, Character sex, String addrNbr,
			String addrStr, String addrApt, String addrCity, String addrSt, String addrZip, String addrZip4,
			String smrAddrNbr, String smrAddrStr, String smrAddrApt, String smrAddrCity, String smrAddrSt,
			String smrAddrZip, String smrAddrZip4, Character restrictCd, Character restrictCdPublic, String phoneArea,
			String phoneNbr, String phoneAreaBus, String phoneNbrBus, String busPhoneExt, String email, String locUse1,
			String locUse2, String emerContact, String emerPhoneAc, String emerPhoneNbr, String emerPhoneExt,
			String emerRel, String emerNote, String chkNamePre, String chkNameF, Character chkNameM, String chkNameL,
			Character chkNameGen, String trsNamePre, String trsNameF, String trsNameM, String trsNameL, Character trsNameGen,
			String dtLastChanged, String supplAddr, String supplCntry, String supplDelivName, String phoneAreaCell,
			String phoneNbrCell, String dtDlExpr, Character ethnHispanic, Character raceAmerIndian, Character raceAsian,
			Character raceBlack, Character racePacificIsl, Character raceWhite, String hmEmail, String addrCtry, String module,
			String txUniqueStfId, Character nonEmp, BhrEmpEmply bhrEmpEmply) {
		this.empNbr = empNbr;
		this.staffId = staffId;
		this.priorStaffId = priorStaffId;
		this.namePre = namePre;
		this.nameF = nameF;
		this.nameM = nameM;
		this.nameL = nameL;
		this.nameGen = nameGen;
		this.nameMaiden = nameMaiden;
		this.prvNamePre = prvNamePre;
		this.prvNameF = prvNameF;
		this.prvNameM = prvNameM;
		this.prvNameL = prvNameL;
		this.prvNameGen = prvNameGen;
		this.bilInd = bilInd;
		this.citzFlg = citzFlg;
		this.deceased = deceased;
		this.demoRevCd = demoRevCd;
		this.dob = dob;
		this.driversLicNbr = driversLicNbr;
		this.driversLicSt = driversLicSt;
		this.ethn = ethn;
		this.maritalStat = maritalStat;
		this.sex = sex;
		this.addrNbr = addrNbr;
		this.addrStr = addrStr;
		this.addrApt = addrApt;
		this.addrCity = addrCity;
		this.addrSt = addrSt;
		this.addrZip = addrZip;
		this.addrZip4 = addrZip4;
		this.smrAddrNbr = smrAddrNbr;
		this.smrAddrStr = smrAddrStr;
		this.smrAddrApt = smrAddrApt;
		this.smrAddrCity = smrAddrCity;
		this.smrAddrSt = smrAddrSt;
		this.smrAddrZip = smrAddrZip;
		this.smrAddrZip4 = smrAddrZip4;
		this.restrictCd = restrictCd;
		this.restrictCdPublic = restrictCdPublic;
		this.phoneArea = phoneArea;
		this.phoneNbr = phoneNbr;
		this.phoneAreaBus = phoneAreaBus;
		this.phoneNbrBus = phoneNbrBus;
		this.busPhoneExt = busPhoneExt;
		this.email = email;
		this.locUse1 = locUse1;
		this.locUse2 = locUse2;
		this.emerContact = emerContact;
		this.emerPhoneAc = emerPhoneAc;
		this.emerPhoneNbr = emerPhoneNbr;
		this.emerPhoneExt = emerPhoneExt;
		this.emerRel = emerRel;
		this.emerNote = emerNote;
		this.chkNamePre = chkNamePre;
		this.chkNameF = chkNameF;
		this.chkNameM = chkNameM;
		this.chkNameL = chkNameL;
		this.chkNameGen = chkNameGen;
		this.trsNamePre = trsNamePre;
		this.trsNameF = trsNameF;
		this.trsNameM = trsNameM;
		this.trsNameL = trsNameL;
		this.trsNameGen = trsNameGen;
		this.dtLastChanged = dtLastChanged;
		this.supplAddr = supplAddr;
		this.supplCntry = supplCntry;
		this.supplDelivName = supplDelivName;
		this.phoneAreaCell = phoneAreaCell;
		this.phoneNbrCell = phoneNbrCell;
		this.dtDlExpr = dtDlExpr;
		this.ethnHispanic = ethnHispanic;
		this.raceAmerIndian = raceAmerIndian;
		this.raceAsian = raceAsian;
		this.raceBlack = raceBlack;
		this.racePacificIsl = racePacificIsl;
		this.raceWhite = raceWhite;
		this.hmEmail = hmEmail;
		this.addrCtry = addrCtry;
		this.module = module;
		this.txUniqueStfId = txUniqueStfId;
		this.nonEmp = nonEmp;
		this.bhrEmpEmply = bhrEmpEmply;
	}

	public BhrEmpDemo(String empNbr, String staffId, String nameF, String nameM, String nameL, Character nameGen,
			String dob, Character sex, String addrNbr, String addrStr, String addrApt, String addrCity, String addrSt,
			String addrZip, String addrZip4, String phoneArea, String phoneNbr, String email, String hmEmail,
			String namePre, String smrAddrNbr, String smrAddrStr, String smrAddrApt, String smrAddrCity, String smrAddrSt, String smrAddrZip, String smrAddrZip4,
			String phoneAreaBus, String phoneNbrBus, String busPhoneExt, String phoneAreaCell, String phoneNbrCell,
			Character restrictCd, Character restrictCdPublic, Character maritalStat, String driversLicNbr, String driversLicSt,
			String emerContact, String emerPhoneAc,String emerPhoneNbr, String emerPhoneExt, String emerRel, String emerNote) {
		this.empNbr = empNbr;
		this.staffId = staffId;
		this.nameF = nameF;
		this.nameM = nameM;
		this.nameL = nameL;
		this.nameGen = nameGen;
		this.dob = dob;
		this.sex = sex;
		this.addrNbr = addrNbr;
		this.addrStr = addrStr;
		this.addrApt = addrApt;
		this.addrCity = addrCity;
		this.addrSt = addrSt;
		this.addrZip = addrZip;
		this.addrZip4 = addrZip4;
		this.phoneArea = phoneArea;
		this.phoneNbr = phoneNbr;
		this.email = email;
		this.hmEmail = hmEmail;
		this.namePre = namePre;
		this.smrAddrNbr = smrAddrNbr;
		this.smrAddrStr = smrAddrStr;
		this.smrAddrApt = smrAddrApt;
		this.smrAddrCity = smrAddrCity;
		this.smrAddrSt = smrAddrSt;
		this.smrAddrZip = smrAddrZip;
		this.smrAddrZip4 = smrAddrZip4;
		this.phoneAreaBus = phoneAreaBus;
		this.phoneNbrBus = phoneNbrBus;
		this.busPhoneExt = busPhoneExt;
		this.phoneAreaCell = phoneAreaCell;
		this.phoneNbrCell = phoneNbrCell;
		this.restrictCd = restrictCd;
		this.restrictCdPublic = restrictCdPublic;
		this.maritalStat = maritalStat;
		this.driversLicNbr = driversLicNbr;
		this.driversLicSt = driversLicSt;
		this.emerContact = emerContact;
		this.emerPhoneAc = emerPhoneAc;
		this.emerPhoneNbr = emerPhoneNbr;
		this.emerPhoneExt = emerPhoneExt;
		this.emerRel = emerRel;
		this.emerNote = emerNote;
	}
	
	@Id

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "STAFF_ID", nullable = false, length = 9)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "PRIOR_STAFF_ID", nullable = false, length = 9)
	public String getPriorStaffId() {
		return this.priorStaffId;
	}

	public void setPriorStaffId(String priorStaffId) {
		this.priorStaffId = priorStaffId;
	}

	@Column(name = "NAME_PRE", nullable = false, length = 4)
	public String getNamePre() {
		return this.namePre;
	}

	public void setNamePre(String namePre) {
		this.namePre = namePre;
	}

	@Column(name = "NAME_F", nullable = false, length = 17)
	public String getNameF() {
		return this.nameF;
	}

	public void setNameF(String nameF) {
		this.nameF = nameF;
	}

	@Column(name = "NAME_M", nullable = false, length = 14)
	public String getNameM() {
		return this.nameM;
	}

	public void setNameM(String nameM) {
		this.nameM = nameM;
	}

	@Column(name = "NAME_L", nullable = false, length = 25)
	public String getNameL() {
		return this.nameL;
	}

	public void setNameL(String nameL) {
		this.nameL = nameL;
	}

	@Column(name = "NAME_GEN", nullable = false, length = 1)
	public Character getNameGen() {
		return this.nameGen;
	}

	public void setNameGen(Character nameGen) {
		this.nameGen = nameGen;
	}

	@Column(name = "NAME_MAIDEN", nullable = false, length = 25)
	public String getNameMaiden() {
		return this.nameMaiden;
	}

	public void setNameMaiden(String nameMaiden) {
		this.nameMaiden = nameMaiden;
	}

	@Column(name = "PRV_NAME_PRE", nullable = false, length = 4)
	public String getPrvNamePre() {
		return this.prvNamePre;
	}

	public void setPrvNamePre(String prvNamePre) {
		this.prvNamePre = prvNamePre;
	}

	@Column(name = "PRV_NAME_F", nullable = false, length = 17)
	public String getPrvNameF() {
		return this.prvNameF;
	}

	public void setPrvNameF(String prvNameF) {
		this.prvNameF = prvNameF;
	}

	@Column(name = "PRV_NAME_M", nullable = false, length = 14)
	public String getPrvNameM() {
		return this.prvNameM;
	}

	public void setPrvNameM(String prvNameM) {
		this.prvNameM = prvNameM;
	}

	@Column(name = "PRV_NAME_L", nullable = false, length = 25)
	public String getPrvNameL() {
		return this.prvNameL;
	}

	public void setPrvNameL(String prvNameL) {
		this.prvNameL = prvNameL;
	}

	@Column(name = "PRV_NAME_GEN", nullable = false, length = 1)
	public Character getPrvNameGen() {
		return this.prvNameGen;
	}

	public void setPrvNameGen(Character prvNameGen) {
		this.prvNameGen = prvNameGen;
	}

	@Column(name = "BIL_IND", nullable = false, length = 1)
	public Character getBilInd() {
		return this.bilInd;
	}

	public void setBilInd(Character bilInd) {
		this.bilInd = bilInd;
	}

	@Column(name = "CITZ_FLG", nullable = false, length = 1)
	public Character getCitzFlg() {
		return this.citzFlg;
	}

	public void setCitzFlg(Character citzFlg) {
		this.citzFlg = citzFlg;
	}

	@Column(name = "DECEASED", nullable = false, length = 1)
	public Character getDeceased() {
		return this.deceased;
	}

	public void setDeceased(Character deceased) {
		this.deceased = deceased;
	}

	@Column(name = "DEMO_REV_CD", nullable = false, length = 1)
	public Character getDemoRevCd() {
		return this.demoRevCd;
	}

	public void setDemoRevCd(Character demoRevCd) {
		this.demoRevCd = demoRevCd;
	}

	@Column(name = "DOB", nullable = false, length = 8)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "DRIVERS_LIC_NBR", nullable = false, length = 19)
	public String getDriversLicNbr() {
		return this.driversLicNbr;
	}

	public void setDriversLicNbr(String driversLicNbr) {
		this.driversLicNbr = driversLicNbr;
	}

	@Column(name = "DRIVERS_LIC_ST", nullable = false, length = 2)
	public String getDriversLicSt() {
		return this.driversLicSt;
	}

	public void setDriversLicSt(String driversLicSt) {
		this.driversLicSt = driversLicSt;
	}

	@Column(name = "ETHN", nullable = false, length = 1)
	public Character getEthn() {
		return this.ethn;
	}

	public void setEthn(Character ethn) {
		this.ethn = ethn;
	}

	@Column(name = "MARITAL_STAT", nullable = false, length = 1)
	public Character getMaritalStat() {
		return this.maritalStat;
	}

	public void setMaritalStat(Character maritalStat) {
		this.maritalStat = maritalStat;
	}

	@Column(name = "SEX", nullable = false, length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Column(name = "ADDR_NBR", nullable = false, length = 8)
	public String getAddrNbr() {
		return this.addrNbr;
	}

	public void setAddrNbr(String addrNbr) {
		this.addrNbr = addrNbr;
	}

	@Column(name = "ADDR_STR", nullable = false, length = 20)
	public String getAddrStr() {
		return this.addrStr;
	}

	public void setAddrStr(String addrStr) {
		this.addrStr = addrStr;
	}

	@Column(name = "ADDR_APT", nullable = false, length = 7)
	public String getAddrApt() {
		return this.addrApt;
	}

	public void setAddrApt(String addrApt) {
		this.addrApt = addrApt;
	}

	@Column(name = "ADDR_CITY", nullable = false, length = 25)
	public String getAddrCity() {
		return this.addrCity;
	}

	public void setAddrCity(String addrCity) {
		this.addrCity = addrCity;
	}

	@Column(name = "ADDR_ST", nullable = false, length = 2)
	public String getAddrSt() {
		return this.addrSt;
	}

	public void setAddrSt(String addrSt) {
		this.addrSt = addrSt;
	}

	@Column(name = "ADDR_ZIP", nullable = false, length = 5)
	public String getAddrZip() {
		return this.addrZip;
	}

	public void setAddrZip(String addrZip) {
		this.addrZip = addrZip;
	}

	@Column(name = "ADDR_ZIP4", nullable = false, length = 4)
	public String getAddrZip4() {
		return this.addrZip4;
	}

	public void setAddrZip4(String addrZip4) {
		this.addrZip4 = addrZip4;
	}

	@Column(name = "SMR_ADDR_NBR", nullable = false, length = 8)
	public String getSmrAddrNbr() {
		return this.smrAddrNbr;
	}

	public void setSmrAddrNbr(String smrAddrNbr) {
		this.smrAddrNbr = smrAddrNbr;
	}

	@Column(name = "SMR_ADDR_STR", nullable = false, length = 20)
	public String getSmrAddrStr() {
		return this.smrAddrStr;
	}

	public void setSmrAddrStr(String smrAddrStr) {
		this.smrAddrStr = smrAddrStr;
	}

	@Column(name = "SMR_ADDR_APT", nullable = false, length = 7)
	public String getSmrAddrApt() {
		return this.smrAddrApt;
	}

	public void setSmrAddrApt(String smrAddrApt) {
		this.smrAddrApt = smrAddrApt;
	}

	@Column(name = "SMR_ADDR_CITY", nullable = false, length = 17)
	public String getSmrAddrCity() {
		return this.smrAddrCity;
	}

	public void setSmrAddrCity(String smrAddrCity) {
		this.smrAddrCity = smrAddrCity;
	}

	@Column(name = "SMR_ADDR_ST", nullable = false, length = 2)
	public String getSmrAddrSt() {
		return this.smrAddrSt;
	}

	public void setSmrAddrSt(String smrAddrSt) {
		this.smrAddrSt = smrAddrSt;
	}

	@Column(name = "SMR_ADDR_ZIP", nullable = false, length = 5)
	public String getSmrAddrZip() {
		return this.smrAddrZip;
	}

	public void setSmrAddrZip(String smrAddrZip) {
		this.smrAddrZip = smrAddrZip;
	}

	@Column(name = "SMR_ADDR_ZIP4", nullable = false, length = 4)
	public String getSmrAddrZip4() {
		return this.smrAddrZip4;
	}

	public void setSmrAddrZip4(String smrAddrZip4) {
		this.smrAddrZip4 = smrAddrZip4;
	}

	@Column(name = "RESTRICT_CD", nullable = false, length = 1)
	public Character getRestrictCd() {
		return this.restrictCd;
	}

	public void setRestrictCd(Character restrictCd) {
		this.restrictCd = restrictCd;
	}

	@Column(name = "RESTRICT_CD_PUBLIC", nullable = false, length = 1)
	public Character getRestrictCdPublic() {
		return this.restrictCdPublic;
	}

	public void setRestrictCdPublic(Character restrictCdPublic) {
		this.restrictCdPublic = restrictCdPublic;
	}

	@Column(name = "PHONE_AREA", nullable = false, length = 3)
	public String getPhoneArea() {
		return this.phoneArea;
	}

	public void setPhoneArea(String phoneArea) {
		this.phoneArea = phoneArea;
	}

	@Column(name = "PHONE_NBR", nullable = false, length = 7)
	public String getPhoneNbr() {
		return this.phoneNbr;
	}

	public void setPhoneNbr(String phoneNbr) {
		this.phoneNbr = phoneNbr;
	}

	@Column(name = "PHONE_AREA_BUS", nullable = false, length = 3)
	public String getPhoneAreaBus() {
		return this.phoneAreaBus;
	}

	public void setPhoneAreaBus(String phoneAreaBus) {
		this.phoneAreaBus = phoneAreaBus;
	}

	@Column(name = "PHONE_NBR_BUS", nullable = false, length = 7)
	public String getPhoneNbrBus() {
		return this.phoneNbrBus;
	}

	public void setPhoneNbrBus(String phoneNbrBus) {
		this.phoneNbrBus = phoneNbrBus;
	}

	@Column(name = "BUS_PHONE_EXT", nullable = false, length = 4)
	public String getBusPhoneExt() {
		return this.busPhoneExt;
	}

	public void setBusPhoneExt(String busPhoneExt) {
		this.busPhoneExt = busPhoneExt;
	}

	@Column(name = "EMAIL", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "LOC_USE_1", nullable = false, length = 10)
	public String getLocUse1() {
		return this.locUse1;
	}

	public void setLocUse1(String locUse1) {
		this.locUse1 = locUse1;
	}

	@Column(name = "LOC_USE_2", nullable = false, length = 10)
	public String getLocUse2() {
		return this.locUse2;
	}

	public void setLocUse2(String locUse2) {
		this.locUse2 = locUse2;
	}

	@Column(name = "EMER_CONTACT", nullable = false, length = 26)
	public String getEmerContact() {
		return this.emerContact;
	}

	public void setEmerContact(String emerContact) {
		this.emerContact = emerContact;
	}

	@Column(name = "EMER_PHONE_AC", nullable = false, length = 3)
	public String getEmerPhoneAc() {
		return this.emerPhoneAc;
	}

	public void setEmerPhoneAc(String emerPhoneAc) {
		this.emerPhoneAc = emerPhoneAc;
	}

	@Column(name = "EMER_PHONE_NBR", nullable = false, length = 7)
	public String getEmerPhoneNbr() {
		return this.emerPhoneNbr;
	}

	public void setEmerPhoneNbr(String emerPhoneNbr) {
		this.emerPhoneNbr = emerPhoneNbr;
	}

	@Column(name = "EMER_PHONE_EXT", nullable = false, length = 6)
	public String getEmerPhoneExt() {
		return this.emerPhoneExt;
	}

	public void setEmerPhoneExt(String emerPhoneExt) {
		this.emerPhoneExt = emerPhoneExt;
	}

	@Column(name = "EMER_REL", nullable = false, length = 25)
	public String getEmerRel() {
		return this.emerRel;
	}

	public void setEmerRel(String emerRel) {
		this.emerRel = emerRel;
	}

	@Column(name = "EMER_NOTE", nullable = false, length = 25)
	public String getEmerNote() {
		return this.emerNote;
	}

	public void setEmerNote(String emerNote) {
		this.emerNote = emerNote;
	}

	@Column(name = "CHK_NAME_PRE", nullable = false, length = 4)
	public String getChkNamePre() {
		return this.chkNamePre;
	}

	public void setChkNamePre(String chkNamePre) {
		this.chkNamePre = chkNamePre;
	}

	@Column(name = "CHK_NAME_F", nullable = false, length = 17)
	public String getChkNameF() {
		return this.chkNameF;
	}

	public void setChkNameF(String chkNameF) {
		this.chkNameF = chkNameF;
	}

	@Column(name = "CHK_NAME_M", nullable = false, length = 1)
	public Character getChkNameM() {
		return this.chkNameM;
	}

	public void setChkNameM(Character chkNameM) {
		this.chkNameM = chkNameM;
	}

	@Column(name = "CHK_NAME_L", nullable = false, length = 25)
	public String getChkNameL() {
		return this.chkNameL;
	}

	public void setChkNameL(String chkNameL) {
		this.chkNameL = chkNameL;
	}

	@Column(name = "CHK_NAME_GEN", nullable = false, length = 1)
	public Character getChkNameGen() {
		return this.chkNameGen;
	}

	public void setChkNameGen(Character chkNameGen) {
		this.chkNameGen = chkNameGen;
	}

	@Column(name = "TRS_NAME_PRE", nullable = false, length = 4)
	public String getTrsNamePre() {
		return this.trsNamePre;
	}

	public void setTrsNamePre(String trsNamePre) {
		this.trsNamePre = trsNamePre;
	}

	@Column(name = "TRS_NAME_F", nullable = false, length = 17)
	public String getTrsNameF() {
		return this.trsNameF;
	}

	public void setTrsNameF(String trsNameF) {
		this.trsNameF = trsNameF;
	}

	@Column(name = "TRS_NAME_M", nullable = false, length = 14)
	public String getTrsNameM() {
		return this.trsNameM;
	}

	public void setTrsNameM(String trsNameM) {
		this.trsNameM = trsNameM;
	}

	@Column(name = "TRS_NAME_L", nullable = false, length = 25)
	public String getTrsNameL() {
		return this.trsNameL;
	}

	public void setTrsNameL(String trsNameL) {
		this.trsNameL = trsNameL;
	}

	@Column(name = "TRS_NAME_GEN", nullable = false, length = 1)
	public Character getTrsNameGen() {
		return this.trsNameGen;
	}

	public void setTrsNameGen(Character trsNameGen) {
		this.trsNameGen = trsNameGen;
	}

	@Column(name = "DT_LAST_CHANGED", nullable = false, length = 8)
	public String getDtLastChanged() {
		return this.dtLastChanged;
	}

	public void setDtLastChanged(String dtLastChanged) {
		this.dtLastChanged = dtLastChanged;
	}

	@Column(name = "SUPPL_ADDR", nullable = false, length = 40)
	public String getSupplAddr() {
		return this.supplAddr;
	}

	public void setSupplAddr(String supplAddr) {
		this.supplAddr = supplAddr;
	}

	@Column(name = "SUPPL_CNTRY", nullable = false, length = 40)
	public String getSupplCntry() {
		return this.supplCntry;
	}

	public void setSupplCntry(String supplCntry) {
		this.supplCntry = supplCntry;
	}

	@Column(name = "SUPPL_DELIV_NAME", nullable = false, length = 40)
	public String getSupplDelivName() {
		return this.supplDelivName;
	}

	public void setSupplDelivName(String supplDelivName) {
		this.supplDelivName = supplDelivName;
	}

	@Column(name = "PHONE_AREA_CELL", nullable = false, length = 3)
	public String getPhoneAreaCell() {
		return this.phoneAreaCell;
	}

	public void setPhoneAreaCell(String phoneAreaCell) {
		this.phoneAreaCell = phoneAreaCell;
	}

	@Column(name = "PHONE_NBR_CELL", nullable = false, length = 7)
	public String getPhoneNbrCell() {
		return this.phoneNbrCell;
	}

	public void setPhoneNbrCell(String phoneNbrCell) {
		this.phoneNbrCell = phoneNbrCell;
	}

	@Column(name = "DT_DL_EXPR", nullable = false, length = 8)
	public String getDtDlExpr() {
		return this.dtDlExpr;
	}

	public void setDtDlExpr(String dtDlExpr) {
		this.dtDlExpr = dtDlExpr;
	}

	@Column(name = "ETHN_HISPANIC", nullable = false, length = 1)
	public Character getEthnHispanic() {
		return this.ethnHispanic;
	}

	public void setEthnHispanic(Character ethnHispanic) {
		this.ethnHispanic = ethnHispanic;
	}

	@Column(name = "RACE_AMER_INDIAN", nullable = false, length = 1)
	public Character getRaceAmerIndian() {
		return this.raceAmerIndian;
	}

	public void setRaceAmerIndian(Character raceAmerIndian) {
		this.raceAmerIndian = raceAmerIndian;
	}

	@Column(name = "RACE_ASIAN", nullable = false, length = 1)
	public Character getRaceAsian() {
		return this.raceAsian;
	}

	public void setRaceAsian(Character raceAsian) {
		this.raceAsian = raceAsian;
	}

	@Column(name = "RACE_BLACK", nullable = false, length = 1)
	public Character getRaceBlack() {
		return this.raceBlack;
	}

	public void setRaceBlack(Character raceBlack) {
		this.raceBlack = raceBlack;
	}

	@Column(name = "RACE_PACIFIC_ISL", nullable = false, length = 1)
	public Character getRacePacificIsl() {
		return this.racePacificIsl;
	}

	public void setRacePacificIsl(Character racePacificIsl) {
		this.racePacificIsl = racePacificIsl;
	}

	@Column(name = "RACE_WHITE", nullable = false, length = 1)
	public Character getRaceWhite() {
		return this.raceWhite;
	}

	public void setRaceWhite(Character raceWhite) {
		this.raceWhite = raceWhite;
	}

	@Column(name = "HM_EMAIL", nullable = false, length = 45)
	public String getHmEmail() {
		return this.hmEmail;
	}

	public void setHmEmail(String hmEmail) {
		this.hmEmail = hmEmail;
	}

	@Column(name = "ADDR_CTRY", nullable = false, length = 30)
	public String getAddrCtry() {
		return this.addrCtry;
	}

	public void setAddrCtry(String addrCtry) {
		this.addrCtry = addrCtry;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "TX_UNIQUE_STF_ID", nullable = false, length = 10)
	public String getTxUniqueStfId() {
		return this.txUniqueStfId;
	}

	public void setTxUniqueStfId(String txUniqueStfId) {
		this.txUniqueStfId = txUniqueStfId;
	}

	@Column(name = "NON_EMP", nullable = false, length = 1)
	public Character getNonEmp() {
		return this.nonEmp;
	}

	public void setNonEmp(Character nonEmp) {
		this.nonEmp = nonEmp;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "bhrEmpDemo")
	public BhrEmpEmply getBhrEmpEmply() {
		return this.bhrEmpEmply;
	}

	public void setBhrEmpEmply(BhrEmpEmply bhrEmpEmply) {
		this.bhrEmpEmply = bhrEmpEmply;
	}


	@Transient 
	public String getGenDescription() {
		return genDescription;
	}


	@Transient 
	public void setGenDescription(String genDescription) {
		this.genDescription = genDescription;
	}

}
