package com.esc20.model;
// Generated Jan 4, 2019 3:40:12 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpExtraDutyBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_EXTRA_DUTY_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrEmpExtraDutyBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpExtraDutyBkupPaycalcs5Id id;

	public BhrEmpExtraDutyBkupPaycalcs5() {
	}

	public BhrEmpExtraDutyBkupPaycalcs5(BhrEmpExtraDutyBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "extraDutyCd", column = @Column(name = "EXTRA_DUTY_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "extraDutyAmt", column = @Column(name = "EXTRA_DUTY_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "remainAmt", column = @Column(name = "REMAIN_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "remainPymts", column = @Column(name = "REMAIN_PYMTS", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BhrEmpExtraDutyBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrEmpExtraDutyBkupPaycalcs5Id id) {
		this.id = id;
	}

}
