package com.esc20.model;
// Generated Jan 4, 2019 3:40:36 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrEmpLvXmital generated by hbm2java
 */
@Entity
@Table(name = "BHR_EMP_LV_XMITAL", schema = "rsccc", catalog = "rsccc")
public class BhrEmpLvXmital implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrEmpLvXmitalId id;
	private String lvTyp;
	private String absRsn;
	private String dtOfAbs;
	private String begTime;
	private BigDecimal lvUnitsUsed;
	private BigDecimal lvUnitsEarned;
	private String subst;
	private String rsn;
	private String processDt;
	private String userId;
	private String module;
	private int lvId;
	
	public BhrEmpLvXmital() {
	}

	public BhrEmpLvXmital(BhrEmpLvXmitalId id, String lvTyp, String absRsn, String dtOfAbs, String begTime,
			BigDecimal lvUnitsUsed, BigDecimal lvUnitsEarned, String subst, String rsn, String processDt, String userId,
			String module, int lvId) {
		this.id = id;
		this.lvTyp = lvTyp;
		this.absRsn = absRsn;
		this.dtOfAbs = dtOfAbs;
		this.begTime = begTime;
		this.lvUnitsUsed = lvUnitsUsed;
		this.lvUnitsEarned = lvUnitsEarned;
		this.subst = subst;
		this.rsn = rsn;
		this.processDt = processDt;
		this.userId = userId;
		this.module = module;
		this.lvId = lvId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "lvSeq", column = @Column(name = "LV_SEQ", nullable = false, precision = 3, scale = 0)) })
	public BhrEmpLvXmitalId getId() {
		return this.id;
	}

	public void setId(BhrEmpLvXmitalId id) {
		this.id = id;
	}

	@Column(name = "LV_TYP", nullable = false, length = 2)
	public String getLvTyp() {
		return this.lvTyp;
	}

	public void setLvTyp(String lvTyp) {
		this.lvTyp = lvTyp;
	}

	@Column(name = "ABS_RSN", nullable = false, length = 2)
	public String getAbsRsn() {
		return this.absRsn;
	}

	public void setAbsRsn(String absRsn) {
		this.absRsn = absRsn;
	}

	@Column(name = "DT_OF_ABS", nullable = false, length = 8)
	public String getDtOfAbs() {
		return this.dtOfAbs;
	}

	public void setDtOfAbs(String dtOfAbs) {
		this.dtOfAbs = dtOfAbs;
	}

	@Column(name = "BEG_TIME", nullable = false, length = 6)
	public String getBegTime() {
		return this.begTime;
	}

	public void setBegTime(String begTime) {
		this.begTime = begTime;
	}

	@Column(name = "LV_UNITS_USED", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvUnitsUsed() {
		return this.lvUnitsUsed;
	}

	public void setLvUnitsUsed(BigDecimal lvUnitsUsed) {
		this.lvUnitsUsed = lvUnitsUsed;
	}

	@Column(name = "LV_UNITS_EARNED", nullable = false, precision = 7, scale = 3)
	public BigDecimal getLvUnitsEarned() {
		return this.lvUnitsEarned;
	}

	public void setLvUnitsEarned(BigDecimal lvUnitsEarned) {
		this.lvUnitsEarned = lvUnitsEarned;
	}

	@Column(name = "SUBST", nullable = false, length = 2)
	public String getSubst() {
		return this.subst;
	}

	public void setSubst(String subst) {
		this.subst = subst;
	}

	@Column(name = "RSN", nullable = false, length = 20)
	public String getRsn() {
		return this.rsn;
	}

	public void setRsn(String rsn) {
		this.rsn = rsn;
	}

	@Column(name = "PROCESS_DT", nullable = false, length = 8)
	public String getProcessDt() {
		return this.processDt;
	}

	public void setProcessDt(String processDt) {
		this.processDt = processDt;
	}

	@Column(name = "USER_ID", nullable = false, length = 12)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "LV_ID", nullable = false)
	public int getLvId() {
		return this.lvId;
	}

	public void setLvId(int lvId) {
		this.lvId = lvId;
	}

}
