package com.esc20.model;
// Generated Jan 4, 2019 3:42:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrHrlyDataXmitalBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_HRLY_DATA_XMITAL_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrHrlyDataXmitalBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrHrlyDataXmitalBkupPaycalcs5Id id;

	public BhrHrlyDataXmitalBkupPaycalcs5() {
	}

	public BhrHrlyDataXmitalBkupPaycalcs5(BhrHrlyDataXmitalBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "dts", column = @Column(name = "DTS", nullable = false, length = 16)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, length = 5)),
			@AttributeOverride(name = "regHrsWrk", column = @Column(name = "REG_HRS_WRK", nullable = false, precision = 5)),
			@AttributeOverride(name = "absDed", column = @Column(name = "ABS_DED", nullable = false, precision = 7)),
			@AttributeOverride(name = "adjSalaryCd", column = @Column(name = "ADJ_SALARY_CD", nullable = false, length = 1)),
			@AttributeOverride(name = "daysEarned", column = @Column(name = "DAYS_EARNED", nullable = false, precision = 5)),
			@AttributeOverride(name = "campusId", column = @Column(name = "CAMPUS_ID", nullable = false, length = 3)),
			@AttributeOverride(name = "dept", column = @Column(name = "DEPT", nullable = false, length = 1)),
			@AttributeOverride(name = "jobCd", column = @Column(name = "JOB_CD", nullable = false, length = 4)),
			@AttributeOverride(name = "servRecDaysDeduct", column = @Column(name = "SERV_REC_DAYS_DEDUCT", nullable = false, precision = 5)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 12)),
			@AttributeOverride(name = "processDt", column = @Column(name = "PROCESS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "transmittalType", column = @Column(name = "TRANSMITTAL_TYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "rsn", column = @Column(name = "RSN", nullable = false, length = 30)),
			@AttributeOverride(name = "createdCip", column = @Column(name = "CREATED_CIP", nullable = false, length = 1)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)),
			@AttributeOverride(name = "actHrs", column = @Column(name = "ACT_HRS", nullable = false, precision = 5)),
			@AttributeOverride(name = "actDt", column = @Column(name = "ACT_DT", nullable = false, length = 8)) })
	public BhrHrlyDataXmitalBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrHrlyDataXmitalBkupPaycalcs5Id id) {
		this.id = id;
	}

}
