package com.esc20.model;
// Generated Jan 4, 2019 3:42:57 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrHrlyDataXmitalBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BhrHrlyDataXmitalBkupPaycalcs5Id implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private char cyrNyrFlg;
	private char payFreq;
	private String empNbr;
	private String dtOfPay;
	private String dts;
	private String seqNbr;
	private BigDecimal regHrsWrk;
	private BigDecimal absDed;
	private char adjSalaryCd;
	private BigDecimal daysEarned;
	private String campusId;
	private char dept;
	private String jobCd;
	private BigDecimal servRecDaysDeduct;
	private String userId;
	private String processDt;
	private char transmittalType;
	private String rsn;
	private char createdCip;
	private String module;
	private BigDecimal actHrs;
	private String actDt;

	public BhrHrlyDataXmitalBkupPaycalcs5Id() {
	}

	public BhrHrlyDataXmitalBkupPaycalcs5Id(char cyrNyrFlg, char payFreq, String empNbr, String dtOfPay, String dts,
			String seqNbr, BigDecimal regHrsWrk, BigDecimal absDed, char adjSalaryCd, BigDecimal daysEarned,
			String campusId, char dept, String jobCd, BigDecimal servRecDaysDeduct, String userId, String processDt,
			char transmittalType, String rsn, char createdCip, String module, BigDecimal actHrs, String actDt) {
		this.cyrNyrFlg = cyrNyrFlg;
		this.payFreq = payFreq;
		this.empNbr = empNbr;
		this.dtOfPay = dtOfPay;
		this.dts = dts;
		this.seqNbr = seqNbr;
		this.regHrsWrk = regHrsWrk;
		this.absDed = absDed;
		this.adjSalaryCd = adjSalaryCd;
		this.daysEarned = daysEarned;
		this.campusId = campusId;
		this.dept = dept;
		this.jobCd = jobCd;
		this.servRecDaysDeduct = servRecDaysDeduct;
		this.userId = userId;
		this.processDt = processDt;
		this.transmittalType = transmittalType;
		this.rsn = rsn;
		this.createdCip = createdCip;
		this.module = module;
		this.actHrs = actHrs;
		this.actDt = actDt;
	}

	@Column(name = "CYR_NYR_FLG", nullable = false, length = 1)
	public char getCyrNyrFlg() {
		return this.cyrNyrFlg;
	}

	public void setCyrNyrFlg(char cyrNyrFlg) {
		this.cyrNyrFlg = cyrNyrFlg;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "DT_OF_PAY", nullable = false, length = 8)
	public String getDtOfPay() {
		return this.dtOfPay;
	}

	public void setDtOfPay(String dtOfPay) {
		this.dtOfPay = dtOfPay;
	}

	@Column(name = "DTS", nullable = false, length = 16)
	public String getDts() {
		return this.dts;
	}

	public void setDts(String dts) {
		this.dts = dts;
	}

	@Column(name = "SEQ_NBR", nullable = false, length = 5)
	public String getSeqNbr() {
		return this.seqNbr;
	}

	public void setSeqNbr(String seqNbr) {
		this.seqNbr = seqNbr;
	}

	@Column(name = "REG_HRS_WRK", nullable = false, precision = 5)
	public BigDecimal getRegHrsWrk() {
		return this.regHrsWrk;
	}

	public void setRegHrsWrk(BigDecimal regHrsWrk) {
		this.regHrsWrk = regHrsWrk;
	}

	@Column(name = "ABS_DED", nullable = false, precision = 7)
	public BigDecimal getAbsDed() {
		return this.absDed;
	}

	public void setAbsDed(BigDecimal absDed) {
		this.absDed = absDed;
	}

	@Column(name = "ADJ_SALARY_CD", nullable = false, length = 1)
	public char getAdjSalaryCd() {
		return this.adjSalaryCd;
	}

	public void setAdjSalaryCd(char adjSalaryCd) {
		this.adjSalaryCd = adjSalaryCd;
	}

	@Column(name = "DAYS_EARNED", nullable = false, precision = 5)
	public BigDecimal getDaysEarned() {
		return this.daysEarned;
	}

	public void setDaysEarned(BigDecimal daysEarned) {
		this.daysEarned = daysEarned;
	}

	@Column(name = "CAMPUS_ID", nullable = false, length = 3)
	public String getCampusId() {
		return this.campusId;
	}

	public void setCampusId(String campusId) {
		this.campusId = campusId;
	}

	@Column(name = "DEPT", nullable = false, length = 1)
	public char getDept() {
		return this.dept;
	}

	public void setDept(char dept) {
		this.dept = dept;
	}

	@Column(name = "JOB_CD", nullable = false, length = 4)
	public String getJobCd() {
		return this.jobCd;
	}

	public void setJobCd(String jobCd) {
		this.jobCd = jobCd;
	}

	@Column(name = "SERV_REC_DAYS_DEDUCT", nullable = false, precision = 5)
	public BigDecimal getServRecDaysDeduct() {
		return this.servRecDaysDeduct;
	}

	public void setServRecDaysDeduct(BigDecimal servRecDaysDeduct) {
		this.servRecDaysDeduct = servRecDaysDeduct;
	}

	@Column(name = "USER_ID", nullable = false, length = 12)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "PROCESS_DT", nullable = false, length = 8)
	public String getProcessDt() {
		return this.processDt;
	}

	public void setProcessDt(String processDt) {
		this.processDt = processDt;
	}

	@Column(name = "TRANSMITTAL_TYPE", nullable = false, length = 1)
	public char getTransmittalType() {
		return this.transmittalType;
	}

	public void setTransmittalType(char transmittalType) {
		this.transmittalType = transmittalType;
	}

	@Column(name = "RSN", nullable = false, length = 30)
	public String getRsn() {
		return this.rsn;
	}

	public void setRsn(String rsn) {
		this.rsn = rsn;
	}

	@Column(name = "CREATED_CIP", nullable = false, length = 1)
	public char getCreatedCip() {
		return this.createdCip;
	}

	public void setCreatedCip(char createdCip) {
		this.createdCip = createdCip;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "ACT_HRS", nullable = false, precision = 5)
	public BigDecimal getActHrs() {
		return this.actHrs;
	}

	public void setActHrs(BigDecimal actHrs) {
		this.actHrs = actHrs;
	}

	@Column(name = "ACT_DT", nullable = false, length = 8)
	public String getActDt() {
		return this.actDt;
	}

	public void setActDt(String actDt) {
		this.actDt = actDt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrHrlyDataXmitalBkupPaycalcs5Id))
			return false;
		BhrHrlyDataXmitalBkupPaycalcs5Id castOther = (BhrHrlyDataXmitalBkupPaycalcs5Id) other;

		return (this.getCyrNyrFlg() == castOther.getCyrNyrFlg()) && (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
						&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& ((this.getDtOfPay() == castOther.getDtOfPay()) || (this.getDtOfPay() != null
						&& castOther.getDtOfPay() != null && this.getDtOfPay().equals(castOther.getDtOfPay())))
				&& ((this.getDts() == castOther.getDts()) || (this.getDts() != null && castOther.getDts() != null
						&& this.getDts().equals(castOther.getDts())))
				&& ((this.getSeqNbr() == castOther.getSeqNbr()) || (this.getSeqNbr() != null
						&& castOther.getSeqNbr() != null && this.getSeqNbr().equals(castOther.getSeqNbr())))
				&& ((this.getRegHrsWrk() == castOther.getRegHrsWrk()) || (this.getRegHrsWrk() != null
						&& castOther.getRegHrsWrk() != null && this.getRegHrsWrk().equals(castOther.getRegHrsWrk())))
				&& ((this.getAbsDed() == castOther.getAbsDed()) || (this.getAbsDed() != null
						&& castOther.getAbsDed() != null && this.getAbsDed().equals(castOther.getAbsDed())))
				&& (this.getAdjSalaryCd() == castOther.getAdjSalaryCd())
				&& ((this.getDaysEarned() == castOther.getDaysEarned()) || (this.getDaysEarned() != null
						&& castOther.getDaysEarned() != null && this.getDaysEarned().equals(castOther.getDaysEarned())))
				&& ((this.getCampusId() == castOther.getCampusId()) || (this.getCampusId() != null
						&& castOther.getCampusId() != null && this.getCampusId().equals(castOther.getCampusId())))
				&& (this.getDept() == castOther.getDept())
				&& ((this.getJobCd() == castOther.getJobCd()) || (this.getJobCd() != null
						&& castOther.getJobCd() != null && this.getJobCd().equals(castOther.getJobCd())))
				&& ((this.getServRecDaysDeduct() == castOther.getServRecDaysDeduct())
						|| (this.getServRecDaysDeduct() != null && castOther.getServRecDaysDeduct() != null
								&& this.getServRecDaysDeduct().equals(castOther.getServRecDaysDeduct())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getProcessDt() == castOther.getProcessDt()) || (this.getProcessDt() != null
						&& castOther.getProcessDt() != null && this.getProcessDt().equals(castOther.getProcessDt())))
				&& (this.getTransmittalType() == castOther.getTransmittalType())
				&& ((this.getRsn() == castOther.getRsn()) || (this.getRsn() != null && castOther.getRsn() != null
						&& this.getRsn().equals(castOther.getRsn())))
				&& (this.getCreatedCip() == castOther.getCreatedCip())
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())))
				&& ((this.getActHrs() == castOther.getActHrs()) || (this.getActHrs() != null
						&& castOther.getActHrs() != null && this.getActHrs().equals(castOther.getActHrs())))
				&& ((this.getActDt() == castOther.getActDt()) || (this.getActDt() != null
						&& castOther.getActDt() != null && this.getActDt().equals(castOther.getActDt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCyrNyrFlg();
		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + (getDtOfPay() == null ? 0 : this.getDtOfPay().hashCode());
		result = 37 * result + (getDts() == null ? 0 : this.getDts().hashCode());
		result = 37 * result + (getSeqNbr() == null ? 0 : this.getSeqNbr().hashCode());
		result = 37 * result + (getRegHrsWrk() == null ? 0 : this.getRegHrsWrk().hashCode());
		result = 37 * result + (getAbsDed() == null ? 0 : this.getAbsDed().hashCode());
		result = 37 * result + this.getAdjSalaryCd();
		result = 37 * result + (getDaysEarned() == null ? 0 : this.getDaysEarned().hashCode());
		result = 37 * result + (getCampusId() == null ? 0 : this.getCampusId().hashCode());
		result = 37 * result + this.getDept();
		result = 37 * result + (getJobCd() == null ? 0 : this.getJobCd().hashCode());
		result = 37 * result + (getServRecDaysDeduct() == null ? 0 : this.getServRecDaysDeduct().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getProcessDt() == null ? 0 : this.getProcessDt().hashCode());
		result = 37 * result + this.getTransmittalType();
		result = 37 * result + (getRsn() == null ? 0 : this.getRsn().hashCode());
		result = 37 * result + this.getCreatedCip();
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		result = 37 * result + (getActHrs() == null ? 0 : this.getActHrs().hashCode());
		result = 37 * result + (getActDt() == null ? 0 : this.getActDt().hashCode());
		return result;
	}

}
