package com.esc20.model;
// Generated Jan 4, 2019 3:42:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrInsurCoverage generated by hbm2java
 */
@Entity
@Table(name = "BHR_INSUR_COVERAGE", schema = "rsccc", catalog = "rsccc")
public class BhrInsurCoverage implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrInsurCoverageId id;
	private String nameF;
	private String nameM;
	private String nameL;
	private String dtCoverageBeg;
	private String dtCoverageEnd;
	private char relation;
	private String ssn;
	private String dob;
	private String module;
	private char nameGen;

	public BhrInsurCoverage() {
	}

	public BhrInsurCoverage(BhrInsurCoverageId id, String nameF, String nameM, String nameL,
			String dtCoverageBeg, String dtCoverageEnd, char relation, String ssn, String dob, String module,
			char nameGen) {
		this.id = id;
		this.nameF = nameF;
		this.nameM = nameM;
		this.nameL = nameL;
		this.dtCoverageBeg = dtCoverageBeg;
		this.dtCoverageEnd = dtCoverageEnd;
		this.relation = relation;
		this.ssn = ssn;
		this.dob = dob;
		this.module = module;
		this.nameGen = nameGen;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "companyCd", column = @Column(name = "COMPANY_CD", nullable = false, length = 5)),
			@AttributeOverride(name = "planNbr", column = @Column(name = "PLAN_NBR", nullable = false, length = 20)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, precision = 3, scale = 0)) })
	public BhrInsurCoverageId getId() {
		return this.id;
	}

	public void setId(BhrInsurCoverageId id) {
		this.id = id;
	}

	@Column(name = "NAME_F", nullable = false, length = 17)
	public String getNameF() {
		return this.nameF;
	}

	public void setNameF(String nameF) {
		this.nameF = nameF;
	}

	@Column(name = "NAME_M", nullable = false, length = 14)
	public String getNameM() {
		return this.nameM;
	}

	public void setNameM(String nameM) {
		this.nameM = nameM;
	}

	@Column(name = "NAME_L", nullable = false, length = 25)
	public String getNameL() {
		return this.nameL;
	}

	public void setNameL(String nameL) {
		this.nameL = nameL;
	}

	@Column(name = "DT_COVERAGE_BEG", nullable = false, length = 8)
	public String getDtCoverageBeg() {
		return this.dtCoverageBeg;
	}

	public void setDtCoverageBeg(String dtCoverageBeg) {
		this.dtCoverageBeg = dtCoverageBeg;
	}

	@Column(name = "DT_COVERAGE_END", nullable = false, length = 8)
	public String getDtCoverageEnd() {
		return this.dtCoverageEnd;
	}

	public void setDtCoverageEnd(String dtCoverageEnd) {
		this.dtCoverageEnd = dtCoverageEnd;
	}

	@Column(name = "RELATION", nullable = false, length = 1)
	public char getRelation() {
		return this.relation;
	}

	public void setRelation(char relation) {
		this.relation = relation;
	}

	@Column(name = "SSN", nullable = false, length = 9)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Column(name = "DOB", nullable = false, length = 8)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "NAME_GEN", nullable = false, length = 1)
	public char getNameGen() {
		return this.nameGen;
	}

	public void setNameGen(char nameGen) {
		this.nameGen = nameGen;
	}

}
