package com.esc20.model;
// Generated Jan 4, 2019 3:44:27 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayDeductHistBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAY_DEDUCT_HIST_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrPayDeductHistBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayDeductHistBkupPaycalcs5Id id;

	public BhrPayDeductHistBkupPaycalcs5() {
	}

	public BhrPayDeductHistBkupPaycalcs5(BhrPayDeductHistBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "voidOrIss", column = @Column(name = "VOID_OR_ISS", nullable = false, length = 1)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "dedCd", column = @Column(name = "DED_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "dedSeq", column = @Column(name = "DED_SEQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dedAmt", column = @Column(name = "DED_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "dedRemain", column = @Column(name = "DED_REMAIN", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "dedTaken", column = @Column(name = "DED_TAKEN", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "cafeFlg", column = @Column(name = "CAFE_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "emplrAmt", column = @Column(name = "EMPLR_AMT", nullable = false, precision = 7)),
			@AttributeOverride(name = "emplrContribFactor", column = @Column(name = "EMPLR_CONTRIB_FACTOR", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "refundFlg", column = @Column(name = "REFUND_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "caseNbr", column = @Column(name = "CASE_NBR", nullable = false, length = 20)),
			@AttributeOverride(name = "causeNbr", column = @Column(name = "CAUSE_NBR", nullable = false, length = 12)),
			@AttributeOverride(name = "teaHealthInsContrib", column = @Column(name = "TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)),
			@AttributeOverride(name = "teaHealthInsContribFactor", column = @Column(name = "TEA_HEALTH_INS_CONTRIB_FACTOR", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "w2EmplrHlthcare", column = @Column(name = "W2_EMPLR_HLTHCARE", nullable = false, length = 1)) })
	public BhrPayDeductHistBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrPayDeductHistBkupPaycalcs5Id id) {
		this.id = id;
	}

}
