package com.esc20.model;
// Generated Jan 4, 2019 3:44:27 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrPayHist generated by hbm2java
 */
@Entity
@Table(name = "BHR_PAY_HIST", schema = "rsccc", catalog = "rsccc")
public class BhrPayHist implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrPayHistId id;
	private char chkCleared;
	private String payCampus;
	private char payDept;
	private BigDecimal absDedCoded;
	private BigDecimal absDedRefund;
	private BigDecimal absDedAmt;
	private BigDecimal absDedAmtTot;
	private char accruCd;
	private BigDecimal accruEmplrNonAnnuitContrib;
	private BigDecimal accruFedGrant;
	private BigDecimal accruFedCare;
	private BigDecimal accruFedIns;
	private BigDecimal accruFicaTax;
	private BigDecimal accruPay;
	private BigDecimal accruUnempIns;
	private BigDecimal accruDaysEarned;
	private BigDecimal accruEmplrAnnuitContrib;
	private BigDecimal accruEmplr457;
	private String dtPayoff;
	private char finalPayFlg;
	private BigDecimal eicAmt;
	private BigDecimal earnPay;
	private char ficaElig;
	private BigDecimal ficaGross;
	private BigDecimal ficaTax;
	private BigDecimal regGrossSch;
	private BigDecimal medTax;
	private BigDecimal medGross;
	private BigDecimal grossPayTot;
	private BigDecimal hlthInsDed;
	private BigDecimal hrlyPayRate;
	private char maritalStatTax;
	private short nbrTaxExempts;
	private char taxExemptFlg;
	private BigDecimal netAdjAmt;
	private BigDecimal netPay;
	private BigDecimal ovtmGross;
	private BigDecimal ovtmHrsWrk;
	private BigDecimal regHrsWrk;
	private BigDecimal retroactivePay;
	private BigDecimal trsSalaryRed;
	private char adjSalaryCd;
	private BigDecimal stdGross;
	private BigDecimal stdGrossTot;
	private BigDecimal stSalary;
	private BigDecimal extraDutyGross;
	private BigDecimal taxedBenefits;
	private BigDecimal busAllowanceNontax;
	private BigDecimal busAllowanceTax;
	private BigDecimal trsDeposit;
	private BigDecimal trsFee;
	private BigDecimal trsGross;
	private BigDecimal trsIns;
	private BigDecimal trsCare;
	private BigDecimal unempGross;
	private BigDecimal unempIns;
	private BigDecimal whGross;
	private BigDecimal whTax;
	private BigDecimal wrkCompIns;
	private char drctDepositFlg;
	private char distrErrFlg;
	private char emplrInsContribFlg;
	private BigDecimal emplrNonAnnuityContrib;
	private BigDecimal emplrAnnuityContrib;
	private BigDecimal emplr457;
	private BigDecimal emp457;
	private BigDecimal miscDedAmt;
	private BigDecimal extraDutyPayLoc;
	private BigDecimal annuityDed;
	private BigDecimal cafeAmt;
	private BigDecimal whollySepAmt;
	private BigDecimal dependCare;
	private BigDecimal taxEmplrLife;
	private BigDecimal taxEmplrLifeGrp;
	private BigDecimal distContribAboveSt;
	private BigDecimal nontrsReimbrExcess;
	private BigDecimal nontrsReimbrBase;
	private BigDecimal nontrsBusAllow;
	private BigDecimal nontrsNontaxBusAllow;
	private BigDecimal nontrsNonpayBusAllow;
	private BigDecimal nontrsNontaxNonpayAllow;
	private BigDecimal nontrsSuppl;
	private BigDecimal nontrsNontaxNonpayExpend;
	private char trsActiveCareEligFlg;
	private BigDecimal trsSupplComp;
	private BigDecimal teaHealthInsContrib;
	private BigDecimal accruTeaHealthInsContrib;
	private boolean trsSupplCompFactor;
	private BigDecimal emplrTrsCareContrib;
	private BigDecimal accruEmplrTrsCareContrib;
	private BigDecimal daysWrk;
	private char multiHrlyRates;
	private char trsSupplEligCd;
	private BigDecimal perforPayGross;
	private BigDecimal perforPayDeposit;
	private BigDecimal perforPayIns;
	private BigDecimal trsGrantGross;
	private BigDecimal trsGrantDeposit;
	private BigDecimal trsGrantCare;
	private BigDecimal accruCafeAmt;
	private BigDecimal emplrRetGross;
	private BigDecimal emplrRetPensnSurchg;
	private BigDecimal accruEmplrRetPensnSurchg;
	private BigDecimal emplrTrsCareSurchg;
	private BigDecimal accruEmplrTrsCareSurchg;
	private BigDecimal emplrNewTrsGross;
	private BigDecimal emplrNewTrsPensnContrib;
	private char takeRetSurchg;
	private BigDecimal emplrDependCare;
	private BigDecimal accruEmplrDependCare;
	private BigDecimal annuityRoth;
	private String micrChkNbr;
	private String reconDts;
	private BigDecimal emplrDependCareTax;
	private BigDecimal hsaEmpSalRedctnContrib;
	private BigDecimal hsaEmplrContrib;
	private BigDecimal emplrFicaTax;
	private BigDecimal emplrMiscDedContrib;
	private BigDecimal accruEmplrMiscDedContrib;
	private BigDecimal emplrMedTax;
	private BigDecimal medGrosCalYtd;
	private BigDecimal emplrTrsNonOasdiContrib;
	private BigDecimal annuityRoth457b;
	private char ersRetHlthElig;
	private char trsStatCd;

	public BhrPayHist() {
	}

	public BhrPayHist(BhrPayHistId id, char chkCleared, String payCampus, char payDept, BigDecimal absDedCoded,
			BigDecimal absDedRefund, BigDecimal absDedAmt, BigDecimal absDedAmtTot, char accruCd,
			BigDecimal accruEmplrNonAnnuitContrib, BigDecimal accruFedGrant, BigDecimal accruFedCare,
			BigDecimal accruFedIns, BigDecimal accruFicaTax, BigDecimal accruPay, BigDecimal accruUnempIns,
			BigDecimal accruDaysEarned, BigDecimal accruEmplrAnnuitContrib, BigDecimal accruEmplr457, String dtPayoff,
			char finalPayFlg, BigDecimal eicAmt, BigDecimal earnPay, char ficaElig, BigDecimal ficaGross,
			BigDecimal ficaTax, BigDecimal regGrossSch, BigDecimal medTax, BigDecimal medGross, BigDecimal grossPayTot,
			BigDecimal hlthInsDed, BigDecimal hrlyPayRate, char maritalStatTax, short nbrTaxExempts, char taxExemptFlg,
			BigDecimal netAdjAmt, BigDecimal netPay, BigDecimal ovtmGross, BigDecimal ovtmHrsWrk, BigDecimal regHrsWrk,
			BigDecimal retroactivePay, BigDecimal trsSalaryRed, char adjSalaryCd, BigDecimal stdGross,
			BigDecimal stdGrossTot, BigDecimal stSalary, BigDecimal extraDutyGross, BigDecimal taxedBenefits,
			BigDecimal busAllowanceNontax, BigDecimal busAllowanceTax, BigDecimal trsDeposit, BigDecimal trsFee,
			BigDecimal trsGross, BigDecimal trsIns, BigDecimal trsCare, BigDecimal unempGross, BigDecimal unempIns,
			BigDecimal whGross, BigDecimal whTax, BigDecimal wrkCompIns, char drctDepositFlg, char distrErrFlg,
			char emplrInsContribFlg, BigDecimal emplrNonAnnuityContrib, BigDecimal emplrAnnuityContrib,
			BigDecimal emplr457, BigDecimal emp457, BigDecimal miscDedAmt, BigDecimal extraDutyPayLoc,
			BigDecimal annuityDed, BigDecimal cafeAmt, BigDecimal whollySepAmt, BigDecimal dependCare,
			BigDecimal taxEmplrLife, BigDecimal taxEmplrLifeGrp, BigDecimal distContribAboveSt,
			BigDecimal nontrsReimbrExcess, BigDecimal nontrsReimbrBase, BigDecimal nontrsBusAllow,
			BigDecimal nontrsNontaxBusAllow, BigDecimal nontrsNonpayBusAllow, BigDecimal nontrsNontaxNonpayAllow,
			BigDecimal nontrsSuppl, BigDecimal nontrsNontaxNonpayExpend, char trsActiveCareEligFlg,
			BigDecimal trsSupplComp, BigDecimal teaHealthInsContrib, BigDecimal accruTeaHealthInsContrib,
			boolean trsSupplCompFactor, BigDecimal emplrTrsCareContrib, BigDecimal accruEmplrTrsCareContrib,
			BigDecimal daysWrk, char multiHrlyRates, char trsSupplEligCd, BigDecimal perforPayGross,
			BigDecimal perforPayDeposit, BigDecimal perforPayIns, BigDecimal trsGrantGross, BigDecimal trsGrantDeposit,
			BigDecimal trsGrantCare, BigDecimal accruCafeAmt, BigDecimal emplrRetGross, BigDecimal emplrRetPensnSurchg,
			BigDecimal accruEmplrRetPensnSurchg, BigDecimal emplrTrsCareSurchg, BigDecimal accruEmplrTrsCareSurchg,
			BigDecimal emplrNewTrsGross, BigDecimal emplrNewTrsPensnContrib, char takeRetSurchg,
			BigDecimal emplrDependCare, BigDecimal accruEmplrDependCare, BigDecimal annuityRoth, String micrChkNbr,
			String reconDts, BigDecimal emplrDependCareTax, BigDecimal hsaEmpSalRedctnContrib,
			BigDecimal hsaEmplrContrib, BigDecimal emplrFicaTax, BigDecimal emplrMiscDedContrib,
			BigDecimal accruEmplrMiscDedContrib, BigDecimal emplrMedTax, BigDecimal medGrosCalYtd,
			BigDecimal emplrTrsNonOasdiContrib, BigDecimal annuityRoth457b, char ersRetHlthElig, char trsStatCd) {
		this.id = id;
		this.chkCleared = chkCleared;
		this.payCampus = payCampus;
		this.payDept = payDept;
		this.absDedCoded = absDedCoded;
		this.absDedRefund = absDedRefund;
		this.absDedAmt = absDedAmt;
		this.absDedAmtTot = absDedAmtTot;
		this.accruCd = accruCd;
		this.accruEmplrNonAnnuitContrib = accruEmplrNonAnnuitContrib;
		this.accruFedGrant = accruFedGrant;
		this.accruFedCare = accruFedCare;
		this.accruFedIns = accruFedIns;
		this.accruFicaTax = accruFicaTax;
		this.accruPay = accruPay;
		this.accruUnempIns = accruUnempIns;
		this.accruDaysEarned = accruDaysEarned;
		this.accruEmplrAnnuitContrib = accruEmplrAnnuitContrib;
		this.accruEmplr457 = accruEmplr457;
		this.dtPayoff = dtPayoff;
		this.finalPayFlg = finalPayFlg;
		this.eicAmt = eicAmt;
		this.earnPay = earnPay;
		this.ficaElig = ficaElig;
		this.ficaGross = ficaGross;
		this.ficaTax = ficaTax;
		this.regGrossSch = regGrossSch;
		this.medTax = medTax;
		this.medGross = medGross;
		this.grossPayTot = grossPayTot;
		this.hlthInsDed = hlthInsDed;
		this.hrlyPayRate = hrlyPayRate;
		this.maritalStatTax = maritalStatTax;
		this.nbrTaxExempts = nbrTaxExempts;
		this.taxExemptFlg = taxExemptFlg;
		this.netAdjAmt = netAdjAmt;
		this.netPay = netPay;
		this.ovtmGross = ovtmGross;
		this.ovtmHrsWrk = ovtmHrsWrk;
		this.regHrsWrk = regHrsWrk;
		this.retroactivePay = retroactivePay;
		this.trsSalaryRed = trsSalaryRed;
		this.adjSalaryCd = adjSalaryCd;
		this.stdGross = stdGross;
		this.stdGrossTot = stdGrossTot;
		this.stSalary = stSalary;
		this.extraDutyGross = extraDutyGross;
		this.taxedBenefits = taxedBenefits;
		this.busAllowanceNontax = busAllowanceNontax;
		this.busAllowanceTax = busAllowanceTax;
		this.trsDeposit = trsDeposit;
		this.trsFee = trsFee;
		this.trsGross = trsGross;
		this.trsIns = trsIns;
		this.trsCare = trsCare;
		this.unempGross = unempGross;
		this.unempIns = unempIns;
		this.whGross = whGross;
		this.whTax = whTax;
		this.wrkCompIns = wrkCompIns;
		this.drctDepositFlg = drctDepositFlg;
		this.distrErrFlg = distrErrFlg;
		this.emplrInsContribFlg = emplrInsContribFlg;
		this.emplrNonAnnuityContrib = emplrNonAnnuityContrib;
		this.emplrAnnuityContrib = emplrAnnuityContrib;
		this.emplr457 = emplr457;
		this.emp457 = emp457;
		this.miscDedAmt = miscDedAmt;
		this.extraDutyPayLoc = extraDutyPayLoc;
		this.annuityDed = annuityDed;
		this.cafeAmt = cafeAmt;
		this.whollySepAmt = whollySepAmt;
		this.dependCare = dependCare;
		this.taxEmplrLife = taxEmplrLife;
		this.taxEmplrLifeGrp = taxEmplrLifeGrp;
		this.distContribAboveSt = distContribAboveSt;
		this.nontrsReimbrExcess = nontrsReimbrExcess;
		this.nontrsReimbrBase = nontrsReimbrBase;
		this.nontrsBusAllow = nontrsBusAllow;
		this.nontrsNontaxBusAllow = nontrsNontaxBusAllow;
		this.nontrsNonpayBusAllow = nontrsNonpayBusAllow;
		this.nontrsNontaxNonpayAllow = nontrsNontaxNonpayAllow;
		this.nontrsSuppl = nontrsSuppl;
		this.nontrsNontaxNonpayExpend = nontrsNontaxNonpayExpend;
		this.trsActiveCareEligFlg = trsActiveCareEligFlg;
		this.trsSupplComp = trsSupplComp;
		this.teaHealthInsContrib = teaHealthInsContrib;
		this.accruTeaHealthInsContrib = accruTeaHealthInsContrib;
		this.trsSupplCompFactor = trsSupplCompFactor;
		this.emplrTrsCareContrib = emplrTrsCareContrib;
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
		this.daysWrk = daysWrk;
		this.multiHrlyRates = multiHrlyRates;
		this.trsSupplEligCd = trsSupplEligCd;
		this.perforPayGross = perforPayGross;
		this.perforPayDeposit = perforPayDeposit;
		this.perforPayIns = perforPayIns;
		this.trsGrantGross = trsGrantGross;
		this.trsGrantDeposit = trsGrantDeposit;
		this.trsGrantCare = trsGrantCare;
		this.accruCafeAmt = accruCafeAmt;
		this.emplrRetGross = emplrRetGross;
		this.emplrRetPensnSurchg = emplrRetPensnSurchg;
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
		this.emplrTrsCareSurchg = emplrTrsCareSurchg;
		this.accruEmplrTrsCareSurchg = accruEmplrTrsCareSurchg;
		this.emplrNewTrsGross = emplrNewTrsGross;
		this.emplrNewTrsPensnContrib = emplrNewTrsPensnContrib;
		this.takeRetSurchg = takeRetSurchg;
		this.emplrDependCare = emplrDependCare;
		this.accruEmplrDependCare = accruEmplrDependCare;
		this.annuityRoth = annuityRoth;
		this.micrChkNbr = micrChkNbr;
		this.reconDts = reconDts;
		this.emplrDependCareTax = emplrDependCareTax;
		this.hsaEmpSalRedctnContrib = hsaEmpSalRedctnContrib;
		this.hsaEmplrContrib = hsaEmplrContrib;
		this.emplrFicaTax = emplrFicaTax;
		this.emplrMiscDedContrib = emplrMiscDedContrib;
		this.accruEmplrMiscDedContrib = accruEmplrMiscDedContrib;
		this.emplrMedTax = emplrMedTax;
		this.medGrosCalYtd = medGrosCalYtd;
		this.emplrTrsNonOasdiContrib = emplrTrsNonOasdiContrib;
		this.annuityRoth457b = annuityRoth457b;
		this.ersRetHlthElig = ersRetHlthElig;
		this.trsStatCd = trsStatCd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)),
			@AttributeOverride(name = "chkNbr", column = @Column(name = "CHK_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "voidOrIss", column = @Column(name = "VOID_OR_ISS", nullable = false, length = 1)),
			@AttributeOverride(name = "adjNbr", column = @Column(name = "ADJ_NBR", nullable = false, precision = 3, scale = 0)) })
	public BhrPayHistId getId() {
		return this.id;
	}

	public void setId(BhrPayHistId id) {
		this.id = id;
	}

	@Column(name = "CHK_CLEARED", nullable = false, length = 1)
	public char getChkCleared() {
		return this.chkCleared;
	}

	public void setChkCleared(char chkCleared) {
		this.chkCleared = chkCleared;
	}

	@Column(name = "PAY_CAMPUS", nullable = false, length = 3)
	public String getPayCampus() {
		return this.payCampus;
	}

	public void setPayCampus(String payCampus) {
		this.payCampus = payCampus;
	}

	@Column(name = "PAY_DEPT", nullable = false, length = 1)
	public char getPayDept() {
		return this.payDept;
	}

	public void setPayDept(char payDept) {
		this.payDept = payDept;
	}

	@Column(name = "ABS_DED_CODED", nullable = false, precision = 7)
	public BigDecimal getAbsDedCoded() {
		return this.absDedCoded;
	}

	public void setAbsDedCoded(BigDecimal absDedCoded) {
		this.absDedCoded = absDedCoded;
	}

	@Column(name = "ABS_DED_REFUND", nullable = false, precision = 7)
	public BigDecimal getAbsDedRefund() {
		return this.absDedRefund;
	}

	public void setAbsDedRefund(BigDecimal absDedRefund) {
		this.absDedRefund = absDedRefund;
	}

	@Column(name = "ABS_DED_AMT", nullable = false, precision = 7)
	public BigDecimal getAbsDedAmt() {
		return this.absDedAmt;
	}

	public void setAbsDedAmt(BigDecimal absDedAmt) {
		this.absDedAmt = absDedAmt;
	}

	@Column(name = "ABS_DED_AMT_TOT", nullable = false, precision = 7)
	public BigDecimal getAbsDedAmtTot() {
		return this.absDedAmtTot;
	}

	public void setAbsDedAmtTot(BigDecimal absDedAmtTot) {
		this.absDedAmtTot = absDedAmtTot;
	}

	@Column(name = "ACCRU_CD", nullable = false, length = 1)
	public char getAccruCd() {
		return this.accruCd;
	}

	public void setAccruCd(char accruCd) {
		this.accruCd = accruCd;
	}

	@Column(name = "ACCRU_EMPLR_NON_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrNonAnnuitContrib() {
		return this.accruEmplrNonAnnuitContrib;
	}

	public void setAccruEmplrNonAnnuitContrib(BigDecimal accruEmplrNonAnnuitContrib) {
		this.accruEmplrNonAnnuitContrib = accruEmplrNonAnnuitContrib;
	}

	@Column(name = "ACCRU_FED_GRANT", nullable = false, precision = 9)
	public BigDecimal getAccruFedGrant() {
		return this.accruFedGrant;
	}

	public void setAccruFedGrant(BigDecimal accruFedGrant) {
		this.accruFedGrant = accruFedGrant;
	}

	@Column(name = "ACCRU_FED_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruFedCare() {
		return this.accruFedCare;
	}

	public void setAccruFedCare(BigDecimal accruFedCare) {
		this.accruFedCare = accruFedCare;
	}

	@Column(name = "ACCRU_FED_INS", nullable = false, precision = 9)
	public BigDecimal getAccruFedIns() {
		return this.accruFedIns;
	}

	public void setAccruFedIns(BigDecimal accruFedIns) {
		this.accruFedIns = accruFedIns;
	}

	@Column(name = "ACCRU_FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getAccruFicaTax() {
		return this.accruFicaTax;
	}

	public void setAccruFicaTax(BigDecimal accruFicaTax) {
		this.accruFicaTax = accruFicaTax;
	}

	@Column(name = "ACCRU_PAY", nullable = false, precision = 9)
	public BigDecimal getAccruPay() {
		return this.accruPay;
	}

	public void setAccruPay(BigDecimal accruPay) {
		this.accruPay = accruPay;
	}

	@Column(name = "ACCRU_UNEMP_INS", nullable = false, precision = 9)
	public BigDecimal getAccruUnempIns() {
		return this.accruUnempIns;
	}

	public void setAccruUnempIns(BigDecimal accruUnempIns) {
		this.accruUnempIns = accruUnempIns;
	}

	@Column(name = "ACCRU_DAYS_EARNED", nullable = false, precision = 5)
	public BigDecimal getAccruDaysEarned() {
		return this.accruDaysEarned;
	}

	public void setAccruDaysEarned(BigDecimal accruDaysEarned) {
		this.accruDaysEarned = accruDaysEarned;
	}

	@Column(name = "ACCRU_EMPLR_ANNUIT_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrAnnuitContrib() {
		return this.accruEmplrAnnuitContrib;
	}

	public void setAccruEmplrAnnuitContrib(BigDecimal accruEmplrAnnuitContrib) {
		this.accruEmplrAnnuitContrib = accruEmplrAnnuitContrib;
	}

	@Column(name = "ACCRU_EMPLR_457", nullable = false, precision = 9)
	public BigDecimal getAccruEmplr457() {
		return this.accruEmplr457;
	}

	public void setAccruEmplr457(BigDecimal accruEmplr457) {
		this.accruEmplr457 = accruEmplr457;
	}

	@Column(name = "DT_PAYOFF", nullable = false, length = 8)
	public String getDtPayoff() {
		return this.dtPayoff;
	}

	public void setDtPayoff(String dtPayoff) {
		this.dtPayoff = dtPayoff;
	}

	@Column(name = "FINAL_PAY_FLG", nullable = false, length = 1)
	public char getFinalPayFlg() {
		return this.finalPayFlg;
	}

	public void setFinalPayFlg(char finalPayFlg) {
		this.finalPayFlg = finalPayFlg;
	}

	@Column(name = "EIC_AMT", nullable = false, precision = 9)
	public BigDecimal getEicAmt() {
		return this.eicAmt;
	}

	public void setEicAmt(BigDecimal eicAmt) {
		this.eicAmt = eicAmt;
	}

	@Column(name = "EARN_PAY", nullable = false, precision = 9)
	public BigDecimal getEarnPay() {
		return this.earnPay;
	}

	public void setEarnPay(BigDecimal earnPay) {
		this.earnPay = earnPay;
	}

	@Column(name = "FICA_ELIG", nullable = false, length = 1)
	public char getFicaElig() {
		return this.ficaElig;
	}

	public void setFicaElig(char ficaElig) {
		this.ficaElig = ficaElig;
	}

	@Column(name = "FICA_GROSS", nullable = false, precision = 9)
	public BigDecimal getFicaGross() {
		return this.ficaGross;
	}

	public void setFicaGross(BigDecimal ficaGross) {
		this.ficaGross = ficaGross;
	}

	@Column(name = "FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getFicaTax() {
		return this.ficaTax;
	}

	public void setFicaTax(BigDecimal ficaTax) {
		this.ficaTax = ficaTax;
	}

	@Column(name = "REG_GROSS_SCH", nullable = false, precision = 9)
	public BigDecimal getRegGrossSch() {
		return this.regGrossSch;
	}

	public void setRegGrossSch(BigDecimal regGrossSch) {
		this.regGrossSch = regGrossSch;
	}

	@Column(name = "MED_TAX", nullable = false, precision = 9)
	public BigDecimal getMedTax() {
		return this.medTax;
	}

	public void setMedTax(BigDecimal medTax) {
		this.medTax = medTax;
	}

	@Column(name = "MED_GROSS", nullable = false, precision = 9)
	public BigDecimal getMedGross() {
		return this.medGross;
	}

	public void setMedGross(BigDecimal medGross) {
		this.medGross = medGross;
	}

	@Column(name = "GROSS_PAY_TOT", nullable = false, precision = 9)
	public BigDecimal getGrossPayTot() {
		return this.grossPayTot;
	}

	public void setGrossPayTot(BigDecimal grossPayTot) {
		this.grossPayTot = grossPayTot;
	}

	@Column(name = "HLTH_INS_DED", nullable = false, precision = 7)
	public BigDecimal getHlthInsDed() {
		return this.hlthInsDed;
	}

	public void setHlthInsDed(BigDecimal hlthInsDed) {
		this.hlthInsDed = hlthInsDed;
	}

	@Column(name = "HRLY_PAY_RATE", nullable = false, precision = 9)
	public BigDecimal getHrlyPayRate() {
		return this.hrlyPayRate;
	}

	public void setHrlyPayRate(BigDecimal hrlyPayRate) {
		this.hrlyPayRate = hrlyPayRate;
	}

	@Column(name = "MARITAL_STAT_TAX", nullable = false, length = 1)
	public char getMaritalStatTax() {
		return this.maritalStatTax;
	}

	public void setMaritalStatTax(char maritalStatTax) {
		this.maritalStatTax = maritalStatTax;
	}

	@Column(name = "NBR_TAX_EXEMPTS", nullable = false, precision = 3, scale = 0)
	public short getNbrTaxExempts() {
		return this.nbrTaxExempts;
	}

	public void setNbrTaxExempts(short nbrTaxExempts) {
		this.nbrTaxExempts = nbrTaxExempts;
	}

	@Column(name = "TAX_EXEMPT_FLG", nullable = false, length = 1)
	public char getTaxExemptFlg() {
		return this.taxExemptFlg;
	}

	public void setTaxExemptFlg(char taxExemptFlg) {
		this.taxExemptFlg = taxExemptFlg;
	}

	@Column(name = "NET_ADJ_AMT", nullable = false, precision = 9)
	public BigDecimal getNetAdjAmt() {
		return this.netAdjAmt;
	}

	public void setNetAdjAmt(BigDecimal netAdjAmt) {
		this.netAdjAmt = netAdjAmt;
	}

	@Column(name = "NET_PAY", nullable = false, precision = 9)
	public BigDecimal getNetPay() {
		return this.netPay;
	}

	public void setNetPay(BigDecimal netPay) {
		this.netPay = netPay;
	}

	@Column(name = "OVTM_GROSS", nullable = false, precision = 9)
	public BigDecimal getOvtmGross() {
		return this.ovtmGross;
	}

	public void setOvtmGross(BigDecimal ovtmGross) {
		this.ovtmGross = ovtmGross;
	}

	@Column(name = "OVTM_HRS_WRK", nullable = false, precision = 5)
	public BigDecimal getOvtmHrsWrk() {
		return this.ovtmHrsWrk;
	}

	public void setOvtmHrsWrk(BigDecimal ovtmHrsWrk) {
		this.ovtmHrsWrk = ovtmHrsWrk;
	}

	@Column(name = "REG_HRS_WRK", nullable = false, precision = 5)
	public BigDecimal getRegHrsWrk() {
		return this.regHrsWrk;
	}

	public void setRegHrsWrk(BigDecimal regHrsWrk) {
		this.regHrsWrk = regHrsWrk;
	}

	@Column(name = "RETROACTIVE_PAY", nullable = false, precision = 9)
	public BigDecimal getRetroactivePay() {
		return this.retroactivePay;
	}

	public void setRetroactivePay(BigDecimal retroactivePay) {
		this.retroactivePay = retroactivePay;
	}

	@Column(name = "TRS_SALARY_RED", nullable = false, precision = 9)
	public BigDecimal getTrsSalaryRed() {
		return this.trsSalaryRed;
	}

	public void setTrsSalaryRed(BigDecimal trsSalaryRed) {
		this.trsSalaryRed = trsSalaryRed;
	}

	@Column(name = "ADJ_SALARY_CD", nullable = false, length = 1)
	public char getAdjSalaryCd() {
		return this.adjSalaryCd;
	}

	public void setAdjSalaryCd(char adjSalaryCd) {
		this.adjSalaryCd = adjSalaryCd;
	}

	@Column(name = "STD_GROSS", nullable = false, precision = 9)
	public BigDecimal getStdGross() {
		return this.stdGross;
	}

	public void setStdGross(BigDecimal stdGross) {
		this.stdGross = stdGross;
	}

	@Column(name = "STD_GROSS_TOT", nullable = false, precision = 9)
	public BigDecimal getStdGrossTot() {
		return this.stdGrossTot;
	}

	public void setStdGrossTot(BigDecimal stdGrossTot) {
		this.stdGrossTot = stdGrossTot;
	}

	@Column(name = "ST_SALARY", nullable = false, precision = 9)
	public BigDecimal getStSalary() {
		return this.stSalary;
	}

	public void setStSalary(BigDecimal stSalary) {
		this.stSalary = stSalary;
	}

	@Column(name = "EXTRA_DUTY_GROSS", nullable = false, precision = 9)
	public BigDecimal getExtraDutyGross() {
		return this.extraDutyGross;
	}

	public void setExtraDutyGross(BigDecimal extraDutyGross) {
		this.extraDutyGross = extraDutyGross;
	}

	@Column(name = "TAXED_BENEFITS", nullable = false, precision = 9)
	public BigDecimal getTaxedBenefits() {
		return this.taxedBenefits;
	}

	public void setTaxedBenefits(BigDecimal taxedBenefits) {
		this.taxedBenefits = taxedBenefits;
	}

	@Column(name = "BUS_ALLOWANCE_NONTAX", nullable = false, precision = 9)
	public BigDecimal getBusAllowanceNontax() {
		return this.busAllowanceNontax;
	}

	public void setBusAllowanceNontax(BigDecimal busAllowanceNontax) {
		this.busAllowanceNontax = busAllowanceNontax;
	}

	@Column(name = "BUS_ALLOWANCE_TAX", nullable = false, precision = 9)
	public BigDecimal getBusAllowanceTax() {
		return this.busAllowanceTax;
	}

	public void setBusAllowanceTax(BigDecimal busAllowanceTax) {
		this.busAllowanceTax = busAllowanceTax;
	}

	@Column(name = "TRS_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getTrsDeposit() {
		return this.trsDeposit;
	}

	public void setTrsDeposit(BigDecimal trsDeposit) {
		this.trsDeposit = trsDeposit;
	}

	@Column(name = "TRS_FEE", nullable = false, precision = 9)
	public BigDecimal getTrsFee() {
		return this.trsFee;
	}

	public void setTrsFee(BigDecimal trsFee) {
		this.trsFee = trsFee;
	}

	@Column(name = "TRS_GROSS", nullable = false, precision = 9)
	public BigDecimal getTrsGross() {
		return this.trsGross;
	}

	public void setTrsGross(BigDecimal trsGross) {
		this.trsGross = trsGross;
	}

	@Column(name = "TRS_INS", nullable = false, precision = 7)
	public BigDecimal getTrsIns() {
		return this.trsIns;
	}

	public void setTrsIns(BigDecimal trsIns) {
		this.trsIns = trsIns;
	}

	@Column(name = "TRS_CARE", nullable = false, precision = 7)
	public BigDecimal getTrsCare() {
		return this.trsCare;
	}

	public void setTrsCare(BigDecimal trsCare) {
		this.trsCare = trsCare;
	}

	@Column(name = "UNEMP_GROSS", nullable = false, precision = 9)
	public BigDecimal getUnempGross() {
		return this.unempGross;
	}

	public void setUnempGross(BigDecimal unempGross) {
		this.unempGross = unempGross;
	}

	@Column(name = "UNEMP_INS", nullable = false, precision = 9)
	public BigDecimal getUnempIns() {
		return this.unempIns;
	}

	public void setUnempIns(BigDecimal unempIns) {
		this.unempIns = unempIns;
	}

	@Column(name = "WH_GROSS", nullable = false, precision = 9)
	public BigDecimal getWhGross() {
		return this.whGross;
	}

	public void setWhGross(BigDecimal whGross) {
		this.whGross = whGross;
	}

	@Column(name = "WH_TAX", nullable = false, precision = 9)
	public BigDecimal getWhTax() {
		return this.whTax;
	}

	public void setWhTax(BigDecimal whTax) {
		this.whTax = whTax;
	}

	@Column(name = "WRK_COMP_INS", nullable = false, precision = 9)
	public BigDecimal getWrkCompIns() {
		return this.wrkCompIns;
	}

	public void setWrkCompIns(BigDecimal wrkCompIns) {
		this.wrkCompIns = wrkCompIns;
	}

	@Column(name = "DRCT_DEPOSIT_FLG", nullable = false, length = 1)
	public char getDrctDepositFlg() {
		return this.drctDepositFlg;
	}

	public void setDrctDepositFlg(char drctDepositFlg) {
		this.drctDepositFlg = drctDepositFlg;
	}

	@Column(name = "DISTR_ERR_FLG", nullable = false, length = 1)
	public char getDistrErrFlg() {
		return this.distrErrFlg;
	}

	public void setDistrErrFlg(char distrErrFlg) {
		this.distrErrFlg = distrErrFlg;
	}

	@Column(name = "EMPLR_INS_CONTRIB_FLG", nullable = false, length = 1)
	public char getEmplrInsContribFlg() {
		return this.emplrInsContribFlg;
	}

	public void setEmplrInsContribFlg(char emplrInsContribFlg) {
		this.emplrInsContribFlg = emplrInsContribFlg;
	}

	@Column(name = "EMPLR_NON_ANNUITY_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrNonAnnuityContrib() {
		return this.emplrNonAnnuityContrib;
	}

	public void setEmplrNonAnnuityContrib(BigDecimal emplrNonAnnuityContrib) {
		this.emplrNonAnnuityContrib = emplrNonAnnuityContrib;
	}

	@Column(name = "EMPLR_ANNUITY_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrAnnuityContrib() {
		return this.emplrAnnuityContrib;
	}

	public void setEmplrAnnuityContrib(BigDecimal emplrAnnuityContrib) {
		this.emplrAnnuityContrib = emplrAnnuityContrib;
	}

	@Column(name = "EMPLR_457", nullable = false, precision = 9)
	public BigDecimal getEmplr457() {
		return this.emplr457;
	}

	public void setEmplr457(BigDecimal emplr457) {
		this.emplr457 = emplr457;
	}

	@Column(name = "EMP_457", nullable = false, precision = 9)
	public BigDecimal getEmp457() {
		return this.emp457;
	}

	public void setEmp457(BigDecimal emp457) {
		this.emp457 = emp457;
	}

	@Column(name = "MISC_DED_AMT", nullable = false, precision = 7)
	public BigDecimal getMiscDedAmt() {
		return this.miscDedAmt;
	}

	public void setMiscDedAmt(BigDecimal miscDedAmt) {
		this.miscDedAmt = miscDedAmt;
	}

	@Column(name = "EXTRA_DUTY_PAY_LOC", nullable = false, precision = 9)
	public BigDecimal getExtraDutyPayLoc() {
		return this.extraDutyPayLoc;
	}

	public void setExtraDutyPayLoc(BigDecimal extraDutyPayLoc) {
		this.extraDutyPayLoc = extraDutyPayLoc;
	}

	@Column(name = "ANNUITY_DED", nullable = false, precision = 9)
	public BigDecimal getAnnuityDed() {
		return this.annuityDed;
	}

	public void setAnnuityDed(BigDecimal annuityDed) {
		this.annuityDed = annuityDed;
	}

	@Column(name = "CAFE_AMT", nullable = false, precision = 9)
	public BigDecimal getCafeAmt() {
		return this.cafeAmt;
	}

	public void setCafeAmt(BigDecimal cafeAmt) {
		this.cafeAmt = cafeAmt;
	}

	@Column(name = "WHOLLY_SEP_AMT", nullable = false, precision = 9)
	public BigDecimal getWhollySepAmt() {
		return this.whollySepAmt;
	}

	public void setWhollySepAmt(BigDecimal whollySepAmt) {
		this.whollySepAmt = whollySepAmt;
	}

	@Column(name = "DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getDependCare() {
		return this.dependCare;
	}

	public void setDependCare(BigDecimal dependCare) {
		this.dependCare = dependCare;
	}

	@Column(name = "TAX_EMPLR_LIFE", nullable = false, precision = 9)
	public BigDecimal getTaxEmplrLife() {
		return this.taxEmplrLife;
	}

	public void setTaxEmplrLife(BigDecimal taxEmplrLife) {
		this.taxEmplrLife = taxEmplrLife;
	}

	@Column(name = "TAX_EMPLR_LIFE_GRP", nullable = false, precision = 9)
	public BigDecimal getTaxEmplrLifeGrp() {
		return this.taxEmplrLifeGrp;
	}

	public void setTaxEmplrLifeGrp(BigDecimal taxEmplrLifeGrp) {
		this.taxEmplrLifeGrp = taxEmplrLifeGrp;
	}

	@Column(name = "DIST_CONTRIB_ABOVE_ST", nullable = false, precision = 9)
	public BigDecimal getDistContribAboveSt() {
		return this.distContribAboveSt;
	}

	public void setDistContribAboveSt(BigDecimal distContribAboveSt) {
		this.distContribAboveSt = distContribAboveSt;
	}

	@Column(name = "NONTRS_REIMBR_EXCESS", nullable = false, precision = 9)
	public BigDecimal getNontrsReimbrExcess() {
		return this.nontrsReimbrExcess;
	}

	public void setNontrsReimbrExcess(BigDecimal nontrsReimbrExcess) {
		this.nontrsReimbrExcess = nontrsReimbrExcess;
	}

	@Column(name = "NONTRS_REIMBR_BASE", nullable = false, precision = 9)
	public BigDecimal getNontrsReimbrBase() {
		return this.nontrsReimbrBase;
	}

	public void setNontrsReimbrBase(BigDecimal nontrsReimbrBase) {
		this.nontrsReimbrBase = nontrsReimbrBase;
	}

	@Column(name = "NONTRS_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsBusAllow() {
		return this.nontrsBusAllow;
	}

	public void setNontrsBusAllow(BigDecimal nontrsBusAllow) {
		this.nontrsBusAllow = nontrsBusAllow;
	}

	@Column(name = "NONTRS_NONTAX_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsNontaxBusAllow() {
		return this.nontrsNontaxBusAllow;
	}

	public void setNontrsNontaxBusAllow(BigDecimal nontrsNontaxBusAllow) {
		this.nontrsNontaxBusAllow = nontrsNontaxBusAllow;
	}

	@Column(name = "NONTRS_NONPAY_BUS_ALLOW", nullable = false, precision = 9)
	public BigDecimal getNontrsNonpayBusAllow() {
		return this.nontrsNonpayBusAllow;
	}

	public void setNontrsNonpayBusAllow(BigDecimal nontrsNonpayBusAllow) {
		this.nontrsNonpayBusAllow = nontrsNonpayBusAllow;
	}

	@Column(name = "NONTRS_NONTAX_NONPAY_ALLOW", nullable = false, precision = 7)
	public BigDecimal getNontrsNontaxNonpayAllow() {
		return this.nontrsNontaxNonpayAllow;
	}

	public void setNontrsNontaxNonpayAllow(BigDecimal nontrsNontaxNonpayAllow) {
		this.nontrsNontaxNonpayAllow = nontrsNontaxNonpayAllow;
	}

	@Column(name = "NONTRS_SUPPL", nullable = false, precision = 9)
	public BigDecimal getNontrsSuppl() {
		return this.nontrsSuppl;
	}

	public void setNontrsSuppl(BigDecimal nontrsSuppl) {
		this.nontrsSuppl = nontrsSuppl;
	}

	@Column(name = "NONTRS_NONTAX_NONPAY_EXPEND", nullable = false, precision = 7)
	public BigDecimal getNontrsNontaxNonpayExpend() {
		return this.nontrsNontaxNonpayExpend;
	}

	public void setNontrsNontaxNonpayExpend(BigDecimal nontrsNontaxNonpayExpend) {
		this.nontrsNontaxNonpayExpend = nontrsNontaxNonpayExpend;
	}

	@Column(name = "TRS_ACTIVE_CARE_ELIG_FLG", nullable = false, length = 1)
	public char getTrsActiveCareEligFlg() {
		return this.trsActiveCareEligFlg;
	}

	public void setTrsActiveCareEligFlg(char trsActiveCareEligFlg) {
		this.trsActiveCareEligFlg = trsActiveCareEligFlg;
	}

	@Column(name = "TRS_SUPPL_COMP", nullable = false, precision = 7)
	public BigDecimal getTrsSupplComp() {
		return this.trsSupplComp;
	}

	public void setTrsSupplComp(BigDecimal trsSupplComp) {
		this.trsSupplComp = trsSupplComp;
	}

	@Column(name = "TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getTeaHealthInsContrib() {
		return this.teaHealthInsContrib;
	}

	public void setTeaHealthInsContrib(BigDecimal teaHealthInsContrib) {
		this.teaHealthInsContrib = teaHealthInsContrib;
	}

	@Column(name = "ACCRU_TEA_HEALTH_INS_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getAccruTeaHealthInsContrib() {
		return this.accruTeaHealthInsContrib;
	}

	public void setAccruTeaHealthInsContrib(BigDecimal accruTeaHealthInsContrib) {
		this.accruTeaHealthInsContrib = accruTeaHealthInsContrib;
	}

	@Column(name = "TRS_SUPPL_COMP_FACTOR", nullable = false, precision = 1, scale = 0)
	public boolean isTrsSupplCompFactor() {
		return this.trsSupplCompFactor;
	}

	public void setTrsSupplCompFactor(boolean trsSupplCompFactor) {
		this.trsSupplCompFactor = trsSupplCompFactor;
	}

	@Column(name = "EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrTrsCareContrib() {
		return this.emplrTrsCareContrib;
	}

	public void setEmplrTrsCareContrib(BigDecimal emplrTrsCareContrib) {
		this.emplrTrsCareContrib = emplrTrsCareContrib;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrTrsCareContrib() {
		return this.accruEmplrTrsCareContrib;
	}

	public void setAccruEmplrTrsCareContrib(BigDecimal accruEmplrTrsCareContrib) {
		this.accruEmplrTrsCareContrib = accruEmplrTrsCareContrib;
	}

	@Column(name = "DAYS_WRK", nullable = false, precision = 5)
	public BigDecimal getDaysWrk() {
		return this.daysWrk;
	}

	public void setDaysWrk(BigDecimal daysWrk) {
		this.daysWrk = daysWrk;
	}

	@Column(name = "MULTI_HRLY_RATES", nullable = false, length = 1)
	public char getMultiHrlyRates() {
		return this.multiHrlyRates;
	}

	public void setMultiHrlyRates(char multiHrlyRates) {
		this.multiHrlyRates = multiHrlyRates;
	}

	@Column(name = "TRS_SUPPL_ELIG_CD", nullable = false, length = 1)
	public char getTrsSupplEligCd() {
		return this.trsSupplEligCd;
	}

	public void setTrsSupplEligCd(char trsSupplEligCd) {
		this.trsSupplEligCd = trsSupplEligCd;
	}

	@Column(name = "PERFOR_PAY_GROSS", nullable = false, precision = 9)
	public BigDecimal getPerforPayGross() {
		return this.perforPayGross;
	}

	public void setPerforPayGross(BigDecimal perforPayGross) {
		this.perforPayGross = perforPayGross;
	}

	@Column(name = "PERFOR_PAY_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getPerforPayDeposit() {
		return this.perforPayDeposit;
	}

	public void setPerforPayDeposit(BigDecimal perforPayDeposit) {
		this.perforPayDeposit = perforPayDeposit;
	}

	@Column(name = "PERFOR_PAY_INS", nullable = false, precision = 7)
	public BigDecimal getPerforPayIns() {
		return this.perforPayIns;
	}

	public void setPerforPayIns(BigDecimal perforPayIns) {
		this.perforPayIns = perforPayIns;
	}

	@Column(name = "TRS_GRANT_GROSS", nullable = false, precision = 9)
	public BigDecimal getTrsGrantGross() {
		return this.trsGrantGross;
	}

	public void setTrsGrantGross(BigDecimal trsGrantGross) {
		this.trsGrantGross = trsGrantGross;
	}

	@Column(name = "TRS_GRANT_DEPOSIT", nullable = false, precision = 9)
	public BigDecimal getTrsGrantDeposit() {
		return this.trsGrantDeposit;
	}

	public void setTrsGrantDeposit(BigDecimal trsGrantDeposit) {
		this.trsGrantDeposit = trsGrantDeposit;
	}

	@Column(name = "TRS_GRANT_CARE", nullable = false, precision = 7)
	public BigDecimal getTrsGrantCare() {
		return this.trsGrantCare;
	}

	public void setTrsGrantCare(BigDecimal trsGrantCare) {
		this.trsGrantCare = trsGrantCare;
	}

	@Column(name = "ACCRU_CAFE_AMT", nullable = false, precision = 9)
	public BigDecimal getAccruCafeAmt() {
		return this.accruCafeAmt;
	}

	public void setAccruCafeAmt(BigDecimal accruCafeAmt) {
		this.accruCafeAmt = accruCafeAmt;
	}

	@Column(name = "EMPLR_RET_GROSS", nullable = false, precision = 9)
	public BigDecimal getEmplrRetGross() {
		return this.emplrRetGross;
	}

	public void setEmplrRetGross(BigDecimal emplrRetGross) {
		this.emplrRetGross = emplrRetGross;
	}

	@Column(name = "EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getEmplrRetPensnSurchg() {
		return this.emplrRetPensnSurchg;
	}

	public void setEmplrRetPensnSurchg(BigDecimal emplrRetPensnSurchg) {
		this.emplrRetPensnSurchg = emplrRetPensnSurchg;
	}

	@Column(name = "ACCRU_EMPLR_RET_PENSN_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrRetPensnSurchg() {
		return this.accruEmplrRetPensnSurchg;
	}

	public void setAccruEmplrRetPensnSurchg(BigDecimal accruEmplrRetPensnSurchg) {
		this.accruEmplrRetPensnSurchg = accruEmplrRetPensnSurchg;
	}

	@Column(name = "EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getEmplrTrsCareSurchg() {
		return this.emplrTrsCareSurchg;
	}

	public void setEmplrTrsCareSurchg(BigDecimal emplrTrsCareSurchg) {
		this.emplrTrsCareSurchg = emplrTrsCareSurchg;
	}

	@Column(name = "ACCRU_EMPLR_TRS_CARE_SURCHG", nullable = false, precision = 7)
	public BigDecimal getAccruEmplrTrsCareSurchg() {
		return this.accruEmplrTrsCareSurchg;
	}

	public void setAccruEmplrTrsCareSurchg(BigDecimal accruEmplrTrsCareSurchg) {
		this.accruEmplrTrsCareSurchg = accruEmplrTrsCareSurchg;
	}

	@Column(name = "EMPLR_NEW_TRS_GROSS", nullable = false, precision = 9)
	public BigDecimal getEmplrNewTrsGross() {
		return this.emplrNewTrsGross;
	}

	public void setEmplrNewTrsGross(BigDecimal emplrNewTrsGross) {
		this.emplrNewTrsGross = emplrNewTrsGross;
	}

	@Column(name = "EMPLR_NEW_TRS_PENSN_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getEmplrNewTrsPensnContrib() {
		return this.emplrNewTrsPensnContrib;
	}

	public void setEmplrNewTrsPensnContrib(BigDecimal emplrNewTrsPensnContrib) {
		this.emplrNewTrsPensnContrib = emplrNewTrsPensnContrib;
	}

	@Column(name = "TAKE_RET_SURCHG", nullable = false, length = 1)
	public char getTakeRetSurchg() {
		return this.takeRetSurchg;
	}

	public void setTakeRetSurchg(char takeRetSurchg) {
		this.takeRetSurchg = takeRetSurchg;
	}

	@Column(name = "EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getEmplrDependCare() {
		return this.emplrDependCare;
	}

	public void setEmplrDependCare(BigDecimal emplrDependCare) {
		this.emplrDependCare = emplrDependCare;
	}

	@Column(name = "ACCRU_EMPLR_DEPEND_CARE", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrDependCare() {
		return this.accruEmplrDependCare;
	}

	public void setAccruEmplrDependCare(BigDecimal accruEmplrDependCare) {
		this.accruEmplrDependCare = accruEmplrDependCare;
	}

	@Column(name = "ANNUITY_ROTH", nullable = false, precision = 9)
	public BigDecimal getAnnuityRoth() {
		return this.annuityRoth;
	}

	public void setAnnuityRoth(BigDecimal annuityRoth) {
		this.annuityRoth = annuityRoth;
	}

	@Column(name = "MICR_CHK_NBR", nullable = false, length = 6)
	public String getMicrChkNbr() {
		return this.micrChkNbr;
	}

	public void setMicrChkNbr(String micrChkNbr) {
		this.micrChkNbr = micrChkNbr;
	}

	@Column(name = "RECON_DTS", nullable = false, length = 16)
	public String getReconDts() {
		return this.reconDts;
	}

	public void setReconDts(String reconDts) {
		this.reconDts = reconDts;
	}

	@Column(name = "EMPLR_DEPEND_CARE_TAX", nullable = false, precision = 7)
	public BigDecimal getEmplrDependCareTax() {
		return this.emplrDependCareTax;
	}

	public void setEmplrDependCareTax(BigDecimal emplrDependCareTax) {
		this.emplrDependCareTax = emplrDependCareTax;
	}

	@Column(name = "HSA_EMP_SAL_REDCTN_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getHsaEmpSalRedctnContrib() {
		return this.hsaEmpSalRedctnContrib;
	}

	public void setHsaEmpSalRedctnContrib(BigDecimal hsaEmpSalRedctnContrib) {
		this.hsaEmpSalRedctnContrib = hsaEmpSalRedctnContrib;
	}

	@Column(name = "HSA_EMPLR_CONTRIB", nullable = false, precision = 7)
	public BigDecimal getHsaEmplrContrib() {
		return this.hsaEmplrContrib;
	}

	public void setHsaEmplrContrib(BigDecimal hsaEmplrContrib) {
		this.hsaEmplrContrib = hsaEmplrContrib;
	}

	@Column(name = "EMPLR_FICA_TAX", nullable = false, precision = 9)
	public BigDecimal getEmplrFicaTax() {
		return this.emplrFicaTax;
	}

	public void setEmplrFicaTax(BigDecimal emplrFicaTax) {
		this.emplrFicaTax = emplrFicaTax;
	}

	@Column(name = "EMPLR_MISC_DED_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrMiscDedContrib() {
		return this.emplrMiscDedContrib;
	}

	public void setEmplrMiscDedContrib(BigDecimal emplrMiscDedContrib) {
		this.emplrMiscDedContrib = emplrMiscDedContrib;
	}

	@Column(name = "ACCRU_EMPLR_MISC_DED_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getAccruEmplrMiscDedContrib() {
		return this.accruEmplrMiscDedContrib;
	}

	public void setAccruEmplrMiscDedContrib(BigDecimal accruEmplrMiscDedContrib) {
		this.accruEmplrMiscDedContrib = accruEmplrMiscDedContrib;
	}

	@Column(name = "EMPLR_MED_TAX", nullable = false, precision = 9)
	public BigDecimal getEmplrMedTax() {
		return this.emplrMedTax;
	}

	public void setEmplrMedTax(BigDecimal emplrMedTax) {
		this.emplrMedTax = emplrMedTax;
	}

	@Column(name = "MED_GROS_CAL_YTD", nullable = false, precision = 9)
	public BigDecimal getMedGrosCalYtd() {
		return this.medGrosCalYtd;
	}

	public void setMedGrosCalYtd(BigDecimal medGrosCalYtd) {
		this.medGrosCalYtd = medGrosCalYtd;
	}

	@Column(name = "EMPLR_TRS_NON_OASDI_CONTRIB", nullable = false, precision = 9)
	public BigDecimal getEmplrTrsNonOasdiContrib() {
		return this.emplrTrsNonOasdiContrib;
	}

	public void setEmplrTrsNonOasdiContrib(BigDecimal emplrTrsNonOasdiContrib) {
		this.emplrTrsNonOasdiContrib = emplrTrsNonOasdiContrib;
	}

	@Column(name = "ANNUITY_ROTH_457B", nullable = false, precision = 9)
	public BigDecimal getAnnuityRoth457b() {
		return this.annuityRoth457b;
	}

	public void setAnnuityRoth457b(BigDecimal annuityRoth457b) {
		this.annuityRoth457b = annuityRoth457b;
	}

	@Column(name = "ERS_RET_HLTH_ELIG", nullable = false, length = 1)
	public char getErsRetHlthElig() {
		return this.ersRetHlthElig;
	}

	public void setErsRetHlthElig(char ersRetHlthElig) {
		this.ersRetHlthElig = ersRetHlthElig;
	}

	@Column(name = "TRS_STAT_CD", nullable = false, length = 1)
	public char getTrsStatCd() {
		return this.trsStatCd;
	}

	public void setTrsStatCd(char trsStatCd) {
		this.trsStatCd = trsStatCd;
	}
}
