package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrResponsibility generated by hbm2java
 */
@Entity
@Table(name = "BHR_RESPONSIBILITY", schema = "rsccc", catalog = "rsccc")
public class BhrResponsibility implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrResponsibilityId id;
	private String nbrStu;
	private String popSrvd;
	private char escSsa;
	private String jobCd;
	private String classTyp;
	private String mnthlyMin;
	private String module;
	private int nbrDaysWeek1;
	private int nbrDaysWeek2;
	private int nbrDaysWeek3;
	private int nbrDaysWeek4;
	private int nbrMinWeek1;
	private int nbrMinWeek2;
	private int nbrMinWeek3;
	private int nbrMinWeek4;

	public BhrResponsibility() {
	}

	public BhrResponsibility(BhrResponsibilityId id, String nbrStu, String popSrvd, char escSsa, String jobCd,
			String classTyp, String mnthlyMin, String module, int nbrDaysWeek1, int nbrDaysWeek2, int nbrDaysWeek3,
			int nbrDaysWeek4, int nbrMinWeek1, int nbrMinWeek2, int nbrMinWeek3, int nbrMinWeek4) {
		this.id = id;
		this.nbrStu = nbrStu;
		this.popSrvd = popSrvd;
		this.escSsa = escSsa;
		this.jobCd = jobCd;
		this.classTyp = classTyp;
		this.mnthlyMin = mnthlyMin;
		this.module = module;
		this.nbrDaysWeek1 = nbrDaysWeek1;
		this.nbrDaysWeek2 = nbrDaysWeek2;
		this.nbrDaysWeek3 = nbrDaysWeek3;
		this.nbrDaysWeek4 = nbrDaysWeek4;
		this.nbrMinWeek1 = nbrMinWeek1;
		this.nbrMinWeek2 = nbrMinWeek2;
		this.nbrMinWeek3 = nbrMinWeek3;
		this.nbrMinWeek4 = nbrMinWeek4;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "campusId", column = @Column(name = "CAMPUS_ID", nullable = false, length = 3)),
			@AttributeOverride(name = "roleId", column = @Column(name = "ROLE_ID", nullable = false, length = 3)),
			@AttributeOverride(name = "svcId", column = @Column(name = "SVC_ID", nullable = false, length = 8)),
			@AttributeOverride(name = "classId", column = @Column(name = "CLASS_ID", nullable = false, length = 14)) })
	public BhrResponsibilityId getId() {
		return this.id;
	}

	public void setId(BhrResponsibilityId id) {
		this.id = id;
	}

	@Column(name = "NBR_STU", nullable = false, length = 3)
	public String getNbrStu() {
		return this.nbrStu;
	}

	public void setNbrStu(String nbrStu) {
		this.nbrStu = nbrStu;
	}

	@Column(name = "POP_SRVD", nullable = false, length = 2)
	public String getPopSrvd() {
		return this.popSrvd;
	}

	public void setPopSrvd(String popSrvd) {
		this.popSrvd = popSrvd;
	}

	@Column(name = "ESC_SSA", nullable = false, length = 1)
	public char getEscSsa() {
		return this.escSsa;
	}

	public void setEscSsa(char escSsa) {
		this.escSsa = escSsa;
	}

	@Column(name = "JOB_CD", nullable = false, length = 4)
	public String getJobCd() {
		return this.jobCd;
	}

	public void setJobCd(String jobCd) {
		this.jobCd = jobCd;
	}

	@Column(name = "CLASS_TYP", nullable = false, length = 2)
	public String getClassTyp() {
		return this.classTyp;
	}

	public void setClassTyp(String classTyp) {
		this.classTyp = classTyp;
	}

	@Column(name = "MNTHLY_MIN", nullable = false, length = 5)
	public String getMnthlyMin() {
		return this.mnthlyMin;
	}

	public void setMnthlyMin(String mnthlyMin) {
		this.mnthlyMin = mnthlyMin;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "NBR_DAYS_WEEK1", nullable = false)
	public int getNbrDaysWeek1() {
		return this.nbrDaysWeek1;
	}

	public void setNbrDaysWeek1(int nbrDaysWeek1) {
		this.nbrDaysWeek1 = nbrDaysWeek1;
	}

	@Column(name = "NBR_DAYS_WEEK2", nullable = false)
	public int getNbrDaysWeek2() {
		return this.nbrDaysWeek2;
	}

	public void setNbrDaysWeek2(int nbrDaysWeek2) {
		this.nbrDaysWeek2 = nbrDaysWeek2;
	}

	@Column(name = "NBR_DAYS_WEEK3", nullable = false)
	public int getNbrDaysWeek3() {
		return this.nbrDaysWeek3;
	}

	public void setNbrDaysWeek3(int nbrDaysWeek3) {
		this.nbrDaysWeek3 = nbrDaysWeek3;
	}

	@Column(name = "NBR_DAYS_WEEK4", nullable = false)
	public int getNbrDaysWeek4() {
		return this.nbrDaysWeek4;
	}

	public void setNbrDaysWeek4(int nbrDaysWeek4) {
		this.nbrDaysWeek4 = nbrDaysWeek4;
	}

	@Column(name = "NBR_MIN_WEEK1", nullable = false)
	public int getNbrMinWeek1() {
		return this.nbrMinWeek1;
	}

	public void setNbrMinWeek1(int nbrMinWeek1) {
		this.nbrMinWeek1 = nbrMinWeek1;
	}

	@Column(name = "NBR_MIN_WEEK2", nullable = false)
	public int getNbrMinWeek2() {
		return this.nbrMinWeek2;
	}

	public void setNbrMinWeek2(int nbrMinWeek2) {
		this.nbrMinWeek2 = nbrMinWeek2;
	}

	@Column(name = "NBR_MIN_WEEK3", nullable = false)
	public int getNbrMinWeek3() {
		return this.nbrMinWeek3;
	}

	public void setNbrMinWeek3(int nbrMinWeek3) {
		this.nbrMinWeek3 = nbrMinWeek3;
	}

	@Column(name = "NBR_MIN_WEEK4", nullable = false)
	public int getNbrMinWeek4() {
		return this.nbrMinWeek4;
	}

	public void setNbrMinWeek4(int nbrMinWeek4) {
		this.nbrMinWeek4 = nbrMinWeek4;
	}

}
