package com.esc20.model;
// Generated Jan 4, 2019 3:45:09 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhrSchYtdWrkCmpBkupPaycalcs5Id generated by hbm2java
 */
@Embeddable
public class BhrSchYtdWrkCmpBkupPaycalcs5Id implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private char payFreq;
	private String empNbr;
	private char cyrNyrFlg;
	private String schYr;
	private char wrkComp;
	private BigDecimal wrkCompIns;
	private BigDecimal wrkCompGross;
	private String module;

	public BhrSchYtdWrkCmpBkupPaycalcs5Id() {
	}

	public BhrSchYtdWrkCmpBkupPaycalcs5Id(char payFreq, String empNbr, char cyrNyrFlg, String schYr, char wrkComp,
			BigDecimal wrkCompIns, BigDecimal wrkCompGross, String module) {
		this.payFreq = payFreq;
		this.empNbr = empNbr;
		this.cyrNyrFlg = cyrNyrFlg;
		this.schYr = schYr;
		this.wrkComp = wrkComp;
		this.wrkCompIns = wrkCompIns;
		this.wrkCompGross = wrkCompGross;
		this.module = module;
	}

	@Column(name = "PAY_FREQ", nullable = false, length = 1)
	public char getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(char payFreq) {
		this.payFreq = payFreq;
	}

	@Column(name = "EMP_NBR", nullable = false, length = 6)
	public String getEmpNbr() {
		return this.empNbr;
	}

	public void setEmpNbr(String empNbr) {
		this.empNbr = empNbr;
	}

	@Column(name = "CYR_NYR_FLG", nullable = false, length = 1)
	public char getCyrNyrFlg() {
		return this.cyrNyrFlg;
	}

	public void setCyrNyrFlg(char cyrNyrFlg) {
		this.cyrNyrFlg = cyrNyrFlg;
	}

	@Column(name = "SCH_YR", nullable = false, length = 4)
	public String getSchYr() {
		return this.schYr;
	}

	public void setSchYr(String schYr) {
		this.schYr = schYr;
	}

	@Column(name = "WRK_COMP", nullable = false, length = 1)
	public char getWrkComp() {
		return this.wrkComp;
	}

	public void setWrkComp(char wrkComp) {
		this.wrkComp = wrkComp;
	}

	@Column(name = "WRK_COMP_INS", nullable = false, precision = 9)
	public BigDecimal getWrkCompIns() {
		return this.wrkCompIns;
	}

	public void setWrkCompIns(BigDecimal wrkCompIns) {
		this.wrkCompIns = wrkCompIns;
	}

	@Column(name = "WRK_COMP_GROSS", nullable = false, precision = 11)
	public BigDecimal getWrkCompGross() {
		return this.wrkCompGross;
	}

	public void setWrkCompGross(BigDecimal wrkCompGross) {
		this.wrkCompGross = wrkCompGross;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhrSchYtdWrkCmpBkupPaycalcs5Id))
			return false;
		BhrSchYtdWrkCmpBkupPaycalcs5Id castOther = (BhrSchYtdWrkCmpBkupPaycalcs5Id) other;

		return (this.getPayFreq() == castOther.getPayFreq())
				&& ((this.getEmpNbr() == castOther.getEmpNbr()) || (this.getEmpNbr() != null
						&& castOther.getEmpNbr() != null && this.getEmpNbr().equals(castOther.getEmpNbr())))
				&& (this.getCyrNyrFlg() == castOther.getCyrNyrFlg())
				&& ((this.getSchYr() == castOther.getSchYr()) || (this.getSchYr() != null
						&& castOther.getSchYr() != null && this.getSchYr().equals(castOther.getSchYr())))
				&& (this.getWrkComp() == castOther.getWrkComp())
				&& ((this.getWrkCompIns() == castOther.getWrkCompIns()) || (this.getWrkCompIns() != null
						&& castOther.getWrkCompIns() != null && this.getWrkCompIns().equals(castOther.getWrkCompIns())))
				&& ((this.getWrkCompGross() == castOther.getWrkCompGross())
						|| (this.getWrkCompGross() != null && castOther.getWrkCompGross() != null
								&& this.getWrkCompGross().equals(castOther.getWrkCompGross())))
				&& ((this.getModule() == castOther.getModule()) || (this.getModule() != null
						&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPayFreq();
		result = 37 * result + (getEmpNbr() == null ? 0 : this.getEmpNbr().hashCode());
		result = 37 * result + this.getCyrNyrFlg();
		result = 37 * result + (getSchYr() == null ? 0 : this.getSchYr().hashCode());
		result = 37 * result + this.getWrkComp();
		result = 37 * result + (getWrkCompIns() == null ? 0 : this.getWrkCompIns().hashCode());
		result = 37 * result + (getWrkCompGross() == null ? 0 : this.getWrkCompGross().hashCode());
		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		return result;
	}

}
