package com.esc20.model;
// Generated Jan 4, 2019 3:44:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrSavingsBondsBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BHR_SAVINGS_BONDS_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BhrSavingsBondsBkupPaycalcs5 implements java.io.Serializable {
	private static final long serialVersionUID = 6715142900654758429L;
	private BhrSavingsBondsBkupPaycalcs5Id id;

	public BhrSavingsBondsBkupPaycalcs5() {
	}

	public BhrSavingsBondsBkupPaycalcs5(BhrSavingsBondsBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cyrNyrFlg", column = @Column(name = "CYR_NYR_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)),
			@AttributeOverride(name = "dedCd", column = @Column(name = "DED_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "dedSeq", column = @Column(name = "DED_SEQ", nullable = false, length = 1)),
			@AttributeOverride(name = "ownerSsn", column = @Column(name = "OWNER_SSN", nullable = false, length = 9)),
			@AttributeOverride(name = "owner", column = @Column(name = "OWNER", nullable = false, length = 32)),
			@AttributeOverride(name = "ownerAddrNbr", column = @Column(name = "OWNER_ADDR_NBR", nullable = false, length = 8)),
			@AttributeOverride(name = "ownerAddrStr", column = @Column(name = "OWNER_ADDR_STR", nullable = false, length = 20)),
			@AttributeOverride(name = "ownerAddrApt", column = @Column(name = "OWNER_ADDR_APT", nullable = false, length = 7)),
			@AttributeOverride(name = "ownerAddrCity", column = @Column(name = "OWNER_ADDR_CITY", nullable = false, length = 25)),
			@AttributeOverride(name = "ownerAddrSt", column = @Column(name = "OWNER_ADDR_ST", nullable = false, length = 2)),
			@AttributeOverride(name = "ownerAddrZip", column = @Column(name = "OWNER_ADDR_ZIP", nullable = false, length = 5)),
			@AttributeOverride(name = "ownerAddrZip4", column = @Column(name = "OWNER_ADDR_ZIP4", nullable = false, length = 4)),
			@AttributeOverride(name = "benificiary", column = @Column(name = "BENIFICIARY", nullable = false, length = 35)),
			@AttributeOverride(name = "benificiarySsan", column = @Column(name = "BENIFICIARY_SSAN", nullable = false, length = 9)),
			@AttributeOverride(name = "relationship", column = @Column(name = "RELATIONSHIP", nullable = false, length = 3)),
			@AttributeOverride(name = "faceValue", column = @Column(name = "FACE_VALUE", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "statusFlg", column = @Column(name = "STATUS_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "seriesTyp", column = @Column(name = "SERIES_TYP", nullable = false, length = 2)) })
	public BhrSavingsBondsBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BhrSavingsBondsBkupPaycalcs5Id id) {
		this.id = id;
	}

}
