package com.esc20.model;
// Generated Jan 4, 2019 3:47:38 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTeamEd25 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TEAM_ED25", schema = "rsccc", catalog = "rsccc")
public class BhrTeamEd25 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1165998654211182800L;
	private BhrTeamEd25Id id;
	private String origStaffId;
	private String origDob;
	private char origSex;
	private String origNameL;
	private String origNameF;
	private String origNameM;
	private char origNameGen;
	private String newStaffId;
	private String newDob;
	private char newSex;
	private String newNameL;
	private String newNameF;
	private String newNameM;
	private char newNameGen;
	private String newAddrNbr;
	private String newAddrStr;
	private String newAddrApt;
	private String newAddrCity;
	private String newAddrSt;
	private String newAddrZip;
	private String newAddrZip4;
	private String newAddrProvince;
	private String newAddrCtry;
	private String newPostalCd;
	private String newEmail;
	private String newPhoneArea;
	private String newPhoneNbr;
	private String module;

	public BhrTeamEd25() {
	}

	public BhrTeamEd25(BhrTeamEd25Id id, String origStaffId, String origDob, char origSex, String origNameL,
			String origNameF, String origNameM, char origNameGen, String newStaffId, String newDob, char newSex,
			String newNameL, String newNameF, String newNameM, char newNameGen, String newAddrNbr, String newAddrStr,
			String newAddrApt, String newAddrCity, String newAddrSt, String newAddrZip, String newAddrZip4,
			String newAddrProvince, String newAddrCtry, String newPostalCd, String newEmail, String newPhoneArea,
			String newPhoneNbr, String module) {
		this.id = id;
		this.origStaffId = origStaffId;
		this.origDob = origDob;
		this.origSex = origSex;
		this.origNameL = origNameL;
		this.origNameF = origNameF;
		this.origNameM = origNameM;
		this.origNameGen = origNameGen;
		this.newStaffId = newStaffId;
		this.newDob = newDob;
		this.newSex = newSex;
		this.newNameL = newNameL;
		this.newNameF = newNameF;
		this.newNameM = newNameM;
		this.newNameGen = newNameGen;
		this.newAddrNbr = newAddrNbr;
		this.newAddrStr = newAddrStr;
		this.newAddrApt = newAddrApt;
		this.newAddrCity = newAddrCity;
		this.newAddrSt = newAddrSt;
		this.newAddrZip = newAddrZip;
		this.newAddrZip4 = newAddrZip4;
		this.newAddrProvince = newAddrProvince;
		this.newAddrCtry = newAddrCtry;
		this.newPostalCd = newPostalCd;
		this.newEmail = newEmail;
		this.newPhoneArea = newPhoneArea;
		this.newPhoneNbr = newPhoneNbr;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "empNbr", column = @Column(name = "EMP_NBR", nullable = false, length = 6)) })
	public BhrTeamEd25Id getId() {
		return this.id;
	}

	public void setId(BhrTeamEd25Id id) {
		this.id = id;
	}

	@Column(name = "ORIG_STAFF_ID", nullable = false, length = 9)
	public String getOrigStaffId() {
		return this.origStaffId;
	}

	public void setOrigStaffId(String origStaffId) {
		this.origStaffId = origStaffId;
	}

	@Column(name = "ORIG_DOB", nullable = false, length = 8)
	public String getOrigDob() {
		return this.origDob;
	}

	public void setOrigDob(String origDob) {
		this.origDob = origDob;
	}

	@Column(name = "ORIG_SEX", nullable = false, length = 1)
	public char getOrigSex() {
		return this.origSex;
	}

	public void setOrigSex(char origSex) {
		this.origSex = origSex;
	}

	@Column(name = "ORIG_NAME_L", nullable = false, length = 30)
	public String getOrigNameL() {
		return this.origNameL;
	}

	public void setOrigNameL(String origNameL) {
		this.origNameL = origNameL;
	}

	@Column(name = "ORIG_NAME_F", nullable = false, length = 25)
	public String getOrigNameF() {
		return this.origNameF;
	}

	public void setOrigNameF(String origNameF) {
		this.origNameF = origNameF;
	}

	@Column(name = "ORIG_NAME_M", nullable = false, length = 25)
	public String getOrigNameM() {
		return this.origNameM;
	}

	public void setOrigNameM(String origNameM) {
		this.origNameM = origNameM;
	}

	@Column(name = "ORIG_NAME_GEN", nullable = false, length = 1)
	public char getOrigNameGen() {
		return this.origNameGen;
	}

	public void setOrigNameGen(char origNameGen) {
		this.origNameGen = origNameGen;
	}

	@Column(name = "NEW_STAFF_ID", nullable = false, length = 9)
	public String getNewStaffId() {
		return this.newStaffId;
	}

	public void setNewStaffId(String newStaffId) {
		this.newStaffId = newStaffId;
	}

	@Column(name = "NEW_DOB", nullable = false, length = 8)
	public String getNewDob() {
		return this.newDob;
	}

	public void setNewDob(String newDob) {
		this.newDob = newDob;
	}

	@Column(name = "NEW_SEX", nullable = false, length = 1)
	public char getNewSex() {
		return this.newSex;
	}

	public void setNewSex(char newSex) {
		this.newSex = newSex;
	}

	@Column(name = "NEW_NAME_L", nullable = false, length = 30)
	public String getNewNameL() {
		return this.newNameL;
	}

	public void setNewNameL(String newNameL) {
		this.newNameL = newNameL;
	}

	@Column(name = "NEW_NAME_F", nullable = false, length = 25)
	public String getNewNameF() {
		return this.newNameF;
	}

	public void setNewNameF(String newNameF) {
		this.newNameF = newNameF;
	}

	@Column(name = "NEW_NAME_M", nullable = false, length = 25)
	public String getNewNameM() {
		return this.newNameM;
	}

	public void setNewNameM(String newNameM) {
		this.newNameM = newNameM;
	}

	@Column(name = "NEW_NAME_GEN", nullable = false, length = 1)
	public char getNewNameGen() {
		return this.newNameGen;
	}

	public void setNewNameGen(char newNameGen) {
		this.newNameGen = newNameGen;
	}

	@Column(name = "NEW_ADDR_NBR", nullable = false, length = 10)
	public String getNewAddrNbr() {
		return this.newAddrNbr;
	}

	public void setNewAddrNbr(String newAddrNbr) {
		this.newAddrNbr = newAddrNbr;
	}

	@Column(name = "NEW_ADDR_STR", nullable = false, length = 39)
	public String getNewAddrStr() {
		return this.newAddrStr;
	}

	public void setNewAddrStr(String newAddrStr) {
		this.newAddrStr = newAddrStr;
	}

	@Column(name = "NEW_ADDR_APT", nullable = false, length = 50)
	public String getNewAddrApt() {
		return this.newAddrApt;
	}

	public void setNewAddrApt(String newAddrApt) {
		this.newAddrApt = newAddrApt;
	}

	@Column(name = "NEW_ADDR_CITY", nullable = false, length = 20)
	public String getNewAddrCity() {
		return this.newAddrCity;
	}

	public void setNewAddrCity(String newAddrCity) {
		this.newAddrCity = newAddrCity;
	}

	@Column(name = "NEW_ADDR_ST", nullable = false, length = 2)
	public String getNewAddrSt() {
		return this.newAddrSt;
	}

	public void setNewAddrSt(String newAddrSt) {
		this.newAddrSt = newAddrSt;
	}

	@Column(name = "NEW_ADDR_ZIP", nullable = false, length = 5)
	public String getNewAddrZip() {
		return this.newAddrZip;
	}

	public void setNewAddrZip(String newAddrZip) {
		this.newAddrZip = newAddrZip;
	}

	@Column(name = "NEW_ADDR_ZIP4", nullable = false, length = 4)
	public String getNewAddrZip4() {
		return this.newAddrZip4;
	}

	public void setNewAddrZip4(String newAddrZip4) {
		this.newAddrZip4 = newAddrZip4;
	}

	@Column(name = "NEW_ADDR_PROVINCE", nullable = false, length = 20)
	public String getNewAddrProvince() {
		return this.newAddrProvince;
	}

	public void setNewAddrProvince(String newAddrProvince) {
		this.newAddrProvince = newAddrProvince;
	}

	@Column(name = "NEW_ADDR_CTRY", nullable = false, length = 3)
	public String getNewAddrCtry() {
		return this.newAddrCtry;
	}

	public void setNewAddrCtry(String newAddrCtry) {
		this.newAddrCtry = newAddrCtry;
	}

	@Column(name = "NEW_POSTAL_CD", nullable = false, length = 10)
	public String getNewPostalCd() {
		return this.newPostalCd;
	}

	public void setNewPostalCd(String newPostalCd) {
		this.newPostalCd = newPostalCd;
	}

	@Column(name = "NEW_EMAIL", nullable = false, length = 100)
	public String getNewEmail() {
		return this.newEmail;
	}

	public void setNewEmail(String newEmail) {
		this.newEmail = newEmail;
	}

	@Column(name = "NEW_PHONE_AREA", nullable = false, length = 3)
	public String getNewPhoneArea() {
		return this.newPhoneArea;
	}

	public void setNewPhoneArea(String newPhoneArea) {
		this.newPhoneArea = newPhoneArea;
	}

	@Column(name = "NEW_PHONE_NBR", nullable = false, length = 7)
	public String getNewPhoneNbr() {
		return this.newPhoneNbr;
	}

	public void setNewPhoneNbr(String newPhoneNbr) {
		this.newPhoneNbr = newPhoneNbr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
