package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTrsMd25 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TRS_MD25", schema = "rsccc", catalog = "rsccc")
public class BhrTrsMd25 implements java.io.Serializable {

	private BhrTrsMd25Id id;
	private String origStaffId;
	private char origStaffIdCd;
	private String origDob;
	private char origSex;
	private String origNameL;
	private String origNameF;
	private char origNameGen;
	private String origNameM;
	private String newNameL;
	private String newNameF;
	private char newNameGen;
	private String newNameM;
	private char newUsCitizenCd;
	private String newStaffId;
	private char newStaffIdCd;
	private String newDob;
	private char newSex;
	private char adjRsnCd;
	private String module;

	public BhrTrsMd25() {
	}

	public BhrTrsMd25(BhrTrsMd25Id id, String origStaffId, char origStaffIdCd, String origDob, char origSex,
			String origNameL, String origNameF, char origNameGen, String origNameM, String newNameL, String newNameF,
			char newNameGen, String newNameM, char newUsCitizenCd, String newStaffId, char newStaffIdCd, String newDob,
			char newSex, char adjRsnCd, String module) {
		this.id = id;
		this.origStaffId = origStaffId;
		this.origStaffIdCd = origStaffIdCd;
		this.origDob = origDob;
		this.origSex = origSex;
		this.origNameL = origNameL;
		this.origNameF = origNameF;
		this.origNameGen = origNameGen;
		this.origNameM = origNameM;
		this.newNameL = newNameL;
		this.newNameF = newNameF;
		this.newNameGen = newNameGen;
		this.newNameM = newNameM;
		this.newUsCitizenCd = newUsCitizenCd;
		this.newStaffId = newStaffId;
		this.newStaffIdCd = newStaffIdCd;
		this.newDob = newDob;
		this.newSex = newSex;
		this.adjRsnCd = adjRsnCd;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "staffId", column = @Column(name = "STAFF_ID", nullable = false, length = 9)) })
	public BhrTrsMd25Id getId() {
		return this.id;
	}

	public void setId(BhrTrsMd25Id id) {
		this.id = id;
	}

	@Column(name = "ORIG_STAFF_ID", nullable = false, length = 9)
	public String getOrigStaffId() {
		return this.origStaffId;
	}

	public void setOrigStaffId(String origStaffId) {
		this.origStaffId = origStaffId;
	}

	@Column(name = "ORIG_STAFF_ID_CD", nullable = false, length = 1)
	public char getOrigStaffIdCd() {
		return this.origStaffIdCd;
	}

	public void setOrigStaffIdCd(char origStaffIdCd) {
		this.origStaffIdCd = origStaffIdCd;
	}

	@Column(name = "ORIG_DOB", nullable = false, length = 8)
	public String getOrigDob() {
		return this.origDob;
	}

	public void setOrigDob(String origDob) {
		this.origDob = origDob;
	}

	@Column(name = "ORIG_SEX", nullable = false, length = 1)
	public char getOrigSex() {
		return this.origSex;
	}

	public void setOrigSex(char origSex) {
		this.origSex = origSex;
	}

	@Column(name = "ORIG_NAME_L", nullable = false, length = 25)
	public String getOrigNameL() {
		return this.origNameL;
	}

	public void setOrigNameL(String origNameL) {
		this.origNameL = origNameL;
	}

	@Column(name = "ORIG_NAME_F", nullable = false, length = 25)
	public String getOrigNameF() {
		return this.origNameF;
	}

	public void setOrigNameF(String origNameF) {
		this.origNameF = origNameF;
	}

	@Column(name = "ORIG_NAME_GEN", nullable = false, length = 1)
	public char getOrigNameGen() {
		return this.origNameGen;
	}

	public void setOrigNameGen(char origNameGen) {
		this.origNameGen = origNameGen;
	}

	@Column(name = "ORIG_NAME_M", nullable = false, length = 25)
	public String getOrigNameM() {
		return this.origNameM;
	}

	public void setOrigNameM(String origNameM) {
		this.origNameM = origNameM;
	}

	@Column(name = "NEW_NAME_L", nullable = false, length = 25)
	public String getNewNameL() {
		return this.newNameL;
	}

	public void setNewNameL(String newNameL) {
		this.newNameL = newNameL;
	}

	@Column(name = "NEW_NAME_F", nullable = false, length = 25)
	public String getNewNameF() {
		return this.newNameF;
	}

	public void setNewNameF(String newNameF) {
		this.newNameF = newNameF;
	}

	@Column(name = "NEW_NAME_GEN", nullable = false, length = 1)
	public char getNewNameGen() {
		return this.newNameGen;
	}

	public void setNewNameGen(char newNameGen) {
		this.newNameGen = newNameGen;
	}

	@Column(name = "NEW_NAME_M", nullable = false, length = 25)
	public String getNewNameM() {
		return this.newNameM;
	}

	public void setNewNameM(String newNameM) {
		this.newNameM = newNameM;
	}

	@Column(name = "NEW_US_CITIZEN_CD", nullable = false, length = 1)
	public char getNewUsCitizenCd() {
		return this.newUsCitizenCd;
	}

	public void setNewUsCitizenCd(char newUsCitizenCd) {
		this.newUsCitizenCd = newUsCitizenCd;
	}

	@Column(name = "NEW_STAFF_ID", nullable = false, length = 9)
	public String getNewStaffId() {
		return this.newStaffId;
	}

	public void setNewStaffId(String newStaffId) {
		this.newStaffId = newStaffId;
	}

	@Column(name = "NEW_STAFF_ID_CD", nullable = false, length = 1)
	public char getNewStaffIdCd() {
		return this.newStaffIdCd;
	}

	public void setNewStaffIdCd(char newStaffIdCd) {
		this.newStaffIdCd = newStaffIdCd;
	}

	@Column(name = "NEW_DOB", nullable = false, length = 8)
	public String getNewDob() {
		return this.newDob;
	}

	public void setNewDob(String newDob) {
		this.newDob = newDob;
	}

	@Column(name = "NEW_SEX", nullable = false, length = 1)
	public char getNewSex() {
		return this.newSex;
	}

	public void setNewSex(char newSex) {
		this.newSex = newSex;
	}

	@Column(name = "ADJ_RSN_CD", nullable = false, length = 1)
	public char getAdjRsnCd() {
		return this.adjRsnCd;
	}

	public void setAdjRsnCd(char adjRsnCd) {
		this.adjRsnCd = adjRsnCd;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
