package com.esc20.model;
// Generated Jan 4, 2019 3:47:57 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BhrTrsMd20 generated by hbm2java
 */
@Entity
@Table(name = "BHR_TRS_MD20", schema = "rsccc", catalog = "rsccc")
public class BhrTrsMd20 implements java.io.Serializable {

	private BhrTrsMd20Id id;
	private char staffIdCd;
	private String dob;
	private char sex;
	private String nameL;
	private String nameF;
	private char nameGen;
	private String nameM;
	private char usCitizenCd;
	private String module;

	public BhrTrsMd20() {
	}

	public BhrTrsMd20(BhrTrsMd20Id id, char staffIdCd, String dob, char sex, String nameL, String nameF, char nameGen,
			String nameM, char usCitizenCd, String module) {
		this.id = id;
		this.staffIdCd = staffIdCd;
		this.dob = dob;
		this.sex = sex;
		this.nameL = nameL;
		this.nameF = nameF;
		this.nameGen = nameGen;
		this.nameM = nameM;
		this.usCitizenCd = usCitizenCd;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rptMon", column = @Column(name = "RPT_MON", nullable = false, length = 2)),
			@AttributeOverride(name = "rptYr", column = @Column(name = "RPT_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "staffId", column = @Column(name = "STAFF_ID", nullable = false, length = 9)) })
	public BhrTrsMd20Id getId() {
		return this.id;
	}

	public void setId(BhrTrsMd20Id id) {
		this.id = id;
	}

	@Column(name = "STAFF_ID_CD", nullable = false, length = 1)
	public char getStaffIdCd() {
		return this.staffIdCd;
	}

	public void setStaffIdCd(char staffIdCd) {
		this.staffIdCd = staffIdCd;
	}

	@Column(name = "DOB", nullable = false, length = 8)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "SEX", nullable = false, length = 1)
	public char getSex() {
		return this.sex;
	}

	public void setSex(char sex) {
		this.sex = sex;
	}

	@Column(name = "NAME_L", nullable = false, length = 25)
	public String getNameL() {
		return this.nameL;
	}

	public void setNameL(String nameL) {
		this.nameL = nameL;
	}

	@Column(name = "NAME_F", nullable = false, length = 25)
	public String getNameF() {
		return this.nameF;
	}

	public void setNameF(String nameF) {
		this.nameF = nameF;
	}

	@Column(name = "NAME_GEN", nullable = false, length = 1)
	public char getNameGen() {
		return this.nameGen;
	}

	public void setNameGen(char nameGen) {
		this.nameGen = nameGen;
	}

	@Column(name = "NAME_M", nullable = false, length = 25)
	public String getNameM() {
		return this.nameM;
	}

	public void setNameM(String nameM) {
		this.nameM = nameM;
	}

	@Column(name = "US_CITIZEN_CD", nullable = false, length = 1)
	public char getUsCitizenCd() {
		return this.usCitizenCd;
	}

	public void setUsCitizenCd(char usCitizenCd) {
		this.usCitizenCd = usCitizenCd;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
