package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrInsurRelationship generated by hbm2java
 */
@Entity
@Table(name = "BTHR_INSUR_RELATIONSHIP", schema = "rsccc", catalog = "rsccc")
public class BthrInsurRelationship implements java.io.Serializable {

	private char relation;
	private String rela;

	public BthrInsurRelationship() {
	}

	public BthrInsurRelationship(char relation, String rela) {
		this.relation = relation;
		this.rela = rela;
	}

	@Id

	@Column(name = "RELATION", nullable = false, length = 1)
	public char getRelation() {
		return this.relation;
	}

	public void setRelation(char relation) {
		this.relation = relation;
	}

	@Column(name = "RELA", nullable = false, length = 20)
	public String getRela() {
		return this.rela;
	}

	public void setRela(String rela) {
		this.rela = rela;
	}

}
