package com.esc20.model;
// Generated Jan 4, 2019 3:50:32 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrBondRelationship generated by hbm2java
 */
@Entity
@Table(name = "BTHR_BOND_RELATIONSHIP", schema = "rsccc", catalog = "rsccc")
public class BthrBondRelationship implements java.io.Serializable {

	private String relationship;
	private String rela;

	public BthrBondRelationship() {
	}

	public BthrBondRelationship(String relationship, String rela) {
		this.relationship = relationship;
		this.rela = rela;
	}

	@Id

	@Column(name = "RELATIONSHIP", nullable = false, length = 3)
	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	@Column(name = "RELA", nullable = false, length = 20)
	public String getRela() {
		return this.rela;
	}

	public void setRela(String rela) {
		this.rela = rela;
	}

}
