package com.esc20.model;
// Generated Jan 4, 2019 3:51:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrCtry generated by hbm2java
 */
@Entity
@Table(name = "BTHR_CTRY", schema = "rsccc", catalog = "rsccc")
public class BthrCtry implements java.io.Serializable {

	private String ctry;
	private String ctryName;

	public BthrCtry() {
	}

	public BthrCtry(String ctry, String ctryName) {
		this.ctry = ctry;
		this.ctryName = ctryName;
	}

	@Id

	@Column(name = "CTRY", nullable = false, length = 3)
	public String getCtry() {
		return this.ctry;
	}

	public void setCtry(String ctry) {
		this.ctry = ctry;
	}

	@Column(name = "CTRY_NAME", nullable = false, length = 50)
	public String getCtryName() {
		return this.ctryName;
	}

	public void setCtryName(String ctryName) {
		this.ctryName = ctryName;
	}

}
