package com.esc20.model;
// Generated Jan 4, 2019 3:53:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BthrNonTrsPymtCd generated by hbm2java
 */
@Entity
@Table(name = "BTHR_NON_TRS_PYMT_CD", schema = "rsccc", catalog = "rsccc")
public class BthrNonTrsPymtCd implements java.io.Serializable {

	private char nonTrsPymtCd;
	private String nonTrsPymtCdDescr;

	public BthrNonTrsPymtCd() {
	}

	public BthrNonTrsPymtCd(char nonTrsPymtCd, String nonTrsPymtCdDescr) {
		this.nonTrsPymtCd = nonTrsPymtCd;
		this.nonTrsPymtCdDescr = nonTrsPymtCdDescr;
	}

	@Id

	@Column(name = "NON_TRS_PYMT_CD", nullable = false, length = 1)
	public char getNonTrsPymtCd() {
		return this.nonTrsPymtCd;
	}

	public void setNonTrsPymtCd(char nonTrsPymtCd) {
		this.nonTrsPymtCd = nonTrsPymtCd;
	}

	@Column(name = "NON_TRS_PYMT_CD_DESCR", nullable = false, length = 20)
	public String getNonTrsPymtCdDescr() {
		return this.nonTrsPymtCdDescr;
	}

	public void setNonTrsPymtCdDescr(String nonTrsPymtCdDescr) {
		this.nonTrsPymtCdDescr = nonTrsPymtCdDescr;
	}

}
