package com.esc20.model;
// Generated Jan 4, 2019 3:50:10 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrAccrualCdBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ACCRUAL_CD_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrAccrualCdBkupPaycalcs5 implements java.io.Serializable {

	private BthrAccrualCdBkupPaycalcs5Id id;

	public BthrAccrualCdBkupPaycalcs5() {
	}

	public BthrAccrualCdBkupPaycalcs5(BthrAccrualCdBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "accruCd", column = @Column(name = "ACCRU_CD", nullable = false, length = 1)),
			@AttributeOverride(name = "totNbrDaysEarned", column = @Column(name = "TOT_NBR_DAYS_EARNED", nullable = false, precision = 5)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrAccrualCdBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrAccrualCdBkupPaycalcs5Id id) {
		this.id = id;
	}

}
