package com.esc20.model;
// Generated Jan 4, 2019 3:53:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrPayDates generated by hbm2java
 */
@Entity
@Table(name = "BTHR_PAY_DATES", schema = "rsccc", catalog = "rsccc")
public class BthrPayDates implements java.io.Serializable {

	private static final long serialVersionUID = 6893306266480374119L;
	private BthrPayDatesId id;
	private String dtPayperBeg;
	private String dtPayperEnd;
	private String trsMonth;
	private char twcQtr;
	private char useAltAddr;
	private String module;
	private String lvReqCutoffDt;
	private String lvLastAprvDt;

	public BthrPayDates() {
	}

	public BthrPayDates(BthrPayDatesId id, String dtPayperBeg, String dtPayperEnd, String trsMonth, char twcQtr,
			char useAltAddr, String module, String lvReqCutoffDt, String lvLastAprvDt) {
		this.id = id;
		this.dtPayperBeg = dtPayperBeg;
		this.dtPayperEnd = dtPayperEnd;
		this.trsMonth = trsMonth;
		this.twcQtr = twcQtr;
		this.useAltAddr = useAltAddr;
		this.module = module;
		this.lvReqCutoffDt = lvReqCutoffDt;
		this.lvLastAprvDt = lvLastAprvDt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "dtOfPay", column = @Column(name = "DT_OF_PAY", nullable = false, length = 8)) })
	public BthrPayDatesId getId() {
		return this.id;
	}

	public void setId(BthrPayDatesId id) {
		this.id = id;
	}

	@Column(name = "DT_PAYPER_BEG", nullable = false, length = 8)
	public String getDtPayperBeg() {
		return this.dtPayperBeg;
	}

	public void setDtPayperBeg(String dtPayperBeg) {
		this.dtPayperBeg = dtPayperBeg;
	}

	@Column(name = "DT_PAYPER_END", nullable = false, length = 8)
	public String getDtPayperEnd() {
		return this.dtPayperEnd;
	}

	public void setDtPayperEnd(String dtPayperEnd) {
		this.dtPayperEnd = dtPayperEnd;
	}

	@Column(name = "TRS_MONTH", nullable = false, length = 2)
	public String getTrsMonth() {
		return this.trsMonth;
	}

	public void setTrsMonth(String trsMonth) {
		this.trsMonth = trsMonth;
	}

	@Column(name = "TWC_QTR", nullable = false, length = 1)
	public char getTwcQtr() {
		return this.twcQtr;
	}

	public void setTwcQtr(char twcQtr) {
		this.twcQtr = twcQtr;
	}

	@Column(name = "USE_ALT_ADDR", nullable = false, length = 1)
	public char getUseAltAddr() {
		return this.useAltAddr;
	}

	public void setUseAltAddr(char useAltAddr) {
		this.useAltAddr = useAltAddr;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "LV_REQ_CUTOFF_DT", nullable = false, length = 8)
	public String getLvReqCutoffDt() {
		return this.lvReqCutoffDt;
	}

	public void setLvReqCutoffDt(String lvReqCutoffDt) {
		this.lvReqCutoffDt = lvReqCutoffDt;
	}

	@Column(name = "LV_LAST_APRV_DT", nullable = false, length = 8)
	public String getLvLastAprvDt() {
		return this.lvLastAprvDt;
	}

	public void setLvLastAprvDt(String lvLastAprvDt) {
		this.lvLastAprvDt = lvLastAprvDt;
	}
}
