package com.esc20.model;
// Generated Jan 4, 2019 3:51:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrEmplmntTyp generated by hbm2java
 */
@Entity
@Table(name = "BTHR_EMPLMNT_TYP", schema = "rsccc", catalog = "rsccc")
public class BthrEmplmntTyp implements java.io.Serializable {

	private BthrEmplmntTypId id;
	private String emplmntTypDesc;

	public BthrEmplmntTyp() {
	}

	public BthrEmplmntTyp(BthrEmplmntTypId id, String emplmntTypDesc) {
		this.id = id;
		this.emplmntTypDesc = emplmntTypDesc;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "emplmntTypRecTyp", column = @Column(name = "EMPLMNT_TYP_REC_TYP", nullable = false, length = 3)),
			@AttributeOverride(name = "emplmntTypCd", column = @Column(name = "EMPLMNT_TYP_CD", nullable = false, length = 1)) })
	public BthrEmplmntTypId getId() {
		return this.id;
	}

	public void setId(BthrEmplmntTypId id) {
		this.id = id;
	}

	@Column(name = "EMPLMNT_TYP_DESC", nullable = false, length = 50)
	public String getEmplmntTypDesc() {
		return this.emplmntTypDesc;
	}

	public void setEmplmntTypDesc(String emplmntTypDesc) {
		this.emplmntTypDesc = emplmntTypDesc;
	}

}
