package com.esc20.model;
// Generated Jan 4, 2019 3:51:33 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrFedIncomeTaxBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_FED_INCOME_TAX_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrFedIncomeTaxBkupPaycalcs5 implements java.io.Serializable {

	private BthrFedIncomeTaxBkupPaycalcs5Id id;

	public BthrFedIncomeTaxBkupPaycalcs5() {
	}

	public BthrFedIncomeTaxBkupPaycalcs5(BthrFedIncomeTaxBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxYr", column = @Column(name = "TAX_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "marriedSingleFlg", column = @Column(name = "MARRIED_SINGLE_FLG", nullable = false, length = 1)),
			@AttributeOverride(name = "seqNbr", column = @Column(name = "SEQ_NBR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "overAmt", column = @Column(name = "OVER_AMT", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "notOver", column = @Column(name = "NOT_OVER", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "taxAmt", column = @Column(name = "TAX_AMT", nullable = false, precision = 9)),
			@AttributeOverride(name = "pct", column = @Column(name = "PCT", nullable = false, precision = 4, scale = 3)),
			@AttributeOverride(name = "inExcess", column = @Column(name = "IN_EXCESS", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrFedIncomeTaxBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrFedIncomeTaxBkupPaycalcs5Id id) {
		this.id = id;
	}

}
