package com.esc20.model;
// Generated Jan 4, 2019 3:49:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrAca1095bCovrgTyp generated by hbm2java
 */
@Entity
@Table(name = "BTHR_ACA_1095B_COVRG_TYP", schema = "rsccc", catalog = "rsccc")
public class BthrAca1095bCovrgTyp implements java.io.Serializable {

	private BthrAca1095bCovrgTypId id;
	private String covrgTypDesc;
	private String module;

	public BthrAca1095bCovrgTyp() {
	}

	public BthrAca1095bCovrgTyp(BthrAca1095bCovrgTypId id, String covrgTypDesc, String module) {
		this.id = id;
		this.covrgTypDesc = covrgTypDesc;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "calYr", column = @Column(name = "CAL_YR", nullable = false, length = 4)),
			@AttributeOverride(name = "covrgTyp", column = @Column(name = "COVRG_TYP", nullable = false, length = 1)) })
	public BthrAca1095bCovrgTypId getId() {
		return this.id;
	}

	public void setId(BthrAca1095bCovrgTypId id) {
		this.id = id;
	}

	@Column(name = "COVRG_TYP_DESC", nullable = false, length = 80)
	public String getCovrgTypDesc() {
		return this.covrgTypDesc;
	}

	public void setCovrgTypDesc(String covrgTypDesc) {
		this.covrgTypDesc = covrgTypDesc;
	}

	@Column(name = "MODULE", nullable = false, length = 25)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
