package com.esc20.model;
// Generated Jan 4, 2019 3:52:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BthrLvRatesBkupPaycalcs5 generated by hbm2java
 */
@Entity
@Table(name = "BTHR_LV_RATES_BKUP_PAYCALCS_5", schema = "rsccc", catalog = "rsccc")
public class BthrLvRatesBkupPaycalcs5 implements java.io.Serializable {

	private BthrLvRatesBkupPaycalcs5Id id;

	public BthrLvRatesBkupPaycalcs5() {
	}

	public BthrLvRatesBkupPaycalcs5(BthrLvRatesBkupPaycalcs5Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "lvTyp", column = @Column(name = "LV_TYP", nullable = false, length = 2)),
			@AttributeOverride(name = "payFreq", column = @Column(name = "PAY_FREQ", nullable = false, length = 1)),
			@AttributeOverride(name = "seqOrder", column = @Column(name = "SEQ_ORDER", nullable = false, length = 1)),
			@AttributeOverride(name = "duration", column = @Column(name = "DURATION", nullable = false, length = 3)),
			@AttributeOverride(name = "dockAmt", column = @Column(name = "DOCK_AMT", nullable = false, precision = 7)),
			@AttributeOverride(name = "dockTyp", column = @Column(name = "DOCK_TYP", nullable = false, length = 1)),
			@AttributeOverride(name = "lvSeq", column = @Column(name = "LV_SEQ", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "module", column = @Column(name = "MODULE", nullable = false, length = 25)) })
	public BthrLvRatesBkupPaycalcs5Id getId() {
		return this.id;
	}

	public void setId(BthrLvRatesBkupPaycalcs5Id id) {
		this.id = id;
	}

}
