create table BEA_EMP_LV_RQST
(
    ID                   integer                        not null,
    PAY_FREQ             char(1)                        not null,
    EMP_NBR              char(6)                        not null,
    DATETIME_SUBMITTED   datetime                       default GETDATE() not null,
    DATETIME_FROM        datetime                       not null,
    DATETIME_TO          datetime                       not null,
    LV_UNITS_DAILY       numeric(7,3)                   not null,
    LV_UNITS_USED        numeric(7,3)                   not null,
    LV_TYP               char(2)                        not null,
    ABS_RSN              char(2)                        not null,
    STATUS_CD            char(1)                        not null,
    DT_OF_PAY            char(8)                        default '' not null,
    primary key (ID)
);

create table BEA_EMP_LV_COMMENTS
(
    ID                   integer                        not null,
    LV_ID                integer                        not null,
    LV_COMMENT_TYP       char(1)                        not null,
    LV_COMMENT_EMP_NBR   char(6)                        not null,
    LV_COMMENT_DATETIME  datetime                       default GETDATE() not null,
    LV_COMMENT           varchar(400)                   null,
    primary key (ID)
);

create table BEA_EMP_LV_WORKFLOW
(
    ID                   	integer                        not null,
    LV_ID                	integer                        not null,
    SEQ_NUM              	integer                        not null,
    INSERT_DATETIME      	datetime                       default GETDATE() not null,
    TMP_APPRVR_EXP_DATETIME	datetime                       null,
    APPRVR_EMP_NBR       	char(6)                        not null,
    primary key (ID)
);

CREATE TABLE BEA_LGL_NAME
(
	EMP_NBR		CHAR(6)			NOT NULL,
	REQ_DTS		CHAR(16)			NOT NULL,
	NAME_PRE		char(4)			NOT NULL,
	NAME_F		varchar(17)			NOT NULL,
	NAME_L		VARCHAR(25)			NOT NULL,
	NAME_M		VARCHAR(14)			NOT NULL,
	NAME_GEN		CHAR(1)			NOT NULL,
	NAME_PRE_NEW	CHAR(4)			NOT NULL,
	NAME_F_NEW		VARCHAR(17)			NOT NULL,
	NAME_L_NEW		VARCHAR(25)			NOT NULL,
	NAME_M_NEW		VARCHAR(14)			NOT NULL,
	NAME_GEN_NEW	CHAR(1)			NOT NULL,
	APPRVD_DTS		CHAR(16)	DEFAULT ''	NOT NULL,
	APPRVR_USR_ID 	INTEGER	DEFAULT 0	NOT NULL,
	STAT_CD		CHAR(1)	DEFAULT ''	NOT NULL,
	Primary key (EMP_NBR, REQ_DTS)
);

create table BHR_PAY_DEDUCT_HIST
(
	CYR_NYR_FLG          char(1)                        not null,
	PAY_FREQ             char(1)                        not null,
	EMP_NBR              char(6)                        not null,
	DT_OF_PAY            char(8)                        not null,
	CHK_NBR              char(6)                        not null,
	VOID_OR_ISS          char(1)                        not null,
	ADJ_NBR              numeric(3)                     not null,
	DED_CD               char(3)                        not null,
	DED_SEQ              char(1)                        not null,
	DED_AMT              numeric(9,2)                   not null,
	DED_REMAIN           numeric(3)                     not null,
	DED_TAKEN            numeric(3)                     not null,
	CAFE_FLG             char(1)                        not null,
	EMPLR_AMT            numeric(7,2)   DEFAULT 0	not null,
	EMPLR_CONTRIB_FACTOR numeric(1)     DEFAULT 0	not null,
	REFUND_FLG           char(1)                        not null,
	CASE_NBR             varchar(20)    DEFAULT ''	not null,
	CAUSE_NBR            varchar(12)    DEFAULT ''	not null,
	TEA_HEALTH_INS_CONTRIB numeric(7,2) DEFAULT 0	not null,
	TEA_HEALTH_INS_CONTRIB_FACTOR numeric(1) DEFAULT 0	not null,
	W2_EMPLR_HLTHCARE    char(1)  DEFAULT 'N'			not null,
    primary key (PAY_FREQ, EMP_NBR, CYR_NYR_FLG, DT_OF_PAY, CHK_NBR, VOID_OR_ISS, ADJ_NBR, DED_CD, DED_SEQ)
);

create table BHR_PAY_HIST
(
    CYR_NYR_FLG          char(1)                        not null,
    PAY_FREQ             char(1)                        not null,
    EMP_NBR              char(6)                        not null,
    DT_OF_PAY            char(8)                        not null,
    CHK_NBR              char(6)                        not null,
    VOID_OR_ISS          char(1)                        not null,
    ADJ_NBR              numeric(3)                     not null,
    CHK_CLEARED          char(1)                        not null,
    PAY_CAMPUS           char(3)                        not null,
    PAY_DEPT             char(1) DEFAULT ''		not null,
    ABS_DED_CODED        numeric(7,2)                   not null,
    ABS_DED_REFUND       numeric(7,2)                   not null,
    ABS_DED_AMT          numeric(7,2)                   not null,
    ABS_DED_AMT_TOT      numeric(7,2)                   not null,
    ACCRU_CD             char(1) DEFAULT ''		not null,
    ACCRU_EMPLR_NON_ANNUIT_CONTRIB numeric(9,2)         not null,
    ACCRU_FED_GRANT      numeric(9,2)                   not null,
    ACCRU_FED_CARE       numeric(9,2)                   not null,
    ACCRU_FED_INS        numeric(9,2)                   not null,
    ACCRU_FICA_TAX       numeric(9,2)                   not null,
    ACCRU_PAY            numeric(9,2)                   not null,
    ACCRU_UNEMP_INS      numeric(9,2)                   not null,
    ACCRU_DAYS_EARNED    numeric(5,2) DEFAULT 0		not null,
    ACCRU_EMPLR_ANNUIT_CONTRIB numeric(9,2)             not null,
    ACCRU_EMPLR_457      numeric(9,2) DEFAULT 0		not null,
    DT_PAYOFF            char(8) DEFAULT ''		not null,
    FINAL_PAY_FLG        char(1)                        not null,
    EIC_AMT              numeric(9,2) DEFAULT 0		not null,
    EARN_PAY             numeric(9,2) DEFAULT 0		not null,
    FICA_ELIG            char(1)                        not null,
    FICA_GROSS           numeric(9,2) DEFAULT 0		not null,
    FICA_TAX             numeric(9,2) DEFAULT 0		not null,
    REG_GROSS_SCH        numeric(9,2) DEFAULT 0		not null,
    MED_TAX              numeric(9,2) DEFAULT 0		not null,
    MED_GROSS            numeric(9,2) DEFAULT 0		not null,
    GROSS_PAY_TOT        numeric(9,2) DEFAULT 0		not null,
    HLTH_INS_DED         numeric(7,2) DEFAULT 0		not null,
    HRLY_PAY_RATE        numeric(9,2) DEFAULT 0		not null,
    MARITAL_STAT_TAX     char(1)                        not null,
    NBR_TAX_EXEMPTS      numeric(3) DEFAULT 0		not null,
    TAX_EXEMPT_FLG       char(1)                        not null,
    NET_ADJ_AMT          numeric(9,2) DEFAULT 0		not null,
    NET_PAY              numeric(9,2)                   not null,
    OVTM_GROSS           numeric(9,2) DEFAULT 0		not null,
    OVTM_HRS_WRK         numeric(5,2) DEFAULT 0		not null,
    REG_HRS_WRK          numeric(5,2) DEFAULT 0		not null,
    RETROACTIVE_PAY      numeric(9,2) DEFAULT 0		not null,
    TRS_SALARY_RED       numeric(9,2) DEFAULT 0		not null,
    ADJ_SALARY_CD        char(1) DEFAULT ''		not null,
    STD_GROSS            numeric(9,2)                   not null,
    STD_GROSS_TOT        numeric(9,2)                   not null,
    ST_SALARY            numeric(9,2) DEFAULT 0		not null,
    EXTRA_DUTY_GROSS     numeric(9,2) DEFAULT 0		not null,
    TAXED_BENEFITS       numeric(9,2) DEFAULT 0		not null,
    BUS_ALLOWANCE_NONTAX numeric(9,2) DEFAULT 0		not null,
    BUS_ALLOWANCE_TAX    numeric(9,2) DEFAULT 0		not null,
    TRS_DEPOSIT          numeric(9,2) DEFAULT 0		not null,
    TRS_FEE              numeric(9,2) DEFAULT 0		not null,
    TRS_GROSS            numeric(9,2) DEFAULT 0		not null,
    TRS_INS              numeric(7,2) DEFAULT 0		not null,
    TRS_CARE             numeric(7,2) DEFAULT 0		not null,
    UNEMP_GROSS          numeric(9,2) DEFAULT 0		not null,
    UNEMP_INS            numeric(9,2) DEFAULT 0		not null,
    WH_GROSS             numeric(9,2) DEFAULT 0		not null,
    WH_TAX               numeric(9,2) DEFAULT 0		not null,
    WRK_COMP_INS         numeric(9,2) DEFAULT 0		not null,
    DRCT_DEPOSIT_FLG     char(1)                        not null,
    DISTR_ERR_FLG        char(1)      DEFAULT ''	not null,
    EMPLR_INS_CONTRIB_FLG char(1)                       not null,
    EMPLR_NON_ANNUITY_CONTRIB numeric(9,2) DEFAULT 0	not null,
    EMPLR_ANNUITY_CONTRIB numeric(9,2) DEFAULT 0	not null,
    EMPLR_457            numeric(9,2)  DEFAULT 0	not null,
    EMP_457              numeric(9,2)  DEFAULT 0	not null,
    MISC_DED_AMT         numeric(7,2)                   not null,
    EXTRA_DUTY_PAY_LOC   numeric(9,2)  DEFAULT 0	not null,
    ANNUITY_DED          numeric(9,2)  DEFAULT 0	not null,
    CAFE_AMT             numeric(9,2)  DEFAULT 0	not null,
    WHOLLY_SEP_AMT       numeric(9,2)  DEFAULT 0	not null,
    DEPEND_CARE          numeric(9,2)  DEFAULT 0	not null,
    TAX_EMPLR_LIFE       numeric(9,2)  DEFAULT 0	not null,
    TAX_EMPLR_LIFE_GRP   numeric(9,2)  DEFAULT 0	not null,
    DIST_CONTRIB_ABOVE_ST numeric(9,2) DEFAULT 0	not null,
    NONTRS_REIMBR_EXCESS       numeric(9,2) DEFAULT 0	not null,
    NONTRS_REIMBR_BASE         numeric(9,2) DEFAULT 0	not null,
    NONTRS_BUS_ALLOW           numeric(9,2) DEFAULT 0	not null,
    NONTRS_NONTAX_BUS_ALLOW    numeric(9,2) DEFAULT 0	not null,
    NONTRS_NONPAY_BUS_ALLOW    numeric(9,2) DEFAULT 0	not null,
    NONTRS_NONTAX_NONPAY_ALLOW numeric(7,2) DEFAULT 0	not null,
    NONTRS_SUPPL               numeric(9,2) DEFAULT 0	not null,
    NONTRS_NONTAX_NONPAY_EXPEND numeric(7,2) DEFAULT 0	not null,
    TRS_ACTIVE_CARE_ELIG_FLG     char(1)      DEFAULT ''	not null,
    TRS_SUPPL_COMP               numeric(7,2) DEFAULT 0	not null,
    TEA_HEALTH_INS_CONTRIB       numeric(7,2) DEFAULT 0	not null,
    ACCRU_TEA_HEALTH_INS_CONTRIB numeric(7,2) DEFAULT 0	not null,
    TRS_SUPPL_COMP_FACTOR         numeric(1)  DEFAULT 0	not null,
    EMPLR_TRS_CARE_CONTRIB        numeric(9,2) DEFAULT 0	not null,
    ACCRU_EMPLR_TRS_CARE_CONTRIB  numeric(9,2) DEFAULT 0	not null,
    DAYS_WRK                      numeric(5,2) DEFAULT 0	not null,
    MULTI_HRLY_RATES              char(1)      DEFAULT ''	not null,
    TRS_SUPPL_ELIG_CD             char(1)      DEFAULT ''	not null,
    PERFOR_PAY_GROSS              numeric(9,2) DEFAULT 0	not null,
    PERFOR_PAY_DEPOSIT            numeric(9,2) DEFAULT 0	not null,
    PERFOR_PAY_INS                numeric(7,2) DEFAULT 0	not null,
    TRS_GRANT_GROSS               numeric(9,2) DEFAULT 0	not null,
    TRS_GRANT_DEPOSIT             numeric(9,2) DEFAULT 0	not null,
    TRS_GRANT_CARE                numeric(7,2) DEFAULT 0	not null,
    ACCRU_CAFE_AMT                numeric(9,2) DEFAULT 0	not null,
    EMPLR_RET_GROSS	          numeric(9,2) DEFAULT 0	not null,
    EMPLR_RET_PENSN_SURCHG	  numeric(7,2) DEFAULT 0	not null,
    ACCRU_EMPLR_RET_PENSN_SURCHG  numeric(7,2) DEFAULT 0	not null,
    EMPLR_TRS_CARE_SURCHG	  numeric(7,2) DEFAULT 0	not null,
    ACCRU_EMPLR_TRS_CARE_SURCHG	  numeric(7,2) DEFAULT 0	not null,
    EMPLR_NEW_TRS_GROSS           numeric(9,2) DEFAULT 0	not null,
    EMPLR_NEW_TRS_PENSN_CONTRIB   numeric(7,2) DEFAULT 0	not null,
    TAKE_RET_SURCHG               char(1)      DEFAULT ''	not null,
    EMPLR_DEPEND_CARE             numeric(9,2) DEFAULT 0	not null,
    ACCRU_EMPLR_DEPEND_CARE       numeric(9,2) DEFAULT 0	not null,
    ANNUITY_ROTH                  numeric(9,2) DEFAULT 0	not null,
    MICR_CHK_NBR                  char(6)      DEFAULT ''	not null,
    RECON_DTS                     varchar(16)  DEFAULT ''	not null,
    EMPLR_DEPEND_CARE_TAX         numeric(7,2) DEFAULT 0	not null,
    HSA_EMP_SAL_REDCTN_CONTRIB    numeric(7,2) DEFAULT 0 	not null,
    HSA_EMPLR_CONTRIB             numeric(7,2) DEFAULT 0 	not null,
    EMPLR_FICA_TAX				  numeric(9,2) DEFAULT 0	not null,
    EMPLR_MISC_DED_CONTRIB		  numeric(9,2) DEFAULT 0 	not null,
    ACCRU_EMPLR_MISC_DED_CONTRIB  numeric(9,2) DEFAULT 0 	not null,
    EMPLR_MED_TAX                 numeric(9,2) default 0    not null,
    MED_GROS_CAL_YTD              numeric(9,2) default 0    not null,
    EMPLR_TRS_NON_OASDI_CONTRIB   numeric(9,2) default 0    not null,
    ANNUITY_ROTH_457B             numeric(9,2) default 0    not null,
    ERS_RET_HLTH_ELIG             char(1) DEFAULT 'N'       not null,
    TRS_STAT_CD                   char(1) DEFAULT ''        not null,
    primary key (PAY_FREQ, EMP_NBR, CYR_NYR_FLG, DT_OF_PAY, CHK_NBR, VOID_OR_ISS, ADJ_NBR)
);

create table BHR_EMP_LV
(
	CYR_NYR_FLG          char(1)                        not null,
	PAY_FREQ             char(1)                        not null,
	EMP_NBR              char(6)                        not null,
	LV_TYP               char(2)                        not null,
	LV_BEGIN_BAL         numeric(7,3)                   not null,
	LV_EARNED            numeric(7,3)                   not null,
	LV_USED              numeric(7,3)                   not null,
	LV_END_BAL           numeric(7,3)                   not null,
	MODULE               varchar(25) DEFAULT ''         not null,
	primary key (PAY_FREQ, EMP_NBR, CYR_NYR_FLG, LV_TYP)
);

create table BHR_EMP_PAY
(
	CYR_NYR_FLG          char(1)                        not null,
	PAY_FREQ             char(1)                        not null,
	EMP_NBR              char(6)                        not null,
	STAT_CD              char(1)                        not null,
	PAY_CAMPUS           char(3)                        not null,
	PAY_DEPT             char(1) DEFAULT ''		not null,
	UNEMP_ELIG_FLG       char(1)                        not null,
	EXTRA_DUTY_ANNUAL    numeric(9,2) DEFAULT 0		not null,
	EXTRA_DUTY_ANNUAL_LOCL numeric(9,2) DEFAULT 0	not null,
	MARITAL_STAT_TAX     char(1)                        not null,
	NBR_TAX_EXEMPTS      numeric(3)                     not null,
	FICA_ELIG            char(1)                        not null,
	TAX_EXEMPT           char(1)                        not null,
	MIN_FOUND_AMT        numeric(9,2) DEFAULT 0		not null,
	NBR_MON_CONTR        numeric(3) DEFAULT 0		not null,
	ACT_DAYS_CONTR       numeric(3) DEFAULT 0		not null,
	EIC                  char(1) DEFAULT ''		not null,
	DT_PAYOFF            char(8) DEFAULT ''		not null,
	LONGEVITY_PAY        numeric(9,2) DEFAULT 0		not null,
	TRS_BEGIN_DT         char(8) DEFAULT ''		not null,
	TRS_CLASS_CD         char(1) DEFAULT ''		not null,
	TRS_FEE_PAID_FLG     char(1) DEFAULT ''		not null,
	TRS_STAT_CD          char(1)                        not null,
	TRS_NON_STD_CD       char(1) DEFAULT ''		not null,
	TRS_NON_STD_ZERO     char(1) DEFAULT ''		not null,
	TRS_NON_STD_RPT      char(1) DEFAULT ''		not null,
	TRS_NON_STD_GROSS    numeric(9,2) DEFAULT 0		not null,
	TRS_NON_STD_DEPOSIT  numeric(9,2) DEFAULT 0		not null,
	BUS_ALLOWANCE_NONTAX numeric(9,2) DEFAULT 0		not null,
	BUS_ALLOWANCE_PAYMNTS_NONTAX char(2) DEFAULT ''	not null,
	ACCRU_CD             char(1) DEFAULT ''		not null,
	ACCRU_RATE           numeric(7,3) DEFAULT 0		not null,
	ACCRU_DAYS_EARNED    numeric(5,2) DEFAULT 0		not null,
	DT_L_UPDATE          char(8)                        not null,
	DT_L_PAYRUN          char(8) DEFAULT ''		not null,
	DT_L_ADJ             char(8) DEFAULT ''		not null,
	LOCL_PAY             numeric(9,2) DEFAULT 0		not null,
	CATASTROPHIC_LV_FLG  char(1) DEFAULT ''		not null,
	DOCK_RATE            numeric(7,3) DEFAULT 0		not null,
	FROZEN_FLG           char(1) DEFAULT ''		not null,
	SICK_LV_BANK         char(2) DEFAULT ''		not null,
	NON_INSTR_PARA_PRO_CD char(2) DEFAULT ''		not null,
	STP_0_SALARY         numeric(5) DEFAULT 0		not null,
	EXC_PERS_BUS_SEM     char(2) DEFAULT ''		not null,
	ST_OLD_PAY_GRD       char(3) DEFAULT ''		not null,
	WHOLLY_SEP_AMT       numeric(7,2) DEFAULT 0		not null,
	EOY_ACCRU_FLG        char(1) DEFAULT ''		not null,
	CERT_MON             char(2) DEFAULT ''		not null,
	BUS_ALLOWANCE_TAX    numeric(9,2) DEFAULT 0		not null,
	BUS_ALLOWANCE_PAYMNTS_TAX  char(2) DEFAULT ''	not null,
	TRS_ACTIVE_CARE_ELIG_FLG   char(1) DEFAULT ''	not null,
	TRS_SUPPL_REMAIN_COMP      numeric(7,2) DEFAULT 0	not null,
	TRS_SUPPL_NBR_REMAIN_PYMTS numeric(3) DEFAULT 0	not null,
	TRS_SUPPL_COMP_FACTOR      numeric(1) DEFAULT 0	not null,
	TRS_SUPPL_ELIG_CD          char(1) DEFAULT ''	not null,
	DT_END_90_DAY_PER          char(8) DEFAULT ''	not null,
	MODULE               varchar(25) DEFAULT ''     not null,
	NEW_PMIS_EMP_FLG     char(1) DEFAULT ''	not null,
	primary key (PAY_FREQ, EMP_NBR, CYR_NYR_FLG)
);

create table BHR_EMP_DEDUCT
(
	CYR_NYR_FLG          char(1)                        not null,
	PAY_FREQ             char(1)                        not null,
	EMP_NBR              char(6)                        not null,
	DED_CD               char(3)                        not null,
	DED_SEQ              char(1)                        not null,
	EMP_AMT              numeric(7,2)                   not null,
	EMPLR_AMT            numeric(7,2)                   not null,
	EMPLR_CONTRIB_FACTOR numeric(1) DEFAULT 0			not null,
	DED_REMAIN           numeric(3)                     not null,
	CAFE_FLG             char(1)                        not null,
	REFUND_ELIG          char(1)                        not null,
	CASE_NBR             varchar(20) DEFAULT ''			not null,
	CAUSE_NBR            varchar(12) DEFAULT ''			not null,
	BANK_CD              char(3) DEFAULT ''				not null,
	BANK_ACCT_NBR        varchar(17) DEFAULT ''			not null,
	BANK_ACCT_TYP        char(1) DEFAULT ''				not null,
	BANK_PRENOTE         char(1) DEFAULT ''				not null,
	TEA_HEALTH_INS_CONTRIB_FACTOR numeric(1) DEFAULT 0	not null,
	MODULE               varchar(25) DEFAULT ''           not null,
	primary key (PAY_FREQ, EMP_NBR, DED_CD, DED_SEQ, CYR_NYR_FLG)
);

create table BHR_EMP_DEMO
(
	EMP_NBR              char(6)                        not null,
	STAFF_ID             char(9)                        not null,
	PRIOR_STAFF_ID       char(9) DEFAULT ''		not null,
	NAME_PRE             char(4) DEFAULT ''		not null,
	NAME_F               varchar(17)                    not null,
	NAME_M               varchar(14) DEFAULT ''		not null,
	NAME_L               varchar(25)                    not null,
	NAME_GEN             char(1) DEFAULT ''		not null,
	NAME_MAIDEN          varchar(25) DEFAULT ''		not null,
	PRV_NAME_PRE         char(4) DEFAULT ''		not null,
	PRV_NAME_F           varchar(17) DEFAULT ''		not null,
	PRV_NAME_M           varchar(14) DEFAULT ''		not null,
	PRV_NAME_L           varchar(25) DEFAULT ''		not null,
	PRV_NAME_GEN         char(1) DEFAULT ''		not null,
	BIL_IND              char(1)                        not null,
	CITZ_FLG             char(1)                        not null,
	DECEASED             char(1)                        not null,
	DEMO_REV_CD          char(1)                        not null,
	DOB                  char(8)                        not null,
	DRIVERS_LIC_NBR      char(19) DEFAULT ''		not null,
	DRIVERS_LIC_ST       char(2) DEFAULT ''		not null,
	ETHN                 char(1) DEFAULT ''     not null,
	MARITAL_STAT         char(1) DEFAULT ''		not null,
	SEX                  char(1)                        not null,
	ADDR_NBR             char(8)                        not null,
	ADDR_STR             varchar(20)                    not null,
	ADDR_APT             char(7) DEFAULT ''		not null,
	ADDR_CITY            varchar(25)                    not null,
	ADDR_ST              char(2)                        not null,
	ADDR_ZIP             char(5)                        not null,
	ADDR_ZIP4            char(4) DEFAULT ''		not null,
	SMR_ADDR_NBR         char(8) DEFAULT ''		not null,
	SMR_ADDR_STR         varchar(20) DEFAULT ''		not null,
	SMR_ADDR_APT         char(7) DEFAULT ''		not null,
	SMR_ADDR_CITY        varchar(17) DEFAULT ''		not null,
	SMR_ADDR_ST          char(2) DEFAULT ''		not null,
	SMR_ADDR_ZIP         char(5) DEFAULT ''		not null,
	SMR_ADDR_ZIP4        char(4) DEFAULT ''		not null,
	RESTRICT_CD          char(1)                        not null,
	RESTRICT_CD_PUBLIC   char(1)                        not null,
	PHONE_AREA           char(3) DEFAULT ''		not null,
	PHONE_NBR            char(7) DEFAULT ''		not null,
	PHONE_AREA_BUS       char(3) DEFAULT ''		not null,
	PHONE_NBR_BUS        char(7) DEFAULT ''		not null,
	BUS_PHONE_EXT        char(4) DEFAULT ''		not null,
	EMAIL                varchar(45) DEFAULT ''		not null,
	LOC_USE_1            char(10) DEFAULT ''		not null,
	LOC_USE_2            char(10) DEFAULT ''		not null,
	EMER_CONTACT         varchar(26) DEFAULT ''		not null,
	EMER_PHONE_AC        char(3) DEFAULT ''		not null,
	EMER_PHONE_NBR       char(7) DEFAULT ''		not null,
	EMER_PHONE_EXT       char(6) DEFAULT ''		not null,
	EMER_REL             varchar(25) DEFAULT ''		not null,
	EMER_NOTE            varchar(25) DEFAULT ''		not null,
	CHK_NAME_PRE         char(4) DEFAULT ''		not null,
	CHK_NAME_F           varchar(17) DEFAULT ''		not null,
	CHK_NAME_M           char(1) DEFAULT ''		not null,
	CHK_NAME_L           varchar(25) DEFAULT ''		not null,
	CHK_NAME_GEN         char(1) DEFAULT ''		not null,
	TRS_NAME_PRE         char(4) DEFAULT ''		not null,
	TRS_NAME_F           varchar(17) DEFAULT ''		not null,
	TRS_NAME_M           varchar(14) DEFAULT ''		not null,
	TRS_NAME_L           varchar(25) DEFAULT ''		not null,
	TRS_NAME_GEN         char(1) DEFAULT ''		not null,
	DT_LAST_CHANGED      char(8)                        not null,
	SUPPL_ADDR           varchar(40)  DEFAULT ''	not null,
	SUPPL_CNTRY          varchar(40)  DEFAULT ''	not null,
	SUPPL_DELIV_NAME     varchar(40)  DEFAULT ''	not null,
	PHONE_AREA_CELL      char(3)      DEFAULT ''	not null,
	PHONE_NBR_CELL       char(7)      DEFAULT ''	not null,
	DT_DL_EXPR           char(8)      DEFAULT ''	not null,
	ETHN_HISPANIC		 char(1)      DEFAULT '0' not null,
	RACE_AMER_INDIAN	 char(1)      DEFAULT '0' not null,
	RACE_ASIAN	         char(1)      DEFAULT '0' not null,
	RACE_BLACK			 char(1)      DEFAULT '0' not null,
	RACE_PACIFIC_ISL	 char(1)      DEFAULT '0' not null,
	RACE_WHITE			 char(1)      DEFAULT '0' not null,
	HM_EMAIL			 varchar(45)  DEFAULT ''  not null,
	ADDR_CTRY			 varchar(30)  DEFAULT ''  not null,
	MODULE               varchar(25)  DEFAULT ''  not null,
	TX_UNIQUE_STF_ID     char(10)     DEFAULT ''  not null,
	NON_EMP              char(1)      DEFAULT 'N' not null,
	primary key (EMP_NBR)
);

create table BHR_EMP_JOB
(
	CYR_NYR_FLG          char(1)                    not null,
	PAY_FREQ             char(1)                    not null,
	EMP_NBR              char(6)                    not null,
	JOB_CD               char(4)                    not null,
	PRIM_JOB             char(1)                    not null,
	PCT_ASSGND           numeric(3,2)               not null,
	CAMPUS_ID            char(3) 					not null,
	DEPT                 char(1) DEFAULT ''			not null,
	EEOC                 char(2) DEFAULT ''			not null,
	CONTR_AMT            numeric(9,2) DEFAULT 0		not null,
	CONTR_REMAIN_AMT     numeric(9,2) DEFAULT 0		not null,
	CAL_CD               char(2) DEFAULT ''			not null,
	CONTR_DT_BEGIN       char(8) DEFAULT ''			not null,
	CONTR_DT_END         char(8) DEFAULT ''			not null,
	CONTR_NON_STD_FLG    char(1) DEFAULT ''			not null,
	CONTR_DAYS           numeric(3) DEFAULT 0		not null,
	ST_STEP              char(2) DEFAULT ''			not null,
	ST_MIN_SALARY        numeric(9,2) DEFAULT 0		not null,
	YRS_CAR_LAD          numeric(1) DEFAULT 0		not null,
	PAY_TYPE             char(1)                    not null,
	PAY_RATE             numeric(9,2) DEFAULT 0		not null,
	PAY_GRD              char(3) DEFAULT ''			not null,
	PAY_SCHED            char(1) DEFAULT ''			not null,
	PAY_STEP             char(2) DEFAULT ''			not null,
	MAX_DAYS             char(3) DEFAULT ''			not null,
	EXEMPT_STAT          char(1)                    not null,
	DLY_RATE_OF_PAY      numeric(7,3) DEFAULT 0		not null,
	REG_HRS_WRK          numeric(5,2) DEFAULT 0		not null,
	HRS_PER_DAY          numeric(5,3) DEFAULT 0		not null,
	NBR_DAYS_EMPLD       numeric(3) DEFAULT 0		not null,
	NBR_DAYS_OFF         numeric(5,1) DEFAULT 0		not null,
	NBR_ANNUAL_PYMTS     numeric(3) DEFAULT 0		not null,
	NBR_REMAIN_PYMTS     numeric(3) DEFAULT 0		not null,
	NBR_MON_CONTR        numeric(3) DEFAULT 0		not null,
	OVTM_ELIG_FLG        char(1)                    not null,
	OVTM_RATE            numeric(5,2) DEFAULT 0		not null,
	WRK_COMP             char(1) DEFAULT ''			not null,
	WRK_COMP_REMAIN      numeric(3) DEFAULT 0		not null,
	TRS_POS_CD           char(2) DEFAULT ''			not null,
	ST_MIN_SALARY_PCT    numeric(3,2) DEFAULT 0		not null,
	ACCRU_JOB            char(1)                    not null,
	ACCRU_RATE	         numeric(7,3) DEFAULT 0		not null,
	CONTR_DAYS_LOC       char(3) DEFAULT ''			not null,
	DT_PAYOFF            char(8) DEFAULT ''			not null,
	YRS_EXP_JOB          char(2) DEFAULT ''			not null,
	ACCRU_CD             char(1) DEFAULT ''			not null,
	WRK_COMP_ANNL_PYMTS  numeric(2) DEFAULT 0       not null,
	HRLY_RATE            numeric(5,2) DEFAULT 0		not null,
	INCR_PAY_STP         char(1)     DEFAULT 'Y'	not null,
	MODULE               varchar(25) DEFAULT ''		not null,
	VACANT_POS           char(1)     DEFAULT 'N'    not null,
	WKLY_HRS_SCHED       NUMERIC(2,0) DEFAULT 0     NOT NULL,
	WHOLLY_SEP_AMT       NUMERIC(7,2) DEFAULT 0     NOT NULL,
	primary key (PAY_FREQ, EMP_NBR, CYR_NYR_FLG, JOB_CD)
);
